### ISSUE TITLE
FFMPEPInput subimages

### ISSUE THREAD

**Issue by sobotka** [OpenImageIO/oiio#1003]
iv shows the correct number of frames with the FFMPEG extensions, but when flipping through the subimages, only one updated frame for approximately every twelve subimages appears to be displayed.

**Comment by lgritz** [comment]
Was this ever resolved?

**Comment by sobotka** [comment]
No. For posterity sake, I'll outline the general problem for those folks that are having more time than myself at the current moment.

All codecs can end up being a mish-mash of I (whole), P (predictive based on previous), and B (bi-directional predictive forward and back) frames. Many H264 encoders rely heavily on B frames to optimize for size.

If we assume a trivial example, the problem manifests itself quickly. Let's assume a series:

Frame Number | 0 | 1 | 2 | 3 | 4
-------------|---|---|---|---|---
Frame Type   | I | P | I | B | I

If OIIO seeks to frame 0, no problem as we have a full frame in the decoded buffer. Frame 1, despite being a predictive frame, we have already sifted through the decode and should have enough information to decode the frame<sup>1</sup>. Frame 2 is again a fresh start and not a problem as it is a full frame. Frame 3 however, is where our issue crops up.

While we can seek to frame 3, it being a bi-directional predictive frame means we rely on both the previous frame and the next I frame, which in this case is frame 4. We do not yet have enough information to pull a full frame off of the buffer.

In FFMPEG terms, the proper technique would be to find our desired frame. From there, we need to seek to the first I frame previous, which is I believe typical FFMPEG behavior. So in our above example, I believe the seek will return frame 2. Then we must decode past the I frame using avcodec_decode_video2 until we pop a full frame, tracking the decoded frames as we go. Once we hit the next I frame, we can figure out what frame the artist / technician desired and present it accordingly.

Phew. Apologies for the spam.

**Comment by lgritz** [comment]
Thanks for clarifying.

**Comment by lgritz** [comment]
I think we long ago merged a PR that was supposed to fix this (#1288). Closing.
