### ISSUE TITLE
build bug on linux

### ISSUE THREAD

**Issue by unicomp21** [OpenImageIO/oiio#1023]
make[3]: Entering directory '/root/oiio/build/linux64'
[ 12%] Building CXX object src/libutil/CMakeFiles/simd_test.dir/simd_test.cpp.o
In file included from /root/oiio/src/libutil/simd_test.cpp:32:0:
/root/oiio/src/include/OpenImageIO/simd.h:1172:43: error: ‘V4f’ in namespace ‘Im
ath’ does not name a type
     OIIO_FORCEINLINE float4 (const Imath::V4f &v) { load ((const float *)&v); }

                                           ^
/root/oiio/src/include/OpenImageIO/simd.h:1190:35: error: ‘V4f’ in namespace ‘Im
ath’ does not name a type
     OIIO_FORCEINLINE const Imath::V4f& V4f () const { return *(const Imath::V4f
*)this; }
                                   ^
/root/oiio/src/include/OpenImageIO/simd.h:1236:61: error: ‘V4f’ in namespace ‘Im
ath’ does not name a type
     OIIO_FORCEINLINE const float4 & operator= (const Imath::V4f &v) {
                                                             ^
src/libutil/CMakeFiles/simd_test.dir/build.make:54: recipe for target 'src/libut
il/CMakeFiles/simd_test.dir/simd_test.cpp.o' failed
make[3]: *** [src/libutil/CMakeFiles/simd_test.dir/simd_test.cpp.o] Error 1
make[3]: Leaving directory '/root/oiio/build/linux64'
CMakeFiles/Makefile2:1212: recipe for target 'src/libutil/CMakeFiles/simd_test.d
ir/all' failed
make[2]: *** [src/libutil/CMakeFiles/simd_test.dir/all] Error 2
make[2]: Leaving directory '/root/oiio/build/linux64'
Makefile:143: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/root/oiio/build/linux64'
Makefile:281: recipe for target 'cmake' failed
make: *** [cmake] Error 2

**Comment by unicomp21** [comment]
still trying to get this building for osl, kicked back to 1.4.9, getting this now

[ 23%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/imagebu
falgo_copy.cpp.o
[ 24%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/imagebu
falgo_deep.cpp.o
[ 24%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/imagebu
falgo_pixelmath.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/build.make:376: recipe for target
'src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/imagebufalgo_pixelmath.cpp.o' fai
led
make[3]: *** [src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/imagebufalgo_pixelma
th.cpp.o] Error 4
make[3]: Leaving directory '/root/oiio/build/linux64'
CMakeFiles/Makefile2:1408: recipe for target 'src/libOpenImageIO/CMakeFiles/Open
ImageIO.dir/all' failed
make[2]: *** [src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/all] Error 2
make[2]: Leaving directory '/root/oiio/build/linux64'
Makefile:143: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/root/oiio/build/linux64'
Makefile:245: recipe for target 'cmake' failed
make: *** [cmake] Error 2

**Comment by lgritz** [comment]
This looks suspiciously similar to #1018, which turned out to be a too-old OpenEXR/Ilmbase installation.

Do you know what version of Ilmbase you have?

**Comment by unicomp21** [comment]
reimaged vm, started over, 1.4.9, got this, I've no idea how pthreads could be missing

/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTryCompileE
xec2866466715.dir/CheckFunctionExists.c.o  -o cmTryCompileExec2866466715 -rdynam
ic -lpthreads
/usr/bin/ld: cannot find -lpthreads
CMakeFiles/cmTryCompileExec2866466715.dir/build.make:88: recipe for target 'cmTr
yCompileExec2866466715' failed
make[2]: Leaving directory '/root/oiio/build/linux64/CMakeFiles/CMakeTmp'
Makefile:114: recipe for target 'cmTryCompileExec2866466715/fast' failed
make[1]: Leaving directory '/root/oiio/build/linux64/CMakeFiles/CMakeTmp'
collect2: error: ld returned 1 exit status
make[2]: *** [cmTryCompileExec2866466715] Error 1
make[1]: *** [cmTryCompileExec2866466715/fast] Error 2

**Comment by unicomp21** [comment]
root@osl005:~/oiio# apt-show-versions libopenexr-dev
libopenexr-dev:amd64/utopic 1.6.1-7ubuntu1 uptodate

**Comment by unicomp21** [comment]
wasn't doing boost-all-dev earlier, now I'm back to:

Scanning dependencies of target simd_test
make[3]: Leaving directory '/root/oiio/build/linux64'
make -f src/libutil/CMakeFiles/simd_test.dir/build.make src/libutil/CMakeFiles/s
imd_test.dir/build
make[3]: Entering directory '/root/oiio/build/linux64'
/usr/bin/cmake -E cmake_progress_report /root/oiio/build/linux64/CMakeFiles 96
[ 12%] Building CXX object src/libutil/CMakeFiles/simd_test.dir/simd_test.cpp.o
cd /root/oiio/build/linux64/src/libutil && /usr/bin/c++   -D__STDC_LIMIT_MACROS
-O3 -DNDEBUG -I/usr/include/OpenEXR -I/root/oiio/src/include -I/root/oiio/build/
linux64/include/OpenImageIO    -Wall -Werror -fno-math-errno -Wno-error=unused-l
ocal-typedefs -Wno-unused-local-typedefs -UUSE_FIELD3D -o CMakeFiles/simd_test.d
ir/simd_test.cpp.o -c /root/oiio/src/libutil/simd_test.cpp
src/libutil/CMakeFiles/simd_test.dir/build.make:54: recipe for target 'src/libut
il/CMakeFiles/simd_test.dir/simd_test.cpp.o' failed
make[3]: Leaving directory '/root/oiio/build/linux64'
CMakeFiles/Makefile2:1212: recipe for target 'src/libutil/CMakeFiles/simd_test.d
ir/all' failed
make[2]: Leaving directory '/root/oiio/build/linux64'
Makefile:143: recipe for target 'all' failed
make[1]: Leaving directory '/root/oiio/build/linux64'
Makefile:281: recipe for target 'cmake' failed

**Comment by unicomp21** [comment]
stuggling w/ openexr and ilmbase builds

**Comment by unicomp21** [comment]
OpenEXR is botched, hopefully ILM guys will fix it soon ...

https://github.com/openexr/openexr/issues/150

**Comment by lgritz** [comment]
Was this ever resolved? I'm closing on the assumption that it's fixed in more recent OpenEXR versions.
