### ISSUE TITLE
wrong exception caught for boost::filesystem

### ISSUE THREAD

**Issue by ThiagoIze** [OpenImageIO/oiio#1025]
I noticed that the OIIO Filesystem class is catching the wrong type of exception when it calls `boost::filesystem` functions.  These functions return an exception of type   `boost::filesystem::filesystem_error` and OIIO is instead trying to catch the unrelated  `std::exception`

Since `filesystem_error` does not inherit from `std::exception`, that means that any thrown exceptions are missed and can end up crashing the application.

You can reproduce this easily with the following code provided you first run the following command in a terminal so we can have a file that is not accessible due to permission reasons:
```bash
mkdir /tmp/deny; chmod a-rwx /tmp/deny
```
```c++
      try {
         printf("testing Filesystem::exists: %d\n", Filesystem::exists("/tmp/deny/etx"));
      } catch(const boost::filesystem::filesystem_error e) {
         std::cout<< "oiio not catching proper exception:  "<<e.what() << std::endl;
      }
      try {
         printf("testing Filesystem::is_directory: %d\n", Filesystem::is_directory("/tmp/deny/etx"));
      } catch(const boost::filesystem::filesystem_error e) {
         std::cout<< "oiio not catching proper exception:  "<<e.what() << std::endl;
      }
      try {
         printf("testing Filesystem::is_regular: %d\n", Filesystem::is_regular("/tmp/deny/etx"));
      } catch(const boost::filesystem::filesystem_error e) {
         std::cout<< "oiio not catching proper exception:  "<<e.what() << std::endl;
      }
      try {
         std::cout <<"testing Filesystem::last_write_time: "<< Filesystem::last_write_time("/tmp/deny/etx") <<std::endl;
      } catch(const boost::filesystem::filesystem_error e) {
         std::cout<< "oiio not catching proper exception:  "<<e.what() << std::endl;
      }
```
Here's the output using OIIO 1.4 which shows that the exceptions were not caught by OIIO and instead were caught by our test code:

```
testing Filesystem::exists: oiio not catching proper exception:  boost::filesystem::status: Permission denied: "/tmp/deny/etx"
testing Filesystem::is_directory: oiio not catching proper exception:  boost::filesystem::status: Permission denied: "/tmp/deny/etx"
testing Filesystem::is_regular: oiio not catching proper exception:  boost::filesystem::status: Permission denied: "/tmp/deny/etx"
testing Filesystem::last_write_time: oiio not catching proper exception:  boost::filesystem::last_write_time: Permission denied: "/tmp/deny/etx"
```

The fix is a pretty simple search and replace in filesystem.cpp.

I didn't check the rest of OIIO, but it might be worth doing some quick investigations to see if this problem exists elsewhere.

**Comment by fpsunflower** [comment]
Did you mean to catch by reference?

As far as I can tell `boost::filesystem::filesystem_error` derives from `std::runtime_error` which itself derives from `std::exception`.

**Comment by lgritz** [comment]
I thought the std::exception would catch anything. Have I used the wrong syntax somehow?
Is it supposed to be a reference or not?

**Comment by ThiagoIze** [comment]
Oops, yes, test code should be by reference, but that doesn't change the results since my catches should never have caught anything to begin with.  The OIIO code should have caught these before it came up to my test code.  Please double check of course what I'm saying!

```catch(...)``` is how you catch everything

**Comment by lgritz** [comment]
I admit to using exceptions so rarely (I'm old, and polluted by the days of yore when they were expensive and unreliable, and I think the catch blocks add needless clutter most of the time) that I'm shaky on the fine points of the semantics. Are not all exceptions ultimately derived from std::exception? No? So in filesystem.cpp, I should change all those catch-alls to catch(...) ?

**Comment by lgritz** [comment]
Again, I'm old and addle-brained, but I'm not sure why it was the wise design choice for bool exists(path) to throw exceptions. It either exists or it doesn't, why isn't the bool enough?

These days, exceptions are essentially free if not thrown, but incur considerable overhead when thrown. So I'm ok with them for truly exceptional circumstances, but I think the rule of thumb is that you shouldn't use them when "fail" is a legit and possibly common result (like testing whether a file exists).

This point is rhetorical and/or off-topic, but I still feel compelled to say it.

As a final aside, just recently Boost::filesystem was accepted into C++17 as std::filesystem (with some minor changes).

**Comment by fpsunflower** [comment]
Which version of boost are you using Thiago? On ours the `filesystem_error` definitely derives from `std::exception`. Did you look in the boost headers to see what yours is doing? On my machine (boost 1.51) I have `filesystem_error` -> `system_error` -> `std::runtime_error` -> `std::exception`.

There is a note in the boost headers about symbol visibility being required to catch the exception. Are you by any chance running in a context where the symbols have been removed?

**Comment by ThiagoIze** [comment]
I'm using 1.55.0.  I don't think the symbols have been removed in my test, but it wouldn't surprise me if that is the case.  In any case, I'll definitely be stripping symbols later on, so if OIIO can work under that use case, I'd appreciate it.

As for ```exists()``` throwing, it makes sense because the file might exist, but the permissions are such that we can't check to see if it exists.  In that case, you can't return true or false since you don't actually know the answer.

**Comment by lgritz** [comment]
OK, I can see that rationale, and it's an unusual circumstance for sure. I think for the sake of our exists() wrapper, it's fine for "I can't find out the answer" to be rounded down to "no."

But anyway, if you add a one more "catch (...) { return false; }" clause to exists(), does that fix it?

**Comment by ThiagoIze** [comment]
Oh, I don't like dealing with exceptions and would prefer that OIIO catch everything so I don't have to litter my code with try/catch blocks!  I was just pointing out why boost probably chose to throw an exception -- by "you" I was referring to a hypothetical boost developer, not oiio.  

Using either ```catch(...)``` or ```catch(filesystem_error&)``` both work for me.  If you really just wanted to catch everything, how about just replacing all the catches in OIIO with ```catch(...)``` and be done with it?

**Comment by lgritz** [comment]
Yes, in the case of these Filesystem wrappers, I can see that the idiom is

    try {
        stuff
    } catch (const std::exception &) {
        return false;   // don't even use the exception
    }

Let's just change these to catch(...) and be done with it.

However, in other places where we catch exceptions, we do something more like

    catch (const std::exception &e) {
        make some use of e.what() in constructing an error message
    }

And so in that case, catch(...) would not be adequate, so I'm unsure of the right thing to do, if we aren't confident that std::exception is the base class that will catch all exceptions. I suppose we could add an *additional* catch(...) like this:

    catch (const std::exception &e) {
        error (e.what());
    } catch (...) {
        error ("unknown exception")
    }

**Comment by ThiagoIze** [comment]
I figured out the problem.  In my application that statically links in OIIO, I use `-fno-rtti` for performance reasons (at least, that's the theory as I haven't checked to see if it actually provided any speedups).  If I get rid of this, then OIIO properly works. 

What I don't understand is why this should matter since the ```exists("/tmp/deny/foo")``` call I made for testing this was actually implemented within OIIO and not my application.  It's a bit scary that if I disable RTTI in just my application, that this will propagate into libraries I link in.

Yes, catching ```std::exception``` makes sense if you want the error message from it.  In that case, a ```catch(...)``` seems like a good stop gap solution for those of us who are disabling RTTI.

Just to clarify, I'm using apple's clang-425.0.28, in case this is a compiler/linker bug.

**Comment by lgritz** [comment]
I don't see the harm in catch(...) for these filesystems cases. I also don't see the harm in *adding* them in places where we do use the exception value, as a 2nd level fallback from which we will have less information to report (but can still nonetheless prevent an uncaught exception crash).

I'm happy to quickly throw together the Filesystem fix, if you want.

**Comment by ThiagoIze** [comment]
2-level catches, where appropriate, seems like a robust fix for people like me that are disabling RTTI.  Incidentally, [this page](http://stackoverflow.com/a/5405221/2548327) seems to indicate that this is an apple bug and that this problem does not exist in linux.  There's no proof given this is a real bug, but interesting none the less...

**Comment by lgritz** [comment]
OK, I'll put together a fix.

**Comment by lgritz** [comment]
See #1026
