### ISSUE TITLE
New OSX build issue...

### ISSUE THREAD

**Issue by meshula** [OpenImageIO/oiio#1039]
Has anyone tried building oiio on this configuration? I've experimented and Google'd a bunch but am coming up dry.

OSX 10.10.1, Xcode 6 beta 3 

CMake fails on compiler validation. Other CMake based builds such as Alembic don't fail out in this way, and I'm wondering if this rings any bells for anyone?

Verbose output looks like 

platform=macosx, hw=x86_64
OPENIMAGEIO_SITE = Nicks-MacBook-Pro.local
dist_dir = dist/macosx
INSTALLDIR = /Users/dp/ThirdParty/mkvfx/extern/OpenImageIO
Re-run cmake no build system arguments
-- The CXX compiler identification is AppleClang 6.0.0.6000038
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- broken
-- Configuring incomplete, errors occurred!
See also "/Users/dp/ThirdParty/mkvfx/extern/OpenImageIO/CMakeFiles/CMakeOutput.log".
See also "/Users/dp/ThirdParty/mkvfx/extern/OpenImageIO/CMakeFiles/CMakeError.log".

Here's the CMakeError.log, and after that CMakeOutput.log

Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: /usr/bin/c++
Build flags: -isystem
Id flags:

The output was:
1
clang: error: no input files

Determining if the CXX compiler works failed with the following output:
Change Dir: /Users/dp/ThirdParty/mkvfx/extern/OpenImageIO/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTryCompileExec3495021755/fast"
/Applications/Xcode6-Beta3.app/Contents/Developer/usr/bin/make -f CMakeFiles/cmTryCompileExec3495021755.dir/build.make CMakeFiles/cmTryCompileExec3495021755.dir/build
/Applications/CMake.app/Contents/bin/cmake -E cmake_progress_report /Users/dp/ThirdParty/mkvfx/extern/OpenImageIO/CMakeFiles/CMakeTmp/CMakeFiles 1
Building CXX object CMakeFiles/cmTryCompileExec3495021755.dir/testCXXCompiler.cxx.o
/usr/bin/c++    -isystem     -o CMakeFiles/cmTryCompileExec3495021755.dir/testCXXCompiler.cxx.o -c /Users/dp/ThirdParty/mkvfx/extern/OpenImageIO/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
clang: error: no such file or directory: 'CMakeFiles/cmTryCompileExec3495021755.dir/testCXXCompiler.cxx.o'
make[1]: *** [CMakeFiles/cmTryCompileExec3495021755.dir/testCXXCompiler.cxx.o] Error 1
make: *** [cmTryCompileExec3495021755/fast] Error 2

Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: /usr/bin/c++
Build flags: -isystem;
Id flags:

The output was:
1
clang: error: no input files

Output log -

The system is: Darwin - 14.0.0 - x86_64
Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
Compiler: /usr/bin/cc 
Build flags: 
Id flags: 

The output was:
0

Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.out"

The C compiler identification is AppleClang, found in "/Users/dp/ThirdParty/mkvfx/extern/OpenImageIO/CMakeFiles/3.0.0/CompilerIdC/a.out"

Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
Compiler: /usr/bin/c++ 
Build flags: -isystem
Id flags: -c

The output was:
0

Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "a.out"

The CXX compiler identification is AppleClang, found in "/Users/dp/ThirdParty/mkvfx/extern/OpenImageIO/CMakeFiles/3.0.0/CompilerIdCXX/a.out"

Determining if the C compiler works passed with the following output:
Change Dir: /Users/dp/ThirdParty/mkvfx/extern/OpenImageIO/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTryCompileExec3553038545/fast"
/Applications/Xcode6-Beta3.app/Contents/Developer/usr/bin/make -f CMakeFiles/cmTryCompileExec3553038545.dir/build.make CMakeFiles/cmTryCompileExec3553038545.dir/build
/Applications/CMake.app/Contents/bin/cmake -E cmake_progress_report /Users/dp/ThirdParty/mkvfx/extern/OpenImageIO/CMakeFiles/CMakeTmp/CMakeFiles 1
Building C object CMakeFiles/cmTryCompileExec3553038545.dir/testCCompiler.c.o
/usr/bin/cc    -o CMakeFiles/cmTryCompileExec3553038545.dir/testCCompiler.c.o   -c /Users/dp/ThirdParty/mkvfx/extern/OpenImageIO/CMakeFiles/CMakeTmp/testCCompiler.c
Linking C executable cmTryCompileExec3553038545
/Applications/CMake.app/Contents/bin/cmake -E cmake_link_script CMakeFiles/cmTryCompileExec3553038545.dir/link.txt --verbose=1
/usr/bin/cc    -Wl,-search_paths_first -Wl,-headerpad_max_install_names   CMakeFiles/cmTryCompileExec3553038545.dir/testCCompiler.c.o  -o cmTryCompileExec3553038545  

Detecting C compiler ABI info compiled with the following output:
Change Dir: /Users/dp/ThirdParty/mkvfx/extern/OpenImageIO/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTryCompileExec2852289994/fast"
/Applications/Xcode6-Beta3.app/Contents/Developer/usr/bin/make -f CMakeFiles/cmTryCompileExec2852289994.dir/build.make CMakeFiles/cmTryCompileExec2852289994.dir/build
/Applications/CMake.app/Contents/bin/cmake -E cmake_progress_report /Users/dp/ThirdParty/mkvfx/extern/OpenImageIO/CMakeFiles/CMakeTmp/CMakeFiles 1
Building C object CMakeFiles/cmTryCompileExec2852289994.dir/CMakeCCompilerABI.c.o
/usr/bin/cc    -o CMakeFiles/cmTryCompileExec2852289994.dir/CMakeCCompilerABI.c.o   -c /Applications/CMake.app/Contents/share/cmake-3.0/Modules/CMakeCCompilerABI.c
Linking C executable cmTryCompileExec2852289994
/Applications/CMake.app/Contents/bin/cmake -E cmake_link_script CMakeFiles/cmTryCompileExec2852289994.dir/link.txt --verbose=1
/usr/bin/cc    -Wl,-search_paths_first -Wl,-headerpad_max_install_names -v -Wl,-v CMakeFiles/cmTryCompileExec2852289994.dir/CMakeCCompilerABI.c.o  -o cmTryCompileExec2852289994   
Apple LLVM version 6.0 (clang-600.0.38) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.0.0
Thread model: posix
 "/Applications/Xcode6-Beta3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld" -demangle -dynamic -arch x86_64 -macosx_version_min 10.10.0 -o cmTryCompileExec2852289994 -search_paths_first -headerpad_max_install_names -v CMakeFiles/cmTryCompileExec2852289994.dir/CMakeCCompilerABI.c.o -lSystem /Applications/Xcode6-Beta3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/6.0/lib/darwin/libclang_rt.osx.a
@(#)PROGRAM:ld  PROJECT:ld64-241.4
configured to support archs: armv6 armv7 armv7s arm64 i386 x86_64 x86_64h armv6m armv7m armv7em
Library search paths:
	/usr/lib
	/usr/local/lib
Framework search paths:
	/Library/Frameworks/
	/System/Library/Frameworks/

Parsed C implicit link information from above output:
  link line regex: [^( *|.*[/\])(ld|([^/\]+-)?ld|collect2)[^/\]*( |$)]
  ignore line: [Change Dir: /Users/dp/ThirdParty/mkvfx/extern/OpenImageIO/CMakeFiles/CMakeTmp]
  ignore line: []
  ignore line: [Run Build Command:"/usr/bin/make" "cmTryCompileExec2852289994/fast"]
  ignore line: [/Applications/Xcode6-Beta3.app/Contents/Developer/usr/bin/make -f CMakeFiles/cmTryCompileExec2852289994.dir/build.make CMakeFiles/cmTryCompileExec2852289994.dir/build]
  ignore line: [/Applications/CMake.app/Contents/bin/cmake -E cmake_progress_report /Users/dp/ThirdParty/mkvfx/extern/OpenImageIO/CMakeFiles/CMakeTmp/CMakeFiles 1]
  ignore line: [Building C object CMakeFiles/cmTryCompileExec2852289994.dir/CMakeCCompilerABI.c.o]
  ignore line: [/usr/bin/cc    -o CMakeFiles/cmTryCompileExec2852289994.dir/CMakeCCompilerABI.c.o   -c /Applications/CMake.app/Contents/share/cmake-3.0/Modules/CMakeCCompilerABI.c]
  ignore line: [Linking C executable cmTryCompileExec2852289994]
  ignore line: [/Applications/CMake.app/Contents/bin/cmake -E cmake_link_script CMakeFiles/cmTryCompileExec2852289994.dir/link.txt --verbose=1]
  ignore line: [/usr/bin/cc    -Wl,-search_paths_first -Wl,-headerpad_max_install_names -v -Wl,-v CMakeFiles/cmTryCompileExec2852289994.dir/CMakeCCompilerABI.c.o  -o cmTryCompileExec2852289994   ]
  ignore line: [Apple LLVM version 6.0 (clang-600.0.38) (based on LLVM 3.5svn)]
  ignore line: [Target: x86_64-apple-darwin14.0.0]
  ignore line: [Thread model: posix]
  link line: [ "/Applications/Xcode6-Beta3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld" -demangle -dynamic -arch x86_64 -macosx_version_min 10.10.0 -o cmTryCompileExec2852289994 -search_paths_first -headerpad_max_install_names -v CMakeFiles/cmTryCompileExec2852289994.dir/CMakeCCompilerABI.c.o -lSystem /Applications/Xcode6-Beta3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/6.0/lib/darwin/libclang_rt.osx.a]
    arg [/Applications/Xcode6-Beta3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld] ==> ignore
    arg [-demangle] ==> ignore
    arg [-dynamic] ==> ignore
    arg [-arch] ==> ignore
    arg [x86_64] ==> ignore
    arg [-macosx_version_min] ==> ignore
    arg [10.10.0] ==> ignore
    arg [-o] ==> ignore
    arg [cmTryCompileExec2852289994] ==> ignore
    arg [-search_paths_first] ==> ignore
    arg [-headerpad_max_install_names] ==> ignore
    arg [-v] ==> ignore
    arg [CMakeFiles/cmTryCompileExec2852289994.dir/CMakeCCompilerABI.c.o] ==> ignore
    arg [-lSystem] ==> lib [System]
    arg [/Applications/Xcode6-Beta3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/6.0/lib/darwin/libclang_rt.osx.a] ==> lib [/Applications/Xcode6-Beta3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/6.0/lib/darwin/libclang_rt.osx.a]
  Library search paths: [;/usr/lib;/usr/local/lib]
  Framework search paths: [;/Library/Frameworks/;/System/Library/Frameworks/]
  remove lib [System]
  collapse lib [/Applications/Xcode6-Beta3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/6.0/lib/darwin/libclang_rt.osx.a] ==> [/Applications/Xcode6-Beta3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/6.0/lib/darwin/libclang_rt.osx.a]
  collapse library dir [/usr/lib] ==> [/usr/lib]
  collapse library dir [/usr/local/lib] ==> [/usr/local/lib]
  collapse framework dir [/Library/Frameworks/] ==> [/Library/Frameworks]
  collapse framework dir [/System/Library/Frameworks/] ==> [/System/Library/Frameworks]
  implicit libs: [/Applications/Xcode6-Beta3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/6.0/lib/darwin/libclang_rt.osx.a]
  implicit dirs: [/usr/lib;/usr/local/lib]
  implicit fwks: [/Library/Frameworks;/System/Library/Frameworks]

Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
Compiler: /usr/bin/c++ 
Build flags: -isystem;
Id flags: -c

The output was:
0

Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "a.out"

The CXX compiler identification is AppleClang, found in "/Users/dp/ThirdParty/mkvfx/extern/OpenImageIO/CMakeFiles/3.0.0/CompilerIdCXX/a.out"

Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
Compiler: /usr/bin/c++ 
Build flags: -isystem;
Id flags: -c

The output was:
0

Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "a.out"

The CXX compiler identification is AppleClang, found in "/Users/dp/ThirdParty/mkvfx/extern/OpenImageIO/CMakeFiles/3.0.0/CompilerIdCXX/a.out"

Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
Compiler: /usr/bin/c++ 
Build flags: -isystem;
Id flags: -c

The output was:
0

Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "a.out"

The CXX compiler identification is AppleClang, found in "/Users/dp/ThirdParty/mkvfx/extern/OpenImageIO/CMakeFiles/3.0.0/CompilerIdCXX/a.out"

**Comment by nieder** [comment]
Why are you using such an old version of Xcode?  Latest is 6.1.1. If you still want to use such an old version, make sure Xcode and the command line tools are at the same version.

**Comment by meshula** [comment]
Good point. Was mucking about with xcodeselect. With 6.1.1 (The CXX compiler identification is AppleClang 6.0.0.6000056) I get the same result. Cmake is 3.1.1

The compiler tests all fail one after in the same way. I wonder if the temp files are actually being generated somewhere else besides the CMakeFiles/CMakeTmp directory...


Determining if the CXX compiler works failed with the following output:
Change Dir: /Users/dp/ThirdParty/mkvfx/extern/OpenImageIO/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTryCompileExec3495021755/fast"
/Applications/Xcode6-Beta3.app/Contents/Developer/usr/bin/make -f CMakeFiles/cmTryCompileExec3495021755.dir/build.make CMakeFiles/cmTryCompileExec3495021755.dir/build
/Applications/CMake.app/Contents/bin/cmake -E cmake_progress_report /Users/dp/ThirdParty/mkvfx/extern/OpenImageIO/CMakeFiles/CMakeTmp/CMakeFiles 1
Building CXX object CMakeFiles/cmTryCompileExec3495021755.dir/testCXXCompiler.cxx.o
/usr/bin/c++    -isystem     -o CMakeFiles/cmTryCompileExec3495021755.dir/testCXXCompiler.cxx.o -c /Users/dp/ThirdParty/mkvfx/extern/OpenImageIO/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
clang: error: no such file or directory: 'CMakeFiles/cmTryCompileExec3495021755.dir/testCXXCompiler.cxx.o'
make[1]: *** [CMakeFiles/cmTryCompileExec3495021755.dir/testCXXCompiler.cxx.o] Error 1
make: *** [cmTryCompileExec3495021755/fast] Error 2


Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: /usr/bin/c++ 
Build flags: -isystem;
Id flags: 

The output was:
1
clang: error: no input files

**Comment by meshula** [comment]
Checked the cmake sources. The test it is failing on is trivial, so nothing is lost by bypassing it with a 

 -D CMAKE_CXX_COMPILER_WORKS=1

on the command line. 

For reference, the test for a working C++ compiler is to make the following file and try to compile it. For whatever reason, the file does not get created where the generated Makefile wants it. Probably something weird in my system somewhere. Only affects OIIO and nothing else, so moving on.

  FILE(WRITE ${CMAKE_BINARY_DIR}${CMAKE_FILES_DIRECTORY}/CMakeTmp/testCXXCompiler.cxx 
    "#ifndef __cplusplus\n"
    "# error \"The CMAKE_CXX_COMPILER is set to a C compiler\"\n"
    "#endif\n"
    "int main(){return 0;}\n")

**Comment by lgritz** [comment]
Weird. Well, if you ever figure out exactly why this is failing on your system, let us know in case it comes up for somebody else. And why wouldn't it have the same problem for any other cmake-based project?

**Comment by meshula** [comment]
I'm working on a fairly complex build script, and it's possible I've tied something in a knot somewhere. At some point soon, I'll be scrubbing my system clean and starting over. If I can get repro on a clean system, I'll chase it all the way to ground and report.
