### ISSUE TITLE
1.5 build warnings with clang

### ISSUE THREAD

**Issue by ThiagoIze** [OpenImageIO/oiio#1069]
Building OIIO 1.5.12 with clang 3.3 and earlier gives the following warning:
```
In file included from src/libutil/fmath_test.cpp:31:
src/include/OpenImageIO/fmath.h:86:35: error: comparison of unsigned expression >= 0 is always true [-Werror,-Wtautological-compare]
    return (x & (x-1)) == 0 && (x >= 0);
                                ~ ^  ~
src/libutil/fmath_test.cpp:55:28: note: in instantiation of function template specialization 'OpenImageIO::v1_5::ispow2<unsigned long>' requested
      here
        OIIO_CHECK_ASSERT (ispow2(i));
                           ^
src/include/OpenImageIO/unittest.h:44:7: note: expanded from macro 'OIIO_CHECK_ASSERT'
    ((x) ? ((void)0)                                                    \
      ^
```

This was fixed in clang 3.4 (http://llvm.org/bugs/show_bug.cgi?id=8682), but for those of us still stuck with earlier clang builds, one way to fix this is by temporarily disabling the warning with a bunch of ugly code:

```c++
#ifdef __clang__
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wtautological-compare"
#endif

    // Numerous references for this bit trick are on the web.  The
    // principle is that x is a power of 2 <=> x == 1<<b <=> x-1 is
    // all 1 bits for bits < b.
    return (x & (x-1)) == 0 && (x >= 0);

#ifdef __clang__
#pragma clang diagnostic pop
#endif
```

Another warning comes when we try to build our code with OIIO:
```
OpenImageIO/include/OpenImageIO/platform.h:225:23: error: unused function 'bigendian' [-Werror,-Wunused-function]
OIIO_FORCEINLINE bool bigendian (void)
                      ^
```
I suppose we could fix this in the same way, by using a pragma to ignore the warning, but a cleaner solution is to make the function static:
```c++
static OIIO_FORCEINLINE bool bigendian (void)
{
    return ! littleendian();
}
```

**Comment by lgritz** [comment]
Sorry, Thiago, this seems to have slipped through the cracks. Or at least, we never closed this.

I think that in both master and 1.5, we have long since set both `-Wno-unused-function` and `-Wno-tautological-compare`, so this should no longer be an issue, even on clang 3.3.

Is it still a problem for you?

**Comment by ThiagoIze** [comment]
We've since upgraded way past clang 3.3, so I guess the tautological-compare issue doesn't matter anymore for us.  On top of that, I see the `-Wno-tautological-compare` was added a couple months ago, so even if we still used an old clang we'd be fine.  

Personally, I'd prefer to keep the tautological-compare warning active for clang 3.4 and above since it does raise legitimate warnings.  If we find that it's giving false positives, then we could consider disabling that warning, but after clang 3.4, that doesn't seem to happen.

The `-Wno-unused-function` was added years ago, but if I recall, the problem we have with the unused function warning is that this is occurring when we build our software which includes the platform.h header file, not when we build OIIO, so whatever compiler flags are added to OIIO doesn't really help us.  We could suppress this inside of our software's build, but we like having the unused function warning.  Having said that, it looks like with our latest clang this problem also doesn't occur.

**Comment by lgritz** [comment]
IIRC, I need to leave both of those warning suppressions in place for the OIIO build because of 3rd party libraries. 

But in any case, seems like clang 3.3 was too aggressive (an unused *inline* function should never have been a warning, that happens all the time). So closing.
