### ISSUE TITLE
error building: 'TIFFCreateEXIFDirectory' was not declared in this scope

### ISSUE THREAD

**Issue by britalmeida** [OpenImageIO/oiio#1117]
Hi,
I have downloaded oiio-Release-1.5.13
typed 'make' and I get the following errors:

    [ 78%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/tiff.imageio/tiffoutput.cpp.o
    /home/.../oiio-Release-1.5.13/src/tiff.imageio/tiffoutput.cpp: In member function 'bool OpenImageIO::v1_5::TIFFOutput::write_exif_data()':
    /home/.../oiio-Release-1.5.13/src/tiff.imageio/tiffoutput.cpp:549:39: error: 'TIFFCreateEXIFDirectory' was not declared in this scope
         if (TIFFCreateEXIFDirectory (m_tif) != 0) {
                                           ^
    /home/.../oiio-Release-1.5.13/src/tiff.imageio/tiffoutput.cpp:586:5: error: 'uint64' was not declared in this scope
         uint64 dir_offset = 0;
         ^
    /home/.../oiio-Release-1.5.13/src/tiff.imageio/tiffoutput.cpp:586:12: error: expected ';' before 'dir_offset'
         uint64 dir_offset = 0;
                ^
    /home/.../oiio-Release-1.5.13/src/tiff.imageio/tiffoutput.cpp:587:45: error: 'dir_offset' was not declared in this scope
         if (! TIFFWriteCustomDirectory (m_tif, &dir_offset)) {
                                                 ^
    /home/.../oiio-Release-1.5.13/src/tiff.imageio/tiffoutput.cpp:587:55: error: 'TIFFWriteCustomDirectory' was not declared in this scope
         if (! TIFFWriteCustomDirectory (m_tif, &dir_offset)) {
                                                           ^
    /home/.../oiio-Release-1.5.13/src/tiff.imageio/tiffoutput.cpp:594:43: error: 'dir_offset' was not declared in this scope
         TIFFSetField (m_tif, TIFFTAG_EXIFIFD, dir_offset);
                                               ^
    make[3]: *** [src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/tiff.imageio/tiffoutput.cpp.o] Error 1
    make[3]: Leaving directory `/home/.../oiio-Release-1.5.13/build/linux64'
    make[2]: *** [src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/all] Error 2
    make[2]: Leaving directory `/home/.../oiio-Release-1.5.13/build/linux64'
    make[1]: *** [all] Error 2
    make[1]: Leaving directory `/home/.../oiio-Release-1.5.13/build/linux64'
    make: *** [cmake] Error 2

Tried 1.5.12 too, with the same results.

**Comment by lgritz** [comment]
What version of libtiff do you have installed?

**Comment by britalmeida** [comment]
libtiff-3.9.7-x86_64-1

**Comment by lgritz** [comment]
Would you mind, find your tiffvers.h, and look for the line that defines TIFFLIB_VERSION, and let me know what it says?

**Comment by lgritz** [comment]
I see what's going on. I assumed that TIFFLIB_VERSION would increase monotonically and be a reliable way to detect whether a version is new enough to contain recently-added API calls (for example, TIFFCreateEXIFDirectory is in TIFF 4.x, but not 3.x).

But haha, joke is on me -- 3.9.7 has a TIFFLIB_VERSION that's the same as 4.0.3. Oy.

I'll try to figure out an alternate way to do the conditional compilation to avoid these errors.

**Comment by britalmeida** [comment]
If I'm not too late, my TIFFLIB_VERSION is:
#define TIFFLIB_VERSION 20120922

Thank you for your interest on this

**Comment by lgritz** [comment]
Yeah, I downloaded a couple different versions. It seems that this TIFFLIB_VERSION grows monotonically within each major release (3.x vs 4.x) but they are not unique. That is, you can have a TIFFLIB_VERSION number in 3.9.x that's higher than one in 4.0.x. But I have another idea, stay tuned...

**Comment by britalmeida** [comment]
I will, thanks!

**Comment by lgritz** [comment]
OK, there is a spot in tiffoutput.cpp where it says

    #if TIFFLIB_VERSION >= 20120922

change that line to instead say

    #if defined(TIFF_VERSION_BIG) && TIFFLIB_VERSION >= 20120922

and see if you get a clean build that way.
