### ISSUE TITLE
PNG writer doesn't use PixelAspectRatio

### ISSUE THREAD

**Issue by mjmvisser** [OpenImageIO/oiio#1135]
I'm not actually sure if this is a bug or a limitation of the PNG file format, but a PixelAspectRatio other than 1.0 is lost when converting to png.

**Comment by lgritz** [comment]
I think #1142 should fix this.

**Comment by mjmvisser** [comment]
Kinda fixed. Metadata is propagated correctly when outputting PNG, but unfortunately no viewer I tried respects it (imagemagick's display, RV, nuke and ffmpeg). Though if I took the same png and converted it back to dpx, RV showed it with the correct PAR.

Is there a way to bake the PAR into the output with oiiotool? My use case is generating quicktimes with an OCIO color space baked in, so png is just an intermediate format.

BTW (unrelated), I had a build error (well, warning) until I commented out imagebufalgo_compare.cpp empty_sample_region:
/home/mvisser/workspace/oiio/src/libOpenImageIO/imagebufalgo_compare.cpp:648: error: ‘bool OpenImageIO::v1_6::empty_sample_region(const OpenImageIO::v1_6::ImageBuf&, OpenImageIO::v1_6::ROI)’ defined but not used

**Comment by lgritz** [comment]
Mark, is it possible for you to send me a PNG with a *correctly* set pixel aspect ratio (non-1.0) that displays properly in your viewer of choice, so I can examine the image versus ours and see exactly which metadata we are failing to set?

**Comment by lgritz** [comment]
I'm fixing the compile error right now, just removing that unused inline function and will push it out to master.

**Comment by lgritz** [comment]
As for the oiiotool question, this is what I think should work:

    oiiotool input.png --attrib PixelAspectRation 2.0 -o out.png

This doesn't scale the image, it just changes the metadata saying what the PAR is.

**Comment by mjmvisser** [comment]
You're doing it right. Here's a non-square pixel PNG from PngSuite: http://www.schaik.com/pngsuite/cdfn2c08.png

The problem is that no viewers actually use the metadata to display non-square pixels. e.g. even viewing this page in Chrome doesn't render non-square-pixel pngs correctly: http://www.schaik.com/pngsuite/pngsuite_cnk_png.html 

Is iv supposed to handle non-square pixels? It doesn't seem to.

For my second question, I think I need something like:

    oiiotool input.dpx --pixelscale 1.0 square.png

This hypothetical command would compute an appropriate scale factor so that the output has the given PAR. Given an input that is 16x32 with a PAR of 2.0, the output would be 32x32 with a PAR of 1.0.

**Comment by mjmvisser** [comment]
I'll send a pull request for the proposed --pixelscale action tomorrow.

**Comment by lgritz** [comment]
neat!

You might also be able to do something like

    oiiotool input.dpx --resize {TOP.width*TOP.PixelAspectRatio}x{TOP.height} -attrib PixelAspectRatio 1.0 -o out.png

Though I agree that if this is common, it's easier to have a single --pixelscale command.

Should I go ahead and merge the PNG fixes of this PR?

It's probably not hard to make 'iv' scale correctly for display, but I don't recall having tried to make it do that when I wrote it.

**Comment by lgritz** [comment]
I merged the PNG part of the fix.

**Comment by mjmvisser** [comment]
I'm not sure if this is a bug or feature, but if you're reading and writing a PNG that has PixelAspectRatio/XResolution/YResolution attributes, you must set all three for the pixel aspect to "stick". e.g.

    $ oiiotool cdfn2c08.png -attrib PixelAspectRatio 1.0 -o out.png
    $ oiiotool -v --info out.png
    Reading out.png
    out.png              :    8 x   32, 3 channel, uint8 png
        channel list: R, G, B
        oiio:Gamma: 1
        oiio:ColorSpace: "Linear"
        Exif:ImageHistory: "./oiiotool cdfn2c08.png -attrib PixelAspectRatio 1.0 -o out.png"
        Software: "OpenImageIO 1.6.3dev : ./oiiotool cdfn2c08.png -attrib PixelAspectRatio 1.0 -o out.png"
        ResolutionUnit: "none"
        XResolution: 1
        YResolution: 4
        PixelAspectRatio: 4
    
    $ oiiotool cdfn2c08.png -attrib PixelAspectRatio 1.0 -attrib XResolution 1 -attrib YResolution 1 -o out.png
    $ oiiotool -v --info out.png
    Reading out.png
    out.png              :    8 x   32, 3 channel, uint8 png
        channel list: R, G, B
        oiio:Gamma: 1
        oiio:ColorSpace: "Linear"
        Exif:ImageHistory: "./oiiotool cdfn2c08.png -attrib PixelAspectRatio 1.0 -attrib XResolution 1 -attrib YResolution 1 -o out.png"
        Software: "OpenImageIO 1.6.3dev : ./oiiotool cdfn2c08.png -attrib PixelAspectRatio 1.0 -attrib XResolution 1 -attrib YResolution 1 -o out.png"

**Comment by lgritz** [comment]
Mark, sorry for the delay, I've been chasing an unrelated bug (not even in OIIO) for several days and it's been all-consuming.

I'm confused by this last comment you made. Is this against the current master, the one with my recent PNG fixes? Because I'm not quite getting this behavior.

**Comment by mjmvisser** [comment]
Whoops, you're right, it works as advertised. My git-fu needs work.
