### ISSUE TITLE
convert_image question

### ISSUE THREAD

**Issue by kirijiri** [OpenImageIO/oiio#1138]
I'm converting an RGBA float to RGBA half and have noticed some unexpected behaviour.
in imageio.cpp lines 554-555

    bool contig = (src_xstride == dst_xstride && 
                  src_xstride == stride_t(nchannels*src_type.size()));

Shouldn't the comparison of `src_xstride` with `stride_t` read

    src_xstride == stride_t(nchannels*dst_type.size())

comparing the `src_xstride` with the num channels times `dst_type.size()`?

**Comment by lgritz** [comment]
I don't think so.

The test is whether we can convert a whole scanline at a time, or if we have to go pixel by pixel.  So for an RGBA image,

    RGBARGBARGBA        (contiguous, can do it in one shot)
    RGBA...RGBA...RGBA  (not contiguous, must do pixels separately and leave the ... alone)

So part of what we're testing for is whether the stride (distance between 'R's) is the same as the number of channels times the size per channel. That tells us whether there is "extra stuff" in each pixel that should not be copied or overwritten.

However, I'm a little uneasy about the conditional. It's the *other* clause that worries me -- who cares if src_xstride and dst_xstride are the same? In fact, we expect them to be different if we are doing many varieties of data conversion.

I am tempted to think that the correct test is

    bool contig = src_xstride == stride_t(nchannels*src_type.size()) &&
                  dst_xstride == stride_t(nchannels*dst_type.size());

What do you think about that?

**Comment by kirijiri** [comment]
Hello and thanks for getting back to me.
Your fix works fine for me! I just tested it.

I'm sure I just don't quite understand AutoStride. I figured
channels*type.size() would be the stride, so it'd always be true, but it
seems like that is not the case. I will have to check how it actually works.

Thanks for having a look at it. If this could be in future versions of
oiio, I would appreciate it.
Claudia

**Comment by lgritz** [comment]
Yes, I'll port this fix to both master and RB-1.5 today.

**Comment by lgritz** [comment]
PR #1144 addresses this. I'll merge later today if there are no objections from anyone.

**Comment by lgritz** [comment]
Closing because #1144 fixed it.

**Comment by kirijiri** [comment]
thank you very much
