### ISSUE TITLE
ImageBufAlgo zero/fill modifies at least one row/column even if ROI width/height is zero

### ISSUE THREAD

**Issue by Tristimulus** [OpenImageIO/oiio#1139]
Hi.

When we apply a black mask to an image using ImageBufAlgo::zero with a ROI that has a width of zero we still get a single column of black pixels - which we didn't expect.
Is that supposed to happen?
It looks like the width and height of the fill area are forced to be at least 1 (I'm guessing to protect against a devide-by-zero):

https://github.com/OpenImageIO/oiio/blob/master/src/libOpenImageIO/imagebufalgo_draw.cpp#L121-L122

But shouldn't the function simply return instead in this case?

Kind Regards,
Matthias

**Comment by lgritz** [comment]
I would think so, yes. I consider that a bug. Hang on, I'll fix immediately.

**Comment by Tristimulus** [comment]
Hi Larry.

Ok, brilliant and thanks for getting back so quickly!

Matthias

**Comment by lgritz** [comment]
Proposed fix (a general solution, not just for fill) is in #1141.
