### ISSUE TITLE
docbug: section on expressions doesn't mention lack of operator precedence or parens

### ISSUE THREAD

**Issue by mjmvisser** [OpenImageIO/oiio#1149]
After an hour of head-scratching, I found this in the commit message for expressions:

> * Simple arithmetic: expr + expr, expr - expr, expr * expr, expr / expr
> (simple left to right evaluation, no operator precedence)

Which isn't mentioned in the docs.

The comment in oiiotool.h is also inaccurate:

    // Expand substitution expressions in string str. Expressions are
    // enclosed in braces: {...}. An expression consists of:
    //   * a numeric constant ("42" or "3.14")
    //   * a parenthesized expression ("(expr)")

**Comment by lgritz** [comment]
Oops. Will fix right away.

**Comment by lgritz** [comment]
Fixed, and I also rebuild the PDF docs for master, it had been a while.
