### ISSUE TITLE
oiio1.5.11 seg faults when trying to resize a deep exr

### ISSUE THREAD

**Issue by ian-watson** [OpenImageIO/oiio#1169]
we are trying to create proxy versions of our deep renders (mostly from maya/vray) and have been getting the following error when trying a 25% resize on a sample image:

$ /ce_apps/linux/openimageio1.5.11/dist/linux64/bin/oiiotool /syd_prod/vfx/obic/shots/crw_051_010/pic/crw_051_010_deepTest_v01_t01_bm/crw_051_010_deepTest_v01_t01_bm.0102.exr --resize 25% -o /scratch/deep_resize__crw_051_010_deepTest_v01_t01_bm.0102.exr
Segmentation fault (core dumped)

$ /ce_apps/linux/openimageio1.5.11/dist/linux64/bin/iinfo /syd_prod/vfx/obic/shots/crw_051_010/pic/crw_051_010_deepTest_v01_t01_bm/crw_051_010_deepTest_v01_t01_bm.0102.exr  
/syd_prod/vfx/obic/shots/crw_051_010/pic/crw_051_010_deepTest_v01_t01_bm/crw_051_010_deepTest_v01_t01_bm.0102.exr : 2048 x 1556, 85 channel, deep half/half/half/half/float/float/uint/float/float/uint/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half/half openexr

Cheers,

Ian Watson
Cutting Edge Sydney

**Comment by lgritz** [comment]
I'll definitely try to fix it to give a good error message instead of crashing, but I don't expect resize to "work" for deep images.

What "should" happen? I suppose that if you are downsizing by a whole-number ratio in both dimensions, you could just combine all the samples from the covered pixels? But anything other than a whole number resize wouldn't seem to have a lot of meaning. Or am I wrong?

**Comment by lgritz** [comment]
Closing, as this has long since been fixed. (For the value of "fixed" == "instead of crashing, it issues an error message about resize not working for deep images".)
