### ISSUE TITLE
ustring::string() returns empty string when using the new C++11 ABI

### ISSUE THREAD

**Issue by foutrelis** [OpenImageIO/oiio#1174]
I noticed that when using GCC 5.1 with the new [libstdc++ ABI](https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html) enabled, `oslc foo.osl` (from OpenShadingLanguage) would choose `.oso` as the output filename instead of `foo.oso`.

oslc uses `shader_decl()->shadername().string() + ".oso"` as the default output filename if one is not provided via the `-o` option. Further testing indicates that OpenImageIO's `ustring::string()` method is broken and returns an empty string on the new C++11 ABI.

Bellow is an example test program and GDB backtrace that show the issue.

```c
#include <OpenImageIO/ustring.h>

int main(void) {
    auto a = OpenImageIO::v1_4::ustring("123");
    std::string b = "123";

    std::cout << "a = " << a.string() << std::endl << "b = " << b << std::endl;
    return 0;
}
```

```
Breakpoint 1, main () at test.cc:8
8		std::cout << "a = " << a.string() << std::endl << "b = " << b << std::endl;

(gdb) p a
$1 = {static npos = 18446744073709551615, m_chars = 0x61d870 "123", 
  static empty_std_string = <optimized out>}

(gdb) p a.string
$2 = {const std::__cxx11::string &(const OpenImageIO::v1_4::ustring * const)} 0x4010e6 <OpenImageIO::v1_4::ustring::string[abi:cxx11]() const>

(gdb) p &a.string()
$3 = (const std::__cxx11::string *) 0x61d838

(gdb) p a.string()
$4 = ""

(gdb) c
Continuing.
a = 
b = 123
```

**Comment by lgritz** [comment]
Can you test this workaround? https://github.com/OpenImageIO/oiio/pull/1176

**Comment by foutrelis** [comment]
Seems to work, thanks!

Please note that most (if not all) Linux distros configure GCC 5.1 to use the old ABI (using `--with-default-libstdcxx-abi=c++98`). The issue won't manifest in such configurations, though building OIIO and its dependencies with `-D_GLIBCXX_USE_CXX11_ABI=1` should be enough to reproduce it.
