### ISSUE TITLE
LIBRAW_DECODER_FLATFIELD no longer supported

### ISSUE THREAD

**Issue by cwilling** [OpenImageIO/oiio#1203]
The most recent version of LibRaw (0.17.0) no longer defines LIBRAW_DECODER_FLATFIELD, therefore compilation of oiio fails with:
/tmp/SBo/oiio-Release-1.5.18/src/raw.imageio/rawinput.cpp: In member function ‘virtual bool OpenImageIO::v1_5::RawInput::open(const string&, OpenImageIO::v1_5::ImageSpec&, const OpenImageIO::v1_5::ImageSpec&)’:
/tmp/SBo/oiio-Release-1.5.18/src/raw.imageio/rawinput.cpp:207:48: error: ‘LIBRAW_DECODER_FLATFIELD’ was not declared in this scope
             if (!(decoder_info.decoder_flags & LIBRAW_DECODER_FLATFIELD)) {

Removing the relevant lines from rawinput.cpp allows the build to complete, as does hiding them behind an #ifdef LIBRAW_DECODER_FLATFIELD (enabling its use with older versions of LibRaw). Not sure if that has unintended runtime consequences though.

chris

**Comment by lgritz** [comment]
Fixed in #1204
