### ISSUE TITLE
Build fail on 1.5.19

### ISSUE THREAD

**Issue by Justinzobel** [OpenImageIO/oiio#1215]
+ make -j5
Scanning dependencies of target OpenImageIO_Util
Scanning dependencies of target OpenImageIO
[  1%] [  1%] [  2%] [  2%] Building CXX object src/libutil/CMakeFiles/OpenImageIO_Util.dir/errorhandler.cpp.o
Building CXX object src/libutil/CMakeFiles/OpenImageIO_Util.dir/filter.cpp.o
Building CXX object src/libutil/CMakeFiles/OpenImageIO_Util.dir/argparse.cpp.o
Building CXX object src/libutil/CMakeFiles/OpenImageIO_Util.dir/filesystem.cpp.o
[  2%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/exif.cpp.o
[  3%] Building CXX object src/libutil/CMakeFiles/OpenImageIO_Util.dir/hashes.cpp.o
[  3%] Building CXX object src/libutil/CMakeFiles/OpenImageIO_Util.dir/paramlist.cpp.o
[  4%] Building CXX object src/libutil/CMakeFiles/OpenImageIO_Util.dir/plugin.cpp.o
[  5%] Building CXX object src/libutil/CMakeFiles/OpenImageIO_Util.dir/SHA1.cpp.o
[  6%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/formatspec.cpp.o
[  6%] Building CXX object src/libutil/CMakeFiles/OpenImageIO_Util.dir/strutil.cpp.o
[  7%] Building CXX object src/libutil/CMakeFiles/OpenImageIO_Util.dir/sysutil.cpp.o
[  7%] Building CXX object src/libutil/CMakeFiles/OpenImageIO_Util.dir/timer.cpp.o
[  8%] Building CXX object src/libutil/CMakeFiles/OpenImageIO_Util.dir/typedesc.cpp.o
[  8%] Building CXX object src/libutil/CMakeFiles/OpenImageIO_Util.dir/ustring.cpp.o
[  8%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/imagebuf.cpp.o
[  9%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/imageinput.cpp.o
[  9%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/imageio.cpp.o
[ 10%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/imageioplugin.cpp.o
Linking CXX shared library libOpenImageIO_Util.so
[ 10%] Built target OpenImageIO_Util
Scanning dependencies of target array_view_test
[ 10%] Building CXX object src/libutil/CMakeFiles/array_view_test.dir/array_view_test.cpp.o
Linking CXX executable array_view_test
[ 10%] Built target array_view_test
Scanning dependencies of target atomic_test
[ 11%] Building CXX object src/libutil/CMakeFiles/atomic_test.dir/atomic_test.cpp.o
[ 12%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/imageoutput.cpp.o
[ 12%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/iptc.cpp.o
[ 13%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/xmp.cpp.o
Linking CXX executable atomic_test
[ 13%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/color_ocio.cpp.o
libOpenImageIO_Util.so.1.5.19: undefined reference to `boost::match_results<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > >::maybe_assign(boost::match_results<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > const&)'
libOpenImageIO_Util.so.1.5.19: undefined reference to `boost::re_detail::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::construct_init(boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags)'
collect2: error: ld returned 1 exit status
src/libutil/CMakeFiles/atomic_test.dir/build.make:94: recipe for target 'src/libutil/atomic_test' failed
make[2]: *** [src/libutil/atomic_test] Error 1
CMakeFiles/Makefile2:1037: recipe for target 'src/libutil/CMakeFiles/atomic_test.dir/all' failed
make[1]: *** [src/libutil/CMakeFiles/atomic_test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 14%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/imagebufalgo.cpp.o
[ 14%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/imagebufalgo_compare.cpp.o
[ 15%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/imagebufalgo_copy.cpp.o
[ 16%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/imagebufalgo_deep.cpp.o
[ 16%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/imagebufalgo_draw.cpp.o
[ 17%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/imagebufalgo_pixelmath.cpp.o
[ 17%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/imagebufalgo_xform.cpp.o
[ 18%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/imagebufalgo_yee.cpp.o
[ 18%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/imagebufalgo_opencv.cpp.o
[ 19%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/maketexture.cpp.o
[ 20%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/libutil/argparse.cpp.o
[ 20%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/libutil/errorhandler.cpp.o
[ 21%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/libutil/filesystem.cpp.o
[ 21%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/libutil/filter.cpp.o
[ 22%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/libutil/hashes.cpp.o
[ 22%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/libutil/paramlist.cpp.o
[ 23%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/libutil/plugin.cpp.o
[ 24%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/libutil/SHA1.cpp.o
[ 24%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/libutil/strutil.cpp.o
[ 25%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/libutil/sysutil.cpp.o
[ 25%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/libutil/timer.cpp.o
[ 26%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/libutil/typedesc.cpp.o
[ 26%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/libutil/ustring.cpp.o
[ 27%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/libtexture/texturesys.cpp.o
[ 28%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/libtexture/texture3d.cpp.o
[ 28%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/libtexture/environment.cpp.o
[ 29%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/libtexture/texoptions.cpp.o
[ 29%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/libtexture/imagecache.cpp.o
[ 30%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/include/OpenImageIO/pugixml.cpp.o
[ 30%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/bmp.imageio/bmpinput.cpp.o
[ 31%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/bmp.imageio/bmpoutput.cpp.o
[ 32%] [ 32%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/cineon.imageio/cineoninput.cpp.o
Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/bmp.imageio/bmp_pvt.cpp.o
[ 33%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/cineon.imageio/cineonoutput.cpp.o
[ 33%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/cineon.imageio/libcineon/Cineon.cpp.o
[ 34%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/cineon.imageio/libcineon/Codec.cpp.o
[ 34%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/cineon.imageio/libcineon/Reader.cpp.o
[ 35%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/cineon.imageio/libcineon/Writer.cpp.o
[ 36%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/cineon.imageio/libcineon/CineonHeader.cpp.o
[ 36%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/cineon.imageio/libcineon/ElementReadStream.cpp.o
[ 37%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/cineon.imageio/libcineon/InStream.cpp.o
[ 37%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/dds.imageio/ddsinput.cpp.o
[ 38%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/dds.imageio/ddsoutput.cpp.o
[ 38%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/dds.imageio/squish/alpha.cpp.o
[ 39%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/dds.imageio/squish/clusterfit.cpp.o
[ 40%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/dds.imageio/squish/colourblock.cpp.o
[ 40%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/dds.imageio/squish/colourfit.cpp.o
[ 41%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/dds.imageio/squish/colourset.cpp.o
[ 41%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/dds.imageio/squish/maths.cpp.o
[ 42%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/dds.imageio/squish/rangefit.cpp.o
[ 42%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/dds.imageio/squish/singlecolourfit.cpp.o
[ 43%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/dds.imageio/squish/squish.cpp.o
[ 44%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/dpx.imageio/dpxinput.cpp.o
[ 44%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/dpx.imageio/dpxoutput.cpp.o
[ 45%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/dpx.imageio/libdpx/DPX.cpp.o
[ 45%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/dpx.imageio/libdpx/OutStream.cpp.o
[ 46%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/dpx.imageio/libdpx/RunLengthEncoding.cpp.o
[ 46%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/dpx.imageio/libdpx/Codec.cpp.o
[ 47%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/dpx.imageio/libdpx/Reader.cpp.o
[ 48%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/dpx.imageio/libdpx/Writer.cpp.o
[ 48%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/dpx.imageio/libdpx/DPXHeader.cpp.o
[ 49%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/dpx.imageio/libdpx/ElementReadStream.cpp.o
[ 49%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/dpx.imageio/libdpx/InStream.cpp.o
[ 50%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/dpx.imageio/libdpx/DPXColorConverter.cpp.o
[ 50%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/fits.imageio/fitsinput.cpp.o
[ 51%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/fits.imageio/fitsoutput.cpp.o
[ 52%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/fits.imageio/fits_pvt.cpp.o
[ 52%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/hdr.imageio/hdrinput.cpp.o
[ 53%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/hdr.imageio/hdroutput.cpp.o
[ 53%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/hdr.imageio/rgbe.cpp.o
[ 54%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/ico.imageio/icoinput.cpp.o
[ 54%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/ico.imageio/icooutput.cpp.o
[ 55%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/iff.imageio/iffinput.cpp.o
[ 56%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/iff.imageio/iffoutput.cpp.o
[ 56%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/iff.imageio/iff_pvt.cpp.o
[ 57%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/jpeg.imageio/jpeginput.cpp.o
[ 57%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/jpeg.imageio/jpegoutput.cpp.o
[ 58%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/png.imageio/pnginput.cpp.o
[ 58%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/png.imageio/pngoutput.cpp.o
[ 59%] [ 60%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/pnm.imageio/pnminput.cpp.o
Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/pnm.imageio/pnmoutput.cpp.o
[ 60%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/psd.imageio/psdinput.cpp.o
[ 61%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/psd.imageio/psdoutput.cpp.o
[ 61%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/psd.imageio/jpeg_memory_src.cpp.o
[ 62%] [ 62%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/ptex.imageio/ptexinput.cpp.o
Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/ptex.imageio/ptexoutput.cpp.o
[ 63%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/ptex.imageio/ptex/PtexCache.cpp.o
[ 64%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/ptex.imageio/ptex/PtexFilters.cpp.o
[ 64%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/ptex.imageio/ptex/PtexHalf.cpp.o
[ 65%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/ptex.imageio/ptex/PtexReader.cpp.o
[ 65%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/ptex.imageio/ptex/PtexSeparableFilter.cpp.o
[ 66%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/ptex.imageio/ptex/PtexSeparableKernel.cpp.o
[ 66%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/ptex.imageio/ptex/PtexTriangleFilter.cpp.o
[ 67%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/ptex.imageio/ptex/PtexTriangleKernel.cpp.o
[ 68%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/ptex.imageio/ptex/PtexUtils.cpp.o
[ 68%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/ptex.imageio/ptex/PtexWriter.cpp.o
[ 69%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/openexr.imageio/exrinput.cpp.o
[ 69%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/openexr.imageio/exroutput.cpp.o
[ 70%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/rla.imageio/rlainput.cpp.o
[ 70%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/rla.imageio/rlaoutput.cpp.o
[ 71%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/sgi.imageio/sgiinput.cpp.o
[ 72%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/sgi.imageio/sgioutput.cpp.o
[ 72%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/softimage.imageio/softimageinput.cpp.o
[ 73%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/softimage.imageio/softimageoutput.cpp.o
[ 73%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/softimage.imageio/softimage_pvt.cpp.o
[ 74%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/targa.imageio/targainput.cpp.o
[ 74%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/targa.imageio/targaoutput.cpp.o
[ 75%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/tiff.imageio/tiffinput.cpp.o
[ 76%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/tiff.imageio/tiffoutput.cpp.o
[ 76%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/zfile.imageio/zfile.cpp.o
[ 77%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/socket.imageio/socketinput.cpp.o
[ 77%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/socket.imageio/socketoutput.cpp.o
[ 78%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/socket.imageio/socket_pvt.cpp.o
[ 78%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/webp.imageio/webpinput.cpp.o
[ 79%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/webp.imageio/webpoutput.cpp.o
Linking CXX shared library libOpenImageIO.so
[ 79%] Built target OpenImageIO
Makefile:146: recipe for target 'all' failed
make: *** [all] Error 2
Build failure: Command '['/bin/sh', '/tmp/eopkg-buildgkU97z']' returned non-zero exit status 2

**Comment by lgritz** [comment]
I believe we've seen this reported before, and my theory is that you are compiling OIIO with different -std=c++11 than was used when building the boost library you are using.

Do you know which version of boost you are using, and whether it was compiled using C++11 or not?

Try this (bash) to get a full build log:

    make nuke
    make VERBOSE=1

That should at least reveal for sure which C++ standard you are using, and which boost version. But it won't tell us, unfortunately, what build flags were used when building boost.

**Comment by Justinzobel** [comment]
Ahh yes we've recently updated to gcc 5.2 so I'll rebuild boost and see how
I go. Thanks for the awesomely quick response. You can close this, if I run
into further issues I'll re-open.

**Comment by lgritz** [comment]
Great, thanks.

Now that many boost libraries have been incorporated into the C++ standard itself, the boost versions are modified so that when C++11 is detected, they just "wrap" the standard versions, whereas for too-old C++ compilers, boost provides its own implementation.

So if you aren't consistent with compiler versions (and -std= flags!), you can get a situation where boost and oiio don't agree on whether or not the C++ std version is required, and so it's not referenced properly and results in a link error.
