### ISSUE TITLE
Bizzarre tiff causes OIIO segfault.  To fix or not?

### ISSUE THREAD

**Issue by mike1158** [OpenImageIO/oiio#1220]
Somehow, we ended up with a very bizarre .tx file that crashes OpenImageIO when reading some parts of it (as with 'oiiotool --stats', or during a render, for example).  Other than the fact that is is a perfectly valid tiff, I'll spare the details.  I still can't fathom how it was created.  Regardless, the specific cause of the crash is this optimization in tiffinput.cpp:

    // If we're emulating a MIPmap, only resolution is allowed to change
    // between MIP levels, so if we already have a valid level in m_spec,
    // we don't need to re-parse metadata, it's guaranteed to be the same.
    bool read_meta = !(m_emulate_mipmap && m_tif && m_subimage >= 0);

It turns out that in this particular case, that's not a safe assumption.  The question is--what's the best way to keep this optimization and still provide some safety from oddly composed, but otherwise perfectly valid, files?

One thought--add a 'pedantic=1' option (that could be set via env var) which forces read_meta to be always true.

Thoughts?

**Comment by lgritz** [comment]
Can you explain exactly how the metadata is inconsistent in such a way as to break the assumptions?

Can you send me the tx file in question so I can take a closer look?

**Comment by mike1158** [comment]
I knew you'd ask! :)

It's 2048x2048 mipmap'd texture.  Sub-images 0-10 are what you'd expect: 2048x2048, down to 2x2.  Metadata indicates it was written with prman 19 (presumably txmake), LZW compressed separate image planes.  BUT, there are also more sub-images, 11-22, which start at 1024x1024, down to 1x1.  Metadata on those indicate they are from OIIO maketx, AdobeDeflate compressed, single image plane.  I can use tiffsplit to break out all 23, and they all have the correct image and are valid.

So yeah, it's a bizzare monster.  It shouldn't exist.  I have tried to figure out how it was made, but without any success.  We can re-make it properly and fix our render crashes.  But, it took us an annoyingly long time to find it, as most tools don't report it as being invalid (because *technically*, it's not).

The file is 13MB--what's the best way to send it to you?

**Comment by lgritz** [comment]
Wow, so weird! Send me (lg AT larrygritz DOT com) your email address, and I'll share a Dropbox folder with you where you can place it.

**Comment by lgritz** [comment]
I can reproduce it with your example.

It's crashing inside libtiff (when we call TIFFClose). But it may be simply an artifact of something we have corrupted before that point.

I sure don't understand how such a file could possibly have been created! But I can propose a couple checks to allow us to reject a malformed file.

**Comment by mike1158** [comment]
Yes, we also saw that it was crashing in libtiff.  I'm guessing something is running off the end of an array somewhere due to the bizarre data.

But yeah, I'd have no problem having OIIO just spit this file out as unreadable.

Thanks much!

**Comment by lgritz** [comment]
I am kind of suspecting that it's the switch from planar to contig half way through the file that throws it off. I think this is not hard to figure out.

**Comment by lgritz** [comment]
Proposed change in #1221

Try this out, Mike. If it works, I'll backport it to 1.5 as well.

**Comment by mike1158** [comment]
Thanks Larry.  That does fix the oiiotool --stats crash with the texture in question.  I have no way to test the render itself, as it's a 3rd-party product using OIIO 1.3.2dev.  The beta rev of their product is on 1.5.18, and hopefully they'll update to the latest before the final release....

**Comment by lgritz** [comment]
I tried it on my end, looks fine. Basically, it will just find the appropriate MIP levels from the "first half" of the file, and ignore the second half. Stupid, but it makes a picture that is probably what you want. 

I can't fathom how that file would have been created in the first place. I would recommend re-maketx'ing it, and any other that seem to be like that. You can use the existing weird texture as the source input if you wish -- it will just take the top (highest res) level and turn it into a proper texture.

I'll backport the fix to 1.5 and cut a tagged release, just in case that makes it easier for the renderer to upgrade.
