### ISSUE TITLE
Make idiff quiet

### ISSUE THREAD

**Issue by sopvop** [OpenImageIO/oiio#1229]
I'm using idiff for automated testing, and it currently is too noisy for that use case. For me it would be preferable if idiff only outputed anything to stderr on failure.

I propose adding flags:

`-q --quiet` -  Don't output anything to stdout/stderr, user relies on return code. This one is easy.

`-qd` - Don't output anything unless diff fails. This one is a bit more complex, since you'll have to
   output "Comparing a b" message before error messages.

Just making idiff always use stderr will be fine for me, but I think solution should be more generic.

**Comment by lgritz** [comment]
I'm fine with -q meaning a quiet mode that outputs nothing for success, and only printing "FAILURE" to stderr if it fails (and setting return code, of course). Is that sufficient? Or do you truly need NO output to stderr?

Another easy solution is to write your own Python script that uses the OIIO Python bindings to do something like

    #!/usr/bin/env python
    import sys
    import OpenImageIO as oiio
    comp = oiio.ImageBufAlgo.compare (oiio.ImageBuf(sys.argv[1]), oiio.ImageBuf(sys.argv[2]))
    if comp.nwarn > 0 or comp.nfail > 0 :
        exit (-1)
    else : 
        exit (0)

Simple and does exactly what you want.

**Comment by sopvop** [comment]
I'm ok with output to stderr, but currently idiff outputs to stdout which is not that great.
Python script would be ok too, but I still think -q mode would be nice.

**Comment by lgritz** [comment]
Proposed fix in #1231 

Please give it a try on your end and see if the behavior is satisfactory.

**Comment by sopvop** [comment]
Exactly what I need, thank you!
I wanted to submit PR today, and was really surprised that you've implemented it already.

Also, I see that some of the thing which used to be written to stdout are now written to stderr even without flag and I hope this does not break idiff for people who rely on parsing stdout.

**Comment by lgritz** [comment]
Oh, it only took a few minutes.

I did redirect a couple things from stdout to stderr, but only error messages.

**Comment by lgritz** [comment]
Sorry if I stepped on your toes by doing this. Sometimes it's hard to discern whether one of these filed issues is a request for me to do something, or a proposal that somebody else is about to do it.

**Comment by lgritz** [comment]
Do you need this backported to 1.5?

**Comment by sopvop** [comment]
No need, I'm on master.
