### ISSUE TITLE
EXR calculation for PixelAspectRatio broken

### ISSUE THREAD

**Issue by ThiagoIze** [OpenImageIO/oiio#1243]
The code, at least in OIIO 1.5.20, to do this is:

``` c++
    float xdensity = spec.get_float_attribute ("XResolution", 0.0f);
    float ydensity = spec.get_float_attribute ("XResolution", 0.0f);
    if (! aspect && xdensity && ydensity) {
        // No aspect ratio. Compute it from density, if supplied.
        spec.attribute ("PixelAspectRatio", xdensity / ydensity);
    }
```

is ydensity really supposed to be using X and not Y resolution?  As coded, won't this always produce a ratio of 1 if aspect was not previously set?

I guess what happened is that YResolution is not specified by the EXR standard, so the author gave up and committed the following broken code?  If so, maybe it's better just to hard code the aspect ratio to 1.

**Comment by lgritz** [comment]
I'm not sure there is a bug here.

Remember, this may be outputting to exr, but we don't know where the image has come from.

So the logic that this is using is: If the spec gives an aspect ratio, use it. Otherwise, compute it from x and y densities.

There's also logic in the exr reader to set YResolution (implicitly, based on the xresolution and aspect in the exr file being read). 

So in general, this code should be confident that either aspect is set, or both xresolution & yresolution are set, or else it gives up and doesn't attempt to set a non-default aspect ratio.

**Comment by ThiagoIze** [comment]
How is the above code different from:

```c++
    float xdensity = spec.get_float_attribute ("XResolution", 0.0f);
    float ydensity = xdensity;
    if (! aspect && xdensity && ydensity) {
        // No aspect ratio. Compute it from density, if supplied.
        spec.attribute ("PixelAspectRatio", xdensity / ydensity);
    }
```

or even:
```c++
    float xdensity = spec.get_float_attribute ("XResolution", 0.0f);
    if (! aspect && xdensity) {
        // No aspect ratio. Compute it from density, if supplied.
        spec.attribute ("PixelAspectRatio", 1);
    }
```

**Comment by lgritz** [comment]
Oh, crap. Not only did I botch the code with a typo, but I completely misread (clearly did not carefully read) your post here.

So sorry. It's an obvious cut and paste error in the code. I'll submit a patch immediately.

**Comment by lgritz** [comment]
Sometimes you have to just spell it out for me as plainly as possible. I think I would not have botched this one if you had just said:

------

    float xdensity = spec.get_float_attribute ("XResolution", 0.0f);
    float ydensity = spec.get_float_attribute ("XResolution", 0.0f);

The second line should retrieve "YResolution", shouldn't it? Probably a cut-and-paste error.

-----

I'll try to read more and think more carefully about issues as they whiz through my inbox. :-)

**Comment by ZeroCrunch** [comment]
I'm currently having issues with OIIO not using namespaces with OpenEXR on Windows. Anyone else?

**Comment by lgritz** [comment]
@ZeroCrunch  Related to this ticket specifically?

**Comment by ZeroCrunch** [comment]
No. Sorry, in general. My mistake.

**Comment by lgritz** [comment]
It would be better to ask on the oiio-dev mail list, where it would be read by lots of people who have built OIIO on many platforms. These GitHub "issues" are only seen automatically by people who subscribe, which is a tiny slice of the community.

Also, it will help to describe precisely which versions of OIIO and OpenEXR are involved, and exactly what you mean by "issues," directly quoting commands and error messages where possible.

**Comment by lgritz** [comment]
I think this has long since been fixed.
