### ISSUE TITLE
Image Cache race condition

### ISSUE THREAD

**Issue by MrKepzie** [OpenImageIO/oiio#1248]
@lgritz I'm hitting another bug as well:

If  a record of the last file read is kept and this file is invalidated if a different file is read, then we may enter a race condition with multiple threads:
## Thread A:
- _ImageCacheImpl::invalidate(filename)_ will call _ImageCacheFile::invalidate()_ which in turns calls _invalidate_spec()_  which clears _m_subimages_. This operation is **protected** by _m_input_mutex_.
- Set the purge = 1 atomic int  in _purge_perthread_microcaches()_, actually _queueing_ a purge of the _tile_ pointer on **all** the per-threads data (meaning thread B included)
## Thread B:
- Inside ImageCacheImpl::get_pixels, before _purge_perthread_microcaches()_ is called from thread A, so the purge is not actually done by thread B yet (i.e: the _tile_ pointer is not reset)
- The _tile_ member on the per-thread data of thread B is in a dirty state: its spec has been invalidated but the pointer is still around
- An assertion is triggered right after in get_pixels when entering this line:

https://github.com/OpenImageIO/oiio/blob/master/src/libtexture/imagecache.cpp#L2680
Which in turns calls
https://github.com/OpenImageIO/oiio/blob/master/src/libtexture/imagecache.cpp#L1389
Which leads to this assert being triggered:
https://github.com/OpenImageIO/oiio/blob/master/src/libtexture/imagecache_pvt.h#L265

It is triggered because the spec is invalidated (so m_subimages has been cleared) but the pointer can still be accessed. 

It appears to me that there are 2 possible solutions:
- Either take a global lock (ruining multi-threading)
- Let the last thread using the tile (i.e: when the use_count of the ref counted ptr drops to 1)  call invalidate on the ImageCacheFile instead of doing it immediately whilst others could still be using that tile.

**Comment by devernay** [comment]
Note that the cache may be empty when entering check_max_mem, because add_tile_to_cache didn't find the tile and thus holds no lock.
Patch for RB-1.5 available at https://raw.githubusercontent.com/MrKepzie/Natron/5ed58e179312130852ca8e7302ded3fffe97b756/tools/MacOSX/ports/graphics/openimageio/files/oiio-1.5.23-checkmaxmem.patch
(easy to transpose to other branches)

**Comment by MrKepzie** [comment]
This patch fixes potential crash arising from this bug: https://github.com/MrKepzie/Natron/blob/workshop/tools/MacOSX/ports/graphics/openimageio/files/oiio-1.5.23-invalidatespec.patch

It may not "solve" the issue, but at least fixes the crash.

This bug may be reproducible in any application that does the following:

1)- Thread A: Pick a file
2)- Thread A: Install a watcher on the file to get notified from file system modifications (such as removal)
3)- Thread B: Read a file from the OIIO cache 
4)- Thread A: Clear the OIIO cache whenever the handler of the notifier gets called

If 3) is still running while 4) happens, the the crash is likely to happen 

If

**Comment by lgritz** [comment]
I believed this was fixed by #1696, but we never closed the issue. (N.B. An issue will auto-close upon a PR merge if somewhere in the PR discussion there is the phrase "`Fixes #<issue>`".)
