### ISSUE TITLE
EXR-2.0 part/subimage handling in OpenImageIO / oiiotool

### ISSUE THREAD

**Issue by peterhillman** [OpenImageIO/oiio#1271]
Processing EXR-2.0 image sequences with oiiotool becomes complicated when extracting channels from multipart image sequences with varying structure.

EXR-2.0 supports distributing channels within an image throughout multiple 'parts'.
E.g, part 1 may contain "R,G,B", part 2 contain "A", part 3 contain "plate.R","plate.G","plate.B"
Splitting into parts can rarely read channels slowing down access, allow mixing of tiles and scanlines, or allow different compression schemes to be used on different channels.

Parts are handled using subimages in OpenImageIO, but they are conceptually different: EXR parts are still one image, it's just the storage of different channels can be separated. subimages are independent, but related, images.

We have a situation where an extra layer (say "CG.R","CG.G","CG.B","CG.A") appears within the sequence, and gets assigned as part 3. The plate layer is then moved to part 4.
To process just "plate" for all images in a sequence, we need to check the part structure for every file and call oiiotool with the correct -subimage for each frame For some frames, we need to pass "-subimage 3" and for others "-subimage 4".

Possible improvements could be:
 * an option to force an EXR-2.0 to open as a single 'flat' image (parts are merged at load time)
 * support in OpenImageIO to collapse subimages into a single image, combining the channels from each into a single image. This should be the same as doing --sisplit followed by one --chappend for each subimage in the stack (but wouldn't require a priori knowledge of how many parts the file has)
 * support for accessing subimages by name instead of number. EXR-2.0 parts must have a unique name, so doing -subimage "plate" will likely always pull out the right thing regardless of which subimage that is.

**Comment by lgritz** [comment]
Sorry for the delay.

Option 3 sounds best to me: just allow --subimage to take a name. That sounds like the most direct solution, makes total sense. I'll give that a try, stay tuned.

**Comment by lgritz** [comment]
I'm thinking that if the argument to --subimage is an integer, it will be interpreted as the subimage number, and for anything else it will try to look it up by name. 

Does that sound reasonable?

Is anybody concerned about the ambiguity of a subimage #5 that is named "3"? Or does somebody doing something so foolish get what the deserve?

**Comment by peterhillman** [comment]
That sounds reasonable to me. I suppose a safer option would be --subimagename or somesuch, but naming parts things like "3" is such a bad idea it should be discouraged anyway.

Incidentally, either of the first two approaches would allow easy conversion of multipart EXR-2.0 to single part, backwards compatible EXRs, which I think isn't trivial with oiiotool (or indeed with any of the utilities that ship with OpenEXR). It would be nice to add that kind of functionality as well.

**Comment by lgritz** [comment]
Yes, I agree that "turn subimages into channels" would be a good feature as well. I'll do that also.

**Comment by lgritz** [comment]
Proposed fix in #1287 

We'll do this first, then I'll tackle the "subimages to channels" feature.
