### ISSUE TITLE
master fails to compile on CentOS 6.6

### ISSUE THREAD

**Issue by sebastianelsner** [OpenImageIO/oiio#1292]
I think the issue was introduced in the deep refactoring pull request:

$ make
[  9%] Built target OpenImageIO_Util
[  9%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/deepdata.cpp.o
/workspace/build/oiio/src/libOpenImageIO/deepdata.cpp: In member function ‘size_t OpenImageIO::v1_6::DeepData::Impl::data_offset(int, int, int)’:
/workspace/build/oiio/src/libOpenImageIO/deepdata.cpp:84: warning: comparison between signed and unsigned integer expressions
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/x86_64-redhat-linux/bits/c++allocator.h:35,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/allocator.h:49,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/string:44,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/locale_classes.h:43,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/ios_base.h:44,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ios:44,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ostream:41,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/iostream:41,
                 from /usr/local/include/OpenEXR/half.h:90,
                 from /workspace/build/oiio/src/libOpenImageIO/deepdata.cpp:36:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ext/new_allocator.h: At global scope:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ext/new_allocator.h: In instantiation of ‘__gnu_cxx::new_allocator<const OpenImageIO::v1_6::TypeDesc>’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/allocator.h:87:   instantiated from ‘std::allocator<const OpenImageIO::v1_6::TypeDesc>’
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_vector.h:71:   instantiated from ‘std::_Vector_base<const OpenImageIO::v1_6::TypeDesc, std::allocator<const OpenImageIO::v1_6::TypeDesc> >’
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_vector.h:171:   instantiated from ‘std::vector<const OpenImageIO::v1_6::TypeDesc, std::allocator<const OpenImageIO::v1_6::TypeDesc> >’
/workspace/build/oiio/src/libOpenImageIO/deepdata.cpp:223:   instantiated from here
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ext/new_allocator.h:79: error: ‘const _Tp* __gnu_cxx::new_allocator<_Tp>::address(const _Tp&) const [with _Tp = const OpenImageIO::v1_6::TypeDesc]’ cannot be overloaded
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ext/new_allocator.h:76: error: with ‘_Tp* __gnu_cxx::new_allocator<_Tp>::address(_Tp&) const [with _Tp = const OpenImageIO::v1_6::TypeDesc]’
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ext/new_allocator.h: In instantiation of ‘__gnu_cxx::new_allocator<const unsigned int>’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/allocator.h:87:   instantiated from ‘std::allocator<const unsigned int>’
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_vector.h:71:   instantiated from ‘std::_Vector_base<const unsigned int, std::allocator<const unsigned int> >’
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_vector.h:171:   instantiated from ‘std::vector<const unsigned int, std::allocator<const unsigned int> >’
/workspace/build/oiio/src/libOpenImageIO/deepdata.cpp:488:   instantiated from here
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ext/new_allocator.h:79: error: ‘const _Tp* __gnu_cxx::new_allocator<_Tp>::address(const _Tp&) const [with _Tp = const unsigned int]’ cannot be overloaded
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ext/new_allocator.h:76: error: with ‘_Tp* __gnu_cxx::new_allocator<_Tp>::address(_Tp&) const [with _Tp = const unsigned int]’
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ext/new_allocator.h: In instantiation of ‘__gnu_cxx::new_allocator<const char>’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/allocator.h:87:   instantiated from ‘std::allocator<const char>’
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_vector.h:71:   instantiated from ‘std::_Vector_base<const char, std::allocator<const char> >’
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_vector.h:171:   instantiated from ‘std::vector<const char, std::allocator<const char> >’
/workspace/build/oiio/src/libOpenImageIO/deepdata.cpp:498:   instantiated from here
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ext/new_allocator.h:79: error: ‘const _Tp* __gnu_cxx::new_allocator<_Tp>::address(const _Tp&) const [with _Tp = const char]’ cannot be overloaded
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ext/new_allocator.h:76: error: with ‘_Tp* __gnu_cxx::new_allocator<_Tp>::address(_Tp&) const [with _Tp = const char]’
make[2]: *** [src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/deepdata.cpp.o] Error 1
make[1]: *** [src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/all] Error 2
make: *** [all] Error 2

**Comment by lgritz** [comment]
Please change line 84 from

        DASSERT (m_cumsamples.size() > pixel);

to

        DASSERT (int(m_cumsamples.size()) > pixel);

and let me know if that fixes it, or if there's another error after that.

**Comment by sebastianelsner** [comment]
There is another error:

make -j 20
[  0%] [  1%] [  2%] [  2%] [  3%] [  3%] [  4%] Building CXX object src/libutil/CMakeFiles/OpenImageIO_Util.dir/errorhandler.cpp.o
Building CXX object src/libutil/CMakeFiles/OpenImageIO_Util.dir/filesystem.cpp.o
[  4%] Building CXX object src/libutil/CMakeFiles/OpenImageIO_Util.dir/argparse.cpp.o
[  5%] [  6%] Building CXX object src/libutil/CMakeFiles/OpenImageIO_Util.dir/hashes.cpp.o
Building CXX object src/libutil/CMakeFiles/OpenImageIO_Util.dir/farmhash.cpp.o
Building CXX object src/libutil/CMakeFiles/OpenImageIO_Util.dir/paramlist.cpp.o
[  7%] [  7%] Building CXX object src/libutil/CMakeFiles/OpenImageIO_Util.dir/SHA1.cpp.o
Building CXX object src/libutil/CMakeFiles/OpenImageIO_Util.dir/filter.cpp.o
Building CXX object src/libutil/CMakeFiles/OpenImageIO_Util.dir/strutil.cpp.o
Building CXX object src/libutil/CMakeFiles/OpenImageIO_Util.dir/plugin.cpp.o
Building CXX object src/libutil/CMakeFiles/OpenImageIO_Util.dir/timer.cpp.o
[  7%] [  8%] Building CXX object src/libutil/CMakeFiles/OpenImageIO_Util.dir/sysutil.cpp.o
[  9%] Building CXX object src/libutil/CMakeFiles/OpenImageIO_Util.dir/ustring.cpp.o
Building CXX object src/libutil/CMakeFiles/OpenImageIO_Util.dir/typedesc.cpp.o
Building CXX object src/libutil/CMakeFiles/OpenImageIO_Util.dir/xxhash.cpp.o
[ 10%] [ 10%] [ 10%] [ 11%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/exif.cpp.o
Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/formatspec.cpp.o
[ 11%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/deepdata.cpp.o
[ 12%] [ 13%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/imagebuf.cpp.o
[ 13%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/imageinput.cpp.o
[ 14%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/imageio.cpp.o
Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/imageioplugin.cpp.o
Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/imageoutput.cpp.o
Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/iptc.cpp.o
[ 15%] [ 16%] [ 16%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/xmp.cpp.o
Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/imagebufalgo.cpp.o
Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/color_ocio.cpp.o
[ 16%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/imagebufalgo_compare.cpp.o
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/x86_64-redhat-linux/bits/c++allocator.h:34,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/allocator.h:48,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/string:43,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/locale_classes.h:42,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/ios_base.h:43,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ios:43,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ostream:40,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/iostream:40,
                 from /usr/local/include/OpenEXR/half.h:89,
                 from /workspace/build/oiio/src/libOpenImageIO/deepdata.cpp:35:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ext/new_allocator.h: In instantiation of ‘__gnu_cxx::new_allocator<const OpenImageIO::v1_6::TypeDesc>’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/allocator.h:87:   instantiated from ‘std::allocator<const OpenImageIO::v1_6::TypeDesc>’
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_vector.h:71:   instantiated from ‘std::_Vector_base<const OpenImageIO::v1_6::TypeDesc, std::allocator<const OpenImageIO::v1_6::TypeDesc> >’
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_vector.h:171:   instantiated from ‘std::vector<const OpenImageIO::v1_6::TypeDesc, std::allocator<const OpenImageIO::v1_6::TypeDesc> >’
/workspace/build/oiio/src/libOpenImageIO/deepdata.cpp:223:   instantiated from here
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ext/new_allocator.h:79: error: ‘const _Tp* __gnu_cxx::new_allocator<_Tp>::address(const _Tp&) const [with _Tp = const OpenImageIO::v1_6::TypeDesc]’ cannot be overloaded
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ext/new_allocator.h:76: error: with ‘_Tp* __gnu_cxx::new_allocator<_Tp>::address(_Tp&) const [with _Tp = const OpenImageIO::v1_6::TypeDesc]’
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ext/new_allocator.h: In instantiation of ‘__gnu_cxx::new_allocator<const unsigned int>’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/allocator.h:87:   instantiated from ‘std::allocator<const unsigned int>’
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_vector.h:71:   instantiated from ‘std::_Vector_base<const unsigned int, std::allocator<const unsigned int> >’
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_vector.h:171:   instantiated from ‘std::vector<const unsigned int, std::allocator<const unsigned int> >’
/workspace/build/oiio/src/libOpenImageIO/deepdata.cpp:488:   instantiated from here
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ext/new_allocator.h:79: error: ‘const _Tp* __gnu_cxx::new_allocator<_Tp>::address(const _Tp&) const [with _Tp = const unsigned int]’ cannot be overloaded
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ext/new_allocator.h:76: error: with ‘_Tp* __gnu_cxx::new_allocator<_Tp>::address(_Tp&) const [with _Tp = const unsigned int]’
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ext/new_allocator.h: In instantiation of ‘__gnu_cxx::new_allocator<const char>’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/allocator.h:87:   instantiated from ‘std::allocator<const char>’
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_vector.h:71:   instantiated from ‘std::_Vector_base<const char, std::allocator<const char> >’
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_vector.h:171:   instantiated from ‘std::vector<const char, std::allocator<const char> >’
/workspace/build/oiio/src/libOpenImageIO/deepdata.cpp:498:   instantiated from here
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ext/new_allocator.h:79: error: ‘const _Tp* __gnu_cxx::new_allocator<_Tp>::address(const _Tp&) const [with _Tp = const char]’ cannot be overloaded
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ext/new_allocator.h:76: error: with ‘_Tp* __gnu_cxx::new_allocator<_Tp>::address(_Tp&) const [with _Tp = const char]’
[ 17%] make[2]: *** [src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/deepdata.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....

**Comment by lgritz** [comment]
Sometimes I really hate C++. I can't for the life of me figure out what these error messages mean or where the actual error is.

I need to see more.

    make clean
    make VERBOSE=1 > build.log

**Comment by Nava2** [comment]
It's to do with allocation of a vector of `const` values. You can not
allocate that in a vector.

Simple example: https://ideone.com/ArRPRG

Kevin

On Thu, Dec 17, 2015 at 1:32 PM, Larry Gritz <notifications@github.com>
wrote:

> Sometimes I really hate C++. I can't for the life of me figure out what
> these error messages mean or where the actual error is.
>
> I need to see more.
>
> make clean
> make VERBOSE=1 > build.log
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenImageIO/oiio/issues/1292#issuecomment-165540617>.
>



-- 
Kevin Brightwell*. BESc., BSc.*
​MESc. Candidate 2017
Western University​
c. 226.448.8493

**Comment by lgritz** [comment]
Why don't I get that error on any of the other systems I test on?

Which compiler are you using?

**Comment by lgritz** [comment]
ok, hang on, let me devise a workaround

**Comment by lgritz** [comment]
Try this? https://github.com/OpenImageIO/oiio/pull/1294

**Comment by sebastianelsner** [comment]
Does not fix the problem. I verified I have the changed lines, nuked the build dir, re-generated with cmake. See link below for the output of make VERBOSE=1 > build.log 2>&1

https://gist.github.com/sebastianelsner/587e799ecfd69103e878

**Comment by lgritz** [comment]
Can you repeat the "regenerated with cmake" step, with VERBOSE=1, and send that? 

Which gcc version are you using?

**Comment by sebastianelsner** [comment]
It did not add any new information. That is strange.

**Comment by lgritz** [comment]
mkdir build
    cd build
    cmake .. -DVERBOSE=1

That prints stuff like this:

```
-- Project source dir = /Users/lg/code/oiio/oiio.lg
-- Project build dir = /Users/lg/code/oiio/oiio.lg/build
-- CMAKE_CXX_COMPILER is /usr/local/opt/ccache/libexec/clang++
-- CMAKE_CXX_COMPILER_ID is Clang
-- The compiler is Clang: AppleClang version 7.0
-- Building with thread support
-- Setting Namespace to: OpenImageIO
-- CMAKE_SYSTEM_NAME = Darwin
-- CMAKE_SYSTEM_VERSION = 14.5.0
-- CMAKE_SYSTEM_PROCESSOR = x86_64
-- Unix! Darwin
-- platform = macosx
-- THIRD_PARTY_TOOLS_HOME = unknown
-- SPECIAL_COMPILE_FLAGS =
-- Found Threads: TRUE
-- Found IlmBase: /usr/local/include
-- Found IlmBase: optimized;/usr/local/lib/libHalf.dylib;debug;/usr/local/lib/libHalf.dylib;optimized;/usr/local/lib/libIex.dylib;debug;/usr/local/lib/libIex.dylib;optimized;/usr/local/lib/libImath.dylib;debug;/usr/local/lib/libImath.dylib;optimized;/usr/local/lib/libIlmThread.dylib;debug;/usr/local/lib/libIlmThread.dylib
-- Found OpenEXR: /usr/local/include
-- Found OpenEXR: optimized;/usr/local/lib/libIlmImf.dylib;debug;/usr/local/lib/libIlmImf.dylib
-- OPENEXR_VERSION = 2.2.0
-- OpenEXR version 2.x
-- BOOST_ROOT
-- Boost version: 1.59.0
-- Found the following Boost libraries:
--   filesystem
--   regex
--   system
--   thread
....
```

**Comment by sebastianelsner** [comment]
Got you!
```
Project source dir = /workspace/build/oiio
Project build dir = /workspace/build/oiio-build
CMAKE_CXX_COMPILER is /usr/bin/c++
CMAKE_CXX_COMPILER_ID is GNU
Using gcc 4.4.7 as the compiler
Building with thread support
Setting Namespace to: OpenImageIO
CMAKE_SYSTEM_NAME = Linux
CMAKE_SYSTEM_VERSION = 2.6.32-504.1.3.el6.x86_64
CMAKE_SYSTEM_PROCESSOR = x86_64
Unix! Linux
platform = linux64
THIRD_PARTY_TOOLS_HOME = unknown
SPECIAL_COMPILE_FLAGS = 
OPENEXR_VERSION = 2.2.0
OpenEXR version 2.x
BOOST_ROOT 
Boost version: 1.55.0
Found the following Boost libraries:
  filesystem
  regex
  system
  thread
BOOST_ROOT 
Boost found 1 
Boost version      105500
Boost include dirs /usr/local/include
Boost library dirs /usr/local/lib
Boost libraries    /usr/local/lib/libboost_filesystem.so;/usr/local/lib/libboost_regex.so;/usr/local/lib/libboost_system.so;/usr/local/lib/libboost_thread.so;rt
Boost python found ON
OPENGL_FOUND=TRUE USE_OPENGL=ON
Found OCIO library /usr/lib64/libOpenColorIO.so
Found OCIO includes /usr/include
OpenColorIO enabled
OCIO_INCLUDES: /usr/include
QT4_FOUND=TRUE
QT_INCLUDES=/usr/include/QtDesigner;/usr/include/QtAssistant;/usr/include/QtAssistant;/usr/include/QtScriptTools;/usr/include/QtDBus;/usr/include/QtDesigner;/usr/include/QtXml;/usr/include/QtSql;/usr/include/QtOpenGL;/usr/include/QtMultimedia;/usr/include/QtNetwork;/usr/include/phonon;/usr/include/QtXmlPatterns;/usr/include/QtHelp;/usr/include/QtUiTools;/usr/include/QtTest;/usr/include/QtScript;/usr/include/QtSvg;/usr/include/Qt3Support;/usr/include/QtGui;/usr/include/QtCore;/usr/lib64/qt4/mkspecs/default;/usr/include;/usr/include/QtCore
QT_LIBRARIES=
GLEW includes = /usr/include/GL
GLEW library = /usr/lib64/libGLEW.so
Field3d will not be used
Looking for LibRaw with 
Found LibRaw, include /usr/include/libraw
WEBP_HOME=
WebP library not found
Not using OpenCV
Found FREETYPE library /usr/lib64/libfreetype.so
Found FREETYPE includes /usr/include;/usr/include/freetype2;/usr/include/freetype2/freetype
Freetype includes = /usr/include;/usr/include/freetype2;/usr/include/freetype2/freetype 
Freetype libs = /usr/lib64/libfreetype.so 
OpenSSL enabled
OPENSSL_INCLUDES: /usr/include
Setting SOVERSION to: 1.6
Create imagio_pvt.h from imageio_pvt.h.in
FFmpeg plugin will not be built
Field3D plugin will not be built
WebP plugin will not be built
PTex plugin will not be built
Linking OpenColorIO /usr/lib64/libOpenColorIO.so
Setting SOVERSION to: 1.6
Boost version: 1.55.0
Found the following Boost libraries:
  python
Python found TRUE 
Python include dirs /usr/include/python2.6
Python libraries    /usr/lib64/libpython2.6.so
Python to include 'lib' prefix: OFF
Python to include SO version: OFF
Create oiioversion.h from oiioversion.h.in
```

**Comment by lgritz** [comment]
You seem to be using gcc 4.4.7.

I have verified that this code compiles fine on gcc 4.8, 4.9, 5.2, as well as clang 3.4 and 3.7.

Your gcc 4.4 may just be too old to understand something we are doing in the array_view template. (Although I'm having trouble understanding from the error messages exactly what we are doing that is problematic.)

We are determined to make sure that the new stable release branch, OIIO 1.6 (and any patches thereto) continues to work with any compilers that will build it today (including gcc 4.4).

But for OIIO 1.7 (the current master) we are following the VFX Platform recommendation (http://www.vfxplatform.com/), which for 2016-released software assumes a minimum of gcc 4.8.2 and C++11.  (The minimum for 2015 was also supposed to be gcc 4.8, though without the C++11 requirement.)

We haven't actually thrown the C++11 switch yet by purposely adding something that won't compile with C++03, but we are prepared to do so whenever it naturally comes up. I fully expect that long before we turn 1.7 into a stable branch, it will no longer be able to compile as C++03.

I fear that any work to make the current master build against gcc 4.4 is merely a very temporary stay of execution. There is probably little point in doing any work to ensure compilation even now, with a compiler that is too old to support C++11 when that time comes.

If you can find a minor change that will make it build, and that doesn't sacrifice any functionality, I'm happy to incorporate it. But I don't have the time myself to put into compilers that are several versions older than our currently advertised minimal requirements.

Am I approaching this unreasonably?

**Comment by hobbes1069** [comment]
If possible, update to RHEL/CentOS 7 which has 4.8.5...

You might be able to come up with a parallel install of a newer version of of gcc (/usr/local prefix) or even something prebuilt in /opt but I think it would get very messy quickly.

**Comment by sebastianelsner** [comment]
I have read the previous emails you send on the mailing list about this topic and I totally agree. I can work with 1.6.x. I just wanted to get the fix for #1286, but back then I told you I don't need a backport :D 
So I either stay in that master commit from #1286 or backport to 1.6. Sorry for the trouble.

On a side note: We are a rather small shop with only one Pipeline guy (me) and two admins. Switching to CentOS 7 is not going to be a quick step for us. I am curious how bigger facilities handle this since the amount of computers to be updated is much higher and I would expect palnning with CentOS is more of a long-term (enterprisey) thing.

**Comment by lgritz** [comment]
#1286 has already been backported to 1.6.

**Comment by sebastianelsner** [comment]
Many thanks!

**Comment by lgritz** [comment]
Don't feel bad, I'm in a HUGE facility and we are also still struggling to upgrade to RHEL7!

There are basically three use cases for OIIO here: (a) embedded in the renderer (for the texture system, image output, and various uses by OSL); (b) extensive standalone use of oiiotool, maketx, and other command line tools; (c) apps or plugins that need to link to libOpenImageIO and simultaneously maintain link/compiler compatibility with things we don't control (like Nuke, Houdini, etc.).

For (a) and (b), we build from master because the renderer and the scripts that use oiiotool are constantly wanting the very latest feature additions or perf improvements, which are often added at their specific request. We use clang to build so we are essentially independent of the system default gcc and are free to throw the C++11 switch whenever it becomes necessary.

Use case (c) is trickier, because of the link compatibility requirements with other apps. A build for this purpose is released and versioned separately (and much less frequently) than a&b and compiled with the system gcc, so the release for this case will probably stay on 1.6 for a while.

I'm kind of playing "chicken" with case (c) at the moment -- hoping that we can upgrade all our systems to the new OS and compilers, before there is an absolute requirement for a feature that can't be safely backported to 1.6.
