### ISSUE TITLE
Build fails on Ubuntu 15.10

### ISSUE THREAD

**Issue by panmari** [OpenImageIO/oiio#1293]
I get the following error trace:

```
libOpenImageIO_Util.so.1.5.22: undefined reference to `boost::match_results<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > > >::maybe_assign(boost::match_results<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > > > const&)'
libOpenImageIO_Util.so.1.5.22: undefined reference to `boost::re_detail::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::construct_init(boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags)'
collect2: error: ld returned 1 exit status
src/libutil/CMakeFiles/atomic_test.dir/build.make:95: recipe for target 'src/libutil/atomic_test' failed
make[2]: *** [src/libutil/atomic_test] Error 1
CMakeFiles/Makefile2:1037: recipe for target 'src/libutil/CMakeFiles/atomic_test.dir/all' failed
make[1]: *** [src/libutil/CMakeFiles/atomic_test.dir/all] Error 2
Makefile:146: recipe for target 'all' failed
make: *** [all] Error 2
```

Seems like the included version of boost is too high/low? Currently included version is

    Boost version (currently 1.58).

**Comment by lgritz** [comment]
Hmmm. Mismatched header and library? It obviously found the headers when it compiled the .cpp file, now it's having trouble linking.

How about a 'make clean' and then 'make VERBOSE=1 > build.log', and send us the whole build output log. Maybe we can spot the problem.

**Comment by panmari** [comment]
Sure, I put the output [here](https://gist.github.com/panmari/36e844643bfc70006937)

**Comment by lgritz** [comment]
I need you to 'make clean' or 'make nuke' first. I need to see the whole part where it figures out what is where in the system and which versions of all the packages it's picking up.

**Comment by panmari** [comment]
Oh, I'm actually using cmake for that, then running make on the generated Makefile. Should I dump the cmake cache?

**Comment by panmari** [comment]
Updated [gist](https://gist.github.com/panmari/36e844643bfc70006937) below the build output I attached CMakeCache.txt.

**Comment by lgritz** [comment]
I want to see all the messages that cmake prints when it's running the scripts the first time. Please blow away the 'build' area entirely, and start from the beginning with 'cmake .. VERBOSE=1 > setup.log', then 'make VERBOSE=1 > build.log'.

Sorry for all the trouble. This is hard to debug by remote control!

**Comment by panmari** [comment]
No problem, thanks for your guidance and sorry for being inexperienced with cmake/make! I'll report back asap.

**Comment by panmari** [comment]
Here's what I got: https://gist.github.com/panmari/238e7b81e66e346653a3

I executed cmake as `cmake VERBOSE=1 .. > setup.log`, since the other argument order did not work. Hope that's the output you're looking for.

**Comment by panmari** [comment]
I found out what's causing the problem. I installed gcc 4.9 from https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test and activated it with `update-alternatives` for bringing cuda to work. Once I switch back to gcc 5 (default bundled with Ubuntu 15.10), the error vanishes.

Strange :confused:

**Comment by lgritz** [comment]
Ah, no, not so strange!

I believe that when using a compiler that supports C++11 std::regex or its own equivalent, Boost falls back on that rather than use its own pre-C++11 version. 

Therefore, if your boost installation was compiled in C++11 mode (perhaps using gcc5?), then you compile OIIO with gcc4.x without C++11, there can be a mismatch where at OIIO build time the boost regex headers think "C++ isn't giving me regex, so I'll use my own and expect it to link at runtime" but in fact the boost libraries don't contain the regex functions because when boost was built it thought "aha, this C++ has its own regex, so I don't need to build mine."

**Comment by lgritz** [comment]
A more succinct way of phrasing it:

* When you compiled OIIO with gcc 4.9, the boost headers expect a full boost implementation of regex to be available at link time.

* When you compiled boost itself with gcc 5.x, boost regex merely "wraps" std::regex, and therefore does not build regex into boost libraries themselves.

**Comment by lgritz** [comment]
We can close this issue now, correct?

**Comment by panmari** [comment]
Sure, thanks for the explanation!
