### ISSUE TITLE
undefined reference to `OpenImageIO::v1_6::CSHA1::Update(unsigned char const*, unsigned long)

### ISSUE THREAD

**Issue by svenstaro** [OpenImageIO/oiio#1298]
OIIO 1.6.8 fails to link to one of its own utils only on i686. x86_64 works fine in this regard. This is on Arch Linux against boost 1.60 with gcc 5.3. Building with clang fails likewise which makes me think it's a wrongly configured build system.

x86_64 build log (works): http://b.1339.cf/srradra.log
i686 build log (fails): http://b.1339.cf/tsealju.log

**Comment by svenstaro** [comment]
I would like to note that this works with OpenSSL enabled.

**Comment by hobbes1069** [comment]
Running into the same problem on Fedora Rawhide.

**Comment by lgritz** [comment]
See #1312 as proposed solution. I strongly suspect this ultimately the same problem as #1311.

**Comment by lgritz** [comment]
This should be fixed in today's master and the head of RB-1.6.
