### ISSUE TITLE
Make iv work via ssh with X forwarding

### ISSUE THREAD

**Issue by panmari** [OpenImageIO/oiio#1317]
Hi

First of all I want to give a huge thanks to the collaborators of this project! It's awesome how much convenience it provides when working with images. 

I noticed that the image viewer `iv` doesn't work well with x-forwarding over ssh. Opening e. g. some png images fails with:

```
$ iv *.png
X Error: BadValue (integer parameter out of range for operation) 2
  Extension:    154 (Uknown extension)
  Minor opcode: 3 (Unknown request)
  Resource id:  0x0
X Error: BadValue (integer parameter out of range for operation) 2
  Extension:    154 (Uknown extension)
  Minor opcode: 3 (Unknown request)
  Resource id:  0x0
QGLTempContext: Unable to create GL context.
X Error: BadValue (integer parameter out of range for operation) 2
  Extension:    154 (Uknown extension)
  Minor opcode: 3 (Unknown request)
  Resource id:  0x0
QGLTempContext: Unable to create GL context.
```

Is there any way to make this work? Thanks in advance!

**Comment by lgritz** [comment]
I'm not sure. This sounds like a good question to ask on the oiio-dev mail list. An "issue" on GitHub is only read by a small subset of people, and is great for reporting a reproducible bug and tracking when it gets fixed. But for open-ended "how do I..." questions, oiio-dev will reach a lot more people who have the potential to know the answer.

**Comment by lgritz** [comment]
Nobody has replied or followed up with this. Closing.
