### ISSUE TITLE
The -7 Bog of Custom CMake Paths

### ISSUE THREAD

**Issue by sobotka** [OpenImageIO/oiio#1327]
So as per mailing list, the CMake modules don't function correctly.

I'm relatively sure that https://github.com/OpenImageIO/oiio/blob/c3655799b60718b99d4e0baec212ed8e4ba55370/src/cmake/modules/FindOpenEXR.cmake#L89 never has. What appears to happen if you dump status checks through the CMake build, is that as soon as this macro is hit near the bottom, all of the libraries accumulated, of which customs are in, get jettisoned and the whole thing defaults to the whatever SelectLibraryConfigurations is doing, with complete disregard for the detection in this CMake module.

I suppose it would be possible to check and skip this, but not sure. There's also interesting nuances that happen if someone uses the *_HOME variables over say, *_CUSTOM as well, each breaking each other.

Perhaps we should consider a singular path for custom libraries and includes instead of several variables?

For anyone that wishes to dive into this to test, using Qt Creator with OIIO will reveal the issues almost immediately if you choose an external building directory.

More to come if I can overcome the dreaded "No recipe for building /usr/local/lib64" error...

**Comment by lgritz** [comment]
The FindOpenEXR.cmake and FindIlmBase.cmake files are broken beyond repair and should be replaced. There are several to choose from, and a parallel discussion on the openexr-devel mail list of having a canonical one included/endorsed by the OpenEXR development community. I hope to get this sorted out this week. If in the next few days a good candidate is not forthcoming from openexr-devel, I think we should just pick one of the candidates, even if we ultimately replace it again.

Searching around the net myself for other projects containing a FindOpenEXR.cmake file, I found the following candidates from respectable sources:

* Intel: https://github.com/embree/embree/blob/master/common/cmake/FindOpenEXR.cmake
* NVIDIA texture tools: https://code.google.com/p/nvidia-texture-tools/source/browse/trunk/cmake/FindOpenEXR.cmake
* Blender: https://github.com/dfelinto/blender/blob/master/build_files/cmake/Modules/FindOpenEXR.cmake
* OpenSceneGraph: https://github.com/dfelinto/blender/blob/master/build_files/cmake/Modules/FindOpenEXR.cmake

Please do feel free to experiment on your end with replacing ours with one (or all, in turn) of these and see if any meet your needs, and let us know the results. I have absolutely no ties or preference to our current implementation, and would be very happy to replace it. I just don't yet know which one is best.

**Comment by sobotka** [comment]
Just tried the Blender configuration. It works as expected with a little twiddling because it clumps all of Ilm based elements under the same banner as OpenEXR. I added a cheat that added the macro for the ILM base elements in the externalpackages.cmake, commented out the previous ILMBASE elements, and all was well.

**Comment by lgritz** [comment]
Is this fixed by #1346?

**Comment by sobotka** [comment]
I did a compile recently without passing a single custom variable to cmake from QtCreator, and it worked painlessly here. Anecdotal evidence is not evidence of course, so I'd suspect you'd need to get more systems tested to consider it completely valid. The -7 Bog of Custom CMake Paths appears to have had the curse lifted...

**Comment by lgritz** [comment]
OK, closing then.
