### ISSUE TITLE
mj2 files not seeking properly past 1 sec in time

### ISSUE THREAD

**Issue by Agartner** [OpenImageIO/oiio#1330]
[vids.zip](https://github.com/OpenImageIO/oiio/files/107564/vids.zip)

I'm trying to extract each frame of a mj2 file into tif's using just ImageInput/Output. It seems something is weird about the read_frame() seek() functions in the ffmpeg plugin. It will extract up to 1 sec (so 24frames at 24fps) of tif images and then just hold (like it never cleared the ffmpeg buffer but it appears to try to seek the next set of frames).  

I tested a regular .mov file and that worked perfectly fine.  I've attached my test mj2 files and movs respectively. For reference I'm on the latest from master (1.7dev), but this was tried on 1.5 and 1.6 release builds.

Any help would be great. 

Cheers,

~Andrew

```
    ImageInput *in = ImageInput::open(filename);
    int num_of_subimages = 0;
    if (!in)
        return -1;
    ImageSpec spec = in->spec();
    while (in->seek_subimage (num_of_subimages, 0, spec)) {
            int nchannels = spec.nchannels;
            int pixelsize = spec.width * spec.height;
            unsigned char *pixels = new unsigned char [pixelsize * nchannels];
            in->read_image(TypeDesc::UINT8, pixels);
            std::string extension = ".tif";
            std::string outfileName = std::to_string(num_of_subimages) +  extension;
            ImageOutput *out = ImageOutput::create(outfileName);
            ImageSpec outSpec = ImageSpec(spec);

            out->open(outfileName, outSpec);
            //std::cout<<"writing:"<<outfileName<<std::endl;
            out->write_image(TypeDesc::UINT8, pixels);
            out->close();
            delete out;
            delete [] pixels;
            num_of_subimages++;
    }
    std::cout<<num_of_subimages<<std::endl;
    in->close();
```

**Comment by lgritz** [comment]
I'm going to speculatively close this, because we're several versions of ffmpeg and quite a bit of OIIO development since this was originally filed. 

Apologies for this seeming to slip through the cracks.

If anybody believes that this is still an issue with the current OIIO and a fairly recent ffmpeg, then please re-open or re-file.
