### ISSUE TITLE
1.6.x fails to read correctly mixed bit depth EXR file

### ISSUE THREAD

**Issue by MrKepzie** [OpenImageIO/oiio#1335]
1.5.23 reads correctly the following file https://github.com/MrKepzie/build-oiio/blob/master/chopper.exr 
with oiiotool:

`oiiotool chopper.exr -o chopper_o.exr `

But seems to be broken in 1.6.9: the output file for the RGBA pass only has the red channel set and other passes are blanked

**Comment by lgritz** [comment]
I'll take a look, sorry for the delay.

**Comment by lgritz** [comment]
Fix proposed in #1354

**Comment by lgritz** [comment]
I wish that when you submit PR, there was a way to directly and irrevocably tie it to an "issue", to give them a single ID number and merge their conversations.

**Comment by MrKepzie** [comment]
Issue seems fixed
