### ISSUE TITLE
Build errors on Windows with Unicode enabled

### ISSUE THREAD

**Issue by roelandschoukens** [OpenImageIO/oiio#1337]
There are a couple of places in _libutil_ where it is assumed that `TCHAR` is defined as a `char`, i.e. the build is set up to use the multibyte character set. These places are:
- [`plugin.cpp:78`](https://github.com/OpenImageIO/oiio/blob/master/src/libutil/plugin.cpp#L78)
- [`SHA1.cpp:86`](https://github.com/OpenImageIO/oiio/blob/master/src/libutil/SHA1.cpp#L86): `ReportHashStl` accepts a string of `TCHAR`, not a `std::string`.
- [`sysutil.cpp:241`](https://github.com/OpenImageIO/oiio/blob/master/src/libutil/sysutil.cpp#L241)

Not sure how to deal with `CSHA1::ReportHash`, the other two can be fixed for both ANSI and Unicode builds by explicitly using the wide version of the function (as in `LoadLibraryW (wide_plugin_filename)`) and converting the output to UTF-8 with `WideCharToMultiByte`.

**Comment by lgritz** [comment]
I don't have access to a Windows machine at all to check. Can you submit a PR with the changes to the parts that you know how to fix?

**Comment by lgritz** [comment]
Pinging on this, there was no reply. Can you suggest a specific fix?

**Comment by roelandschoukens** [comment]
I wasn't trying to build the whole source tree, so unfortunately I'm not able to provide a full pull request for now. I can try to fix libutil. Are you using the win32 API in other places?

But to give some background: In Windows you can choose to define strings as either *multibyte* *Unicode*. When using the the former, `TCHAR` is defined as a `char` and strings are encoded in whatever 8-bit code page your system is using as default. The latter means `TCHAR` = `WCHAR`, which is a 16-bit `wchar_t`, strings are encoded as UTF-16. My expectation is that most users of the library will use *Unicode* builds, the other option is really only useful to build code for Windows 95/98/ME, and will cause major PITA when encountering non-ASCII characters anywhere.

So the problem is that the code gets the function signatures wrong. For any public function in the Windows API which accepts strings, there are actually 2 versions:

    // multibyte string version. Avoid like the plague if there's any chance of encountering
    // non-ASCII characters
    LoadLibraryA(char *filename)
    // UTF-16 version:
    LoadLibraryW(WCHAR *filename)

Depending on the build configuration `LoadLibrary` is defined to be either `LoadLibraryA` or `LoadLibraryW`, and `TCHAR` is defined to the matching string type.

**Comment by roelandschoukens** [comment]
Pull request here: [#1454 — Fix build errors on Windows when making Unicode builds](https://github.com/OpenImageIO/oiio/pull/1454)

**Comment by lgritz** [comment]
Closing issue. This was closed long ago by #1454.
