### ISSUE TITLE
16-bits PNM are MSB-first, pnminput.c's raw_to_raw should swap bytes if sizeof(T)==2

### ISSUE THREAD

**Issue by devernay** [OpenImageIO/oiio#1343]
reference: http://netpbm.sourceforge.net/doc/pamendian.html
note that this is already taken care of in pnmoutput.c

**Comment by devernay** [comment]
patch can be found at
https://raw.githubusercontent.com/MrKepzie/Natron/workshop/tools/MacOSX/ports/graphics/openimageio/files/oiio-pnm16.patch

**Comment by lgritz** [comment]
Thanks!
Proposed patch in PR #1352
