### ISSUE TITLE
Gif input: spec.full_width == 0 and spec.full_height == 0

### ISSUE THREAD

**Issue by MrKepzie** [OpenImageIO/oiio#1347]
As said, the GifInput plug-in does not set spec.full_width and spec.full_height members. 
Is this a bug or is it documented somewhere that they may be left to 0,0 implying they are equal to spec.width and spec.height ?

**Comment by lgritz** [comment]
I believe you are correct. Preparing a patch now...

**Comment by lgritz** [comment]
Fix proposed in PR #1348
