### ISSUE TITLE
invalid C++: imagebufalgo_pixelmath.cpp tries to allocate std::vector<const TypeDesc>

### ISSUE THREAD

**Issue by devernay** [OpenImageIO/oiio#1364]
### Problem

imagebufalgo_pixemath.cpp declares at two places a `array_view<const TypeDesc>`, which resolves to a `std::vector<const TypeDesc>`, but STL containers must contain assignable values.

The compiler may or may not accept this, depending on the STL implementation.

Older GCC versions don't accept it: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=16875

**Expected behavior:** [What you expected to happen]

Use a `array_view<TypeDesc>` instead. This doesn't break anything.

**Actual behavior:** [What actually happened]

build error:

https://gist.github.com/devernay/58f93957598ab6db31dc

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Versions

* OIIO branch/version: 1.6.10
* OS: Mac OS X 10.6
* C++ compiler: gcc 4.2.1

**Comment by lgritz** [comment]
Solution proposed in #1367 (patch against 1.6, will port to master if it checks out with you).

**Comment by devernay** [comment]
that's what I did too, and it worked.

I think this stuff has been clarified in C++11, though I cannot find an exact reference.

**Comment by lgritz** [comment]
Merged.

I'm only putting this in 1.6.  The code in this area is different for master, and given that master will require C++11 eventually (probably soon), I don't think we need to accommodate older gcc limitations.
