### ISSUE TITLE
[Enhancement] ImageOutput: identify a buffer with it's orientation 

### ISSUE THREAD

**Issue by MrKepzie** [OpenImageIO/oiio#1382]
Currently if we want to inverse an image to write, we just give a negative Y stride.
If we attempt to write _native_ data (i.e: by passing Typdesc::UNKNOWN to _ImageOutput::write_image_)  with the negative Y stride, then in the case where the xStride passed is equal to the stride computed by Autostride then it will still require **ImageOutput::to_native_rectangle** to actually shuffle the buffer. 

This is OK for most format, but if the application has a bottom-up oriented image and we want it written to the file bottom-up, then it will be converted once to top-down to match OIIO images orientation. 

Also, OpenEXR does support writing scan-lines either top-down or bottom-up and the client should be able to control that directly without inducing a re-layout of the buffer.

The condition currently to detect that _to_native_rectangle_ shouldn't do anything is:

```
contiguous = (xstride == (stride_t)(m_spec.pixel_bytes(native_data)));
...

contiguous &= ((ystride == xstride*width || height == 1) &&
                   (zstride == ystride*height || depth == 1));
```

When this could actually be

```
contiguous = (xstride == (stride_t)(m_spec.pixel_bytes(native_data)));
...

contiguous &= ((std::abs(ystride) == xstride*width || height == 1) &&
                   (std::abs(zstride) == ystride*height || depth == 1));
```

This change alone is not enough since we would then need to flag images that are bottom-up instead of top-down, as such:

```
bool isBottomUp = yStride  < 0
```

Some plug-ins then may declare or not that they do or do not support bottom-up images.

**Comment by lgritz** [comment]
I understand the idea here. I think that only OpenEXR is the main (only?) format that would benefit from this, though that's an important format. But since in over 2 years nobody has stepped forward to do the work

**Comment by lgritz** [comment]
Dammit, didn't mean to send... hang on, editing...

**Comment by lgritz** [comment]
I understand the idea here. I think that only OpenEXR is the main (only?) format that would benefit from this, though that's an important format. 

But since in over 2 years nobody has stepped forward to do the work, nor to chime in that it's important to them as well, I'm going to close the issue.

I would welcome a PR against the current master that used OpenEXR's ability to write in either direction to recognize or mess with the strides to avoid the extra copies.
