### ISSUE TITLE
Find Ptex recipe out of date

### ISSUE THREAD

**Issue by meshula** [OpenImageIO/oiio#1396]
### Problem

The latest Ptex has a file called PtexVersion.h. The existing Cmake recipe searches for versions in Ptexture.h which is no longer valid.

Describe the problem or suggestion here.

**Expected behavior:**

I expect that with an old Ptex, Ptexture.h will be searched, but a new Ptex will allow the search in PtexVersion.h

This patch below works for top of tree Ptex. My Cmake knowledge isn't yet good enough to do the right thing for new or old Ptex, but I need to be able to use new Ptex, not the ptex embedded in the OIIO sources. 

diff --git a/src/cmake/modules/FindPTex.cmake b/src/cmake/modules/FindPTex.cmake
index f8fdfc2..9294fcb 100644
--- a/src/cmake/modules/FindPTex.cmake
+++ b/src/cmake/modules/FindPTex.cmake
@@ -83,15 +83,15 @@ else ()
             DOC "The Ptex library")
 endif ()
 
-if (PTEX_INCLUDE_DIR AND EXISTS "${PTEX_INCLUDE_DIR}/Ptexture.h" )
+if (PTEX_INCLUDE_DIR AND EXISTS "${PTEX_INCLUDE_DIR}/PtexVersion.h" )
 
-    file(STRINGS "${PTEX_INCLUDE_DIR}/Ptexture.h" TMP REGEX "^#define PtexAPIVersion.*$")
+    file(STRINGS "${PTEX_INCLUDE_DIR}/PtexVersion.h" TMP REGEX "^#define PtexAPIVersion.*$")
     string(REGEX MATCHALL "[0-9]+" API ${TMP})
     
-    file(STRINGS "${PTEX_INCLUDE_DIR}/Ptexture.h" TMP REGEX "^#define PtexFileMajorVersion.*$")
+    file(STRINGS "${PTEX_INCLUDE_DIR}/PtexVersion.h" TMP REGEX "^#define PtexFileMajorVersion.*$")
     string(REGEX MATCHALL "[0-9]+" MAJOR ${TMP})
 
-    file(STRINGS "${PTEX_INCLUDE_DIR}/Ptexture.h" TMP REGEX "^#define PtexFileMinorVersion.*$")
+    file(STRINGS "${PTEX_INCLUDE_DIR}/PtexVersion.h" TMP REGEX "^#define PtexFileMinorVersion.*$")
     string(REGEX MATCHALL "[0-9]+" MINOR ${TMP})
 
     set(PTEX_VERSION ${API}.${MAJOR}.${MINOR})

**Comment by lgritz** [comment]
Please give the patch in #1400 a try.

Note that if you install Ptex via Homebrew, the recipe does not install PtexVersion.h! You will have to copy that file yourself, or build Ptex by hand.

**Comment by meshula** [comment]
Works great! Thanks.
