### ISSUE TITLE
USE_LIBCPLUSPLUS does not work

### ISSUE THREAD

**Issue by ThiagoIze** [OpenImageIO/oiio#1403]
I've encountered a problem when trying to use libc++ on my OSX machine with clang.  This is with an unmodified master from a day or so ago. The problem is that `make nuke && make USE_LIBCPLUSPLUS=1` isn't actually enabling libc++.  From the build output:

```
-- Building with thread support
-- Building for C++11
-- Setting Namespace to: OpenImageIO
```
The fix for that is:
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 192f363..8ff0881 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -249,7 +249,7 @@ if (CMAKE_COMPILER_IS_GNUCC OR CMAKE_COMPILER_IS_CLANG OR CMAKE_COMPILER_IS_INTE
     endif ()
 endif ()
 
-if (USE_LIBCPLUSPLUS AND CMAKE_COMPILER_IS_CLANG)
+if (OIIO_BUILD_LIBCPLUSPLUS AND CMAKE_COMPILER_IS_CLANG)
     message (STATUS "Using libc++")
     add_definitions ("-stdlib=libc++")
 endif ()
```
Which then gives us:
```
-- Building with thread support
-- Building for C++11
-- Using libc++
-- Setting Namespace to: OpenImageIO
```

This should be pretty easy to test.  Just look for the "-- Using libc++" output when running `make USE_LIBCPLUSPLUS=1` or run with `make USE_LIBCPLUSPLUS= 1 VERBOSE=1` and examine the actual flags being passed to the compiler.

**Comment by lgritz** [comment]
Actually, I think I want to fix it in the other direction: changing all the references to USE_LIBCPLUSPLUS.
I will submit a quick PR shortly.

**Comment by lgritz** [comment]
Aside: on OSX, doesn't it use libc++ regardless, making USE_LIBCPLUSPLUS=1 redundant?

**Comment by lgritz** [comment]
See #1403.

I'll make the same changes on the OSL side.
The reason I prefer USE_LIBCPLUSPLUS rather than OIIO_USE... is so that it doesn't need to be named something different for OSL. Usually people build both with the same flags, and it's awkward to have to set two different names for the same thing.

**Comment by lgritz** [comment]
I think that this is totally unnecessary on OSX, where libc++ is the only game in town. IIRC, the only time you need to use USE_LIBCPLUSPLUS is if you are compiling with clang on Linux, and want to force libc++ instead of falling back on the default libstdc++.

**Comment by ThiagoIze** [comment]
Actually, if you are using the 10.8 Mac OSX SDK, then you do need to specify libc++ or it won't compile since on 10.8 libstdc++ was the default.  Here's some [info](https://trac.macports.org/wiki/LibcxxOnOlderSystems).  In particular, you also need to specify this during the linking stage or you'll get a bunch of linker errors.  Here's an example:
```
Undefined symbols for architecture x86_64:
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::find(char, unsigned long) const", referenced from:
      test_string_view() in strutil_test.cpp.o
```
That actually brings up a second issue.  Using `add_definitions()` isn't good enough for `stdlib` since that is also required by the linker and `add_definitions()` doesn't pass that on to the linking stage.  Instead the following is required: `set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -stdlib=libc++")`.

**Comment by lgritz** [comment]
OK, updated #1404 to reflect this advice.

**Comment by ThiagoIze** [comment]
The commit in #1404 appears to let me compile. Thanks!

**Comment by lgritz** [comment]
OSL side: https://github.com/imageworks/OpenShadingLanguage/pull/639
