### ISSUE TITLE
Build with openCV 3.1

### ISSUE THREAD

**Issue by pkajaba** [OpenImageIO/oiio#1405]
### Problem

I try to build against openCV 3.1, but build fails

**Actual behavior:** [What actually happened]

https://gist.github.com/pkajaba/2ae1c75600b334cee7c76e3c2bb36e20

* OIIO branch/version: stable release
* OS: fedora rawhide
* C++ compiler: gcc 6

**Comment by hobbes1069** [comment]
I brute force added libopencv_videoio to the linker flags and got a good build, however I had a strange issue with iv segfaulting when generating the man page with text2man.

export LDFLAGS='%{optflags} -lopencv_videoio'

**Comment by lgritz** [comment]
I'd never tried building against OpenCV 3.x. 

As a workaround, you can always build with USE_OPENCV=0, assuming you don't immediately require the tiny bit of OpenCV interoperability functionality.

I have a more robust fix proposed in #1410, which I can backport to the release branch.

**Comment by pkajaba** [comment]
I am helping with packaging OpenImageIO into Fedora :) I think that USE_OPENCV=0 is not best workaround. I am going to try fix you mentioned. If it worked, It would be great if you backported it

**Comment by pkajaba** [comment]
Ok, great it builds under rawhide https://copr.fedorainfracloud.org/coprs/sergiomb/opencv/build/181494/

**Comment by hobbes1069** [comment]
@pkajaba as the current Fedora OpenImageIO maintainer I just want to check your meaning. OpenImageIO is already in Fedora. Are you trying to do builds with FFMpeg stuff enabled that isn't allowed in Fedora?

**Comment by hobbes1069** [comment]
I downloaded the patch of the pull request and it applied cleanly to 1.6.12 and appears to have fixed the problem.

**Comment by pkajaba** [comment]
@hobbes1069 I am not trying to build with ffmpeg - I am working on switching from OpenCV 2.4 to OpenCV 3.1. Thanks for fixing it :)

**Comment by lgritz** [comment]
Committed the fix to master and RB-1.6.
I expect to tag a new 1.6 release in the next few days (aiming for May 1).
