### ISSUE TITLE
Jpeg output pixel aspect ratio X_density Y_density swapped

### ISSUE THREAD

**Issue by aoblet** [OpenImageIO/oiio#1413]
### Problem

When using PixelAspectRatio in jpegoutput, it seems that [X_density and Y_density are swapped](https://github.com/OpenImageIO/oiio/blob/master/src/jpeg.imageio/jpegoutput.cpp#L184)

I think that formula is:
PAR = X/Y. So if we set Y to a constant C, we have:
- Y = C
- X = C*PAR

Is it correct for you ?
Thanks

### Solution proposed
PR #1412 

### Versions

* OIIO branch/version: master

**Comment by lgritz** [comment]
Fixed by #1412

**Comment by lgritz** [comment]
By the way, it is not necessary to file both a PR and an Issue. The PR can describe the problem and proposed code for solution. Issues are great when nobody has a solution yet, they remind us of an outstanding problem. But if a solution is implemented, separately filing an "issue" is just extra work with no benefit.

**Comment by aoblet** [comment]
You're right. At the beginning I had no solution to PR. Sorry for that.

**Comment by lgritz** [comment]
No prob, I'm just trying to save you trouble! The issue and the PR were just one number apart, so it certainly seemed as if they were filed simultaneously, or nearly so. I just wanted to make sure you knew that there's no rule that says everything needs an issue.

(Aside: I wish it was possible to fully "upgrade" an existing issue with a PR, and not have them be separate at all, ever. It seems to just be a hassle to tie an issue and PR together, spreads out the discussion unnecessarily.)
