### ISSUE TITLE
Add support for 10-bit and 12-bit movie files

### ISSUE THREAD

**Issue by skycaptain** [OpenImageIO/oiio#1429]
### Problem

When reading 10-bit DPX files via `ImageInput` they get automatically upsampled to UINT16 type so that no information is lost. However, when reading a 10-bit Quicktime ProRes file via the included ffmpeg API it is interpreted as a UINT8 type. Therefore, information is lost.
I know that handling movie files is not of first priority, but since the ffmpeg plugin is already checking for pixel formats, adding 10-bit and 12-bit formats and a switch might be sufficient. 

### Versions

* OIIO branch/version: 1.6.13
* OS: OSX 10.11.5

**Comment by lgritz** [comment]
Fixed by #1430, closing.
