### ISSUE TITLE
Keeping original bit types with oiiotool

### ISSUE THREAD

**Issue by kazuki-takahashi** [OpenImageIO/oiio#1445]
Hi,

I'm not sure if this is intentional but when I use "oiiotool" on a multi-different-bit-layer exr, "oiiotool" seems to change the original bit types.

### Problem

**Expected behavior:** 
I would like to keep the original bit types when merging images if the images have same bit types, and only when specifying "-d" option to change the bit types, I would like it to convert the bit types to the specified bit types.
Basically, what I'm trying to do is to merge multiple tiling images that have same AOVs and bit types.

**Actual behavior:**
"oiiotool" seems to convert all channels to 32 bit even when changing only medatadata.
(Help says "Options that change current image metadata (but not pixel values)" but it changes bit types to "float" from "half", and it may change the pixel values)

### Steps to Reproduce

I'm putting 2 things, one is merging 2 images and one is simply to add metadata only.

## merging images with "--over" option

1) make 2 multi-different-bit-layer exr files like this:
(Basically, I have 2 images that have exact same AOVs and bit types but different dataWindow for tailing renders)
$ exrheader tile_1_1.exr
...
channels (type chlist):
    A, 16-bit floating-point, sampling 1 1
    B, 16-bit floating-point, sampling 1 1
    G, 16-bit floating-point, sampling 1 1
    R, 16-bit floating-point, sampling 1 1
    depth.Z, 32-bit floating-point, sampling 1 1
    diffuse.blue, 16-bit floating-point, sampling 1 1
    diffuse.green, 16-bit floating-point, sampling 1 1
    diffuse.red, 16-bit floating-point, sampling 1 1
...
dataWindow (type box2i): (0 0) - (1027 1555)
...

$ exrheader tile_2_1.exr
...
channels (type chlist):
    A, 16-bit floating-point, sampling 1 1
    B, 16-bit floating-point, sampling 1 1
    G, 16-bit floating-point, sampling 1 1
    R, 16-bit floating-point, sampling 1 1
    depth.Z, 32-bit floating-point, sampling 1 1
    diffuse.blue, 16-bit floating-point, sampling 1 1
    diffuse.green, 16-bit floating-point, sampling 1 1
    diffuse.red, 16-bit floating-point, sampling 1 1
...
dataWindow (type box2i): (1028, 0) - (2047 1555)
...

2) merge the 2 images with "--over" option
$ oiiotool tile_1_1.exr --over tile_2_1.exr -o output.exr

3) chech the bit types and the resolution
$ exrheader output.exr
...
channels (type chlist):
    A, 32-bit floating-point, sampling 1 1
    B, 32-bit floating-point, sampling 1 1
    G, 32-bit floating-point, sampling 1 1
    R, 32-bit floating-point, sampling 1 1
    depth.Z, 32-bit floating-point, sampling 1 1
    diffuse.blue, 32-bit floating-point, sampling 1 1
    diffuse.green, 32-bit floating-point, sampling 1 1
    diffuse.red, 32-bit floating-point, sampling 1 1
...
dataWindow (type box2i): (0 0) - (2047 1555)
...

## just adding a metadata
1) make an multi-different-bit-layer exr like this:
$ exrheader image.0000.exr
...
channels (type chlist):
    A, 16-bit floating-point, sampling 1 1
    B, 16-bit floating-point, sampling 1 1
    G, 16-bit floating-point, sampling 1 1
    R, 16-bit floating-point, sampling 1 1
    depth.Z, 32-bit floating-point, sampling 1 1
    diffuse.blue, 16-bit floating-point, sampling 1 1
    diffuse.green, 16-bit floating-point, sampling 1 1
    diffuse.red, 16-bit floating-point, sampling 1 1
...
2) add a metadata
$ oiiotool image.0000.exr  --sattrib "test" "test value" -o output.exr

3) chech the bit types and the metadata
$ exrheader output.exr
...
channels (type chlist):
    A, 32-bit floating-point, sampling 1 1
    B, 32-bit floating-point, sampling 1 1
    G, 32-bit floating-point, sampling 1 1
    R, 32-bit floating-point, sampling 1 1
    depth.Z, 32-bit floating-point, sampling 1 1
    diffuse.blue, 32-bit floating-point, sampling 1 1
    diffuse.green, 32-bit floating-point, sampling 1 1
    diffuse.red, 32-bit floating-point, sampling 1 1
...
test (type string): "test value"
...

### Versions

* OIIO branch/version: "tags/Release-1.6.14" and "master"
(I've checked v1.6.14 and master but they gave the same results)
* OS: cent 6
* C++ compiler: gcc 4.8.3

Best Regards,
Kazuki Takahashi

**Comment by lgritz** [comment]
I think #1491 fixes this.

**Comment by kazuki-takahashi** [comment]
Awesome! Thanks for the fix!
