### ISSUE TITLE
Build fails with OpenEXR < 2.0

### ISSUE THREAD

**Issue by lisyarus** [OpenImageIO/oiio#1447]
The commit [e3ac66244b0a9a1c5cf3f33b504183f8d0de56ab](https://github.com/OpenImageIO/oiio/commit/e3ac66244b0a9a1c5cf3f33b504183f8d0de56ab) breaks building with old versions of OpenEXR (< 2.0). 

`if (Strutil::icontains(header->type(), "tile")
          && header->hasTileDescription()) {
    ...`

There is no member `type` in `Imf::Header`.

**Comment by lgritz** [comment]
Proposed fix: #1448

**Comment by lgritz** [comment]
That patch is against RB-1.6. I will of course port the fix to master as well.

**Comment by lgritz** [comment]
Closing; this was fixed by #1448
