### ISSUE TITLE
Need to support OpenJPEG 2.x

### ISSUE THREAD

**Issue by lgritz** [OpenImageIO/oiio#1449]
Our FindOpenJPEG.cmake seems to look specifically for OpenJPEG 1.5. We should prefer 2.x, if found, and use it properly. 

The solution will need to be backported to the release branch, since some Linux distributions may drop 1.5 soon.

**Comment by lgritz** [comment]
Let Matteo Vescovi know when this is completed.

**Comment by mfvescovi** [comment]
@lgritz I've noticed that issue #957 could probably be closed once this one has a fix.
And yes, it was reported against 1.4.13... but that version is out of release at this point, afaik.

**Comment by DomT4** [comment]
Hey folks, is there any timeline on the next release at all?

We're trying to update our main `openjpeg` in `homebrew/core` _(Which is the one users get by default when they `brew install openjpeg`)_ to 2.1 & the currently released version of this project is one of the hold-ups: https://github.com/Homebrew/homebrew-science/pull/3865.

That PR there inserts a semi-hacky workaround but if we can hold off for a short time for a new tag & avoid the workaround that's certainly more desirable.

**Comment by lgritz** [comment]
I'm planning to cut releases on Aug 1, and it will build fine against OpenJpeg 2.1. Is that soon enough, or do I need to try to do it sooner? (I'm at SIGGRAPH this week, it's not a good time to try to do a release and be careful about it, unless there's an emergency.)

**Comment by DomT4** [comment]
August 1st sounds great to me. We've waited well over a year to start moving on updating our primary formula to OpenJPEG 2.1, it won't kill us to wait a little under a week more. Thanks!
