### ISSUE TITLE
Nuke txReader doesn't restore tx_mip_level properly

### ISSUE THREAD

**Issue by dbr** [OpenImageIO/oiio#1455]
With the txReader plugin (at least in Nuke 10.0v3, didn't check in older versions yet):

1) load a .tx file into Read node
2) select a different "mip level" option
2) do something like cut and paste the node, or save and reopen the script

This produces an error such as `Read1.tx_mip_level: Bad value for tx_mip_level : 1`

I assume this is because Nuke is restoring the knob value earlier than the `txFmt_->setMipLabels(mipLabels);` call occurs, so there is no options in the dropdown.

As a workaround I just changed the dropdown into a basic integer knob:
```c++
        mipLevelKnob_ = Enumeration_knob(cb, &mipLevel_, EMPTY,
                                         "tx_mip_level", "mip level");
```
..to:
```c++
        mipLevelKnob_ = Int_knob(cb, &mipLevel_, "tx_mip_level", "mip level");
```

..and commented the content of the `setMipLabels` method.

Not the best solution as it loses the nice descriptive labels on the parameter which say the size of each level.. but as a short-term fix it's preferable to not saving properly (and is backwards/forwards compatible as the knob is serialised the same way)

**Comment by nrusch** [comment]
Interesting. I wonder if the order of operations in Reader initialization and loading changed in 10.0. I'll try to take a quick look at this tomorrow to figure out more.

**Comment by nrusch** [comment]
OK, I think I have a decent solution for this. Basically, it involves using a hidden `Int_knob` to store the actual mip level index, but still exposes the pulldown of nice labels to the user.

I was toying with the idea of just throwing the `SAVE_MENU` flag on the enumeration knob, but that feels a little too brute-force, and would create a much larger footprint for the knob's serialized data.

I've tested the two-knob solution, and it appears to be working properly, so I'll put a pull request together. It would be great if you could test it as an outside party so I can be sure I'm not overlooking anything obvious. :)

**Comment by nrusch** [comment]
@dbr Pull request is up if you get the chance to give it a spin any time soon.

**Comment by lgritz** [comment]
Merged the PR, I think this is fixed now.
