### ISSUE TITLE
Cineon gets wrong colorspace metadata

### ISSUE THREAD

**Issue by devernay** [OpenImageIO/oiio#1463]
### Problem

Cineon files, either standard ones like the Kodak DLAD, or Nuke-generated ones present in the Nuke assets, get wrong metadata.

Note that I am not a Cineon specialist, but there is definitely something wrong there.
- the Kodal DLAD is said to be gamma-corrected with a gamma of 0 (see my comment in #154).
- on Nuke-generated files, the Gamma is `4.6006e-41` (which, by the way is `1.0` read with the wrong endianness), and values for cineon:HighData cineon:HighQuantity cineon:WhitePoint cineon:RedPrimary cineon:GreenPrimary cineon:BluePrimary are totally off. Note that it may be a Nuke bug.
- I do not know what "gamma" means in Cineon terms, but I thought Cineon files were always log-encoded (in which case OIIO should never return "GammaEncoded" as colorspace). Shouldn't that gamma conversion (if any) be applied _after_ log-decoding?

See the output of iinfo and ImageMagick's identify in the gist below for more details.
### Steps to Reproduce
1. download Kodak DLAD files from http://motion.kodak.com/motion/support/technical_information/lab_tools_and_techniques/digital_lad/default.htm
2. download Nuke assets from http://thefoundry.s3.amazonaws.com/downloads/Nuke_BasicWorkflows_Media.tgz
3. command:

```
find . -name '*.cin' | while read f; do echo "\$ iinfo -v $f"; iinfo -v "$f"; echo "\$ identify -verbose $f"; identify -verbose "$f"; echo ; done > cineon.log
```

output: https://gist.github.com/devernay/32bfe5fdf2501344e4075014a68260be
### Versions
- OIIO branch/version: 1.6.15
- OS: OS X 10.11.6
- C++ compiler: Apple LLVM version 7.3.0 (clang-703.0.31)

**Comment by devernay** [comment]
it seems like the header data is bigendian, and thus all 32-bit values have to be swabbed on x86, but the libcineon source code seems to only swabs the image data, not the header data (thus the crazy values read from nuke-encoded cineons). Did I miss something?

GraphicsMagick swabs the header members too:
http://hg.code.sf.net/p/graphicsmagick/code/file/7fa54cb64ff8/coders/cineon.c#l512

ImageMagick also swabs header members (it sets image->endian, and then uses ReadBlob*() which swabs):
https://github.com/ImageMagick/ImageMagick/blob/master/coders/cin.c#L450

**Comment by lgritz** [comment]
OK, I updated #1466 to just declare it log and move on.

**Comment by lgritz** [comment]
As for byte swapping, it appears that cineon::Header::Validate() does this.
If we weren't swapping properly, wouldn't the entire header be horribly garbled?

**Comment by devernay** [comment]
Indeed!
But I wonder why all these values are wrong, see `cineon.log` from the gist above:
```
    cineon:HighData: 1.76781e-38, 1.76781e-38, 1.76781e-38
    cineon:HighQuantity: 8.96831e-44, 8.96831e-44, 8.96831e-44
    cineon:WhitePoint: 9.15861e-41, 9.15861e-41
    cineon:RedPrimary: 9.15861e-41, 9.15861e-41
    cineon:GreenPrimary: 9.15861e-41, 9.15861e-41
cineon:BluePrimary: 9.15861e-41, 9.15861e-41
    cineon:XDevicePitch: -1.60948e-35
    cineon:YDevicePitch: -1.60948e-35
    cineon:FramePosition: 16777216
cineon:FrameRate: 4.60957e-41
 oiio:Gamma: 4.6006e-41
```
maybe these are just not reliable?

**Comment by lgritz** [comment]
Are we WRITING it wrong?

Or, did this file come from elsewhere, and they are writing it with the wrong endianness?

**Comment by devernay** [comment]
`./Nuke_BasicWorkflows_Media/BasicWorkflows_ColourManagement/COLOR MANAGEMENT/Source Pics/greenscreen_boy.cin`was written by Nuke 5.2 (it's in the Nuke assets, link is in the issue)
Maybe Nuke is wrong, maybe OIIO is wrong...
You'll also notice that Nuke itself doesn't make that metadata available, so maybe it's just... unreliable and oiio should ignore these fields?

**Comment by devernay** [comment]
Note: I notice that graphicsmagick extracts this metadata and the output is similar to OIIO, so I guess Nuke wrote corrupted file (GM is a pretty good reference with regards to Cineon and DPX, see http://www.graphicsmagick.org/motion-picture.html ).
What I also notice is that graphicsmagick only extracts white point, red green and blue chromaticities if they are != 0 (they are 0 in the Kodak Digital LAD which is a reference Cineon file):
http://hg.code.sf.net/p/graphicsmagick/code/file/7fa54cb64ff8/coders/cineon.c#l1223

**Comment by lgritz** [comment]
I think that #1466, long ago merged, addressed this, so I'm going to close this issue. If there is still something that needs to be done, please re-open or re-file.
