### ISSUE TITLE
Compatibility with Current FFMpeg and OpenJPEG

### ISSUE THREAD

**Issue by jiapei100** [OpenImageIO/oiio#1508]
In order to have oiio successfully built, I've got to disable USE_FFMPEG and USE_OPENJPEG

Any suggestions ?

Cheers
Pei

**Comment by lgritz** [comment]
It would certainly help if you told us exactly in what way the build was unsuccessful. What error messages specifically did you see?

For that matter, you don't tell us what version of OIIO you were trying to build, or what versions of ffmpeg and OpenJPEG you were trying to use.

**Comment by lgritz** [comment]
Looks like somebody has a patch pending (#1503) to update our use of ffmpeg for its latest API. Are you able to try that patch on your end and see if it helps your problem?

**Comment by lgritz** [comment]
I'm going to assume this is fixed and close. I know that both at work and at home, my OIIO builds are able to use ffmpeg and openjpeg with no problem.
