### ISSUE TITLE
Fail to build current oiio-git...

### ISSUE THREAD

**Issue by jiapei100** [OpenImageIO/oiio#1509]
Enviroment:
Ubuntu 16.04.1 + GCC/G++ 5.4.0

> [100%] Generating idiff.1
> cd ......//oiio/build/src/doc && ../idiff/idiff --help | /usr/bin/python ......//oiio/src/doc/help2man_preformat.py | /usr/bin/txt2man -v OpenImageIO -s 1 -t idiff > ......//oiio/build/src/doc/idiff.1
> 
> 
> make[2]: Leaving directory '......//oiio/build'
> CMakeFiles/Makefile2:1906: recipe for target 'src/doc/CMakeFiles/man_pages.dir/all' failed
> make[1]: *** [src/doc/CMakeFiles/man_pages.dir/all] Error 2
> make[1]: Leaving directory '......//oiio/build'
> Makefile:152: recipe for target 'all' failed
> make: *** [all] Error 2
> jiapei:build$ pwd
> ......//oiio/build
> jiapei:build$ ls
> 

is oiio compatible with python3 now?

Cheers
Pei

**Comment by jiapei100** [comment]
A bit improvement, but still errors:




> make -f src/doc/CMakeFiles/man_pages.dir/build.make src/doc/CMakeFiles/man_pages.dir/depend
> make[2]: Entering directory '......//oiio/build'
> cd ......//oiio/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" ......//oiio ......//oiio/src/doc ......//oiio/build ......//oiio/build/src/doc ......//oiio/build/src/doc/CMakeFiles/man_pages.dir/DependInfo.cmake --color=
> make[2]: Leaving directory '......//oiio/build'
> make -f src/doc/CMakeFiles/man_pages.dir/build.make src/doc/CMakeFiles/man_pages.dir/build
> make[2]: Entering directory '......//oiio/build'
> make[2]: *** No rule to make target '../src/doc/iv', needed by 'src/doc/iv.1'.  Stop.
> make[2]: Leaving directory '......//oiio/build'
> CMakeFiles/Makefile2:2802: recipe for target 'src/doc/CMakeFiles/man_pages.dir/all' failed
> make[1]: *** [src/doc/CMakeFiles/man_pages.dir/all] Error 2
> make[1]: Leaving directory '......//oiio/build'
> Makefile:163: recipe for target 'all' failed
> make: *** [all] Error 2
> jiapei:build$ ccmake ../
>

**Comment by lgritz** [comment]
I can't quite tell what's going on from just the tail end of the build logs. Let's get the whole thing. Try this:

    make nuke
    make VERBOSE=1 >& build.log

and paste the full log.

**Comment by jiapei100** [comment]
@lgritz 

Hi, I actually have nuke disabled, because I really do not have such a library named nuke from default repository of Ubuntu 16.04.1

Anyway,  I directly run
`make VERBOSE=1 >& build.log`
and build.log is right here [http://www.longervision.com/questions/build.log](url)

I replaced the directory prefix by "......"


Cheers
Pei

**Comment by lgritz** [comment]
Please do it again, EXACTLY like I said.

In this case 'make nuke' clears out all the caches so that the subsequent make will do the whole cmake setup from scratch and show me all the packages it found and all the build settings.

This is unrelated to USE_NUKE that controls whether to build the plugin for the Nuke compositing system.

Sorry about the confusing nomenclature. 'make nuke' to mean "get rid of everything" came long before we added a plugin for Nuke.

**Comment by jiapei100** [comment]
@lgritz 

> jiapei:build$ make nuke
> make: *** No rule to make target 'nuke'.  Stop.
> jiapei:build$ ls
> build.log  CMakeCache.txt  CMakeFiles  cmake_install.cmake  cpack  CPackConfig.cmake  CPackSourceConfig.cmake  CTestTestfile.cmake  DartConfiguration.tcl  include  Makefile  src  Testing  testsuite
> jiapei:build$ 


Cheers
Pei

**Comment by jiapei100** [comment]
Current Build Error Message:

> [ 99%] Generating iinfo.1
> cd ....../oiio/build/src/doc && ../oiiotool/oiiotool --help | /usr/bin/python3.5 ....../oiio/src/doc/help2man_preformat.py | /usr/bin/txt2man -v OpenImageIO -s 1 -t oiiotool > ....../oiio/build/src/doc/oiiotool.1
> cd ....../oiio/build/src/doc && ../iinfo/iinfo --help | /usr/bin/python3.5 ....../oiio/src/doc/help2man_preformat.py | /usr/bin/txt2man -v OpenImageIO -s 1 -t iinfo > ....../oiio/build/src/doc/iinfo.1
> 
> 
> make[2]: Leaving directory '....../oiio/build'
> CMakeFiles/Makefile2:2882: recipe for target 'src/doc/CMakeFiles/man_pages.dir/all' failed
> make[1]: *** [src/doc/CMakeFiles/man_pages.dir/all] Error 2
> make[1]: Leaving directory '....../oiio/build'
> Makefile:152: recipe for target 'all' failed
> make: *** [all] Error 2
> 


Cheers
Pei

**Comment by lgritz** [comment]
Not in the build area, at the top level. 'make nuke' removes the build area and starts over with the cmake setup.

**Comment by jiapei100** [comment]
@lgritz 

- Check the updated build.log at [http://www.longervision.com/questions/build.log](http://www.longervision.com/questions/build.log) .

- The error message seems to tell there is a conflict again FFMPEG, however, even if I "USE_FFMPEG             OFF", there is still error message as in my previous posted messages.


Any suggestions?
Pei

**Comment by lgritz** [comment]
Proposed fix is in #1514 

I think your real trouble (in this ticket) is that it's not building `iv` because it's not finding a suitable Qt version, but it's still trying to build the man page for it, and that requires executing iv.

**Comment by lgritz** [comment]
Please look at #1514 and see if you can apply that patch on your side, then let us know if it fixes your problem.

**Comment by lgritz** [comment]
@jiapei100 , have you had a chance to check if #1514 fixes your build problem with the man pages?
