### ISSUE TITLE
VS2013 - boost python def_readonly breaks build

### ISSUE THREAD

**Issue by mikaelsundell** [OpenImageIO/oiio#1516]
One last issue with VS2013 and vc120.

When building the python binding the file py_deepdata.cpp breaks with:

Error   9   error C2665: 'boost::python::detail::make_getter' : none of the 3 overloads could convert all the argument types    C:\git\build\win\vc120\x86_amd64\debug\include\boost-1_60\boost\python\data_members.hpp 279 1   PyOpenImageIO

The actual line(s) that calls make_getter (def_readonly):

```
    .def_readonly ("npixels",    &DeepData::pixels)   //DEPRECATED(1.7)
    .def_readonly ("nchannels",  &DeepData::channels) //DEPRECATED(1.7)
    .def_readonly ("pixels",     &DeepData::pixels)
    .def_readonly ("channels",   &DeepData::channels)
```

I'm not a boost expert but it seems to be related to the signature of the function pointer in VS2013, I tried several workarounds without success, .def(...) works as expected.

I looked around in PyOpenImageIO and found:

py_imagebuf.cpp:448

```
    .add_property("subimage", &ImageBuf::subimage)
    .add_property("nsubimages", &ImageBuf::nsubimages)
    .add_property("miplevel", &ImageBuf::miplevel)
    .add_property("nmiplevels", &ImageBuf::nmiplevels)
    .add_property("nchannels", &ImageBuf::nchannels)
```

This is very similar functionality BUT defined as properties, any reason why we don't use properties for exposure of read_only functions such as npixels, nchannels through all of the bindings?

This will probably break compatibility, if py_deepdata.cpp def_readonly is changed to add_property it builds as expected.

This is a proposal for a workaround and does not solve the first problem with make_getter.

**Comment by lgritz** [comment]
In master we've switched away from boost python entirely. Closing.
