### ISSUE TITLE
FTBFS on rebuilding the documentation

### ISSUE THREAD

**Issue by mfvescovi** [OpenImageIO/oiio#1550]
### Versions ###
* OIIO version: 1.7.7
* OS: Debian unstable/sid
* C++ compiler: gcc 6.2.0

Hi Larry.

As reported early this month via IM, compiling OIIO v1.7.7 in Debian unstable/sid for testing purpose before the official upload to Debian archives fails while building documentation stuff, namely the figures set prepared and bundled in the PDF file.

A snippet of the buildlog follows:
--------------- >8 ---------------
make[2]: Entering directory '/<<PKGBUILDDIR>>/src/doc'
/usr/bin/make figures
make[3]: Entering directory '/<<PKGBUILDDIR>>/src/doc'
(cmake -E make_directory figures ; \
 cd figures ; \
 OIIOTOOL=""../../../build/src/oiiotool/oiiotool"" bash ../makefigures.bash ; \
)
Using OIIOTOOL=../../../build/src/oiiotool/oiiotool
oiiotool ERROR: colorconvert : Could not construct the color transform
oiiotool ERROR: colorconvert : Could not construct the color transform
oiiotool WARNING: -o : Can't save 4 channels to jpeg... saving only R,G,B
oiiotool WARNING: -o : Can't save 4 channels to jpeg... saving only R,G,B
make[3]: Leaving directory '/<<PKGBUILDDIR>>/src/doc'
--------------- >8 ---------------

Later on, PDF creation fails with:
--------------- >8 ---------------
Overfull \hbox (34.445pt too wide) in paragraph at lines 2029--2032
[]\OT1/ptm/m/n/10.95 If \OT1/pcr/m/n/10.95 oiiotool\OT1/ptm/m/n/10.95 's global
 \OT1/pcr/m/n/10.95 -a \OT1/ptm/m/n/10.95 flag is used (\OT1/ptm/b/n/10.95 a\OT
1/ptm/m/n/10.95 ll subim-ages)), or if the op-tional \OT1/pcr/m/n/10.95 --crop:
allsubimages=1
<use figures/tahoe-small.jpg>

LaTeX Warning: File `figures/crop.jpg' not found on input line 2043.

! Package pdftex.def Error: File `figures/crop.jpg' not found.

See the pdftex.def package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.2043 ...egraphics[width=1.5in]{figures/crop.jpg}
                                                  
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on openimageio.log.
Makefile:13: recipe for target 'openimageio.pdf' failed
make[2]: *** [openimageio.pdf] Error 1
make[2]: Leaving directory '/<<PKGBUILDDIR>>/src/doc'
debian/rules:26: recipe for target 'override_dh_auto_build-indep' failed
make[1]: *** [override_dh_auto_build-indep] Error 2
make[1]: Leaving directory '/<<PKGBUILDDIR>>'
--------------- >8 ---------------

Full build log can be grabbed at:
  http://debomatic-amd64.debian.net/distribution#experimental/openimageio/1.7.7~dfsg0-1/buildlog

Cheers.

**Comment by lgritz** [comment]
I think I have a fix!  #1551

**Comment by mfvescovi** [comment]
Hi Larry!

On 2016-10-31 at 23:38 (-0700), Larry Gritz wrote:
> I think I have a fix!  #1551 

That is a fix against master branch, while I'm "stuck" at v1.7.7 so if
doesn't apply cleanly.

Could you please provide a patch against v1.7.7 so I can test it and
tell you if it works just fine?

Thanks in advance.


-- 
Matteo F. Vescovi

**Comment by lgritz** [comment]
That IS a patch against 1.7.

I will port it forward to master if it works. 



On November 1, 2016 7:21:19 AM PDT, "Matteo F. Vescovi" <notifications@github.com> wrote:
>Hi Larry!
>
>On 2016-10-31 at 23:38 (-0700), Larry Gritz wrote:
>> I think I have a fix!  #1551 
>
>That is a fix against master branch, while I'm "stuck" at v1.7.7 so if
>doesn't apply cleanly.
>
>Could you please provide a patch against v1.7.7 so I can test it and
>tell you if it works just fine?
>
>Thanks in advance.
>
>
>-- 
>Matteo F. Vescovi
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/OpenImageIO/oiio/issues/1550#issuecomment-257578414

-- 
Larry Gritz
lg@larrygritz.com

**Comment by mfvescovi** [comment]
Hi!

On 2016-11-01 at 07:51 (-0700), Larry Gritz wrote:
> That IS a patch against 1.7.

Against Release-1.7 branch, while I use released tarball to package the
library; so I need a patch against commit 222dee3.

Thanks in advance for your patience ;-)

-- 
Matteo F. Vescovi

**Comment by lgritz** [comment]
I don't make PRs against old releases, only against the tip of branches that will become future releases.

There are no conflicts in this small patch, so it should be easy to either test this directly, or to apply the diffs of this PR to an older commit if you want, but I think that's pointless.

The tip of RB-1.7 is going to become the next stable production release TODAY (first of each month). Hopefully, you're still awake and able to test my patch, so that if anything is wrong there is (rapidly dwindling) time to fix it before today's release. Otherwise, it'll make it into the next release.

**Comment by mfvescovi** [comment]
Hi @lgritz!

On 2016-11-01 at 11:46 (-0700), Larry Gritz wrote:

[...]

> The tip of RB-1.7 is going to become the next stable production
> release TODAY (first of each month). Hopefully, you're still awake and
> able to test my patch, so that if anything is wrong there is (rapidly
> dwindling) time to fix it before today's release. Otherwise, it'll
> make it into the next release.

Sorry for the late reply, but FYI this worked! :)

I'm about uploading it to experimental suite while I test all reverse
dependencies (they're a couple, indeed) ;)

Thanks a lot.

-- 
Matteo F. Vescovi

**Comment by lgritz** [comment]
Awesome!  I'm actually very relieved to hear that. I really wanted this to solve it, and not need to still be working on it for next month's release. :-)

**Comment by lgritz** [comment]
Oh, and I'm also glad I wasn't so grumpy that I didn't look at it. It would have been easy to just say "I don't care if you can't build the docs from scratch", but it turned out to be a legit bug that prevented that doc image from being created.
