### ISSUE TITLE
Can this library be used/ported  in Xcode for iOS ? 

### ISSUE THREAD

**Issue by Marini83** [OpenImageIO/oiio#1557]
Was wondering if this library can be used in Xcode for iOS ? 
Thank you.

**Comment by lgritz** [comment]
This is a great question for the oiio-dev mail list, where it will be seen by more people. We tend to use the mail list for general questions, and the GitHub "issues" only for reporting bugs.

**Comment by Marini83** [comment]
Just sent out the question on oiio-dev mail list. Thank you
