### ISSUE TITLE
Compilation warning treated as error due to GLEW 2.0.0 on CentOS 7

### ISSUE THREAD

**Issue by rskryptik61636** [OpenImageIO/oiio#1558]
### Problem

I get this warning which gets treated as an error when building OIIO on CentOS 7.

> In file included from /home/rshrinath/Downloads/oiio/src/iv/imageviewer.h:49:0,
>                  from /home/rshrinath/Downloads/oiio/src/iv/imageviewer.cpp:38:
> /usr/local/include/GL/glew.h:8689:0: error: "GL_NONE" redefined [-Werror]
>  #define GL_NONE 0x0000
>  ^
> In file included from /home/rshrinath/Downloads/oiio/src/iv/imageviewer.h:49:0,
>                  from /home/rshrinath/Downloads/oiio/src/iv/imageviewer.cpp:38:
> /usr/local/include/GL/glew.h:316:0: note: this is the location of the previous definition
>  #define GL_NONE 0

I have GLEW v2.0.0 installed and the redefinition of GL_NONE at ln 8689 is under an ifdef guard (see following snippet).

`/* -------------------- GL_EGL_KHR_context_flush_control ------------------- */

#ifndef GL_EGL_KHR_context_flush_control
#define GL_EGL_KHR_context_flush_control 1

#define GL_EGL_CONTEXT_RELEASE_BEHAVIOR_NONE_KHR 0x0000
#define GL_NONE 0x0000
#define GL_EGL_CONTEXT_RELEASE_BEHAVIOR_KHR 0x2097
#define GL_EGL_CONTEXT_RELEASE_BEHAVIOR_FLUSH_KHR 0x2098
#define GL_CONTEXT_RELEASE_BEHAVIOR 0x82FB
#define GL_CONTEXT_RELEASE_BEHAVIOR_FLUSH 0x82FC

#define GLEW_EGL_KHR_context_flush_control GLEW_GET_VAR(__GLEW_EGL_KHR_context_flush_control)

#endif /* GL_EGL_KHR_context_flush_control */`

### Steps to Reproduce

1. Install GLEW 2.0.0 to /usr/local and all of OIIO's dependencies.
2. Run make.

### Versions

* OIIO branch/version: master
* OS: CentOS 7
* C++ compiler: GCC 4.8.5 
* GLEW: 2.0.0

**Comment by lgritz** [comment]
Is this still a problem? I build on CentOS 7 all the time.

I'm going to speculatively close this. Please re-open if this is a problem on modern OIIO.
