### ISSUE TITLE
boost version

### ISSUE THREAD

**Issue by remusvrm** [OpenImageIO/oiio#1559]
### Problem
In the install file is recomanded to use boost v1.38.0.
When I compiling it, it's saying "Detected version of boost too old. Required version was 1.42 or newer ...

### Versions

* OIIO branch/version: 1.6.18
* OS: Centos 6.8
* C++ compiler:

**Comment by lgritz** [comment]
It's the documentation that's wrong. I think that for OIIO 1.6, Boost minimum really is 1.42.

I'll fix the docs in current releases.

**Comment by remusvrm** [comment]
Thanks @lgritz! I think the Boost minimum is higher then 1.44; I tried with 1.44 and it didn't work. I compiled with 1.47 and it worked.
