### ISSUE TITLE
Very high res images do not work on Windows

### ISSUE THREAD

**Issue by ThiagoIze** [OpenImageIO/oiio#1561]
I don't think this is a problem on OSX and Linux (though I could be wrong), but on Windows I get the following where no error message is displayed and no output file is presented:

```
D:\temp>oiiotool.exe -v in.png -resize 86400x43200 -o out.png
Reading out.png

D:\temp>
```

If I try even larger resolutions (note the extra 0), I can get a crash:
```
D:\temp>oiiotool.exe -v in.png -resize 86400x432000 -o out.png
Reading out.png
<App crashes at this point>
D:\temp>
```

This particular oiiotool is 1.7.3dev.

**Comment by ThiagoIze** [comment]
I can't remember for sure, but I think the issue was that it was not crashing and instead silently failing which kind of feels worse to me than crashing. Ideally OIIO would catch these errors and report a not enough memory error and then exit. In any case, it's not a big deal and I'm fine with closing this.

As for doing the work in pieces, that'd definitely be way cooler, but I don't know if it's worth the effort -- I at least will probably never need it.

**Comment by lgritz** [comment]
OK, closing. Let me know if you run into problematic cases.
