### ISSUE TITLE
Segfault on errorneous EXIF metadata.

### ISSUE THREAD

**Issue by wmatyjewicz** [OpenImageIO/oiio#1576]
Hi,

Opening the attached file with `ImageInput::open()` causes segmentation fault. It is most likely caused by erroneous EXIF metadata because:

- Stripping the metadata using `-strip` option of ImageMagick makes the problem dissapear.
- Geeqie image viewer prints the following errors & warnings when opening the image:
<pre>
Warning: Directory Image, entry 0x0111: Strip 0 is outside of the data area; ignored.
Error: Directory Image, entry 0x8769 Sub-IFD pointer 0 is out of bounds; ignoring it.
Warning: Ignoring XMP information encoded in the Exif data.
</pre>

The attached file is a minimized version of a texture for which the problem was noticed. The file contains 1x1 version of the texture with EXIF data literally copied.

The problem occurs on Windows and Linux with OpenImageIO 1.7.8.

[carpet_tex.jpg](https://cloud.githubusercontent.com/assets/4330462/20905895/0fccd6f4-bb46-11e6-882e-a7a8df86635f.jpg)

**Comment by lgritz** [comment]
I think the exif blob is badly corrupted. I can't do anything about that, but proposed fix #1585 should at least prevent OIIO software from crashing in that case.

**Comment by wmatyjewicz** [comment]
Thank you. I think it is enough not to crash.

**Comment by lgritz** [comment]
I've already committed the fix to OIIO master, and after the CI tests are back I will also backport it to RB-1.7.
