### ISSUE TITLE
Import OIIO in Nuke with OCIO support - error: undefined symbol: _ZTIN11OpenColorIO2v19ExceptionE

### ISSUE THREAD

**Issue by remusavram** [OpenImageIO/oiio#1587]
We compiled OIIO with OCIO support and try to import it in Nuke. We get the following error:
`ImportError: .../openimageIO/1.6.18/centos-6_x86-64/lib/libOpenImageIO.so.1.6: undefined symbol: _ZTIN11OpenColorIO2v19ExceptionE`

I suppose the error raise because Nuke has it's own OCIO build. 

Is there a way to compile OIIO with OCIO support and import it in Nuke?

### Versions

* OIIO branch/version: 1.6.18
* OS: centOS 6
* C++ compiler: 4.4.7
* OCIO version: 1.0.9 
* Nuke version: 10.0v3

**Comment by lgritz** [comment]
Is it possible that the OCIO build that is compiled into Nuke itself is a different version than the 1.0.9 that you used when you built OIIO?

**Comment by remusvrm** [comment]
I checked the version of the OCIO build into Nuke itself and is the same version, version 1.0.9.

**Comment by remusvrm** [comment]
I also asked on Nuke Forum, but unfortunately the Forum is quite dead...
http://community.thefoundry.co.uk/discussion/topic.aspx?f=191&t=128290

**Comment by nrusch** [comment]
The OCIO library distributed with Nuke uses a custom build namespace of `FnOpenColorIO`, so you either need to roll a separate OIIO build that accounts for that, or provide your own OCIO libraries at runtime.

**Comment by lgritz** [comment]
The conversation seems to have died on this one, and in any case it references outdated versions of OIIO, OCIO, and Nuke. Presuming that it's not an ongoing issue. Closing. Please re-open or re-file if it's a continued problem for anybody with modern versions of those packages.
