### ISSUE TITLE
Can't read the image twice from a PFM file

### ISSUE THREAD

**Issue by dictoon** [OpenImageIO/oiio#1600]
### Problem

**Input file**: [envmap.zip](https://github.com/OpenImageIO/oiio/files/691991/envmap.zip)

**Expected behavior:** `ImageInput::read_image()` returns a valid image every time it is called on the same open input file, regardless of the image file format.

**Actual behavior:** `ImageInput::read_image()` returns false (and `ImageInput::geterror()` returns an empty string) the second time it is invoked on the same open input file (but it returned a valid image the first time).

**Not** tested with newer releases or master because I cannot do that easily.

### Steps to Reproduce

    auto image = ImageInput::open("envmap.pfm");
    auto spec = image->spec();
    auto storage = new unsigned char[spec.width * spec.height * spec.nchannels * 4];

    auto success1 = image->read_image(spec.format, storage);
    auto success2 = image->read_image(spec.format, storage);

    // success1 is true but success2 is false

### Versions

* OIIO branch/version: 1.5.20
* OS: Windows 10 x64
* C++ compiler: Visual Studio 2015

**Comment by dictoon** [comment]
Happens with other PNM files as well.

**Comment by lgritz** [comment]
I'm not sure this is a bug. For any format that doesn't return `input->supports("random_access") == true` (which the PNM reader does not), the scanlines must be read strictly in order. In such files, if you have read scanline N and then you want to read scanline M < N, or after you have already read the last scanline of the image, you are expect to either `close()` and re-`open()` to start over or to read a previously-read scanline.

And `read_image` is equivalent to reading each scanline from first to last, so two successive calls to `read_image` is the equivalent of backtracking in the scanlines you're reading. So I think the solution/workaround is to close and re-open.

Though there are two open questions:

1. In addition to a close/open cycle, should it also work to leave the file open but call `seek_subimage()` again? As currently implemented, that will not work -- seek_subimage to the current (or only) subimage is just a no-op, but I think it's reasonable to argue that seek_subimage to the *current* subimage should have the effect of also resetting the current scanline to 0. What do you think? I'm honestly not sure if that change would break more use cases than it would fix. (It could also be expensive for some formats, still necessitating a full close/open cycle to implement.)

2. For formats that return `input->supports("random_access") == false`, should a request to read scanlines "randomly" (including going back to scanline 0) be an error, as it currently is, or instead should it be supported, but with bad performance performance? (That's potentially a big change that would need to have implementation for every non-random-read format.)

**Comment by dictoon** [comment]
> For any format that doesn't return input->supports("random_access") == true (which the PNM reader does not), the scanlines must be read strictly in order.

Woops, I didn't know about that flag.

>  So I think the solution/workaround is to close and re-open.

Got it.

> In addition to a close/open cycle, should it also work to leave the file open but call seek_subimage() again?

That's the workaround I was initially planning to implement.

It would seem rather natural to me that a call to `seek_subimage()` always resets the file pointer to the beginning of the image, even if the image is the current one, and even if it's the only one in the file.

> Should a request to read scanlines "randomly" (including going back to scanline 0) be an error, as it currently is?

I think so. I personally tend to design APIs that only expose highly performing primitives and make inefficient constructs as explicit as possible (and not supporting them at all is rather explicit).

**Comment by lgritz** [comment]
I think the primary question in this issue was answered long ago. Not sure why it was left open for so long. Closing now.
