### ISSUE TITLE
read_tiles decodes more channels than necessary

### ISSUE THREAD

**Issue by MrKepzie** [OpenImageIO/oiio#1606]
### Problem

[read_tiles](https://github.com/OpenImageIO/oiio/blob/master/src/libOpenImageIO/imageinput.cpp#L408) takes a chbegin and chend in parameter but only honours it in the case of native and contiguous data... for all other cases it allocates a temporary buffer that can contain all possible channels and calls read_tile (without chbegin, chend) resulting in the internal openexr input having to decode all channels of the tile.

For a file with e.g 32 channels it will allocate a temporary buffer bigger than necessary and ask OpenEXR to process data that will then be just discarded. The worse is that these channels are even converted to the requested format in [read_tile](https://github.com/OpenImageIO/oiio/blob/master/src/libOpenImageIO/imageinput.cpp#L486) even if they are going to be thrown away in the [copy_image](https://github.com/OpenImageIO/oiio/blob/master/src/libOpenImageIO/imageinput.cpp#L496) call below.

**Expected behavior:** [What you expected to happen]

Only allocate memory for channels the user asked for and have the internal OpenEXR input decode only those channels.

### Versions

* OIIO branch/version:  master

**Comment by lgritz** [comment]
Are you sure? I think that maybe this was fixed. Looking at the current version of ImageInput::read_tiles, it appears that it calls the variety of `read_native_tiles` that takes a chbegin/chend range, and therefore ought to allocate just the amount it needs (and at least for OpenEXR, avoiding reading the channels outside this range).

The exception is for tiles where the number of pixels is not the full tile width/height, which will generally only happen for the last tile of each row, and the last row of the image (and then, only if the image width or height is not an even multiple of the tile size). For the vast majority of tiles on any large image, it already does the thing you want. (Making it also be fully optimized for those incomplete tiles at the edges is a lot more code complexity, and will only improve the read of a small minority of tiles in the image).

So I *think* this already is done? Therefore I'm going to close the issue, but I urge you to re-open or file again if you think that I'm wrong and that here is a significant performance problem in the current (RB-2.0/master) code base that needs to be addressed.
