### ISSUE TITLE
Links to install on Windows not working

### ISSUE THREAD

**Issue by StefanAchm** [OpenImageIO/oiio#1608]
I just tried to install OpenImageIO on Windows 10, and came to the Site, where it is descriped, how to install it (https://sites.google.com/site/openimageio/building-oiio-on-windows).
There, the link for QT4 is not working (http://qt-windows-binaries.googlecode.com/svn/site/index.html) and also the link for BOOST is not working (http://www.boostpro.com/download)

Are there alternative links?

**Comment by KindDragon** [comment]
You can install it from `vcpkg` https://github.com/Microsoft/vcpkg

**Comment by earthbound19** [comment]
oiio port at vcpkg; may solve a lot of open windows build issues: https://github.com/Microsoft/vcpkg/tree/master/ports/openimageio

**Comment by lgritz** [comment]
Yes. Vcpkg looks pretty cool.

Unfortunately, the oiio recipe disables support for many of the file formats (like gif), doesn't build the python bindings, or the binaries (like oiiotool). Those should all be built if the vcpkg oiio is going to be useful to people who want the whole package.

**Comment by Nuclearfossil** [comment]
Has there been any movement on correcting the documentation issues? Saying "there's a vcpkg" doesn't solve the underlying issue of the links not working and the documentation being incorrect.

**Comment by meimchu** [comment]
Hey Larry I just recently forked this project and built it on my computer (MacOS) and also noticed the same documentation link error. I will be more than happy to create a pull request with the links removed or replaced per your discretion. I looked through the main site map and did not see appropriate links to replace them with at the moment, but if there are, please let me know and I can update the .md file accordingly. Thank you.

**Comment by lgritz** [comment]
Absolutely! Any ways to improve the documentation links, and especially any of the docs for how to build on Windows, would be very much appreciated. Just submit a PR as usual.

By the way, since this issue was first filed, I do think that vcpkg has increased the amount of OIIO functionality that they build, including making the python bindings and the command line utilities.

Also, I think it's relatively straightforward to use "Conan" to build OIIO and its dependencies for Windows.

**Comment by meimchu** [comment]
Pull request [#2502 ](https://github.com/OpenImageIO/oiio/pull/2502) merged.

**Comment by lgritz** [comment]
Does that close the issue, or is there more to do and we should hold it open?

**Comment by lgritz** [comment]
I think this has been updated some time ago. Closing.
