### ISSUE TITLE
Missing OpenImageIO.pc file

### ISSUE THREAD

**Issue by BuildMonkey** [OpenImageIO/oiio#1634]
It would be great for the install script created the pkgconfig file, OpenImageIO.pc, for OpenImageIO. Is this possible? Would make things easier for me to link against the lib.

Thanks!

**Comment by lgritz** [comment]
Hi, sorry to leave this hanging for so long.

I'm afraid I don't know much about pkgconfig. I would love to have this also, but what it really requires is a volunteer who knows more than I do about it, to submit a PR that implements it.

**Comment by hobbes1069** [comment]
Formatting one is not difficult but knowing what to put in it, and properly automated/implemented in CMake would be a little work.

**Comment by hobbes1069** [comment]
Here's one I do on the fly in the RPM spec file for another project/package I maintain on Fedora. It could be a config file with @ONLY substitution with the right variables. This one uses some standard variables for RPM packaging but you get the idea:

```
# Create and install pkgconfig file
mkdir -p %{buildroot}%{_libdir}/pkgconfig
cat > %{buildroot}%{_libdir}/pkgconfig/codec2.pc << EOF
prefix=%{_prefix}
exec_prefix=\${prefix}
includedir=\${prefix}/include/%{name}
libdir=\${exec_prefix}/%{_lib}

Name: codec2
Description: Next-Generation Digital Voice for Two-Way Radio
Version: %{version}
Cflags: -I\${includedir}
Libs: -L\${libdir} -l%{name}
EOF
```

The key is knowing if there's any additional required libraries to link against which can change depending on what optional dependencies are configured at build time.

**Comment by lgritz** [comment]
I'm a true amateur when it comes to pkgconfig. Dunno how it works and dunno how to test it properly.

I invite anybody interested who knows what they are doing to implement, test, and submit a PR for a fully working solution that addresses this issue, and I will happily merge it.

I'll leave it at that. Closing.
