### ISSUE TITLE
Crash on Jpeg with corrupted EXIF 

### ISSUE THREAD

**Issue by Nazg-Gul** [OpenImageIO/oiio#1635]
### Problem

OIIO will crash with specific Jpeg file with corrupted EXIF header.

**Expected behavior:** OIIO should just ignore invalid pars of EXIF.

**Actual behavior:** Any OIIO tool will crash.

This happens with 1.7.8 and latest master.

### Steps to Reproduce

Simply run any tool like iinfo on the attached file.

![wood](https://cloud.githubusercontent.com/assets/23765/23712921/96535c6c-0424-11e7-8ef4-91acff50a05b.jpg)

Here is ASAN output, just in case:  [asan.txt](https://github.com/OpenImageIO/oiio/files/828249/asan.txt)

### Versions

* OIIO branch/version:  1.7.8. and master
* OS: Linux
* C++ compiler: GCC-6

**Comment by lgritz** [comment]
Fixed by #1639

**Comment by lgritz** [comment]
Aside: I was unable to reproduce with this image. Maybe your original upload was broken, but by the time GitHub lets me download it, I think the offending Exif has been stripped on their end. I'm not sure GH attachments is a fruitful way to send images if the exact metadata matters.

Does GH allow zip file attachments? Maybe if you zip it up and attach the zip file, people can then download that to get the exact bit-for-bit original image.

**Comment by lgritz** [comment]
Hmmm, I'm not even sure if it allows arbitrary non-image uploads. So the images it lets you attach are probably just intended to be viewed inline as documentation/explanation of the issue (which allows sanitizing of the image), and not DATA to reproduce the issue (which would require perfect preservation, including crasher corruptions).

**Comment by Nazg-Gul** [comment]
Hi Larry.,

Unfortunately, i'm not sure how to reliably trigger crash on Linux. Thing is: the crash happens really easy when build with MSVC (AFAIK, it does some extra protection checks, especially in debug builds). On Linux the only reliable way to spot the issue was to compile with ASAN (-fsanitize=address). There might be some tweak to the stack protector somewhere in /sys/ to tighten check around pointer dereference, but those magic i'm not aware of. Valgrind will also show the error, but man, it's quite really slow.

As for the picture, it seems to still have the same buggy EXIF as the original file. But just in case, here is a link to original .zip archive in our bug tracker: https://developer.blender.org/F501679

Wood.jpg is the file which demonstrates the issue.

Hope that helps.

P.S. Was still trying to get testsuite to work here without much luck. Will try fresh checkout, with all the demo files and such checked out as well.
