### ISSUE TITLE
Linking Issues on Windows with Visual Studio 2017 BuildTools

### ISSUE THREAD

**Issue by KelSolaar** [OpenImageIO/oiio#1699]
### Problem

Hi,

I have linking issues on Windows using Visual Studio 2017 BuildTools.

**Expected behavior:**

Linking should occur without errors.

**Actual behavior:**

Linking occurs with errors:

```
"D:\Documents\Development\ThirdParty\openimageio\build\oiio\INSTALL.vcxproj" (default target) (1) ->
"D:\Documents\Development\ThirdParty\openimageio\build\oiio\ALL_BUILD.vcxproj" (default target) (3) ->
"D:\Documents\Development\ThirdParty\openimageio\build\oiio\src\libOpenImageIO\OpenImageIO.vcxproj" (default target) (5) ->
(Link target) ->
  jpeg.lib(jerror.c.obj) : error LNK2019: unresolved external symbol __imp___iob_func referenced in function output_message [D:\Documents\Development
\ThirdParty\openimageio\build\oiio\src\libOpenImageIO\OpenImageIO.vcxproj]
  tiff.lib(tif_unix.obj) : error LNK2001: unresolved external symbol __imp___iob_func [D:\Documents\Development\ThirdParty\openimageio\build\oiio\src
\libOpenImageIO\OpenImageIO.vcxproj]
  tiff.lib(tif_unix.obj) : error LNK2019: unresolved external symbol __imp_vfprintf referenced in function unixWarningHandler [D:\Documents\Developme
nt\ThirdParty\openimageio\build\oiio\src\libOpenImageIO\OpenImageIO.vcxproj]
  tiff.lib(snprintf.obj) : error LNK2019: unresolved external symbol __imp__vscprintf referenced in function _TIFF_vsnprintf_f [D:\Documents\Developm
ent\ThirdParty\openimageio\build\oiio\src\libOpenImageIO\OpenImageIO.vcxproj]
  tiff.lib(snprintf.obj) : error LNK2019: unresolved external symbol __imp__vsnprintf_s referenced in function _TIFF_vsnprintf_f [D:\Documents\Develo
pment\ThirdParty\openimageio\build\oiio\src\libOpenImageIO\OpenImageIO.vcxproj]
  D:\Documents\Development\ThirdParty\openimageio\build\oiio\src\libOpenImageIO\Release\OpenImageIO.dll : fatal error LNK1120: 4 unresolved externals
 [D:\Documents\Development\ThirdParty\openimageio\build\oiio\src\libOpenImageIO\OpenImageIO.vcxproj]
```

### Steps to Reproduce

I'm running with a very minimalist set of dependencies right now and the command I issue is as follows:

> cmake D:\Documents\Development\ThirdParty\openimageio\oiio -DCMAKE_INSTALL_PREFIX=D:\Documents\Development\ThirdParty\openimageio/build\release -DILMBASE_INCLUDE_PATH=C:\Users\thomas\Packages\ilmbase\2.2.0\ilmbase\include -DOPENEXR_INCLUDE_PATH=C:\Users\thomas\Packages\openexr\2.2.0\openexr\include -DBOOST_ROOT=C:\Users\thomas\Packages\boost\1.64.0\boost -G "Visual Studio 15 Win64" -T v141,host=x64

Here is a Gist with the full output: https://gist.github.com/KelSolaar/d27ee328824fc7a079fdfbbc28b9d03d

### Versions

* OIIO branch/version: 1.7.15
* OS: Windows 10
* C++ compiler: Visual Studio 2017 BuildTools - cl

**Comment by KelSolaar** [comment]
Just to confirm that same happens with https://github.com/OpenImageIO/oiio/releases/tag/Release-1.8.4dev

**Comment by DaciP** [comment]
Try to link "legacy_stdio_definitions.lib" library to your input project, this is for deprecated function names compatibility that was substituted into recent visual studio releases.
