### ISSUE TITLE
ImageMagick reports errors with tiffs from OIIO

### ISSUE THREAD

**Issue by ThiagoIze** [OpenImageIO/oiio#1700]
Some of the tif files generated by OIIO cause ImageMagick to report errors.  This has been going on for a couple years so it's not a recent bug.  Using the latest ImageMagick-6.9.8-4_0+x11 installed through macports on my OSX machine, combined with a tif file that comes with the OIIO 1.7.15 repository, I get:

```
% identify testsuite/oiiotool/ref/exprgradient.tif
testsuite/oiiotool/ref/exprgradient.tif TIFF 512x384 512x384+0+0 8-bit sRGB 4302B 0.000u 0:00.000
identify: Failed to allocate memory for to read TIFF directory (0 elements of 12 bytes each). `testsuite/oiiotool/ref/exprgradient.tif' @ error/tiff.c/TIFFErrors/567.
identify: Failed to read custom directory at offset 3184. `TIFFReadCustomDirectory' @ error/tiff.c/TIFFErrors/567.
```
Since this is happening with a tif file that is included with OIIO, this can't be due to my building OIIO or the tif library incorrectly.  It is, however, entirely possible the bug is in ImageMagick.

The good news is that despite the errors printed out, ImageMagick still seems to finish the operation requested of it, so at least this isn't a critical bug.

**Comment by lgritz** [comment]
Well, 'tiffinfo' also complains, so I don't think it's an ImageMagick error.
I'll take a look. The tiffinfo error message is a little different, and gives an interesting clue:

TIFFFetchDirectory: Sanity check on directory count failed, zero tag directories not supported.
TIFFReadCustomDirectory: Failed to read custom directory at offset 3184.

**Comment by lgritz** [comment]
Interestingly, although `tiffinfo` sees this error on the reference image, it does not have any problem with the NEW image generated by running the testsuite.

Maybe there was something weird, at the time that I first generated the ref image?

Thiago, if you run the testsuite and then use `identify` on the newly generated image of the same name (not in testsuite/oiiotool/ref, but rather in dist/PLATFORM/testsuite/oiiotool), does it still have the error, or no?

Are you able to coax modern OIIO into making a file that ImageMagick doesn't like? Or is it only for long-ago created reference images?

**Comment by ThiagoIze** [comment]
Good news, it looks like somewhere between 1.7.12 and 1.7.15 this was fixed (probably one of the many tiff exif related fixes?).  I thought I was looking at recently generated tif files, but I guess not.

Sorry for the noise and happy to see this bug finally gone :)

**Comment by ThiagoIze** [comment]
Just in case anyone else comes across this and upgrading OIIO doesn't help, I should note we also upgraded at the same time to tif-4.0.8, so it could also be that which fixed things.

**Comment by lgritz** [comment]
I'll update the reference image for this test. Are there any others you found with these errors?

**Comment by ThiagoIze** [comment]
If my script worked correctly, the following files generated an error:

testsuite/oiiotool/ref/exprcropped.tif
testsuite/oiiotool/ref/exprgradient.tif
testsuite/oiiotool/ref/exprstrcatlzw.tif
testsuite/oiiotool/ref/filled.tif
testsuite/oiiotool/ref/flip-crop.tif
testsuite/oiiotool/ref/flipflop-crop.tif
testsuite/oiiotool/ref/flop-crop.tif
testsuite/oiiotool/ref/invert.tif
testsuite/oiiotool/ref/pixelaspect.tif
testsuite/oiiotool/ref/reorient1.tif
testsuite/oiiotool/ref/reorient2.tif
testsuite/oiiotool/ref/reorient3.tif
testsuite/oiiotool/ref/rotate180.tif
testsuite/oiiotool/ref/rotate270-crop.tif
testsuite/oiiotool/ref/rotate270.tif
testsuite/oiiotool/ref/rotate90-crop.tif
testsuite/oiiotool/ref/rotate90.tif
testsuite/oiiotool/ref/tahoe-median.tif
testsuite/oiiotool/ref/transpose-crop.tif
testsuite/oiiotool/ref/trim.tif
testsuite/oiiotool/ref/unsharp-median.tif
testsuite/oiiotool/src/tahoe-tiny.tif
testsuite/oiiotool-pattern/ref/fill4.tif
testsuite/oiiotool-pattern/ref/filled.tif
testsuite/oiiotool-pattern/ref/fillh.tif
testsuite/oiiotool-pattern/ref/fillv.tif
testsuite/oiiotool-pattern/ref/noise-gauss.tif
testsuite/oiiotool-pattern/ref/noise-salt.tif
testsuite/oiiotool-pattern/ref/noise-uniform3.tif
testsuite/oiiotool-pattern/ref/pattern-const.tif
testsuite/oiiotool-pattern/ref/pattern-gradient4.tif
testsuite/oiiotool-pattern/ref/pattern-gradienth.tif
testsuite/oiiotool-pattern/ref/pattern-gradientv.tif
testsuite/oiiotool-text/ref/text.tif
testsuite/python-imagebuf/ref/outarray.tif
testsuite/python-imagebuf/ref/outarrayB.tif
testsuite/python-imagebuf/ref/outarrayH.tif
testsuite/python-imagebuf/ref/outtuple.tif
testsuite/texture-mip-nomip/ref/out.tif
testsuite/texture-mip-onelevel/ref/out.tif

**Comment by lgritz** [comment]
interesting! I'll update the ref images

**Comment by lgritz** [comment]
Updated ref images in master and RB-1.7. Closing.
