### ISSUE TITLE
Libraw headers are not properly included during compilation on Windows.

### ISSUE THREAD

**Issue by KelSolaar** [OpenImageIO/oiio#1703]
### Problem

Libraw headers are not properly included during compilation on Windows.

The configuration step seem to behave as expected:

```
-- Looking for LibRaw with
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE)
-- Found LibRaw: K:/Packages/ThirdParty/libraw/0.18.2/platform-windows/arch-AMD64/libraw/lib/libraw.lib (found version "0.18.2")
-- Found LibRaw, include K:/Packages/ThirdParty/libraw/0.18.2/platform-windows/arch-AMD64/libraw/libraw
```

Well actually, on Windows I'm specifying both `-DLibRaw_LIBRARIES` and `-DLibRaw_r_LIBRARIES` with same values as the library is [thread-safe](https://www.libraw.org/docs/Install-LibRaw.html)

I will try to print messages around to see if I can find something, that being said I'm pretty much a **CMake** noob.

**Expected behavior:**

Libraw headers should be properly included.

**Actual behavior:**

> D:\Documents\Development\ThirdParty\openimageio\oiio\src\raw.imageio\rawinput.cpp(36): fatal error C1083: Cannot open include file: 'libraw/libraw.h': No such file or directory [D:\Documents\Development\ThirdParty\openimageio\build\oiio\src\libOpenImageIO\OpenImageIO.vcxproj]

### Steps to Reproduce

This is my current and growing invocation command:

> call vcbuildtools.bat amd64 && cd /d D:\Documents\Development\ThirdParty\openimageio/build\oiio && cmake D:\Documents\Development\ThirdParty\openimageio\oiio -DVERBOSE=ON -DCMAKE_INSTALL_PREFIX=D:\Documents\Development\ThirdParty\openimageio/build\release -DILMBASE_INCLUDE_PATH=K:\Packages\ThirdParty\ilmbase\2.2.0\platform-windows\arch-AMD64\ilmbase\include -DOPENEXR_INCLUDE_PATH=K:\Packages\ThirdParty\openexr\2.2.0\platform-windows\arch-AMD64\openexr\include -DBOOST_ROOT=K:\Packages\ThirdParty\boost\1.64.0\platform-windows\arch-AMD64\boost -DZLIB_ROOT=K:\Packages\ThirdParty\zlib\1.2.11\platform-windows\arch-AMD64\zlib -DJPEG_LIBRARY=K:\Packages\ThirdParty\libjpeg_turbo\1.5.1\platform-windows\arch-AMD64\libjpeg-turbo\lib\jpeg.lib -DJPEG_INCLUDE_DIR=K:\Packages\ThirdParty\libjpeg_turbo\1.5.1\platform-windows\arch-AMD64\libjpeg-turbo\include -DTIFF_LIBRARY=K:/Packages/ThirdParty/libtiff/4.0.8/platform-windows/arch-AMD64/tiff/lib/tiff.lib -DTIFF_INCLUDE_DIR=K:\Packages\ThirdParty\libtiff\4.0.8\platform-windows\arch-AMD64\tiff\include -DPNG_LIBRARY=K:/Packages/ThirdParty/libpng/1.6.29/platform-windows/arch-AMD64/libpng/lib/libpng16.lib -DPNG_INCLUDE_DIR=K:\Packages\ThirdParty\libpng\1.6.29\platform-windows\arch-AMD64\libpng\include -DLibRaw_LIBRARIES=K:\Packages\ThirdParty\libraw\0.18.2\platform-windows\arch-AMD64\libraw\lib\libraw.lib -DLibRaw_r_LIBRARIES=K:\Packages\ThirdParty\libraw\0.18.2\platform-windows\arch-AMD64\libraw\lib\libraw.lib -DLibRaw_INCLUDE_DIR=K:\Packages\ThirdParty\libraw\0.18.2\platform-windows\arch-AMD64\libraw\libraw -G "Visual Studio 14 2015 Win64" -T v140,host=x64

### Versions

* OIIO branch/version: 1.8.4dev
* OS: Windows 10
* C++ compiler: MSVC 2015

**Comment by lgritz** [comment]
The libraw finding has been revised since this ticket was filed, and PR #1959 I think fixed this. Re-open or re-file if there are further problems.
