### ISSUE TITLE
Unsetting the various "*PYTHON*" variables prevents passing a custom interpreter to "CMake".

### ISSUE THREAD

**Issue by KelSolaar** [OpenImageIO/oiio#1704]
### Problem

Unsetting the various **\*PYTHON\*** variables in the related [CMakeList.txt](https://github.com/OpenImageIO/oiio/blob/master/src/python/CMakeLists.txt#L30) file prevents passing a custom Python interpreter to *CMake*.

**Expected behavior:**

I would like to be able to pass a custom Python interpreter to *CMake*, and managed to do so by commenting all the `unset` statements.

**Actual behavior:**

It is impossible to pass a custom Python interpreter to *CMake*.

### Steps to Reproduce

Invoke *CMake* with path to custom Python interpreter:

> cmake ... -DPYTHON_LIBRARY=/path/to/python27.lib -DPYTHON_INCLUDE_DIR=/path/to/python/includes 

### Versions

* OIIO branch/version: 1.8.4dev
* OS: Windows
* C++ compiler: MSVC 2015

**Comment by lgritz** [comment]
I changed some things about the python finding in #2015, among others. I think you ought to be able to build if you explicitly `-DPYTHON_EXECUTABLE=...`. Can you check if the current master still is a problem for this?

**Comment by lgritz** [comment]
No reply. Maybe fixed? Closing. Please re-open if it's still a problem in OIIO 2.0 or the current master.
