### ISSUE TITLE
"OpenCV" "CMake" built libraries are not found on Windows.

### ISSUE THREAD

**Issue by KelSolaar** [OpenImageIO/oiio#1707]
### Problem

*OpenCV* *CMake* built libraries are not found on Windows.

**Expected behavior:**

`FindOpenCV.cmake` should be able to find them.

**Actual behavior:**

`FindOpenCV.cmake` did not find the libraries because when compiling *OpenCV* on Windows with *CMake*, the libraries get a version number appended to their name:

```
OpenCVConfig.cmake
OpenCVModules-release.cmake
OpenCVModules.cmake
opencv_calib3d2413.lib
opencv_contrib2413.lib
opencv_core2413.lib
opencv_features2d2413.lib
opencv_flann2413.lib
opencv_gpu2413.lib
opencv_highgui2413.lib
opencv_imgproc2413.lib
opencv_legacy2413.lib
opencv_ml2413.lib
opencv_nonfree2413.lib
opencv_objdetect2413.lib
opencv_ocl2413.lib
opencv_photo2413.lib
opencv_stitching2413.lib
opencv_superres2413.lib
opencv_ts2413.lib
opencv_video2413.lib
opencv_videostab2413.lib
```

I did patch the offending file as follows on my end: https://github.com/KelSolaar/oiio/commit/c970073e2e8f482ce611a6ebb2aab1a714d68d61

### Steps to Reproduce

Build *OpenImageIO* with *OpenCV* *CMake* built libraries on Windows.

### Versions

* OIIO branch/version: 1.8.4dev
* OS: Windows
* C++ compiler: MSCV2015

**Comment by lgritz** [comment]
Can you submit your solution as a PR?

**Comment by KelSolaar** [comment]
Hey Larry,

I have no clue if my fork patch is working on Linux or macOs at all, it was merely a hack to get it working on my end.

**Comment by lgritz** [comment]
Yeah, but if you submit your patch that makes it work on Windows, the CI builds it kicks off on Travis will tell us right away if it works there, and if not, I can fix it.

I don't have a Windows machine (or any expertise whatsoever), so the one thing I can't do myself is figure out how to make it work on Windows. But I can easily take somebody else's Windows code and make sure it doesn't break Linux/Mac.

**Comment by lgritz** [comment]
The cmake scripts in question (related to opencv) have been considerably edited since this was filed. I'm going to presume the problem is fixed. Please re-open or re-file if it's still broken in OIIO 2.0+.

**Comment by KelSolaar** [comment]
Hey @lgritz,

This is still an issue and I had to do that to get it working:

```diff
diff --git a/src/cmake/modules/FindOpenCV.cmake b/src/cmake/modules/FindOpenCV.cmake
index 8d42ddd40..93f2d4098 100644
--- a/src/cmake/modules/FindOpenCV.cmake
+++ b/src/cmake/modules/FindOpenCV.cmake
@@ -36,8 +36,10 @@ if (EXISTS "${_ocv_version_file}")
     string (REGEX MATCHALL "[0-9]+" CV_VERSION_REVISION ${TMP})
     if (CV_VERSION_EPOCH)
         set (OpenCV_VERSION "${CV_VERSION_EPOCH}.${CV_VERSION_MAJOR}.${CV_VERSION_MINOR}")
+        string(REPLACE "." "" OpenCV_VERSION_SUFFIX "${OpenCV_VERSION}")
     else ()
         set (OpenCV_VERSION "${CV_VERSION_MAJOR}.${CV_VERSION_MINOR}.${CV_VERSION_REVISION}")
+        string(REPLACE "." "" OpenCV_VERSION_SUFFIX "${OpenCV_VERSION}")
     endif ()
 endif ()

@@ -50,11 +52,11 @@ set (libdirs "${PROJECT_SOURCE_DIR}/lib"
              )

 if (NOT ${OpenCV_VERSION} VERSION_LESS 4.0.0)
-    set (opencv_components opencv_core opencv_imgproc opencv_videoio)
+    set (opencv_components opencv_core opencv_imgproc opencv_videoio opencv_core${OpenCV_VERSION_SUFFIX} opencv_imgproc${OpenCV_VERSION_SUFFIX} opencv_videoio${OpenCV_VERSION_SUFFIX})
 elseif (NOT ${OpenCV_VERSION} VERSION_LESS 3.0.0)
-    set (opencv_components opencv_videoio opencv_imgproc opencv_core)
+    set (opencv_components opencv_videoio opencv_imgproc opencv_core opencv_videoio${OpenCV_VERSION_SUFFIX} opencv_imgproc${OpenCV_VERSION_SUFFIX} opencv_core${OpenCV_VERSION_SUFFIX})
 else (NOT ${OpenCV_VERSION} VERSION_LESS 2.0.0)
-    set (opencv_components opencv_highgui opencv_imgproc opencv_core)
+    set (opencv_components opencv_highgui opencv_imgproc opencv_core opencv_highgui${OpenCV_VERSION_SUFFIX} opencv_imgproc${OpenCV_VERSION_SUFFIX} opencv_core${OpenCV_VERSION_SUFFIX})
 endif ()
 foreach (component ${opencv_components})
     find_library (${component}_lib
```

I will create a PR this time! :)

**Comment by lgritz** [comment]
Cool, looking forward to the PR!

**Comment by KelSolaar** [comment]
I'm documenting quite a few problems (with solutions when I found them) while building the latest on Windows. I will open a separate issue summarizing all that.
