### ISSUE TITLE
ADX missing in DPX transfer and colorimetric caracteristics

### ISSUE THREAD

**Issue by peegee70** [OpenImageIO/oiio#1725]
ADX color space from ACES is not supported in DPX transfer and colorimetric metadata.  It is defined in an SMPTE amendment: "Amendment 1:2012 to SMPTE 268M-2003".  It is defined like this:

Value: 13
Description: SMPTE ST 2065-3 Academy Density Exchange Encoding (ADX)

That would be great if someone could add this.  Thanks everyone for this great piece of software.

**Comment by lgritz** [comment]
Sorry for the inexcusably long delay, this slipped through the cracks somehow.
Fix is in the works!
