### ISSUE TITLE
maketx relies on initialization order of static variables when OCIO support is enabled

### ISSUE THREAD

**Issue by dictoon** [OpenImageIO/oiio#1750]
### Problem

OIIO relies on initialization order of static variables when OCIO support is enabled.

First static variable (`maketx.cpp` line 73):

    static ColorConfig colorconfig;

This leads to a call to `ColorConfig::Impl::inventory()`:

    void
    ColorConfig::Impl::inventory ()
    {
    #ifdef USE_OCIO
        if (config_) {
            bool nonraw = false;
            for (int i = 0, e = config_->getNumColorSpaces();  i < e;  ++i)
                nonraw |= ! Strutil::iequals(config_->getColorSpaceNameByIndex(i), "raw");
            // ...
        }
        // ...
    #endif
        // ...
    }

`Strutil::iequals()` calls `boost::algorithm::iequals()` with `loc` as 3rd argument. `loc` is the second static variable (`strutil.cpp` lines 303-305):

    namespace {
    static std::locale loc = std::locale::classic();
    }

Minimal standalone repro case that exhibits the problem:

    #include <locale>

    extern std::locale loc;

    inline bool iequals(const std::locale& Loc = std::locale()) {
        return true;
    }

    struct C {
        C()     {
            iequals(loc);
        }
    };

    static C c;

    static std::locale loc = std::locale::classic();

    int main() {
        return 0;
    }

### Versions

* OIIO branch/version: 1.7.10
* OS: Windows 10 64-bit
* C++ compiler: Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24213.1 for x64

**Comment by lgritz** [comment]
Proposed solution in #1757 

@dictoon, Can you try that PR and let me know if it seems to solve the problem on your end?
