### ISSUE TITLE
segmentation fault on opening possibly corrupted jpeg file. 

### ISSUE THREAD

**Issue by tomansill** [OpenImageIO/oiio#1759]
### Problem

I was using OIIO for my application and I've noticed that OIIO causes my program to throw a segmentation fault when it was trying to open a certain jpeg file. GDB reports the segmentation fault comes from jpeg_alloc_quant_table () from libjpeg.so.8. 

The stack looks like:
https://gist.github.com/tomansill/0cfbed5784e0467363da3765a0dc2420

I've investigated my code to see if it was causing OIIO to throw a segmentation fault but I cannot seem to find it. I tried to open the same image that caused my program to break, with oiiotool to see if the problem is limited to my application. It turns out that it is not limited to my application as it threw a segmentation fault also. 

My terminal shows:
indigo% oiiotool 34535.jpg -resize 8x8 -o resized.jpg
zsh: segmentation fault (core dumped)  oiiotool 34535.jpg -resize 8x8 -o resized.jpg

Running GDB shows (with where command):
https://gist.github.com/tomansill/c50c940cacdab408ef43dbacac22e61a

The problem could be coming from libjpeg so I've decided to test for that also to confirm the source of the problem. I tried djpeg program that is reportedly to be using libjpeg. It did not crash but it reports that the jpeg file is corrupted. 

My terminal shows:
indigo% djpeg -scale 1/2 34535.jpg > out.jpg              
Corrupt JPEG data: 2 extraneous bytes before marker 0xdb

I was able to open the corrupted jpeg file in Nautilus File Manager and Eye of Gnome Image Viewer just fine. 

**Expected behavior:**  No segmentation fault and it should either fix and continue silently or throw exception.

**Actual behavior:**  Segmentation fault

### Steps to Reproduce

1. Obtain an corrupted jpeg file (I've attached a zip file containing the corrupted jpeg file, never mind the content of the file)
2. Use oiiotool on the file with commands similar to oiiotool file -resize 8x8 -o out
3. Observe the segmentation fault

### Versions

* OIIO branch/version: 1.7.13
* OS:  Arch Linux x64
* C++ compiler: Installed using pacman with precompiled package

Corrupted file download: [corrupted_jpeg.zip](https://github.com/OpenImageIO/oiio/files/1271618/corrupted_jpeg.zip)

**Comment by tomansill** [comment]
UPDATE:
I've been successfully reproduced the problem with latest OIIO 1.8.5 that was pulled from master branch of this repository and compiled with GCC 7.1.1

**Comment by lgritz** [comment]
Good news, I have a fix for this old bug: #2073
