### ISSUE TITLE
Merge layered EXR to single file

### ISSUE THREAD

**Issue by paulwinex** [OpenImageIO/oiio#1764]
### Problem: I can't merge list of layered EXR files.

I have list of EXR files (rendered tiles) like this:

![regions](https://user-images.githubusercontent.com/7323236/30238244-0dae3bd4-954c-11e7-907e-b5fa9f2baca6.png)
Each file have list of layers. C, N, P, Reflection, SSS etc...
Now i need to merge all regions to single EXR with **ADD** operation and save all layers.

### Steps to Reproduce

I try this code

```
import OpenImageIO as oiio

b0 = oiio.ImageBuf("D:/regions/reg_0.exr")
b1 = oiio.ImageBuf("D:/regions/reg_1.exr")
b2 = oiio.ImageBuf("D:/regions/reg_2.exr")
b3 = oiio.ImageBuf("D:/regions/reg_3.exr")
b4 = oiio.ImageBuf("D:/regions/reg_4.exr")
b5 = oiio.ImageBuf("D:/regions/reg_5.exr")
full_size = oiio.ImageBuf()
oiio.ImageBufAlgo.add(full_size, b0, b1)
oiio.ImageBufAlgo.add(full_size, full_size, b2)
oiio.ImageBufAlgo.add(full_size, full_size, b3)
oiio.ImageBufAlgo.add(full_size, full_size, b4)
oiio.ImageBufAlgo.add(full_size, full_size, b5)

out_file = "D:/regions/output.exr"
full_size.write(out_file)
```
Now i have all layers but only two first images in output file.
![regions2](https://user-images.githubusercontent.com/7323236/30238280-b0ba59ca-954c-11e7-834a-2d7af3eb116a.png)

I thing i not understand something. Ok, let's try different way. I have coordinates of all regions and i try to PASTE each region to final image:
```
# join
d = "D:/regions"
# load file with region coordinates, something like this:
#
#[
#   [ [x1, y1, x2, y2],[x1, y1, x2, y2],[x1, y1, x2, y2],[x1, y1, x2, y2] ].
#   [ [x1, y1, x2, y2],[x1, y1, x2, y2],[x1, y1, x2, y2],[x1, y1, x2, y2] ].
#   [ [x1, y1, x2, y2],[x1, y1, x2, y2],[x1, y1, x2, y2],[x1, y1, x2, y2] ].
#]

mx = json.load(open(matrix_file)) 
# get and sort list of regions files
regions = [os.path.join(d, x) for x in sorted(os.listdir(d), key=lambda x: int(re.findall(r"\d+$", os.path.splitext(x)[0])[0]))]
#result:
# >>> regions
# ['D:/regions/reg_0.exr', 'D:/regions/reg_1.exr', 'D:/regions/reg_2.exr', ...]
# now i collect all images to ImageBuf array
array = []
for row in mx:
    for reg in row:
        path = regions.pop(0)
        print path, reg
        array.append(dict(
            region=reg,
            img=oiio.ImageBuf(path),
            path=path
        ))
# get spec from first file, all files have same spec
spec = array[0]['img'].spec()
# new output file, i use maximum resolution from coordinates, channels count and format
full_size = oiio.ImageBuf(oiio.ImageSpec(mx[-1][-1][-2], mx[-1][-1][-1], spec.nchannels, spec.format))
# now i combine all regions to single image
for reg in array:
    oiio.ImageBufAlgo.paste(full_size, reg['region'][0], reg['region'][1], 0, 0, reg['img'])
# and save it
full_size.write("D:/output.exr")
```
Now i have cool final image, but names and order of channels is broken (((
![regions3](https://user-images.githubusercontent.com/7323236/30238392-80c2d6ea-954f-11e7-815b-2caf43aa8517.png)
Please, help me to understand how to merge regions to single image with multilayer EXR. Maybe you have library of examples for Python?

### Versions

* OIIO branch/version: Python module OpenImageIO‑1.5.22‑bin‑vc9‑x64 from http://www.lfd.uci.edu/~gohlke/pythonlibs/#openimageio
* OS: WIndows 10
* C++ compiler: vc9

_PS: [Regions files for tests](https://www.dropbox.com/s/wsnyxmi9w46jthv/regions.zip?dl=0) _

**Comment by fredlllll** [comment]
it seems the add function can also work with less parameters, so doing full_size = oiio.ImageBufAlgo.add(b0, b1) and then full_size = oiio.ImageBufAlgo.add(full_size, b2) might work for you? would be worth a try

**Comment by paulwinex** [comment]
YEssss!

```
full_size = oiio.ImageBufAlgo.add(b0, b1)
full_size = oiio.ImageBufAlgo.add(full_size, b2)
full_size = oiio.ImageBufAlgo.add(full_size, b3)
full_size = oiio.ImageBufAlgo.add(full_size, b4)
full_size = oiio.ImageBufAlgo.add(full_size, b5)
```
Just 2 year of waiting and problem is solved))) Thanks!

**Comment by fredlllll** [comment]
glad that its still relevant :P

**Comment by lgritz** [comment]
Sorry this one fell through the cracks.

Despite the new variety of add() call working, I'm not sure why the old one failed and would like to track down the problem.

Do you think you could attach (or email me) the files so I can directly try it myself?

**Comment by paulwinex** [comment]
This is my test files
https://www.dropbox.com/s/watuwiw21z8mg6g/regions.zip?dl=0

**Comment by lgritz** [comment]
Thanks (and I see now that you had the link all along, sorry to ask again).

I can reproduce the problem, which is a good start.

**Comment by lgritz** [comment]
OK, I see what's happening. It's not actually a bug, but it is somewhat counter-intuitive behavior that we may want to debate whether it should be changed.

So basically, IBA functions that look like this:

    result_img = IBA::function (A_img, B_img, ...);

create an entirely new ImageBuf for the result, and it will be allocated to be (generally) the union of the data windows of A and B.

The IBA functions that look like this:

    IBA::function (result_img, A_img, B_img, ...)

if result_img is uninitialized, it will be allocated and sized to be the union of the data windows of A and B (same as above).

But if result_img is already an existing image, the interpretation is that it should not be resized, and the region on which you are doing the computation is the data window of the existing image. So of course, if you are saying

    IBA::add (A, A, B);

This will only add B to the parts of A that already exist.

**Discussion**

For this task, you definitely want to use the `result=add(A,B)` form. In fact, now that this exists (as of 2.0), I recommend that everybody always use this more intuitive form unless there are reasons not to.

The whole point of still having the 3-argument version of `add(result,A,B)` is for power users with performance-sensitive cases to avoid any extra copies or allocations, or to write a sub-region into an existing image without disturbing the rest of it.

So there are two ways forward:

1. If our priority is for `IBA::func(result,...)` to be a power user feature that doesn't re-allocate or copy: Leave everything as is. And in any case, now that the `result=IBA::func(A,B,...)` form is provided, that's the main one we're documenting and promoting, so hopefully people getting bit by this counter-intuitive case will be rare.

2. If our priority is to ensure that `A=func(A,B)` is ALWAYS equivalent to `func(A,A,B)` by definition: We could perhaps automatically detect the cases where the result destination is the same as one of the input images and reallocate if necessary? This has the benefit of the "principle of least surprise", but it's probably an extensive and error-prone set of changes to make sure the behavior is sensible for every single IBA function.

I'm leaning toward (1), but feedback is welcome on how to proceed from here.

**Comment by paulwinex** [comment]
Actually no different for me now, it will be more clear later when i will develop my "stitcher". I can not advise in this case. I know that i will need to merge images not simply "add" method but with "cut->paste" by specific coordinates. Because source images will have padding 2-5 pixels to avoiding line on seams. Its second sketch from my first message. Can you test it too?

**Comment by lgritz** [comment]
So I want to point out another way that the original code code have been fixed:

    # NO: empty initialization will get a size of the first thing you give it, b0+b1
    # full_size = oiio.ImageBuf()

    # YES: start with the full size image really being the full size, then as you
    # add things into it, the plxels have someplace to go:
    fullspec = b0.spec()
    fullspec.set_roi (oiio.roi_union(fullspec.roi(), b1.roi())
    fullspec.set_roi (oiio.roi_union(fullspec.roi(), b2.roi())
    fullspec.set_roi (oiio.roi_union(fullspec.roi(), b3.roi())
    fullspec.set_roi (oiio.roi_union(fullspec.roi(), b4.roi())
    fullspec.set_roi (oiio.roi_union(fullspec.roi(), b5.roi())
    full_size = oiio.ImageBuf (fullspec)

    # Now this all should work fine:
    oiio.ImageBufAlgo.add(full_size, b0, b1)
    oiio.ImageBufAlgo.add(full_size, full_size, b2)
    oiio.ImageBufAlgo.add(full_size, full_size, b3)
    oiio.ImageBufAlgo.add(full_size, full_size, b4)
    oiio.ImageBufAlgo.add(full_size, full_size, b5)

Hopefully this points the way for you to use paste...

1. Set up the an ImageBuf initialized to the full size as above.

2. Use ImageBufAlgo.copy() to paste each section at its nominal position:

        oiio.ImageBufAlgo.copy(full_size, b0)
        oiio.ImageBufAlgo.copy(full_size, b1)
        ....

   Note that `copy()` is the same thing as `paste()`, when you are pasting into the offset that the src already has, if you catch my drift. You only need paste when you want to change the offset.

**Comment by lgritz** [comment]
Sorry, slight mistake in the last message:

Where I wrote `imagebuf.roi()`, that should really be `imagebuf.roi`, it is exposed as an attribute rather than a method.

**Comment by paulwinex** [comment]
I use OpenImageIO 2.0.7 on WIndows 10 and get errors:
```
AttributeError: 'OpenImageIO.ImageSpec' object has no attribute 'set_roi'
AttributeError: module 'OpenImageIO' has no attribute 'roi_union'
```
What wrong?

Code:
```
import OpenImageIO as oiio
print(oiio.__version__)
# '2.0.7'
b0 = oiio.ImageBuf("D:/regions/reg_0.exr")
b1 = oiio.ImageBuf("D:/regions/reg_1.exr")
b2 = oiio.ImageBuf("D:/regions/reg_2.exr")
b3 = oiio.ImageBuf("D:/regions/reg_3.exr")
b4 = oiio.ImageBuf("D:/regions/reg_4.exr")
b5 = oiio.ImageBuf("D:/regions/reg_5.exr")

fullspec = b0.spec()
fullspec.set_roi(oiio.roi_union(fullspec.roi, b1.roi))  # ERRORS
fullspec.set_roi(oiio.roi_union(fullspec.roi, b2.roi))
fullspec.set_roi(oiio.roi_union(fullspec.roi, b3.roi))
fullspec.set_roi(oiio.roi_union(fullspec.roi, b4.roi))
fullspec.set_roi(oiio.roi_union(fullspec.roi, b5.roi))
full_size = oiio.ImageBuf(fullspec)

oiio.ImageBufAlgo.add(full_size, b0, b1)
oiio.ImageBufAlgo.add(full_size, full_size, b2)
oiio.ImageBufAlgo.add(full_size, full_size, b3)
oiio.ImageBufAlgo.add(full_size, full_size, b4)
oiio.ImageBufAlgo.add(full_size, full_size, b5)

out_file = "D:/regions/output.exr"
full_size.write(out_file)
```

**Comment by lgritz** [comment]
oh my, you are right.

That's what I get for just writing code off the top of my head and not testing.

set_roi() is a method of ImageBuf, not ImageSpec. And I played a little fast and loose with the Python assignment versus copy (I speak Python not at all fluently, and with a very thick C++ accent).

I believe the correct code is:

```
import OpenImageIO as oiio
print(oiio.__version__)

b0 = oiio.ImageBuf("reg_0.exr")
b1 = oiio.ImageBuf("reg_1.exr")
b2 = oiio.ImageBuf("reg_2.exr")
b3 = oiio.ImageBuf("reg_3.exr")
b4 = oiio.ImageBuf("reg_4.exr")
b5 = oiio.ImageBuf("reg_5.exr")

roi = oiio.ROI()
roi = oiio.union(roi, b0.roi)
roi = oiio.union(roi, b1.roi)
roi = oiio.union(roi, b2.roi)
roi = oiio.union(roi, b3.roi)
roi = oiio.union(roi, b4.roi)
roi = oiio.union(roi, b5.roi)

fullspec = b0.spec().copy()
fullspec.roi = roi
fullspec.roi_full = roi
full_size = oiio.ImageBuf(fullspec)

oiio.ImageBufAlgo.zero (full_size)
oiio.ImageBufAlgo.add(full_size, b0, b1)
oiio.ImageBufAlgo.add(full_size, full_size, b2)
oiio.ImageBufAlgo.add(full_size, full_size, b3)
oiio.ImageBufAlgo.add(full_size, full_size, b4)
oiio.ImageBufAlgo.add(full_size, full_size, b5)

out_file = "output.exr"
full_size.write(out_file)
```

**Comment by paulwinex** [comment]
Yes, its works!!! Thanks!
This is the code for any count of regions.

```
import OpenImageIO as oiio

images = [
    "regions/reg_0.exr",
    "regions/reg_1.exr",
    "regions/reg_2.exr",
    "regions/reg_3.exr",
    "regions/reg_4.exr",
    "regions/reg_5.exr",
   # ...
]
roi = oiio.ROI()
buf_array = [oiio.ImageBuf(img) for img in images]
fullspec = buf_array[0].spec().copy()

for buf in buf_array:
    roi = oiio.union(roi, buf.roi)

fullspec.roi = roi
fullspec.roi_full = roi
full_size = oiio.ImageBuf(fullspec)
oiio.ImageBufAlgo.zero(full_size)
oiio.ImageBufAlgo.add(full_size, buf_array.pop(0), buf_array.pop(0))
while buf_array:
    oiio.ImageBufAlgo.add(full_size, full_size, buf_array.pop(0))
out_file = "output.exr"
full_size.write(out_file)
```
And back now to my previous question about coordinates. For example i have specific crop sizes for each region. Ho i  can cut/paste defined regions to the single image?
```
[
  [
    [0, 0, 639, 239], 
    [640, 0, 1280, 239]
  ], 
  [
  	[0, 240, 639, 479], 
    [640, 240, 1280, 479]
  ], 
  [
    [0, 480, 639, 720], 
    [640, 480, 1280, 720
    ]
  ]
]
```

**Comment by lgritz** [comment]
Assuming that each of the image subsections has the right data window (in other words, you are just pasting it into its current position in the assembled image), then simply replace the `add` with:

    b = buf_array.pop(0)
    oiio.ImageBufAlgo.copy(full_size, b, roi=b.roi)

So you are just copying the contents of each image to the master, but restricting the copy region to its own data window (so it doesn't replace the other parts).

If you need to copy to a *different* position, then you could use

    oiio.ImageBufAlgo.paste(full_size, new_x, new_y, new_z, b)

**Comment by paulwinex** [comment]
Each region has padding 2-5 pix and i need to copy only specific region and paste copied part to generic image. x and y is actual coordinates.
Maybe something like this (pseudo code)
```
b = buf_array.pop(0)
oiio.ImageBufAlgo.copy(b, x, y, w, h) # get some part and nothing more
oiio.ImageBufAlgo.paste(full_size, b, x, y) # paste to specific position
```
PS. Maybe i should create new topic for this question?

**Comment by lgritz** [comment]
If you know the region, then just

    oiio.ImageBufAlgo.copy (full_size, b, roi=your_roi)

**Comment by paulwinex** [comment]
Thanks, i understand now)
```
new_region = oiio.ImageBuf()
oiio.ImageBufAlgo.copy(new_region, buffer, oiio.ROI(x, y, w, h))
...
```

**Comment by lgritz** [comment]
Nope, sorry.

ROI constructor arguments are (xbegin, xend, ybegin, yend, zbegin, zend, chbegin, chend)

And remember that the "end" are *exclusive*, i.e., one past the last pixel you wish included.

**Comment by lgritz** [comment]
so, you would want:

    oiio.ImageBufAlgo.copy(new_region, buffer, oiio.ROI(x, x+w, y, y+h, 0, 1, 0, nchannels))

**Comment by paulwinex** [comment]
> so, you would want:
> 
> ```
> oiio.ImageBufAlgo.copy(new_region, buffer, oiio.ROI(x, x+w, y, y+h, 0, 1, 0, nchannels))
> ```

Yes, thanks!

**Comment by lgritz** [comment]
Shall we close the issue at long last?
:-)

**Comment by paulwinex** [comment]
Yes, ofc.
