### ISSUE TITLE
[Documentation] Section 6.18 Uses "PDF" in place of "PSD".

### ISSUE THREAD

**Issue by kennycarruthers** [OpenImageIO/oiio#1767]
I think there's a minor typo in the documentation that accidentally interchanges "PSD" with "PDF". 

OpenImageIO 1.8 Programmer Documentation
25 Mar 2017
Page 107

> Section 6.18 PSD
> 
> PSD is the file format used for storing Adobe PhotoShop images. OpenImageIO provides limited read abilities for PDF, but not currently the ability to write PSD files.

Note the use of the acronym "PDF" in that passage. Unless I'm mistaken, I think it should be "PSD" as there is no other mention of "PDF" file types within the context of Section 6.18.

**Comment by lgritz** [comment]
Thanks for catching! I will fix.
