### ISSUE TITLE
MacOs Brew install not working "out of the box"

### ISSUE THREAD

**Issue by IPv6** [OpenImageIO/oiio#1784]
### Problem
- Installed openimageio via brew on MacOs Sierra 10.12.16

**Expected behavior:**  
- oiiotool should work out-of-the-box

**Actual behavior:**
- dyld: Symbol not found: __ZNK5boost16re_detail_10650031cpp_regex_traits_implementationIcE17transform_primaryEPKcS4_
  Referenced from: /usr/local/Cellar/openimageio/1.7.17/lib/libOpenImageIO.1.7.dylib
  Expected in: /usr/local/opt/boost/lib/libboost_regex-mt.dylib
 in /usr/local/Cellar/openimageio/1.7.17/lib/libOpenImageIO.1.7.dylib

**Comment by skycaptain** [comment]
The formula migrated to Homebrew/homebrew-core, due to Homebrew/homebrew-science#6616. Could you please retry, once Homebrew/homebrew-core#22522 is merged?

**Comment by lgritz** [comment]
That error message looks like something that can crop up when OIIO and Boost were not compiled with the same C++ standard (one with 11, the other with 03, for example) or with quite different gcc versions.

**Comment by earthbound19** [comment]
I believe this is resolved. `brew install openimageio` worked and when I ran some test commands against images via `oiiotool` and `idiff` they produced and saved valid output images.

**Comment by lgritz** [comment]
Great, thanks for the check.
