### ISSUE TITLE
loading EXR with rational type frame rate in metadata prints debug message to terminal

### ISSUE THREAD

**Issue by apetrynet** [OpenImageIO/oiio#1790]
### Problem

Whenever loading an image to an image buffer I get a debug message in the active terminal even when compiled as "Release".
Have only tried in Python, but tracked down error message to [this line](https://github.com/OpenImageIO/oiio/blob/master/src/openexr.imageio/exrinput.cpp#L676) in the main source so I assume it happens in C++ implementations as well.
Everything works, but I guess there was supposed to be a flag here controlling the output or something?

**Expected behavior:**  
Load image without debug message

**Actual behavior:**  
It does what I ask, but prints the following to the terminal even if built as Release:
`OIIO DEBUG: adding rational with numerator 12582913 and denominator 524288 (easy case)`

I have not tried compiling master, but the debug statement lives in both Release-1.8.5 branch and master.
It respects the OPENIMAGEIO_DEBUG=0 environment variable. 

### Steps to Reproduce
in python
1. import OpenImageIO as oiio
2. buf = oiio.ImageBuf('/path/to/image.1001.exr')

### Versions

* OIIO branch/version: Release-1.8.5
* OS: Ubuntu14.04
* C++ compiler: g++ 4.8.4

**Comment by apetrynet** [comment]
Ok, if I added OPENIMAGEIO_DEBUG=0 to the compile options It works fine. Not sure if I'm a complete noob or something changed, but I can't recall having to do this before.

Apologize if this turns out to be nothing and I have wasted your time.

**Comment by lgritz** [comment]
You're right, that's a mistake. Those lines were for debugging while that code was being developed, and should have been removed. I'll take care of it today.

**Comment by apetrynet** [comment]
Thanks!

**Comment by lgritz** [comment]
I took a more detailed look at this, and I'm not sure I understand. What's *supposed* to happen is:

* For release builds, it only prints if `OPENIMAGEIO_DEBUG=1`

* For debug builds, it prints *unless* `OPENIMAGEIO_DEBUG=0`

And it seems to behave that way for me.

Are you really super sure that you were testing a release build, and not a debug build? 

(I still think that those particular debug statements can go away, now that the code in question is working... however, I want to track down why the general debug behavior is not working, before I forget about it.)

**Comment by apetrynet** [comment]
This is really strange.
Just to make super duper sure that I was building a release and still get
the messages I rebuilt today and to my surprise it worked exactly like it's
supposed to. I then tried to provoke the messaging again by digging into my
build history and and applying the options I initially used without being
able to reproduce!

Not able to get my head around how I would make a mistake so many times in
a row resulting in a debug build, I decided to  deliberately build a Debug
release to make sure the messages appear. After confirming this I tried
building a release and now I'm back to getting a debug build even when
passing `CMAKE_BUILD_TYPE=Release`. I confirmed this by going through the
build log. So it seems like once you build a debug there's no way back.

This triggered the idea of this being a case of stale files.
I've tried `make clean` and `make nuke` but still get the Debug build. Even
if I remove all folders I can think of used in building the debug release I
still get a debug build when asking for release.

I'm using make and not cmake directly when building. Could it be some
environment variables set that I don't know of or an issue in overriding
the build type from debug to release through make that's causing this?
Overriding release with debug apparently works.
Now, even passing the `OPENIMAGEIO_DEBUG=0` option doesn't seem to help.

I'll keep looking for answers at my end, but it would be great if you would
be able to check if the debug first, release second causes the same issues
for you.

Thank you so much for you time!

-Daniel

**Comment by apetrynet** [comment]
I found the culprit!
If I have `CODECOV=0` in my options I get a debug build no matter what. If I remove it I get a release as expected.

**Comment by lgritz** [comment]
Aha, great, mystery solved, and I see the error that made that happen.
Patch coming right away...

**Comment by apetrynet** [comment]
Brilliant!
Thanks again!
