### ISSUE TITLE
Unneeded indirect dependency on Qt5

### ISSUE THREAD

**Issue by hobbes1069** [OpenImageIO/oiio#1835]
See: https://bugzilla.redhat.com/show_bug.cgi?id=1412089

I have the following patch for Fedora but I'm not sure if it is the best way to fix the problem (hence the issue instead ofPR)

```
$ cat OpenImageIO-as_needed.patch
--- a/src/cmake/modules/FindOpenCV.cmake
+++ b/src/cmake/modules/FindOpenCV.cmake
@@ -51,9 +51,11 @@
              )


-set (opencv_components opencv_highgui opencv_imgproc opencv_core)
+set (opencv_components opencv_imgproc opencv_core)
 if (NOT ${OpenCV_VERSION} VERSION_LESS 3.0.0)
     set (opencv_components opencv_videoio ${opencv_components})
+else ()
+    set (opencv_components opencv_highgui ${opencv_components})
 endif ()
 foreach (component ${opencv_components})
     find_library (${component}_lib
```

**Comment by lgritz** [comment]
I guess this is fine. So the highgui library is only needed for OpenCV 2.x but not 3.x? 

Can you submit it as a PR?

**Comment by hobbes1069** [comment]
Here's a cut and paste from https://docs.opencv.org/3.2.0/db/dfa/tutorial_transition_guide.html

`highgui module has been split into parts: imgcodecs, videoio and highgui itself`

I'll work on a PR soon.

**Comment by hobbes1069** [comment]
Done.
