### ISSUE TITLE
Could NOT find OpenEXR:

### ISSUE THREAD

**Issue by yonelay11** [OpenImageIO/oiio#1837]
I download openEXR 2..2.1 and build it and pointed into OPENEXR_INCLUDE_PATH.  But they show this error message, **the Could NOT find OpenEXR: Found unsuitable version "1.6.1", but required is
  at least "2.0" (found )**
I saw that version 1.6.1 is in the external directories. (eg. D:\OIIO\external\dist\windows\openexr-1.6.1), but I change OPENEXR_INCLUDE_PATH to version 2.2.1. But, they don't know. Where need I modify?

**Comment by omento** [comment]
I found setting -DILMBASE_HOME and -DOPENEXR_HOME solved this issue for me. Commenting for other's reference.

Cheers,
Mike

**Comment by scimunk** [comment]
Hi Mike, I tried to setup the 2 var you mentioned  (to C:/Workspace/Project/USDProject/openexr-2.3.0/build/IlmBase and C:/Workspace/Project/USDProject/openexr-2.3.0/build/OpenExr), but I still get this message, what is the exact step to make it work ? I'm a real noob with Cmake.

**Comment by johnrbent** [comment]
I had the same error. Fixed it with:
apt-get install libopenexr-dev
rather than just installing the libopenexr22 package

**Comment by lgritz** [comment]
Yeah, quite frequently there are separate packages for just the binaries/libraries, and another one that includes all the headers and whatnot that you need in order to do development.
