### ISSUE TITLE
multilib support for library installation

### ISSUE THREAD

**Issue by ssuominengentoo** [OpenImageIO/oiio#185]
small patch to support multilib, like lib64:

--- CMakeLists.txt
+++ CMakeLists.txt
@@ -91,11 +91,11 @@

 # Exec Install Locations
 set (BINDIR   "${CMAKE_INSTALL_PREFIX}/bin")
-set (LIBDIR   "${CMAKE_INSTALL_PREFIX}/lib")
+set (LIBDIR   "${CMAKE_INSTALL_PREFIX}/lib${LIB_SUFFIX}")
 set (PYLIBDIR "${CMAKE_INSTALL_PREFIX}/python")
 if (EXEC_INSTALL_PREFIX)
     set (BINDIR   "${EXEC_INSTALL_PREFIX}/bin")
-    set (LIBDIR   "${EXEC_INSTALL_PREFIX}/lib")
-    set (LIBDIR   "${EXEC_INSTALL_PREFIX}/lib${LIB_SUFFIX}")
   set (PYLIBDIR "${EXEC_INSTALL_PREFIX}/python")
  endif ()

**Comment by lgritz** [comment]
Closing. This slipped through the cracks somehow, and in years nobody has asked for it. The cmake files have change too much for a direct merge. I trust that if this is important, someone will ask for it again.
