### ISSUE TITLE
Bad conversion with oiiotool of a vertical raw file

### ISSUE THREAD

**Issue by gregoire-dl** [OpenImageIO/oiio#1854]
### Problem

Hi,
We get a bad conversion with **oiiotool** of a raw file (tested with `.CR2` and `.RW2`) to `.JPG` when the image is vertical. The output JPG image becomes horizontal and the image is incorrect.
It works fine when the input RAW image is horizontal and it also works fine when the input image is a `.JPG` (horizontal or vertical).
We get the problem when using the `master` branch or release `1.8.7` and the problem was not there in release `1.7.16`.

**Expected behavior:**

The input vertical raw file should be convert to a vertical `.JPG` file without buffer shift.

**Actual behavior:**

Here is the input `.RW2` image (in a zip to be accepted by github): [P1330452.zip](https://github.com/OpenImageIO/oiio/files/1660708/P1330452.zip)

- Using OpenImageIO `master` branch:

`oiiotool -i P1330452.RW2 -o P1330452_oiiotool_master.jpg`
gives this output image (here re-compressed for github):
![p1330452_oiiotool_master](https://user-images.githubusercontent.com/16002026/35346471-a0b13970-0132-11e8-98a9-37cbaaf832bd.jpg)

- Using OpenImageIO `1.7.16` release:

`oiiotool -i P1330452.RW2 -o P1330452_oiiotool_1_7_16.jpg`
gives this output image: 
![p1330452_oiiotool_1_7_16](https://user-images.githubusercontent.com/16002026/35345072-f45ebfba-012e-11e8-9bd0-a3c3f3fcc6b9.jpg)

### Versions

* OIIO branch/version: master (January 24, 2018)
* OS: Linux
* C++ compiler: g++-4.9

**Comment by fabiencastan** [comment]
Hi,
Any help on this issue would be most appreciated. We are currently stuck as we need a recent version to get metadata, but in this new version we cannot load RAW files anymore.
Thanks,

**Comment by lgritz** [comment]
Looking at it now...

**Comment by lgritz** [comment]
OK, I've got it figured out. There are two potential ways to deal with it.

1. Let libraw rotate the image for us into the right correct display orientation (i.e. from the OIIO client app point of view, the rotated image will be 3464 x 4608).

2. Leave the image in the same orientation as it is stored in the file, but report the orientation with the "Orientation" metadata.

Which do you prefer? Or should there be an open-with-configuration option? (If so, which is default?)

**Comment by fabiencastan** [comment]
Thanks a lot! We will test that tomorrow.
In our use case, we don't need to get the original orientation.

**Comment by lgritz** [comment]
Any word on whether this fixed your issue?

**Comment by gregoire-dl** [comment]
Hi, 
unfortunately no.
Using the first-post vertical `.RW2` image:
`oiiotool -i P1330452.RW2 -o P1330452_oiiotool.jpg`
gives this output image:
![p1330452_oiiotool_master](https://user-images.githubusercontent.com/16002026/35920203-7f7f3dde-0c17-11e8-80cb-789829dc07f8.jpg)

The output image should be vertical but the result is still horizontal. There are no more buffer shift but width and height seem to be swapped.

I also tried your fix with some vertical `.CR2`, `.NEF`, `.ARW` and `.RAW` files from [https://www.rawsamples.ch](https://www.rawsamples.ch): 
- Nikon D3X
- Sony NEX-3N
- Canon EOS 1Ds Mark 2
- Panasonic Lumix FZ18

Results are the same (here with the Canon EOS 1Ds Mark 2):
![1dsm2_oiiotool_master](https://user-images.githubusercontent.com/16002026/35920760-0dee3204-0c19-11e8-8439-4f8ab8f73e24.jpg)

**Comment by fabiencastan** [comment]
@lgritz Can you reproduce the problem that we are facing?

**Comment by fabiencastan** [comment]
Do you have an idea where it comes from?
Could we help to fix it?

**Comment by lgritz** [comment]
I just pushed an update to #1863 that I think is the right fix. Can you give it a try?

**Comment by fabiencastan** [comment]
Great! We just tested it on many raw images and it works fine!
Thanks a lot

**Comment by fabiencastan** [comment]
It may be useful to add one vertical raw image in the unittest.
The following files from https://www.rawsamples.ch are vertical images: [Nikon D3X](http://www.rawsamples.ch/raws/nikon/d3x/RAW_NIKON_D3X.NEF), [Sony NEX-3N](http://rawsamples.ch/raws/sony/RAW_SONY_NEX3N.ARW), [Canon EOS 1Ds Mark 2](http://www.rawsamples.ch/raws/canon/1dsm2/RAW_CANON_1DSM2.CR2), [Panasonic Lumix FZ18](http://www.rawsamples.ch/raws/panasonic/fz18/RAW_PANASONIC_LUMIX_FZ18.RAW).

**Comment by lgritz** [comment]
OK, updated.

1. Changed one of the two test images to be a vertical example (the Nikon D3X).

2. Also fixed the Orientation metadata. Please re-test and make sure you are ok with this. If we're letting libraw reorient the image, we need to reset any Orientation metadata that may have been in the Exif so it doesn't contradict what we decoded.
