### ISSUE TITLE
CMake does not find openjpeg@2.3

### ISSUE THREAD

**Issue by skycaptain** [OpenImageIO/oiio#1867]
### Problem

`FindOpenJpeg.cmake` does not search for recent version of openjpeg (2.3).

### Versions

* OIIO branch/version: master-latest
* OS: N/A
* C++ compiler: N/A

### References

See https://github.com/Homebrew/homebrew-core/pull/22522#issuecomment-364563031

**Comment by lgritz** [comment]
Fix proposed in #1871 
I'll backport to the release branch as well.
