### ISSUE TITLE
how do I use oiiotool on negative frame ranges?

### ISSUE THREAD

**Issue by rebx** [OpenImageIO/oiio#1889]
### Problem

I've been using oiiotool for various tasks (resizing, etc.) but I think I have hit a snag with negative frames. For example, I'm trying to convert a couple of EXR images whose frame range is from -23 to -5 (a subset of a bigger frame range). However, it seems like it starts finding the frames from 0 and exits with an error like 

```
oiiotool ERROR: read : File does not exist: "foo.0000.exr"
```
Can you please let me know if this is a known issue or if there is a workaround for this? Thanks!

**Expected behavior:**  oiiotool should be able to process negative frames

**Actual behavior:**  oiiotool seems to remap the numbering to zero but fails to find the frame as it does not exist

### Steps to Reproduce

1. Create the test frames
```bash
$ mkdir /tmp/testframes
$ cd !$
$ for i in `seq -23 -5`; do frn=$(printf %04d $i); oiiotool --create 1024x768 3 --text:size=100 "test $frn" -o test_frame.$frn.exr; done
```
2. Try to perform an operation, like resize
```bash
$ oiiotool test_frame.#.exr --resize 512x0 -o test_resize.#.exr --frames -23--5
oiiotool ERROR : read : File does not exist: "test_frame.0000.exr"
$ oiiotool test_frame.#.exr --resize 512x0 -o test_resize.#.exr --frames -5--23
oiiotool ERROR : read : File does not exist: "test_frame.0000.exr"
```
### Versions

* OIIO version: 1.5.21
* OS: Linux
* C++ compiler: gcc

**Comment by lgritz** [comment]
You are quite right, it seems that negative frame numbers and ranges are not handled correctly.
Fix coming soon, watch for the pull request shortly.

I'm sorry to say, although I will backport the fix to the current release branch, 1.8, the OIIO 1.5 branch hasn't been supported for almost two years and won't receive any more updates. To get the fix, you will need to move to a modern OIIO.

**Comment by rebx** [comment]
Hi Larry,

Thanks for the reply. I will wait for the release which includes the fix. It's also about time that I moved on to a supported version of OIIO.

Cheers

**Comment by lgritz** [comment]
Merged into master and backported to the release branch (an official tagged release usually happens on the 1st of each month, but you can preview by just using the tip of RB-1.8).
