### ISSUE TITLE
dds dxt/bc7 compression support?

### ISSUE THREAD

**Issue by stephenp24** [OpenImageIO/oiio#1892]
### DDS bc7 compression support

Hi, does latest version of oiio support dds bc7 compression?
From what I see on the dds plugin for oiio, it seems to support only bc1-5.

Can someone confirm with me on this regard?
If it doesnt, does oiio plan on adding the support for this?

Thanks,
S

**Comment by lgritz** [comment]
I can confirm your suspicion -- looking at the code, it doesn't look like bc7 compression is currently supported.

I guess this compression method is newer than when the DDS support was added to OIIO a few years ago?

I would love to see support for this added to OIIO's DDS reader.

But I wouldn't say that this is "planned" in the sense that (a) we were previously unaware of it, (b) OIIO's biggest audience is VFX and its most common platform is Linux, both of which are pretty much outside the DDS sphere of influence. 

Like I said, I would welcome such a contribution, but I think it's going to have to be implemented by somebody with a stake in using it. I can coach, offer guidance, and answer questions, but I certainly don't have the expertise myself (nor access to a Windows machine) to correctly implement or verify it.

**Comment by boberfly** [comment]
I'll implement this eventually, either with https://github.com/GameTechDev/ISPCTextureCompressor which I've implemented before in another codebase, or https://github.com/richgel999/bc7enc16 no ETA though but it was on a roadmap of mine.

**Comment by lgritz** [comment]
A PR that implements this would always be welcome, but this ticket has been stale for a while. Is it helpful to keep this issue open, or should we close it to de-clutter and hope a PR comes at some point?

**Comment by stephenp24** [comment]
I'd say we can close this ticket since this issue hasn't really blocked us from our development.

**Comment by lgritz** [comment]
OK, closing. I'm going to make a note of it so we don't forget it. I think it would be a helpful addition, but I think that DDS support is so far outside the set of features that mainstream OIIO users are relying on, that it's going to have to be the kind of thing that somebody who needs it is going to have to implement and contribute it. I don't want to mislead anybody by leaving an open issue indefinitely, possibly implying that this is formally planned or that a solution is forthcoming. A PR would be happily accepted at any time.
