### ISSUE TITLE
'__optnone__' and 'always_inline' attributes are not compatible

### ISSUE THREAD

**Issue by SylvainCorlay** [OpenImageIO/oiio#1897]
When building on `OS X` (with clang), I get the following compilation error in `benchmark.h`

```
/src/include/OpenImageIO/benchmark.h:410:43: error: '__optnone__' and 'always_inline' attributes are not compatible
```

I am seeing this with `oiio 1.8.6` (however the code in question does not appear to have changed recently). EDIT: I also see the issue in 1.8.8

**Comment by lgritz** [comment]
Can you post a little more of the error chain? Which benchmark is triggering this?

**Comment by SylvainCorlay** [comment]
Here is the issue that I am seeing
```
[ 56%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/webp.imageio/webpoutput.cpp.o
In file included from /Users/travis/miniconda3/conda-bld/openimageio_1520955523932/work/oiio-Release-1.8.6/src/tiff.imageio/tiffoutput.cpp:54:
In file included from /Users/travis/miniconda3/conda-bld/openimageio_1520955523932/work/oiio-Release-1.8.6/src/include/OpenImageIO/timer.h:271:
/Users/travis/miniconda3/conda-bld/openimageio_1520955523932/work/oiio-Release-1.8.6/src/include/OpenImageIO/benchmark.h:410:43: error: '__optnone__' and 'always_inline' attributes are not compatible
OIIO_FORCEINLINE T const & __attribute__((__optnone__))
```

**Comment by SylvainCorlay** [comment]
@lgritz I checked out with the conda package for clang, and it works.

My guess is that this is due to Apple's clang version number scheme (which is different from upstream's clang version number), line https://github.com/OpenImageIO/oiio/blob/master/src/include/OpenImageIO/benchmark.h#L375

**Comment by lgritz** [comment]
I think I know how to fix this, stay tuned...

**Comment by lgritz** [comment]
Oh, I see, this project is using the oldest version of xcode (6.4) that TravisCI still offers, which is quite old and is based on clang ~3.6. That's older than we routinely test against, which is why this issue was not noticed. Working on a patch...
