### ISSUE TITLE
Reading the header only

### ISSUE THREAD

**Issue by edubois** [OpenImageIO/oiio#1928]
Hi,

In a multithreaded environment, I'm getting some slow performances when trying to read the header of a set of images from a network shared drive.
Here is my code:
```
    OpenImageIO::ImageSpec readImageSpec(const boost::filesystem::path & inputFilepath)
    {
        using namespace OpenImageIO;

        boost::scoped_ptr<ImageInput> img(ImageInput::create(inputFilepath.generic_string())); // This part takes most of the time
        if (img.get() == NULL)
        {
            THROW(ai::exception::ReadError(inputFilepath));
        }

        OpenImageIO::ImageSpec spec;
        if (!img->open(inputFilepath.generic_string(), spec))
        {
            THROW(ai::exception::ReadError(inputFilepath));
        }

        img->close();

        return spec;
    }

```

Is this code correct? What do you advise? The create function takes most of the time. **It's idle time, meaning there might be some locks or something similar.**

I'm tempted to cache the ImageInput object but this is dangerous as I think it's using local data per image. Maybe a copy of a common object would be better?

Thanks!

**Comment by edubois** [comment]
Ok, inspecting a bit more with intel vtune shows that this is coming from a call to FindNextFileW, I think there is a Filesystem::exists somewhere, and that is slow because I have 30000 files and its a network access.

I'm just hoping that it's not done in a critical section. I don't think so. I remind that there are some optimized way to check a file existence, might be good to use those. Will ask a friend that knows - or maybe do you already know the trick.

**Comment by edubois** [comment]
Here is a screen cap of the profiling. I don't know why it's taking this path.
![slow-oiio-jpeg](https://user-images.githubusercontent.com/214761/39327853-ed4a6684-495e-11e8-9503-6042b8e79031.jpg)

**Comment by edubois** [comment]
Line 528, I don't see why this check is:
`if (filename != format) {`

To me, it should be more:
`if (extension != format) {`

**Comment by edubois** [comment]
Also, it might come from the fact that fread is always reading 64KB because of the buffer size.
https://softwareengineering.stackexchange.com/questions/171315/optimal-buffer-size-for-fread-fwrite
But in this case, as I am reading from the network and we really need only few bytes, it might be a good idea to set the buffer size manually.
http://www.informit.com/articles/article.aspx?p=98836&seqNum=6

I'm not sure of this.

**Comment by edubois** [comment]
No actually using:
`setvbuf(fd, NULL, _IONBF, 0);`

does not improve the performances.

**Comment by lgritz** [comment]
If there's a more efficient way to check if a file exists, I'd love to know about it.

**Comment by edubois** [comment]
I think this is it:
```
inline bool exists_test3 (const std::string& name) {
  struct stat buffer;   
  return (stat (name.c_str(), &buffer) == 0); 
}
```

Taken from here:
https://stackoverflow.com/questions/12774207/fastest-way-to-check-if-a-file-exist-using-standard-c-c11-c

**Comment by lgritz** [comment]
> because I have 30000 files 

Clarification -- Do you mean that you need to read a total of 30000 files? That each one seems ok on its own, but with that many total to do, you are looking for any way to speed it up?

Or do you mean that you have a directory with 30000 files in it, and your OS is therefore making any underlying file access in that area inordinately expensive, even for a single file?

**Comment by edubois** [comment]
You are right, the exists check is done on my side.

I am randomly reading files from a set of 30000, not necessary all the files. I think it's a samba protocol thing, where the access doesn't seem optimal. And I think the open+fread function is buffered in some way. I need to do more speed testing so that you do not investigate on a ghost problem.

**Comment by lgritz** [comment]
IIRC, there are some file systems in which a very large number of files in one directory does make open & stat calls very slow -- like it needs to walk a linear list or something. I don't recall the details, but this makes me think perhaps it's something like that, which is why I got concerned about all those files being piled in one place. Making more of a directory hierarchy instead of everything in one folder is sometimes a solution to that.

**Comment by edubois** [comment]
Ok, I see. The thing is that most post-production companies we work for are producing films made of a very large number of distinct files, and we cannot ask for a change. For a 2 hours movie at 24fps, it's about 172800 frames. I still think this second check is a bit heavy when you are absolutely sure that all the files in a directory are of the same type.

**Comment by lgritz** [comment]
Is this resolved? At least insofar as there is no obvious avoidable waste on the OIIO side?

**Comment by edubois** [comment]
My only criticize is that when you 100% know that a set of 1000000 files have the same format, it is unecessary to open them, check the file format, close. Especially on AWS instances where the first file access can take a very long time.

**Comment by lgritz** [comment]
If you call create() with the file extension or file type name (e.g., "exr"), rather than the full name of the file, I think it will just create the ImageInput for that format, and not check that any particular file can be opened by the reader.
