### ISSUE TITLE
Win32 build of Release/v1.8.11 fails with wrong alignment

### ISSUE THREAD

**Issue by ggarra13** [OpenImageIO/oiio#1932]
### Problem

The build of latest release 1.8.11 fails on Win32 when reaching  ..\src\libutil\simd_test.cpp.

**Expected behavior:** 

The build to continue.

**Actual behavior:**  

..\src\libutil\simd_test.cpp(302): error C2719: 'v': formal parameter with requested alignment of 16 won't be aligned
..\src\libutil\simd_test.cpp(312): error C2719: 'a': formal parameter with requested alignment of 16 won't be aligned
..\src\libutil\simd_test.cpp(317): error C2719: 'a': formal parameter with requested alignment of 16 won't be aligned
..\src\libutil\simd_test.cpp(322): error C2719: 'a': formal parameter with requested alignment of 16 won't be aligned
..\src\libutil\simd_test.cpp(327): error C2719: 'a': formal parameter with requested alignment of 16 won't be aligned

[build.log](https://github.com/OpenImageIO/oiio/files/1969458/build.log)

### Steps to Reproduce

1. Set the environment and cmake variables to valid values.
2. run cmake with the Ninja or NMake Makefiles generator.
3. build oiio

### Versions

* OIIO Release/v1.8.11: 
* OS: Windows-32 bits
* C++ compiler: VC2015

**Comment by lgritz** [comment]
I think maybe this error only shows up for 32 bit builds, we haven't seen that message before.

But I see that you are right -- there are a few spots where we pass a float3 by value instead of by const reference like we do usually. I'll prepare a patch right away.

**Comment by lgritz** [comment]
Fixed proposed in #1933
