### ISSUE TITLE
Support FFMPEG master HEAD

### ISSUE THREAD

**Issue by ggarra13** [OpenImageIO/oiio#1935]
### Problem

Currently, the ffmpeg plugin goes to the trouble of setting some macros and functions for versions 3, 4, etc. of ffmpeg.  However, ffmpeg is usually used from master HEAD and in that case the code fails with:

m_codec_cap_delay = (bool) (m_codec_context->codec->capabilities & CODEC_CAP_DELAY);

**Expected behavior:** 

CODEC_CAP_DELAY is deprecated.  It should use AV_CODEC_CAP_DELAY or set the macro as it does v4.0.

**Actual behavior:**

It did not compile.

### Steps to Reproduce

1. git clone https://git.ffmpeg.org/ffmpeg.git ffmpeg
2. compile ffmpeg
3. install it
4. point oiio to it.
5. compile oiio

### Versions

* OIIO branch/version: 1.9 
* OS: any
* C++ compiler: any

**Comment by lgritz** [comment]
I'm pretty sure this was fixed by #1926

**Comment by ggarra13** [comment]
Yes, it was.  I was using an ffmpeg that was a tad earlier than 4.0 and that had the constant changed.

**Comment by lgritz** [comment]
If you think we should modify the version number test, by all means make a suggestion for which one. I just made sure it would work with the released 4.0, I did not take the trouble to try to figure out precisely which commit in their tree was the exact spot where the symbol name changed.

**Comment by ggarra13** [comment]
Here's the info on the change:

2015-07-27 - lavc 56.56.100 / 56.35.0 - avcodec.h
444e987 / def97856 - Rename CODEC_CAP_* defines to AV_CODEC_CAP_*.
