### ISSUE TITLE
Can't find OpenJpeg 2.3 installed by MacPorts

### ISSUE THREAD

**Issue by llamafilm** [OpenImageIO/oiio#1947]
MacPorts installs OpenJpeg to `/opt/local/include/openjpeg-2.3`

But OpenImageIO can't find it because it only searches `/opt/local/include`.  If I add the location in `src/cmake/modules/FindOpenJpeg.cmake` then it builds correctly.

**Comment by lgritz** [comment]
Care to make a PR with this fix?

**Comment by llamafilm** [comment]
Okay I have never done a PR before, I hope I did it right.
https://github.com/OpenImageIO/oiio/pull/1948

**Comment by lgritz** [comment]
You certainly did. Thanks, it's much simpler for me to review the code, see that the CI tests pass, and hit the 'merge' button on GH, than it is for me to try to reconstruct it on my end without a good way to test.

**Comment by llamafilm** [comment]
Cool!
