### ISSUE TITLE
MINGW-64 MSYS2 cmake compile failure

### ISSUE THREAD

**Issue by Trilec** [OpenImageIO/oiio#1957]
Hi All,

MSYS2

Compiling on MINGW-64,  
mingw-w64-x86_64-cmake 3.10.2-1 
mingw-w64-x86_64-boost 1.66.0-1 
mingw-w64-x86_64-openimageio 1.8.6-1

cmake -G "MSYS Makefiles" 
make

[  0%] Built target CopyFiles
[  1%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/exif.cpp.obj
H:/projects/programming/3rdparty/OpenImageIO/src/libOpenImageIO/exif.cpp: In function 'void OpenImageIO_v1_9::encode_exif(const OpenImageIO_v1_9::ImageSpec&, std::vector<char>&)':
H:/projects/programming/3rdparty/OpenImageIO/src/libOpenImageIO/exif.cpp:1031:16: error: argument 2 null where non-null expected [-Werror=nonnull]
         memcpy (&dir.tdir_offset, mydata, len);
         ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from F:/devl/msys64/mingw64/include/c++/7.3.0/cstring:42:0,
                 from F:/devl/msys64/mingw64/include/boost/container/detail/copy_move_algo.hpp:37,
                 from F:/devl/msys64/mingw64/include/boost/container/detail/advanced_insert_int.hpp:28,
                 from F:/devl/msys64/mingw64/include/boost/container/vector.hpp:31,
                 from F:/devl/msys64/mingw64/include/boost/container/detail/flat_tree.hpp:30,
                 from F:/devl/msys64/mingw64/include/boost/container/flat_map.hpp:29,
                 from H:/projects/programming/3rdparty/OpenImageIO/src/libOpenImageIO/exif.cpp:40:

**tried adding in** 
_#set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wno-nonnull-compare")
#set(CMAKE_CXX_FLAGS  "${CMAKE_CXX_FLAGS} -Wno-nonnull-compare")
#set(CMAKE_CPP_FLAGS  "${CMAKE_CPP_FLAGS} -Wno-nonnull-compare")
add_compile_options( -Wno-nonnull-compare )_

no change
I would also like to try this as static build but first things first..
Any help to understand this issue appreciated.

PS:is there a reason static builds are not in the pacman packages?

**Comment by Biswa96** [comment]
I have tried to compile in the same msys2/mingw64 environment. I got linking error. The cmake setup step found hdf5 but at build time this error is shown `undefined reference to H5Gclose`. Is there an option to set hdf5 libraries? Or any issue in cmake files?

**Comment by Biswa96** [comment]
This project could be built in MSYS2/MINGW64 since many years. See the required dependencies and commands here [MSYS2/mingw-packages openimageio PKGBUILD file](https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-openimageio/PKGBUILD).

**Comment by lgritz** [comment]
It seems like the original problem of this issue has long since been fixed. This was against OIIO 1.8. In modern versions, the memcpy is enclosed by `if (mydata)` so there is no longer a problem with the memcpy being called with a null argument. I think nobody ever went back to this issue to mark it closed after this change was made. Closing now.
