### ISSUE TITLE
LibRaw does not compile on Windows after variables are set

### ISSUE THREAD

**Issue by ggarra13** [OpenImageIO/oiio#1958]
Some changes are needed in FindLibRaw to make it compile on windows seamlessly.

### Problem

Some changes are needed to make FindLibRaw compile on windows.  These include the name of the library (libraw instead of just raw), and setting the SET( LibRaw_r_LIBRARIES ${LibRaw_LIBRARIES} ) as LibRaw_r_LIBRARIES does not exist on Windows

**Expected behavior:** 

The compile to succeed

**Actual behavior:**  

The cmake system reported that Libraw was not found!

### Versions

* OIIO branch/version: 1.9.3dev
* OS: Windows
* C++ compiler: vc14

[patch.txt](https://github.com/OpenImageIO/oiio/files/2066337/patch.txt)

**Comment by lgritz** [comment]
Can you submit the patch as a PR?

**Comment by lgritz** [comment]
Fixed by #1959
