### ISSUE TITLE
latest release compatible with centos 6?

### ISSUE THREAD

**Issue by remusvrm** [OpenImageIO/oiio#1966]
Which is the latest oiio release compatible with CentOS 6 / which can be compiled for centos 6? (no cpp 11)

**Comment by lgritz** [comment]
The family of releases 1.8 was the first that *required* C++11.

Anything 1.7 or earlier should be able to compile with C++03.

**Comment by remusvrm** [comment]
I try to compile OIIO version `1.7.19` with 

```

**Comment by lgritz** [comment]
Are you using cmake directly, or the makefile wrapper?

**Comment by lgritz** [comment]
Never mind, the answer is:

    -DUSE_CPP11=0

OIIO_BUILD_CPP11 is an internal variable that's used when processing one of the header files.

**Comment by remusvrm** [comment]
Using `-DUSE_CPP11=0` works. But now I got different errors at the compilation time: https://github.com/OpenImageIO/oiio/issues/1970
