### ISSUE TITLE
Build agains Python 3

### ISSUE THREAD

**Issue by bartoszek** [OpenImageIO/oiio#197]
I can not build oiio with python 3 support on openSUSE 12.1
I tried 'make PYTHON_VERSION=3.2' 
Did not work - fall back to python2.7
Manually edited cmake configuration (python executable/include/lib plus boost_python3.so) results in compilation error.
On Debian there was no such problem.

[CODE]
Linking CXX executable iv
[ 95%] Built target iv
Scanning dependencies of target PyOpenImageIO
[ 96%] Building CXX object python/CMakeFiles/PyOpenImageIO.dir/py_imageinput.cpp.o
[ 96%] Building CXX object python/CMakeFiles/PyOpenImageIO.dir/py_imageoutput.cpp.o
[ 97%] Building CXX object python/CMakeFiles/PyOpenImageIO.dir/py_imagecache.cpp.o
[ 98%] Building CXX object python/CMakeFiles/PyOpenImageIO.dir/py_imagespec.cpp.o
/home/bartus/src/OpenImageIO-svn/src/python/py_imagespec.cpp: In function ‘boost::python::api::object PyOpenImageIO::ImageSpec_get_channelnames(const OpenImageIO::v0_11::ImageSpec&)’:
/home/bartus/src/OpenImageIO-svn/src/python/py_imagespec.cpp:44:89: error: ‘PyString_FromString’ was not declared in this scope
make[2]: *** [python/CMakeFiles/PyOpenImageIO.dir/py_imagespec.cpp.o] Błąd 1
make[1]: *** [python/CMakeFiles/PyOpenImageIO.dir/all] Błąd 2
make: *** [all] Błąd 2
[/CODE]

**Comment by lgritz** [comment]
This is an embarrassingly old issue, and I suspect it's long been fixed. Does #997 fix this?

**Comment by treestle** [comment]
Wow! I hope so... I don't have time to set this up right now as I don't work in graphics any more. Perhaps someone else can fix it.

**Comment by hydratim** [comment]
Sorry wrong account. Treestle message was from me.

**Comment by lgritz** [comment]
No prob. I'm going to close this issue on the assumption that Python3 works fine (other Python3 PR's have been merged, so presumably if it didn't build, we'd know it). If it's still a problem for somebody, they'll open a new issue.
