### ISSUE TITLE
OpenEXR and TIFF Plugins fail to link on Windows for OIIO 1.8 when EMBEDPLUGINS=0

### ISSUE THREAD

**Issue by markfinal** [OpenImageIO/oiio#1975]
### Problem

I'm in the process of upgrading from 1.7.15 to 1.8.x.

Windows builds of 1.8 do no link openexr and tiff plugins when built with EMBEDPLUGINS=0, due to referencing a private (i.e. non-exported) symbol from the OpenImageIO dynamic library.

This seems to be a different problem to that fixed in https://github.com/OpenImageIO/oiio/pull/1942

**Expected behavior:**  
OpenExr and Tiff plugins should link as separate dynamic libraries, as they do for 1.7 versions.

**Actual behavior:**  

Build output from VisualStudio 2015 is here:

https://gist.github.com/markfinal/148dcdd586927425176d08b3bc54d58e

I've looked at master, and the call to this private function remains: pvt::check_texture_metadata_sanity.

Since that function isn't exported from the OpenImageIO DLL, this is the reason for the link error on Windows.
It's fine with EMBEDPLUGINS=1.

### Steps to Reproduce

1. Build USD to get up-to-date dependencies (the OIIO Windows instructions were out of date to get the dependencies)
2. Configure OIIO for VS2015 and EMBEDPLUGINS=0, and generate a solution. (You'll need to point CMake at the USD install folder to find the dependencies.)
3. Build the solution. Note the errors.

### Versions

* OIIO branch/version: RB-1.8 (head)
* OS: Windows 8.1
* C++ compiler: VisualStudio 2015 (Update 3)

**Comment by lgritz** [comment]
I believe this was fixed by #2025, which added the correct symbol visibility for `pvt::check_texture_metadata_sanity`. Closing.
