### ISSUE TITLE
std::regex_replace issue with OIIO 1.8.x and GCC 4.8.4

### ISSUE THREAD

**Issue by markfinal** [OpenImageIO/oiio#1976]
### Problem

OIIO does not compile when CMake is configured to use STL regex in GCC 4.8.4, at the head of RB-1.8 branch.

Although the option to build in this configuration is not the default, the documentation also suggests that GCC 4.8.2+ should work (https://github.com/OpenImageIO/oiio/blob/RB-1.8/INSTALL.md#required-dependencies).

I suspect this is more of a documentation fix than a code fix.

It appears that GCC 4.8.x is incomplete for STL regex (https://stackoverflow.com/questions/12530406/is-gcc-4-8-or-earlier-buggy-about-regular-expressions) and 4.9 is the earliest that can be used.

**Expected behavior:**  

OIIO to compile

**Actual behavior:**  

Here's the output and compilation error: https://gist.github.com/markfinal/cef1bd593a2e11560e9e595c35907d21

### Steps to Reproduce

1. `mkdir build && cd build`
2. Configure cmake: `cmake ../oiio/ -DUSE_PYTHON=0 -DUSE_QT=0 -DUSE_STD_REGEX=1 -DEMBEDPLUGINS=0` (I don't embed plugins just as it's faster to fail)
2. Build: `make VERBOSE=1`
3. Observe compilation failure

### Versions

* OIIO branch/version: RB-1.8
* OS: Ubuntu 14
* C++ compiler: GCC 4.8.4

**Comment by lgritz** [comment]
gcc 4.8 std::regex is known to be quite broken. The USE_STD_REGEX will autodetect if you're using a new enough compiler (gcc >= 4.9) and set itself automatically, I think. I don't believe it was intended for people to override it to use std::regex in cases where they were using an old compiler.

What are you suggesting is the right thing to do here? Notice the discrepancy and abort the build?

Was there a reason you were trying to force it to use std::regex in this case?

**Comment by markfinal** [comment]
If I remember correctly, I was just toying with setting various build flags on the cmake command line. I hadn't noticed that there was a check_cxx_source_runs test that detects whether the compiler handles std::regex or not.

I initially thought this was a documentation fix, due to the current indicating 4.8.2+ would work. But if 99% of OIIO users simply invoke cmake, since you've already handled it in a test, this is just transparent to them, and they need not care about details.

So my issue actually only covers the (probably much smaller) number of OIIO users that want to explicitly control build options, like myself. Like you suggest, abort if the compiler says no, but the user wants yes. Something like this, perhaps?

```
check_cxx_source_runs("
      #include <regex>
      int main() {
          std::string r = std::regex_replace(std::string(\"abc\"), std::regex(\"b\"), \" \");
          return r == \"a c\" ? 0 : -1;
      }"
      TEST_USE_STD_REGEX)
if (TEST_USE_STD_REGEX)
    add_definitions (-DUSE_STD_REGEX)
else ()
    if (USE_STD_REGEX) // user requested std::regex on the cmake command line
        message(FATAL_ERROR, "std::regex support in the compiler is incomplete, but USE_STD_REGEX was requested as a build option. Cannot continue.")
    endif()
    add_definitions (-DUSE_BOOST_REGEX)
endif ()
```

**Comment by lgritz** [comment]
The point of the `check_cxx_source_runs` is to verify empirically whether the std regex your compiler uses is working, and if not (such as is the case for gcc 4.8.x), force use of Boost regex instead.

It's all automatic, is not intended to have external override and is not documented as such, because why would anyone want to configure it in the mode we know for sure is broken? The value of `USE_STD_REGEX` is intentionally taken from the `check_cxx_source_runs`.

If you think many users will find it valuable to have this externally controllable as a build setting, we can change the code as you suggest, I guess. But is the number of users wanting to select the broken mode approximately n=1? If so, maybe that one user should change things on their end rather than make the code any more complex?

Am I misunderstanding?

**Comment by markfinal** [comment]
I wasn't sure if it was a common theme among users to delve into the build scripts and try these things. It certainly sounds like it isn't common from what you've said, so any adjustments I suggest won't be beneficial to the majority. I'll close this off. Thanks!
