### ISSUE TITLE
Python bindings for both Py 2.7 and 3.x

### ISSUE THREAD

**Issue by mfvescovi** [OpenImageIO/oiio#1988]
### Preamble
This is a packaging issue, not a compiling one.
Anyway, I decided to open that here to give it more visibility to those maybe interested in the topic.
I'm the package maintainer of OIIO in Debian.

### Problem
[Here](https://bugs.debian.org/889682) I've been asked to add Py3 support for bindings.
My idea was to drop Py2 package and replace it with the Py3-based version.

But then I was thinking of those users that could be forced to stick with Py2 yet and would suffer for the drop of that package.
So, my question is: could it be possibly to make OIIO providing both Py2 and Py3 bindings?
Modifying "SET_VERSION" cmake variable didn't help.

Thanks in advance for your help and effort.

### Versions
* OIIO branch/version: Release-1.8/1.8.12
* OS: Debian unstable/sid
* C++ compiler: GCC-8.x

**Comment by hobbes1069** [comment]
As the Fedora packager of OIIO, I would be interested in this as well.

**Comment by lgritz** [comment]
Are you asking
(a) if you can build a Python3 OIIO binding *at all*? 
(b) if you can build-time select Python2 or Python3?
(c) if you can do a single build that results in both Python2 and Python3 OIIO bindings?

**Comment by mfvescovi** [comment]
Il 2018 8 2 13:42:11 UTC, Larry Gritz <notifications@github.com> ha scritto:
>Are you asking
>(a) if you can build a Python3 OIIO binding *at all*? 
>(b) if you can build-time select Python2 or Python3?
>(c) if you can do a single build that results in both Python2 and
>Python3 OIIO bindings?

(c), in my case.

Don't know about Richard.
-- 
Inviato dal mio dispositivo Android con K-9 Mail. Perdonate la brevità.

**Comment by lgritz** [comment]
(c) would be very desirable, but I'm not sure how much work it is to coax cmake to do it all in a single build. I imagine that even the basics of the FindPythonInterp.cmake is probably not set up to do anything but find a single version per build.

For the release branch, which is still using Boost Python, there may be extra complications, especially if your system Boost was built for only one of the Pythons. But we're getting close to branching for 1.9, and with it the switch away from Boost Python and to pybind11 (already the case in master), which being header-only might be easier to coax into building for multiple python releases in one build.

The whole efforts is certainly something I don't have the time and expertise for, but I would very much welcome the contribution to rig OIIO's build to create both Python 2 and 3 libraries at the same time.

**Comment by skycaptain** [comment]
I had the same issue, when I wrote the Homebrew formula, where we build OpenImageIO two times, once for 2 and 3. This is not elegant at all, but since most people install the pre-built binaries and do not build OpenImageIO from source, it seams acceptable.

**Comment by hobbes1069** [comment]
With the pending EOL of Python 2.x Fedora 30 and up will be python 3 only so I just changed which one I build and the problem will take care of itself in two releases (F29 is about to release).

**Comment by lgritz** [comment]
I recently did some revision on the cmake files, and I'm sorry to say, but CMake's FindPython* files don't appear to easily accommodate doing builds against both 2 and 3 simultaneously. I think the expedient thing is to rely on most places needing EITHER 2 or 3, and the few who need both can do two builds. As has been pointed out, Python2 is EOL (and in the VFX world, VFXPlatform 2020 will switch to Python3), so the amount of time we need to continue supporting both is limited anyway.

Shall we close this issue and sweep it all under the rug, knowing it will simply be overtaken by history soon?

**Comment by lgritz** [comment]
Closing. Too hard to build both (unless somebody wants to volunteer), but it's now easy to build for python 2 and 3 with successive builds.
