### ISSUE TITLE
support of automatic Chromatic Aberration Correction in libraw

### ISSUE THREAD

**Issue by mash-graz** [OpenImageIO/oiio#2029]
it would be very helpful, if OIIO could support libraws automatic CA correction capabilities.

but i'm not sure, if this feature is still missing in the OIIO layer, or just not supported in the GUI of the OIIO based file re reader of the natron video compositing application.

**Comment by lgritz** [comment]
Do you know which libraw parameter this corresponds do?

**Comment by mash-graz** [comment]
it's: '  imgdata.params.aber' (double aber[4])
also used as option '-C' or '-acae'  in dcraw_emu  

as the [documentation of dcraw_emu](https://www.libraw.org/docs/Samples-LibRaw.html) points out:
"Turns on chromatic aberration suppression. r and b parameters are amount of red and blue axis correction respectively. For automatic correction use -acae 0 0."

but it's also important to consider the remarks in the API documentation:

"""
double aber[4];
    dcraw keys: -C
    Correction of chromatic aberrations; the only specified values are
    aber[0], the red multiplier
    aber[2], the blue multiplier. For some formats, it affects RAW data reading , since correction of aberrations changes the output size.
"""
and 

"""
imgdata.params.threshold, imgdata.params.aber
    If these parameters used, then half-sized bitmap will be used for data unpacking. See above for details.
"""

**Comment by lgritz** [comment]
OK, got it. Should be easy. So even though there's a 4-element array, it's only [0] and [2] we care about, so I only need to make it a 2-valued parameter?

**Comment by mash-graz** [comment]
it think, it's perhaps better to use both paramaters, because this will confuse least of all and it also opens the possibility to handle automatic CA corrections e.g. by entries in the lensfun database by applications using OIIO.

**Comment by lgritz** [comment]
If I post a PR against master, will you be able to build it and check if it works as you expect?
I don't have a test case or know what would be the "correct" behavior.

**Comment by mash-graz** [comment]
hmm -- i'll have to look, what's necessary to modify on natrons side resp. the [openfx-io](https://github.com/NatronGitHub/openfx-io) plugin, but it shouldn't be to complicated.

**Comment by lgritz** [comment]
Well, I mean, if you know what's *supposed* to happen for a particular image, then perhaps you could just use oiiotool to inspect the behavior, but using the new control while converting a raw file to some other format like exr or jpeg?

**Comment by mash-graz** [comment]
yes -- i have some real world footage to test it -- and it should work just the same resp. show similar effects as in RawTherapee.

**Comment by lgritz** [comment]
Proposed patch:
https://github.com/OpenImageIO/oiio/pull/2030

**Comment by mash-graz** [comment]
> Proposed patch:
> #20301

o.k. -- i'l test it! :)

but it looks like you set the the default to "0,0" -- i.e. enabling auto CA correction.

maybe this could cause troubles, because it will alter OIIOs previous behavior and i have my doubts, if automatic CA reduction is always desirable?

at least RawTherapy, where this routine stems from, doesn't enable it by default.

i just uploaded a [test file](http://users.mur.at/ms/attachments/A002_10081214_C016_000000.dng) and two screen shots, to document, how this change should affects the image (demonstrated by utilizing RawTherapee):

without automatic CA correction:
![](http://users.mur.at/ms/attachments/rt_without_ca_corr.png)

with enabled automatic CA correction:
![](http://users.mur.at/ms/attachments/rt_with_ca_corr.png)

**Comment by lgritz** [comment]
If the config attribute is not set at all, it will not put anything at all in the libraw `params.aber` field, it will stay at whatever default it had before. I assume that's "auto", but I wasn't touching it in any way before, and I'm still not touching those fields if the user doesn't supply a value.

**Comment by mash-graz** [comment]
> If the config attribute is not set at all, it will not put anything at all in the libraw params.aber field, it will stay at whatever default it had before.

oh -- i see -- that's IMHO a perfect solution!

**Comment by mash-graz** [comment]
unfortunately i can not report an sucessful test :(

i did build your branch and tested it with command similar to your suggested example, but whatever i do (i.e changing the 'aber' parameters or excluding the option at all), the images always look the same :(

and i also get errors on nearly every second run: "Processing image failed, Unsufficient memory"

sure, this could be also caused by other mistakes on my side, but at least i wanted to report it.

**Comment by lgritz** [comment]
I tried on my end, works fine. 

    oiiotool -iconfig:type="float[2]" "raw:aber" "1.01,0.99" ../oiio-images/raw/RAW_OLYMPUS_E3.ORF  -o out.exr

this unambiguously, visibly, messes with the chromatic aberration.

Did you build from my patch directly? I haven't integrated it into master yet. And are you sure that the oiiotool you used to try it is the recently built one, not any other on your system? What values for raw:aber did you use?

As for the "Processing image failed, Unsufficient memory" ("Unsufficient" is a ideal target for 'grep'!), that's not an error message from OIIO, it's from inside libraw. In particular:

    ./src/libraw_cxx.cpp:      return "Unsufficient memory";

So whatever is going on, it's in the underlying libraw, not in the oiio code.

**Comment by mash-graz** [comment]
> Did you build from my patch directly? I haven't integrated it into master yet. And are you sure that the oiiotool you used to try it is the recently built one, not any other on your system? What values for raw:aber did you use?

o.k. this was indeed a mistake on my side -- i was on "master".
but this time i'm on the "lg-raw" branch and most of the issues are unfortunately still the same. :(

i'm using this command:

`build/linux64/src/oiiotool/oiiotool --iconfig:type="float[2]" "raw:aber" "3.0,3.0"  --crop "500x500+2600+0"  ~/Downloads/A002_10081214_C016_000000.dng  -o /tmp/test2.exr`

> And are you sure that the oiiotool you used to try it is the recently built one, not any other on your system?

because it's executed by an explicit given relative path within the build directory, it's IMHO very unlikely, that another binary gets called.

i'm using debian 'testing' and the system wide libraw version utilized is `libraw19:amd64/testing 0.19.0-3`

and now about the issues:

  * the "Processing image failed, Unsufficient memory" aborts are still happening very often.

  * if i specify "raw:aber" "0.0,0.0" i get a green image instead of an automatically CA corrected one.

  * if i use any other values ("3.0,3.0" could perhaps make sense, because these values work satisfaying in RawTherapees GUI), it doesn't seem to have any visible affect.

sorry for bothering you, but it's perhaps easier for you to find a working solution, than for anybody, who isn't familiar with this code base.

**Comment by lgritz** [comment]
The dcraw docs say that the values are expected to be very close to 1.0, very slightly above or below. Hence, in my example, I used 1.01 and 0.99. Values like 3.0 are total nonsensical, it wildly rescales the red and blue channels.

I can confirm that 0,0 gives me something very weird! Which is strange because the dcraw describes 0 values as meaning "figure out the defaults." Using 1.0,1.0 gives me "no change" to the original image, as expected.

**Comment by lgritz** [comment]
So if you use values like 1.01,0.99, do you get the "right" result (no errors, now some visible color fringing)?

**Comment by mash-graz** [comment]
> So if you use values like 1.01,0.99, do you get the "right" result (no errors, now some visible color fringing)?

yes -- this works indeed! ...or at least it gives me a funny colorful image :)

but again: i had to execute it four times before it finally worked without memory error. :(

**Comment by lgritz** [comment]
Strange. The same command run multiple times ought to use the same memory each time. I haven't ever seen this error.

I'm not going to let it hold up merging this code. 

But which platform? And which version of libraw are you building against? And does the RAM available on your machine seem reasonable for this size image?

**Comment by lgritz** [comment]
Sorry, I see from the earlier message which version you use.

**Comment by mash-graz** [comment]
> I'm not going to let it hold up merging this code.

that looks plausible to me.

concerning the "0,0"  resp. auto-CA case:

maybe it's a rounding issue caused be wrong float interpretation of the string to value just close to zero but exactly 0?

in [libraw_cxx.cpp#L424](https://github.com/LibRaw/LibRaw/blob/06028d0c8a1e8544afa2a1dc94d41767aa56f53f/src/libraw_cxx.cpp#L424) the variable get's initialized to a default of:
    double aber[4] = {1, 1, 1, 1};

**Comment by lgritz** [comment]
No, "0,0" will be exact.

But I think I will update the docs I wrote to say that 1,1 is the default, meaning "no change", and eliminate the wording that 0,0 means something special to libraw (clearly it doesn't behave as documented).
