### ISSUE TITLE
external.zip contains libTIFF 3.8.2 but OpenImageIO requires libTIFF 3.9+

### ISSUE THREAD

**Issue by LegalizeAdulthood** [OpenImageIO/oiio#2034]
### Problem

The [instructions for building on Windows](https://sites.google.com/site/openimageio/building-oiio-on-windows) say to download the [precompiled external libraries](http://www.openimageio.org/external.zip) in order to satisfy external library requirements.  However, the external ZIP file contains an outdated version of libTIFF (3.8.2) and OpenImageIO requires libTIFF 3.9+.

**Expected behavior:**  

The external binaries ZIP file should contain current dependencies.

**Actual behavior:**  

The external binaries ZIP file contains stale dependencies.

### Steps to Reproduce

1. Follow [instructions for building on Windows](https://sites.google.com/site/openimageio/building-oiio-on-windows)

### Versions

* OIIO branch/version: HEAD
* OS: Windows
* C++ compiler: VS 2017 (doesn't actually matter)

**Comment by pamrulla** [comment]
Yes, the external lib zip mentioned in the instructions for windows are outdated. Please update.

**Comment by pamrulla** [comment]
@LegalizeAdulthood  I tried to compile on machine different libs and able to compile OpenImageIO, remember the libraries are only compiled under debug mode. If you try and let me know whether it is working on your machine too then will try to work on other libs and release mode too. I compiled them using VS2017
[external.zip](https://github.com/OpenImageIO/oiio/files/2499353/external.zip)

**Comment by lgritz** [comment]
We should probably just get rid of that old external.zip file, it's surely too old to be helpful. If you have an updated one, I can replace it. Or if the preference these days is to avoid that route entirely, and instead use one of the package managers like VcPkg or nuget or whatever. 

What we really need is somebody who regularly builds OIIO for Windows to step up and be willing to update and consistently maintain the Windows build instructions, binary packages (if we want), and the windows testing regime (such as Appveyor). I don't use Windows and don't have easy access (let alone expertise) in this area and thus I cannot be trusted to do this properly myself.

**Comment by ras0219-msft** [comment]
Fwiw, if you'd like to easily continue to provide the external.zip, vcpkg supports doing this via
```
vcpkg export --zip <dependencies>
```

**Comment by lgritz** [comment]
Closing, with the repeat of my plea that we really need somebody to step forward and take ownership of some of the windows build issues and bring the whole thing up to modern standards (including management of dependencies, rewrite building on windows instructions, overhauling our appveyor scripts, maybe change from appveyor to TravisCI Windows support, figuring out vcpkg). I just don't have the background and resources to do it myself.
