### ISSUE TITLE
CMake setup not finding OpenEXR

### ISSUE THREAD

**Issue by zero9178** [OpenImageIO/oiio#2077]
### Problem
I tried building the library using the download link Release-1.8.16.zip from the Release page, as wall as the current master branch
I used following cmake command:
`cmake .. -G "CodeBlocks - MinGW Makefiles" -DOpenEXR_USE_STATIC_LIBS=OFF -DUSE_NUKE=OFF -DUSE_QT=OFF -DUSE_PYTHON=OFF -DOIIO_BUILD_TOOLS=OFF -DOIIO_BUILD_TESTS=OFF -DCMAKE_INSTALL_PREFIX=C:/MGPKG/OpenImageIO-1.8.16 -DCMAKE_PREFIX_PATH=C:/MGPKG/Libpng-1.6.35;C:/MGPKG/boost-1.68.0;C:/MGPKG/OpenEXR-2.3.0;C:/MGPKG/libtiff-4.0.9;C:/MGPKG/zlib-1.2.11  -DBUILD_SHARED_LIBS=OFF
`

It then fails with this cmake call stack

CMake Error at C:/Tools/cmake-3.11.1-win64-x64/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenEXR (missing: OPENEXR_IMATH_LIBRARY
  OPENEXR_ILMIMF_LIBRARY OPENEXR_IEX_LIBRARY OPENEXR_HALF_LIBRARY) (found
  suitable version "2.3.0", minimum required is "2.0")
Call Stack (most recent call first):
  C:/Tools/cmake-3.11.1-win64-x64/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  src/cmake/modules/FindOpenEXR.cmake:160 (find_package_handle_standard_args)
  src/cmake/externalpackages.cmake:62 (find_package)
  CMakeLists.txt:118 (include)

**Expected behavior:**  

I thought it'd find the library as it seems to have found the other variables like the include dir.

**Actual behavior:**  

It did not find the library. It also said that the it found version 2.3 while a minimum require is 2.0. I have no clue if that is relevant

### Steps to Reproduce

`cmake .. -G "CodeBlocks - MinGW Makefiles" -DOpenEXR_USE_STATIC_LIBS=OFF -DUSE_NUKE=OFF -DUSE_QT=OFF -DUSE_PYTHON=OFF -DOIIO_BUILD_TOOLS=OFF -DOIIO_BUILD_TESTS=OFF -DCMAKE_INSTALL_PREFIX=C:/MGPKG/OpenImageIO-1.8.16 -DCMAKE_PREFIX_PATH=C:/MGPKG/Libpng-1.6.35;C:/MGPKG/boost-1.68.0;C:/MGPKG/OpenEXR-2.3.0;C:/MGPKG/libtiff-4.0.9;C:/MGPKG/zlib-1.2.11  -DBUILD_SHARED_LIBS=OFF
`

### Versions

* OIIO branch/version:1.8.16 and current master
* OS: Windows 10 1803
* C++ compiler: MinGW GCC 8.1

**Comment by lgritz** [comment]
Can you try doing the full cmake configuration step again with -DVERBOSE=ON, and then print the results here, so we can see where it's finding everything?

I'm wondering also if there's an interaction between BUILD_SHARED_LIBS=OFF and OpenEXR_USE_STATIC_LIBS=OFF that's causing trouble by falling into some edge case that doesn't work right.

**Comment by zero9178** [comment]
`cmake .. -G "CodeBlocks - MinGW Makefiles" -DOpenEXR_USE_STATIC_LIBS=OFF -DUSE_NUKE=OFF -DUSE_QT=OFF -DUSE_PYTHON=OFF -DOIIO_BUILD_TOOLS=OFF -DOIIO_BUILD_TESTS=OFF -DCMAKE_INSTALL_PREFIX=C:/MGPKG/OpenImageIO-1.8.16 -DCMAKE_PREFIX_PATH=C:/MGPKG/boost-1.68.0;C:/MGPKG/OpenEXR-2.3.0;C:/MGPKG/libtiff-4.0.9;C:/MGPKG/zlib-1.2.11;C:/MGPKG/Libpng-1.6.35 -DVERBOSE=ON
-- The CXX compiler identification is GNU 8.1.0
-- The C compiler identification is GNU 8.1.0
-- Check for working CXX compiler: C:/mingw-w64/8.1/bin/g++.exe
-- Check for working CXX compiler: C:/mingw-w64/8.1/bin/g++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: C:/mingw-w64/8.1/bin/gcc.exe
-- Check for working C compiler: C:/mingw-w64/8.1/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- CMake version is 3.11.1
CMake Deprecation Warning at CMakeLists.txt:17 (cmake_policy):
  The OLD behavior for policy CMP0046 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


-- Project source dir = C:/Users/Markus/go/src/MGPKG/oiio-master
-- Project build dir   = C:/Users/Markus/go/src/MGPKG/oiio-master/build
-- Project install dir = C:/MGPKG/OpenImageIO-1.8.16
-- CMAKE_SYSTEM_NAME = Windows
-- CMAKE_SYSTEM_VERSION = 10.0.17134
-- SYSTEM_PROCESSOR = x86_64
-- platform = windows
-- CMAKE_CXX_COMPILER is C:/mingw-w64/8.1/bin/g++.exe
-- CMAKE_CXX_COMPILER_ID is GNU
-- Using gcc 8.1.0 as the compiler
-- Building for C++11
-- Performing Test USE_STD_REGEX
-- Performing Test USE_STD_REGEX - Success
-- clang-format found: C:/MGPKG/Clang-7.0.0/bin/clang-format.exe
-- Setting Namespace to: OpenImageIO_v2_0
-- Found TIFF: C:/MGPKG/libtiff-4.0.9/lib/libtiff.a (found suitable version "4.0.10", minimum required is "3.9")
-- Found ZLIB: C:/Program Files/Intel/WiFi/bin/zlib1.dll (found version "1.2.11")
-- Found PNG: C:/MGPKG/Libpng-1.6.35/lib/libpng.a (found version "1.6.35")
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
CMake Error at C:/Tools/cmake-3.11.1-win64-x64/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenEXR (missing: OPENEXR_IMATH_LIBRARY
  OPENEXR_ILMIMF_LIBRARY OPENEXR_IEX_LIBRARY OPENEXR_HALF_LIBRARY) (found
  suitable version "2.3.0", minimum required is "2.0")
Call Stack (most recent call first):
  C:/Tools/cmake-3.11.1-win64-x64/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  src/cmake/modules/FindOpenEXR.cmake:146 (find_package_handle_standard_args)
  src/cmake/externalpackages.cmake:67 (find_package)
  CMakeLists.txt:130 (include)


-- Configuring incomplete, errors occurred!
See also "C:/Users/Markus/go/src/MGPKG/oiio-master/build/CMakeFiles/CMakeOutput.log".`
I removed the BUILD_SHARED_LIBS as you said and added the Verbose options. That was my output

**Comment by mfvescovi** [comment]
Try fixing this first:

  `Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)`

thus, install pkg-config in your build environment.

**Comment by lgritz** [comment]
Is this a solved issue? Close, or is there more to investigate?

**Comment by kattkieru** [comment]
Apparently not-- I just hit this right now on Windows / VC2015. :)  I'm specifying the BOOST_INCLUDEDIR and BOOST_LIBRARYDIR paths when calling CMake and it's not making a difference.

**Comment by lgritz** [comment]
Closing because our whole build system got a pretty big overhaul over the last year. If this is still a problem in master or 2.1, please re-open or file again.
