### ISSUE TITLE
Cmake not finding OpnCv 4.0.0

### ISSUE THREAD

**Issue by jeannoeldot** [OpenImageIO/oiio#2087]
Hello.

When I want to compile OIIO with OpenCV 4.0.0, I get the following report:
-- Could NOT find OpenCV (missing: OpenCV_INCLUDE_DIR)
-- OpenCV library not found

Would it be possible to make OIIO compatible with OpenCV 4.0.0?

Thank you.

### Versions

* OIIO version: 1.8.16 and 1.8.17
* OS: Arch Linux
* Open CV 4.0.0
* C++ compiler: gcc version 8.2.1 20180831

**Comment by lgritz** [comment]
I see. Open CV 4.0 is hot off the presses (just released in the last several days, it doesn't even have a Homebrew recipe yet). Our FindOpenCV.cmake needs an update for sure, and possibly some touch-ups in imagebufalgo_opencv.cpp.

I'll give it a shot and see if it's an easy fix.
