### ISSUE TITLE
[Windows] "fatal error C1017: invalid integer constant expression" in simd.h

### ISSUE THREAD

**Issue by SylvainCorlay** [OpenImageIO/oiio#2090]
When building a conda package for openimageio on windows, the compilation is failing with:

```
\src\include\OpenImageIO/simd.h(1789): fatal error C1017: invalid integer constant expression
```

The build command is  

```
cmake -G "NMake Makefiles" ^
	  -DUSE_FFMPEG=ON ^
	  -DOIIO_BUILD_TOOLS=OFF ^
	  -DOIIO_BUILD_TESTS=OFF ^
	  -DUSE_PYTHON=OFF ^
	  -DUSE_OPENCV=OFF ^
	  -DCMAKE_INSTALL_PREFIX=%LIBRARY_PREFIX% ^
	  -DCMAKE_INSTALL_LIBDIR=lib ^
	  %SRC_DIR%
```

The compiler in use is MSVC 2015

Versions of dependencies

```
boost:          1.68.0
ffmpeg:         3.4.2
giflib:         5.1.4
ilmbase:        2.3.0
jpeg:           9c
libpng:         1.6.36
libtiff:        4.0.10
libwebp:        1.0.1 
openexr:        2.3.0
```

**Comment by lgritz** [comment]
I'm not sure why the current line 1789 would produce that error.
Do you know which version of OIIO, possibly even down to which commit hash, was the one you were building?
And do you know what SIMD level or machine it's building for? Like if it's a x86-64, then it's sse2 even if you don't specify sse support.

**Comment by est77** [comment]
I've seen this error in the past when trying things like:

#if true (or any define that expands to true or false)
  ... 
#endif

using 0 or 1 instead usually fixes the problem.

**Comment by SylvainCorlay** [comment]
Sorry for the inaccuracy. The version that we use is 1.8.9.

**Comment by SylvainCorlay** [comment]
`#if defined(ILMBASE_VERSION_MAJOR) && ILMBASE_VERSION_MAJOR >= 2`

**Comment by lgritz** [comment]
Why is that wrong? Do we think that ILMBASE_VERSION_MAJOR is not defined?

**Comment by SylvainCorlay** [comment]
It seems so, in this situation...

**Comment by SylvainCorlay** [comment]
This failure occurs on windows when attempting a packaging of openimageio for conda-forge. https://github.com/conda-forge/staged-recipes/pull/7166

I already have a build for another channel, but ilmbase and openexr are packaged differently on conda-forge (they are two well separated packages, while most of the time, windows build are bundle including both.)

**Comment by lgritz** [comment]
So is the problem that it doesn't like

     #if defined(FOO) && FOO >= 2

is not ok even though it appears to be guarded by the `defined(FOO)` part?

Would it solve this issue to rewrite it like this?

    #if defined(ILMBASE_VERSION_MAJOR)
        #if LMBASE_VERSION_MAJOR >= 2
        #endif   
    #endif

nested rather than compound statements?

**Comment by SylvainCorlay** [comment]
But ILMBASE is supposed to be installed. I will do some cmake debugging tomorrow when I can work on a windows machine.

I suspect an issue with the ILMBASE packaging.

**Comment by lgritz** [comment]
The ILMBASE_VERSION_MAJOR should be defined in headers included by OpenEXR/ImathVec.h at the top of my simd.h, so if ilmbase is not installed at all, there should have been a separate failure about not finding the included header.

**Comment by lgritz** [comment]
@SylvainCorlay  Do you have an opinion on what I wrote a couple comments back? Do you think that changing the `#if` construct slightly as I outlined is likely to help?

**Comment by lgritz** [comment]
@SylvainCorlay Any further thoughts on this?

**Comment by meshula** [comment]
The OpenEXR installation process should install

```
include/OpenEXR/IlmBaseConfig.h
```
and that file should have the macros defined in it. The IlmBase recipe in conda-forge looks good, so if that file is not being written correctly, it's possible there's a bug in IlmBase's autoconf script. I don't have a conda-using system available to me at the moment so I haven't investigated further.

**Comment by lgritz** [comment]
I think everything here is about old versions of OIIO, pre-CMake overhaul of 2019, and old versions of OpenEXR as well. Closing on the assumption that it's probably cleaned up now, and if it weren't more people would be complaining. Please re-open or re-file if it is still a problem on modern versions of everything.
