### ISSUE TITLE
OIIO 2.0.3 fails to build from source (FTBFS) on arm{el,hf}

### ISSUE THREAD

**Issue by mfvescovi** [OpenImageIO/oiio#2098]
### Problem
OIIO 2.0.3 fails to build on both armel and armhf, while building fine on other architectures
(still missing mips* among release's, which will build soon). See [here](https://buildd.debian.org/status/package.php?p=openimageio&suite=experimental).

Build logs following:
- [armel](https://buildd.debian.org/status/fetch.php?pkg=openimageio&arch=armel&ver=2.0.3%7Edfsg0-1&stamp=1544709298&raw=0)
- [armhf](https://buildd.debian.org/status/fetch.php?pkg=openimageio&arch=armhf&ver=2.0.3%7Edfsg0-1&stamp=1544706733&raw=0)

### Versions
* OIIO branch/version: RB-2.0/2.0.3
* OS: Debian unstable/sid | experimental
* C++ compiler: GCC-8.2.0

**Comment by hobbes1069** [comment]
I'm not sure if those arches are equivalent to aarch64 and armv7hl on Fedora but I'm not having any issues...

https://koji.fedoraproject.org/koji/taskinfo?taskID=31442214

**Comment by mfvescovi** [comment]
Hi @hobbes1069! 
> I'm not sure if those arches are equivalent to aarch64 and armv7hl on Fedora but I'm not having any issues...

While aarch64 is arm64 (which builds fine even for me), armv7hl should be 'my' armhf... and it builds for you. Weird.
I'm under the impression that I've enabled some features with this new version that weren't on 1.8.xx and it makes OIIO fails on platforms where GL is not fully supported (since it seems to something connected to that technology).
I've got to diff-check your build and mine and see the differences.
I'll keep you posted on that.

**Comment by lgritz** [comment]
If I try some fixes and point you to another branch, can you build from that branch name and see what happens? I obviously have no ability to directly test on those architectures myself, but I might be able to make some good guesses from the logs.

**Comment by lgritz** [comment]
This was quite a while back. Closing. Please re-file if there are problems compiling master or the current 2.1 release on this architecture.
