### ISSUE TITLE
InputImage::_read_image bug ?

### ISSUE THREAD

**Issue by spinell** [OpenImageIO/oiio#2106]
I think I found a bug with InputImage::read_image(), read_tiles() and read_scanines()
When you use the paramater xStride, in some situation OIIO ignore the value of the xStride paramater.

Let suppose I have a allocated buffer of unsigned char that will containt RGBA values.
When I call read_image with the format UCHAR and a xStride of 4 bytes to read by example a bmp file that contains RGB, the values goes in my buffer at the right place (OIIO skip the alpha channel in my buffer). But if I'm reading by example an OpenEXR image that only have the red channel and the data in the file are float, OIIO ignore my stride value.

I think the problem is, if the pixel size in the image file is equal to the xStride value, OIIO ignore the stride and write the data in continious memory.

Note: I tried with version 1.8

**Comment by spinell** [comment]
yes my buffer is unsigned char.
the format paramater is UCHAR.
the xStride is 4.

The image file internal data is float and the image only have the red channel.
OIIO convert the float to UCHAR write in my buffer without using the stride.

I can repro the same behaviour with an image file that only have the Red and Green channel
but the image file internal data is half-float.

**Comment by lgritz** [comment]
OK, I think I understand. Looking into it...

**Comment by lgritz** [comment]
Yes, I think I see how this happens. It's late, I will look at it more tomorrow. Should be an easy fix.

**Comment by lgritz** [comment]
Fix proposed in #2108

**Comment by lgritz** [comment]
Not sure why this issue didn't close when we merged the fix of #2108. But we did, so closing the ticket now.
