### ISSUE TITLE
“definted” intended to be “defined”?

### ISSUE THREAD

**Issue by sobotka** [OpenImageIO/oiio#2142]
https://github.com/OpenImageIO/oiio/blob/1d012e1626209b7937c17eb4dada20da6ac7a497/src/include/OpenImageIO/imagebufalgo.h#L1287

Appears to be a typo.

**Comment by lgritz** [comment]
Thanks! Fixing.

**Comment by lgritz** [comment]
Typo fix pushed to master and RB-2.0. Thanks for reading carefully!
