### ISSUE TITLE
Corrupted PNG causes crash

### ISSUE THREAD

**Issue by riviera-kid** [OpenImageIO/oiio#2163]
### Problem

Loading the corrupted PNG causes OIIO crash.
The image is corrupted, but it can be displayed in some image viewers.

Image:
http://www.uschovna.cz/zasilka/JSCPUYA82N54BK58-9PA/

**Expected behavior:** 
Detect the corruption and return error.

### Versions

* OIIO branch/version:  2.0.4
* OS: Win 10 x64
* C++ compiler: VS2017

**Comment by lgritz** [comment]
Yes, thanks for the test case. Fix coming up!

**Comment by lgritz** [comment]
Proposed fix: #2167

**Comment by lgritz** [comment]
Fixed by #2167. Closing.
