### ISSUE TITLE
ImageOutput silent failure/segfault with read-only path

### ISSUE THREAD

**Issue by ptooley** [OpenImageIO/oiio#2175]
### Problem

OIIO::ImageOutput::write_image fails either silently or with a  segfault when output path does not have write permissions:

### MWE
```c++
#include <vector>

#include <OpenImageIO/imageio.h>

const int nx = 300;
const int ny = 300;

std::string filename = "somefile.png";

int main()
{
  std::vector<int> pixdata(nx*ny, 0);

  auto img = OIIO::ImageOutput::create(filename);
  OIIO::ImageSpec spec(nx, ny, 1, OIIO::TypeDesc::UINT16);
  img->open(filename, spec);

  img->write_image(OIIO::TypeDesc::DOUBLE, pixdata.data());
  img->close();
#if OIIO_VERSION < 10903
  OIIO::ImageOutput::destroy(img);
#endif //OIIO_VERSION < 10903
}

```
### Steps to Reproduce
- build with ``g++ test.cpp -lOpenImageIO -o test
- make containing directory read only e.g chmod -w .
- running now gives:
    - segfault if writing to png
    - silent failure if writing to jpg

### Expected result

I would expect that an exception would be raised in this situation.

### Versions

* OIIO branch/version: 1.8.x and 2.0.x
* OS: Linux
* C++ compiler: gcc-8.2.0 and 7.2.0

**Comment by lgritz** [comment]
Thanks for alerting me to this.

I wrote a test that tries to write to nonexistent directories, for every file format we support. I will review that separately. But it turned up some interesting failure cases.

#2186 fixes DPX (you didn't mention it, but my test found it)
#2187 fixes PNG and JPG
#2188 Fixes an issue found with heif in master.

**Comment by lgritz** [comment]
#2189 is for the new test that exercises all plugins with this test case.

**Comment by lgritz** [comment]
I think this has been fixed for a while.
