### ISSUE TITLE
segfault on get_image_handle

### ISSUE THREAD

**Issue by ennis** [OpenImageIO/oiio#2179]
### Problem

**Expected behavior:**  
Calling `ImageCache::get_image_handle(path)` should return NULL or an image handle.

**Actual behavior:**  
`get_image_handle` dereferenced a null pointer and segfaulted.

I'm using OpenImageIO 1.8.16 (installed via vcpkg on windows). I did not have the time to compile and test the latest master.

The null pointer dereference seems to happen in the `find_file` function: 
https://github.com/OpenImageIO/oiio/blob/cbdf585a6b69b6a2a5dcff4be5a36c442960a694/src/libtexture/imagecache.cpp#L1157

The code assumes that `thread_info != NULL`, but the function is called by `get_image_handle` with `thread_info=NULL` (the default argument), which is valid according to the documentation.

At first glance, the latest master also makes the same assumption:
https://github.com/OpenImageIO/oiio/blob/3c4a7af1846918376249b1b12698090c5d79768c/src/libtexture/imagecache.cpp#L1192

### Versions

* OIIO branch/version: 1.8.16
* OS: Windows 10 x64
* C++ compiler: MSVC 2017

**Comment by lgritz** [comment]
Yes, you are quire right. I think I have a solution, coming up.

**Comment by lgritz** [comment]
PR #2184 is a proposed fix. Care to try on your end?  (It's a 2-line patch, should be easy to apply on your side, even if not in master.)

**Comment by ennis** [comment]
This seems to fix the issue on my end, thanks!
