### ISSUE TITLE
CMake 3.14.3 issue

### ISSUE THREAD

**Issue by Miaua** [OpenImageIO/oiio#2224]
I have:
CMake 3.14.3
Windows 10
VS 2017 (15.9.28307.586)
clang 9
gcc 7.2
Don't have icc compiler
-------------------------

Need to compile dynamic version of oiio 2.0.7 for x64.
With:
Boost 1.70.0
IlmBaseOpenEXR 2.3.0
LibTIFF 4.0.10
OpenJpeg 2.3.1
libpng 1.6.37
-------------------------

It's looking like the 3'rd party library folder structure and or file naming has changed.
Or another reason why CMake can't auto link anything.

Many times when i manually link, CMake claims wrongly library to be too old. like with IlmBaseOpenEXR 1.6.1, Boost 0.0.0.

The manual linking to Boost sub folders and or files is not clear at all. CMake is not specific enough to find correct files from the 18000 files in Boost library.

**Comment by lgritz** [comment]
Yeah, that "3rd party" stuff is really old. Ignore that. If there are still references to that, we should fix it.

**Comment by lgritz** [comment]
Closing. We note for the record that we need a pretty big overhaul in our Windows build instructions.
