### ISSUE TITLE
Not able to build OpenImageIO in my system.

### ISSUE THREAD

**Issue by myproject24** [OpenImageIO/oiio#2225]
Hi @lgritz @edgarv @fpsunflower  I am  trying to build OpenImageIO/oiio i am getting some compiler errors, as shown below.

> [ 74%] Linking CXX shared library libOpenImageIO.so
> /usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libopencv_imgproc.a(color.cpp.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; **recompile with -fPIC**
> /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libopencv_imgproc.a: error adding symbols: Bad value
> collect2: error: ld returned 1 exit status
> src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/build.make:1949: recipe for target 'src/libOpenImageIO/libOpenImageIO.so.2.1.1' failed
> make[2]: *** [src/libOpenImageIO/libOpenImageIO.so.2.1.1] Error 1
> CMakeFiles/Makefile2:2424: recipe for target 'src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/all' failed
> make[1]: *** [src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/all] Error 2
> Makefile:162: recipe for target 'all' failed
> make: *** [all] Error 2

Even i tried setting **-fPIC** flag in CmakeList.txt but still not able compile it.

**Comment by hobbes1069** [comment]
Just happened to find this while looking for something else. Hopefully you figured out your problem but github issues aren't the best place for general troubleshooting, please pose these types of questions to the mailing list.

**Comment by lgritz** [comment]
No follow-up in some time. Closing. Please re-open if this is still a problem in the current release.
