### ISSUE TITLE
Reading PNG or JPG fails on Windows

### ISSUE THREAD

**Issue by ttddee** [OpenImageIO/oiio#2230]
### Problem

Reading PNG or JPG images fails on Windows, starting with version OIIO 2.0.7.

**Expected behavior:**  
```
shared_ptr<ImageBuf> inputImage (new ImageBuf());
inputImage->init_spec("test.jpg", 0, 0);
bool ok = inputImage->read(0, 0, TypeDesc::FLOAT);
```

`ok` should be true

**Actual behavior:**  

`ok` is false and `inputImage->geterror()` returns the following for JPG images:

`Invalid image file "test.jpg": JPEG error: Not a JPEG file: starts with 0xff 0xe1`

And for PNG images:

```
libpng error: Not a PNG file
Invalid image file "azul.png": PNG read error: Not a PNG file
```

Other image formats work fine.

I have gone through the commits and this change introduces the problem:

https://github.com/OpenImageIO/oiio/commit/7677d498b599295fa8277d050ef994efbd297b55

Anything before works fine.

### Steps to Reproduce

1. Build OIIO master on Windows x64
2. Run the code above on any PNG or JPG

### Versions

* OIIO branch/version: master
* OS: Windows x64 
* C++ compiler: MSVC2017 toolset v141

**Comment by lgritz** [comment]
Can you directly email me a small JPEG file that fails?

**Comment by lgritz** [comment]
Some follow-up questions for you:

* You say that OIIO 2.0.7 is where it first broke. But the commit 7677d49, is on master, not 2.0. The equivalent change was backported to RB-2.0, but it was in what became release 2.0.8, not 2.0.7. 

So I'm confused, I don't see how the changes in that commit could affect release 2.0.7.

Neither the PNG nor JPEG modules were altered between 2.0.6 and 2.0.7.

That commit you cite, though -- that does look suspicious! It touches both PNG and JPEG in similar ways that are related to how the files are opened and read from.

Can you possibly verify if things still seem broken on (a) TODAY's top of RB-2.0, which is imminently about to become 2.0.8, and (b) TODAY's "master" branch?

**Comment by lgritz** [comment]
Can you send me a specific JPG file that exhibits this problem?

**Comment by ttddee** [comment]
Yes I will verify both 2.0 and master and get back to you.

Also sent you a test image.

**Comment by lgritz** [comment]
OK, I finally have a hypothesis about what's going on.

Can you try an experiment for me?

In OIIO's src/libutil/filesystem.cpp, circa line 1000 in the function Filesystem::IOFile::pread(), you will see this line:

    return ReadFile(h, buf, DWORD(size), &bytesread, &overlapped) ? bytesread
                                                                  : 0;

Can you please replace that with the following, rebuild, and see if that fixes the problem?

    size_t r = ReadFile(h, buf, DWORD(size), &bytesread, &overlapped)
                   ? bytesread
                   : 0;
    seek(m_pos);  // In case ReadFile changed the file pointer
    return r;

**Comment by ttddee** [comment]
First of all I think I got confused and the problem might not exist in 2.0.7. The problem with that version was rather that I couldn't manage to build it.

But here is the good news: The code change above seems to have fixed the problem! Both JPG and PNG are reading fine now on master.

**Comment by lgritz** [comment]
Outstanding!

I think that this is going to close a number of separately reported issues that all boil down to this.

I will prepare a PR with the fix right away. Thanks so much for your patience.

**Comment by lgritz** [comment]
I simplified even more. And also started looking suspiciously at our Windows implementation pwrite.

Proposed fix here:   https://github.com/OpenImageIO/oiio/pull/2231

**Comment by lgritz** [comment]
Closing, #2231 fixed this.
