### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by neurister** [OpenImageIO/oiio#2233]
The example in the documentation for IOVecOutput seems to have an error.

It says: 

```
    Filesystem::IOVecOutput vecout (file_buffer);  // I/O proxy object
    void *ptr = &file_buffer;
    spec.attribute ("oiio:ioproxy", TypeDesc::PTR, &ptr);
```
whereas I think it should say:
```
    Filesystem::IOVecOutput vecout (file_buffer);  // I/O proxy object
    void *ptr = &vecout;
    spec.attribute ("oiio:ioproxy", TypeDesc::PTR, &ptr);
```

### Problem

**Expected behavior:**  

**Actual behavior:**  

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Versions

* OIIO branch/version: 
* OS: 
* C++ compiler:

**Comment by lgritz** [comment]
oops, yes, you are quite right
