### ISSUE TITLE
oiiotool ignores --compression option when outputting multipart EXRs

### ISSUE THREAD

**Issue by bengervais** [OpenImageIO/oiio#2251]
When using EXR output and saving a multipart EXR, (either via building one via --siappend in oiiotool, or using as input an EXR that already is multipart) the --compression option is ignored and all EXR parts that are saved in any output file use default (zip) compression.

This occurs under current release (2.0.8) as well as the master branch (2.1.1dev). (running debian stretch, built for C++11)  bug is also present in iconvert.

We found this when trying to optimize some of our EXRs for read performance on another system.  When taking 'sample.exr' that has say R,G,B channels, plus a number of other named channels in the same view/part, let's call them SKY, WATER, FG.  We wanted to move the named channels into the second part of a new, multi-part file. (sample.exr has no compression in this case) 

`oiiotool -i sample.exr --dup --ch "R,G,B" --swap --ch "SKY, WATER, FG" --siappend --compression "none" -o output.exr`

Will yield a file with zip compression (but, curiously a "compressionName" header field that says "none" despite the zip compression.)

**Comment by lgritz** [comment]
I'll try to take a look at this today, thanks for the report.

**Comment by lgritz** [comment]
I don't suppose you can send me (privately is ok) the exr file you start with? Or post a short oiiotool recipe for creating an exr file from scratch that shows the problem?

**Comment by lgritz** [comment]
never mind, I can reproduce. Stay tuned

**Comment by lgritz** [comment]
Fix posted as PR #2252

**Comment by bengervais** [comment]
Sweet!
