### ISSUE TITLE
[BUG] py_oiio::attribute_typed() doesn't handle tuples

### ISSUE THREAD

**Issue by apetrynet** [OpenImageIO/oiio#2275]
**Describe the bug**
For a while now I've been unsuccessful in adding TimeCode to EXR's through python. In my quest to achieve this I've been digging around in the code and discovered what _might_ be the reason. It seems that `attribute_typed()` only supports int, floats and strings. In other words, when passing a tuple which is required for "non-standard" attributes there's nothing to handle them.

Here are a couple of links to my findings: (Please note that I might be barking up the wrong tree here, but seems a bit off)

[When passing a tuple to attribute_typed()...](https://github.com/OpenImageIO/oiio/blob/9dcde4e293e94038e12d413effd42ca4536e1261/src/python/py_imagespec.cpp#L199)
[...nothing catches the tuple and handles it](https://github.com/OpenImageIO/oiio/blob/864580de417e938ad965a1710e03da35f1175b5a/src/python/py_oiio.h#L323)

**To Reproduce**
1. Create an ImageBuf
2. Add TimeCode
3. Write image to EXR

**Expected behavior**
Get an image with the TimeCode passed

**Evidence**
```python
import OpenImageIO as oiio

attrname = 'smpte:TimeCode'

# Create a buffer form image with a valid TimeCode
source_buf = oiio.ImageBuf('./checker_with_tc.exr')
tc_in = source_buf.spec().getattribute(attrname)
print type(tc_in), tc_in  # <type 'tuple'> (16777216L, 0L)

# Create a new buffer and apply the TimeCode from source image
buf = oiio.ImageBuf(oiio.ImageSpec(1600, 900, 3, oiio.HALF))
buf.specmod().attribute(attrname, oiio.TypeTimeCode, tc_in)
buf.write('./oiio_tc_write.exr')

# Did the TimeCode stick?
print buf.spec().getattribute(attrname)  # None
```

**Platform information:**
 - OIIO branch/version: Release 2.0.7
 - OS: CentOS 7
 - C++ compiler: gcc 4.8.5
 - Any non-default build flags when you build OIIO:

**IF YOU ALREADY HAVE A CODE FIX:** There is no need to file a separate issue,
please just go straight to making a [pull request](https://github.com/OpenImageIO/oiio/pulls).

**Comment by lgritz** [comment]
I'll take a look, thanks for the alert. (And thanks for the repro script -- this makes it so very much easier for me to get started tracking something like this down.)

**Comment by apetrynet** [comment]
Thanks! Hope it's not a wild goose chase.

**Comment by lgritz** [comment]
Legit bug. Fix proposed as #2279.

**Comment by apetrynet** [comment]
Sweet! Thanks!

**Comment by apetrynet** [comment]
Your fix works like a charm!
Thanks again!
