### ISSUE TITLE
[BUG] iinfo does not read single channel (grayscale) DPX files

### ISSUE THREAD

**Issue by JoakimZiegler** [OpenImageIO/oiio#2291]
**Describe the bug**
iinfo, and I assume all of OpenImageIO, does not seem to manage to read grayscale (1-channel) DPX files.

**To Reproduce**
1. Find a legitimate grayscale DPX file (I can provide one on request)
2. Run iinfo filename.dpx
3. iinfo bugs out with iinfo: OpenImageIO could not open "filaname.dpx" as dpx: Unable to deliver RGB data from source data

**Expected behavior**
I expected it to give me correct information about the file. This file in particular is generated by the Lasergraphics ScanStation software, and can be read just fine by software like pfClean, Davinci Resolve, etc. Note that problems with single-channel DPX files is not unusual in a lot of software, for instance, Nuke has some trouble with them (resulting in image artifacts), but it does in fact read the file in general, enough to get dimensions, etc. Not surprisingly, iinfo reads RGB DPX files generated by the same software just fine.

**Platform information:**
 - OIIO branch/version: 1.5.24 (installed on CentOS from EPEL)
 - OS: Linux (CentOS 7.5)
 - C++ compiler: Whatever EPEL builds their packages with.
 - Any non-default build flags when you build OIIO: Whatever EPEL builds their packages with.

**Comment by JoakimZiegler** [comment]
Here's a (zipped) DPX file that I'm failing to read.
[arriba_las_mujeres-r01_0086400.dpx.zip](https://github.com/OpenImageIO/oiio/files/3388370/arriba_las_mujeres-r01_0086400.dpx.zip)

**Comment by lgritz** [comment]
Looking into it. It does indeed appear that our dpx reader doesn't currently support 1-channel images. It's shocking that nobody has reported this in the 8-9 years that we've had DPX support, and we use it very extensively in production!

**Comment by lgritz** [comment]
Fix proposed in #2294. Want to give that a try, if you can build it yourself?

I will backport the fix to 2.0, but the version 1.5 you say you're using is several years old. You're going to need to migrate to a supported branch in order to get the fix.

**Comment by JoakimZiegler** [comment]
I'll look at building this to test. I initially tested the version from EPEL because CentOS has fairly old packages of everything required, so I was trying to get something working without building a bunch of packages from source, but it looks like I'll just have to bite the bullet.

Thanks for the extremely quick fix, btw.
