### ISSUE TITLE
[BUG] Static library 

### ISSUE THREAD

**Issue by Soyal7** [OpenImageIO/oiio#2295]
There is some problem when using static library, no matter if I build it myself or use vcpkg.

I have installed the static OIIO with vcpkg and made it available to the project with the following:
.\vcpkg.exe install openimageio:x64-windows-static
.\vcpkg integrate install

Then I edited .vcxproj as instructed [here](https://devblogs.microsoft.com/cppblog/vcpkg-updates-static-linking-is-now-available/):
```
<PropertyGroup Label="Globals">
 <VcpkgTriplet Condition="'$(Platform)'=='x64'">x64-windows-static</VcpkgTriplet>
</PropertyGroup>
```

e.g.
```c++
auto img = OIIO::ImageInput::open(filename);
```

> error LNK2001: unresolved external symbol "__declspec(dllimport) public: static class std::unique_ptr<class OpenImageIO_v2_1::ImageInput,struct std::default_delete<class OpenImageIO_v2_1::ImageInput> > __cdecl OpenImageIO_v2_1::ImageInput::open(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class OpenImageIO_v2_1::ImageSpec const *)" (__imp_?open@ImageInput@OpenImageIO_v2_1@@SA?AV?$unique_ptr@VImageInput@OpenImageIO_v2_1@@U?$default_delete@VImageInput@OpenImageIO_v2_1@@@std@@@std@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@4@PEBVImageSpec@2@@Z)

The same happens when I build the library by myself and set project properties manually.
I tested with Visual Studio 16 2019, msvc_x64_x64.

**Comment by ras0219-msft** [comment]
This looks like in the version packaged, openimageio defaults to dll linkage[1] if no macros are defined. The right fix for vcpkg here will be to add a post-install string replace which explicitly patches the installed headers to define the imports correctly.

For your particular case, you can likely work around this issue by just adding a `#define OIIO_STATIC_BUILD 1` before including the openimageio headers.

[1] https://github.com/OpenImageIO/oiio/blob/Release-2.0.8/src/include/OpenImageIO/export.h#L73-L86

**Comment by Soyal7** [comment]
Thanks! This seems to solve the __declspec(dllimport) issue, but then I got multiple LNK2038 errors:
> error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in ConsoleApplication12.obj

I managed to get rid of them by setting Runtime Library to Multi-threaded (/MT),

Now I get the following:

> 1>Half-2_3_s.lib(half.cpp.obj) : error LNK2005: "class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl operator<<(class std::basic_ostream<char,struct std::char_traits<char> > &,class half)" (??6@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@AEAV01@Vhalf@@@Z) already defined in Half-2_3.lib(Half-2_3.dll)
> 1>Half-2_3_s.lib(half.cpp.obj) : error LNK2005: "private: static short __cdecl half::convert(int)" (?convert@half@@CAFH@Z) already defined in Half-2_3.lib(Half-2_3.dll)
> 1>C:\Users\me\source\repos\ConsoleApplication12\x64\Release\ConsoleApplication12.exe : fatal error LNK1169: one or more multiply defined symbols found

Without using vcpkg at all I get this, but it's more likely I did something wrong:

> 1>ConsoleApplication9.obj : error LNK2001: unresolved external symbol "public: static class std::unique_ptr<class OpenImageIO_v2_0::ImageInput,struct std::default_delete<class OpenImageIO_v2_0::ImageInput> > __cdecl OpenImageIO_v2_0::ImageInput::open(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class OpenImageIO_v2_0::ImageSpec const *)" (?open@ImageInput@OpenImageIO_v2_0@@SA?AV?$unique_ptr@VImageInput@OpenImageIO_v2_0@@U?$default_delete@VImageInput@OpenImageIO_v2_0@@@std@@@std@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@4@PEBVImageSpec@2@@Z)
> 1>C:\Users\me\source\repos\ConsoleApplication9\x64\Release\ConsoleApplication9.exe : fatal error LNK1120: 1 unresolved externals

**Comment by Soyal7** [comment]
I gave it another go and it links correctly now, so I assume the problem has been fixed.
