### ISSUE TITLE
[BUG] Typo in status message

### ISSUE THREAD

**Issue by wrosecrans** [OpenImageIO/oiio#2302]
This is minor / borderline silly, but I noticed a typo and I'm not near a computer where I can conveniently file a PR, so filing as an issue so it doesn't get forgotten

https://github.com/OpenImageIO/oiio/blob/master/src/cmake/modules/FindOpenImageIO.cmake#L76

The FindOpenImageIO.cmake refers to "oiiiotool" with thee i's in the status message rather than "oiiotool" with two.  It's already hard enough to pronounce with two i's!

**Comment by lgritz** [comment]
No worries, I will fix, thanks for the alert.

**Comment by lgritz** [comment]
Fixed in master and 2.0.
