### ISSUE TITLE
[BUG] ImageStabilization/TimeStamp need update

### ISSUE THREAD

**Issue by PhoebeHui** [OpenImageIO/oiio#2305]
Hi,

Building openiamgeio with vs2017 on windows failed with following errors, could you have a look? 
this due to libraw removed ImageStabilization by https://github.com/LibRaw/LibRaw/commit/e7e885e67746e6f56a29cae8ebabadae77cc7aa3#diff-0a212125e7f2d7e9caff074c99b2a360 and removed TimeStamp by https://github.com/LibRaw/LibRaw/commit/f0a503dc81319337dcddef00d29ffec123fbfd45, it's very old revision, but openiamgeio still reference them.

Failures:
F:\VCPKG\src\buildtrees\openimageio\src\ease-2.0.8-1be86a4a75\src\raw.imageio\rawinput.cpp(859): error C2039: 'ImageStabilization': is not a member of 'libraw_olympus_makernotes_t'
f:\vcpkg\src\installed\x64-windows\include\libraw\libraw_types.h(416): note: see declaration of 'libraw_olympus_makernotes_t'
F:\VCPKG\src\buildtrees\openimageio\src\ease-2.0.8-1be86a4a75\src\raw.imageio\rawinput.cpp(985): error C2039: 'TimeStamp': is not a member of 'libraw_sony_info_t'
f:\vcpkg\src\installed\x64-windows\include\libraw\libraw_types.h(490): note: see declaration of 'libraw_sony_info_t'

**To Reproduce**
1. git clone https://github.com/microsoft/vcpkg
2. ./bootstrap-vcpkg.bat
3. ./vcpkg install openimageio[libraw]

**Comment by lgritz** [comment]
I see. These are present in the current release, 0.19.3, but have been removed from the libraw master, which presumably will be an official release some day but not yet. 

You must be building a recent master branch of libraw?

I can fix these, thanks for the alert.

**Comment by lgritz** [comment]
What version of libraw are you building against?

That field certainly appears in my version 0.19.3, which I think is the latest release. But it does look like it was removed

**Comment by PhoebeHui** [comment]
@lgritz, thanks for your quick response!

We use dev version d4f05dd1b9b2d44c8f7e82043cbad3c724db2416 in master branch.

**Comment by lgritz** [comment]
Proposed fix is here:  https://github.com/OpenImageIO/oiio/pull/2306
