### ISSUE TITLE
BUILD: -Wall causing fits for GCC 8.3.0-6

### ISSUE THREAD

**Issue by sobotka** [OpenImageIO/oiio#2337]
`error: ‘char* strncpy(char*, const char*, size_t)’ output may be truncated copying 15 bytes from a string of length 15 [-Werror=stringop-truncation]
   strncpy(szReport, szTemp, 15);`

Any way to get the default build to negotiate this one?

**Comment by lgritz** [comment]
Which OIIO version are you concerned with?

**Comment by sobotka** [comment]
That’s from master. The -Werror triggers compilation failure with that error.

**Comment by lgritz** [comment]
Can you try an experiment for me?

In SHA1.cpp, put this at the top, right before the first #include?

    #define _CRT_SECURE_NO_WARNINGS 1

**Comment by lgritz** [comment]
@sobotka Were you able to try that one line fix to see if it helps?

**Comment by sobotka** [comment]
I’ll test this weekend. Sorry for the delay.

**Comment by sobotka** [comment]
Just tested now. Doesn't appear to have an impact. Still fails with:

```
oiio/src/libutil/SHA1.cpp:286:10: error: ‘char* strncpy(char*, const char*, size_t)’ output may be truncated copying 15 bytes from a string of length 15 [-Werror=stringop-truncation]
   strncpy(szReport, szTemp, 15);

```

**Comment by lgritz** [comment]
How about the proposed fix of #2341 ?

**Comment by sobotka** [comment]
Sadly a clean cmake still trips the warning as error with the patches.

**Comment by lgritz** [comment]
Alternate approach in #2342.  Not just a couple line change this time.

**Comment by sobotka** [comment]
Sorry for the delay.

Tested the lg-oiio branch with `gcc (Debian 8.3.0-6) 8.3.0` and the warning still triggers an error.

**Comment by lgritz** [comment]
Troy, can you try #2342 which is a different approach where I replace all of the SHA1 code with an more recent version that I hope fixes that section of the code?

**Comment by sobotka** [comment]
I did a clone of your `lgritz:lg-sha1` branch. Seemed to still generate the same warning which trips the all warnings as errors compiler flag. Perhaps it’s not worth bothering with given how much of a struggle it appears to be to silence this warning with GCC.

**Comment by sobotka** [comment]
Confirming that brute force carpet bombing approach in #2342 solves the issue.

PS: Discovered https://github.com/lgritz/oiio/tree/lg-prefilter. Did the prefilter end up working?

**Comment by lgritz** [comment]
So just to verify -- you tried #2341 (not accidentally master) and that definitely doesn't work?

I'm good with 2342 for master, but I feel strange about backporting it. I was hoping that we could just splice into release branch the direct disabling of the warning, if that worked, rather than changing to new (to us) code.

prefilter -- I don't even remember, it was in some half-implemented state and I got distracted. I'm sure it's not done.

**Comment by sobotka** [comment]
The two one line patches did not appear to work.

The updated SHA1 appeared to silence the warning.

**Comment by lgritz** [comment]
Do you need a fix in a release branch, or is master all you're after?

**Comment by sobotka** [comment]
I can manually toggle the warnings. Fine here. Just thought I would mention that gcc trips on the warnings. If you intend to update the SHA library anyways, master is more than fine.

**Comment by lgritz** [comment]
OK, I'll merge the big one into master.
