### ISSUE TITLE
[BUG] DPXOutput integer multiplication overflow at high resolutions

### ISSUE THREAD

**Issue by traumedy** [OpenImageIO/oiio#2377]
**Describe the bug**
Handling DPX images at resolutions above around 13000x13000 causes crashes or hangs during input and output.

**To Reproduce**
Generates crash:
`oiiotool /imgs/sample.jpg -resize 16384x16384 -o /imgs/output.dpx`
Also `OpenImageIO.ImageInput.read_image()` causes memory allocation error.

**Evidence**
The problem seems related to `int` overflows as most values in the DPX handler are stored as `int`, I was able to solve the problems for my purposes (though more issues may exist) by static casting some int's to size_t, specifically the main data buffer allocation in `DPXOutput::prep_subimage`:
```
    // allocate space for the image data buffer
    if (allocate)
        m_buf.resize(static_cast<size_t>(m_bytes) * static_cast<size_t>(m_spec.height));
```
and the indexing of the write pointer in `DPXOutput::write_scanline`:
```
    unsigned char* dst = &m_buf[static_cast<size_t>(y - m_spec.y)
                                * static_cast<size_t>(m_bytes)];
```
From a short scan, these do seem to be the only two places in dpxinput/dpxoutput where multiplication is performed.

**Platform information:**
 - OIIO branch/version: Master branch 2.5.1
 - OS: Windows 10
 - C++ compiler: Visual Studio 2017 Enterprise
 - Any non-default build flags when you build OIIO: USE_OCIO

**IF YOU ALREADY HAVE A CODE FIX:** There is no need to file a separate issue,
please just go straight to making a [pull request](https://github.com/OpenImageIO/oiio/pulls).

**Comment by lgritz** [comment]
16k x 16k == 2^28 pixels. If you then multiply a pixel index by 8 (say, the size of 4 channels * 2 bytes, or simply an 8 byte pointer size), you can easily overflow any math that used a signed 32 bit `int`. Once you hit 32k x 32k resolution, even an RGBA with one byte (uint8) data hits the limit of even an `unsigned int`.

I just ran into (and fixed) a resolution limit problem with OpenEXR (which not only was in the OIIO side code, but actually had bugs in the openexr code, for deep images). 

I suspect that many of the other image formats are similarly brittle, including not just our code but deep in the underlying format libraries, particularly in rarely exercised code paths (such as dealing with >4 color channels, or data formats that we use but that are uncommon among web civilians).

I've been thinking that the thing to do is construct a test (perhaps akin to imageinout_test) that just cycles through every file format and tries to write a 32k^2 x 4 chan image that will exceed 32 bits, then read it back, just to fully ferret out these lurking bugs. It will probably be some effort to fix every problem it exposes.

**Comment by lgritz** [comment]
Thanks for alerting me to this. I will have a PR addressing it shortly.

And I will soon have another PR that tests huge images for all formats (and a few associated bug fixes found along the way).
