### ISSUE TITLE
[HELP]

### ISSUE THREAD

**Issue by paulwinex** [OpenImageIO/oiio#2419]
Hi
How to correctly setup font for image processing? 
_ImageBufAlgo.render_text()_ not works and return _False_. I think method cannot found the font. Any command _render_text()_ return _False_, when i not set font (using default) or when i set fontname.
```
buf = oiio.ImageBuf(filename)
oiio.ImageBufAlgo.render_text(buf, 100, 100, "Example")
>>> False
oiio.ImageBufAlgo.render_text(buf, 100, 100, "Example", 40, "Arial")
>>> False
```
I use examples from this page
[https://openimageio.readthedocs.io/en/latest/pythonbindings.html](https://openimageio.readthedocs.io/en/latest/pythonbindings.html)

How i can set absolute path to ttf file or similar solution?
Thanks.
Debian 8, Python 3.6-3.7
Build from [https://github.com/fredrikaverpil/oiio-python](https://github.com/fredrikaverpil/oiio-python)

**Comment by lgritz** [comment]
There are a whole bunch of directories it will search, you can see them here: https://github.com/OpenImageIO/oiio/blob/master/src/libOpenImageIO/imagebufalgo_draw.cpp#L719

That includes many typical system font locations to check, and also it should also have some bundled fonts in $OpenImageIO_ROOT/share/fonts/OpenImageIO (assuming you have set env variable $OpenImageIO_ROOT to point to a correct full install of OIIO).

If none of that works, I worry that perhaps you are working with a build of OpenImageIO that did not enable Freetype support at build time? It's an optional dependency, so it's possible that you built without it. It's required for any text rendering, so if not available at build time, render_text will be disabled.

You can test this hypothesis:

    if not oiio.ImageBufAlgo.render_text(buf, 100, 100, "Example") :
        print ("error: " + buf.geterror())

**Comment by lgritz** [comment]
Also, I just checked to be sure, but absolute paths for fonts are accepted as well. So something like this should work just fine:

    oiio.ImageBufAlgo.render_text(buf, 100, 100, "Example", 40,
              "/Users/lg/code/oiio/oiio.lg/dist/macosx/share/fonts/OpenImageIO/DroidSerif-Italic.ttf")

... unless you built OIIO with FreeType support disabled.

**Comment by paulwinex** [comment]
Yes, that error (
```
buf.geterror()
>>> 'OpenImageIO was not compiled with FreeType for font rendering'
```
Thanks!

**Comment by lgritz** [comment]
OK, closing the issue.
