### ISSUE TITLE
[FEATURE REQUEST] Writing image file to a buffer for Python API

### ISSUE THREAD

**Issue by dalechase** [OpenImageIO/oiio#2428]
I was hoping to use OIIO for a project running on AWS Lambda. However Lambda's storage tops out at 512MB, preventing processing of larger image files. 

This was added on the C++ side relatively recently here https://github.com/OpenImageIO/oiio/issues/1895. Having this added to the Python API would allow me to take advantage of Lambda's 3GB of RAM to process images larger than 512MB.

**Comment by lgritz** [comment]
I'm not sure I understand the use case.

What processing do you need to do?

You should be able to use the full RAM to "process" images (up to what you can fit in 3GB). But you can only store 512MB as disk files. 

#1895 lets you read/write what would have been the fully encoded disk file from/to memory. But how would that help you in this case? Why would you want that in memory and how would it help you in your memory and storage limited cloud instance?

**Comment by dalechase** [comment]
In the case of a 1GB source image, I'd like to download that image directly to a buffer and pass it to OIIO. The idea is to circumvent Lambda's 512MB disk limit by leveraging its RAM.

**Comment by lgritz** [comment]
What file format?



On December 9, 2019 5:01:12 p.m. PST, Dale Chase <notifications@github.com> wrote:
>In the case of a 1GB source image, I'd like to download that image
>directly to a buffer and pass it to OIIO. The idea is to circumvent
>Lambda's 512MB disk limit by leveraging its RAM.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/OpenImageIO/oiio/issues/2428#issuecomment-563511425

-- 
Larry Gritz
lg@larrygritz.com

**Comment by dalechase** [comment]
Support for EXR and PSD would be awesome.

**Comment by lgritz** [comment]
I thought it might either already be possible, or just very minor surgery to make it work from Python... but alas, after a couple hours of serious exploration, I see that it is probably going to be extremely difficult to do properly without a more extensive rearrangement and maybe some compatibility-breaking changes. (Which may not be a bad idea in the long run, but it's not something I can knock out in the short term.)

Is it not possible for you to implement this functionality as a C++ program, it has to be Python?

Another possibility, which I think is possible to do with today's version of the software, though it's very much a "power developer OIIO ninja" approach, would be to write a custom image format reader as a C++ DLL/DSO -- as if it were another file format, but actually it's just a trick that downloads the image, sets up an IOMemReader wrapping the buffer, then instantiates the "real" reader, if you catch my drift. With just this plugin written, you ought to be able to drive the whole thing from Python. If this sounds appealing/possible (in the sense of having a good enough C++ programmer to do the work if I give them some hints), let me know and I'll outline in more detail how it could be made to work.

**Comment by dalechase** [comment]
I was looking at Python because AWS Lambda doesn't provide a C++ runtime
out of the box. But there seems to be a way to add one. I'll explore that,
along with the option of writing my own wrapper. My C++ knowledge has
always been just on the surface. Perhaps I can take this as an opportunity
to become a bit more proficient. Thanks man. Greatly appreciate your taking
the time to investigate the possibility.

**Comment by lgritz** [comment]
I'm not sure what that means. OIIO Python is not pure interpreted python, it's just a python binding wrapping a C++ library. Any way you slice it, there's C++ at the bottom of the stack.

**Comment by lgritz** [comment]
No follow-up for some time. I'm closing on the assumption that it's not still a problem. Please re-open if you are having continued trouble.
