### ISSUE TITLE
[BUG] pkg-config file missing version

### ISSUE THREAD

**Issue by jtojnar** [OpenImageIO/oiio#2440]
**Describe the bug**
After [upgrade](https://github.com/NixOS/nixpkgs/pull/76358#pullrequestreview-336278981) to openimageio 2.1.9.0, the `Version` field in the `OpenImageIO.pc` only contains `..`.

**To Reproduce**
1. Install OpenImageIO

**Expected behavior**
`Version` field should contain `2.1.9.0`.

**Platform information:**
 - OIIO branch/version: 2.1.9.0
 - OS: NixOS (same issue on [Debian](https://packages.debian.org/experimental/amd64/libopenimageio-dev/download))
 - C++ compiler: GNU 8.3.0
 - Any non-default build flags when you build OIIO: `-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_SKIP_BUILD_RPATH=ON -DBUILD_TESTING=OFF -DCMAKE_INSTALL_LOCALEDIR=/nix/store/1h2f37yp8fxx9152rqs9jilzh31642nr-openimageio-2.1.9.0/share/locale -DCMAKE_INSTALL_LIBEXECDIR=/nix/store/1h2f37yp8fxx9152rqs9jilzh31642nr-openimageio-2.1.9.0/libexec -DCMAKE_INSTALL_LIBDIR=/nix/store/1h2f37yp8fxx9152rqs9jilzh31642nr-openimageio-2.1.9.0/lib -DCMAKE_INSTALL_DOCDIR=/nix/store/b768y9ghana4j3iwnwm6i6xqffy9zgw6-openimageio-2.1.9.0-doc/share/doc/ -DCMAKE_INSTALL_INFODIR=/nix/store/7axwcf3cd5gf8khqad9ah3wwrkj2xlw0-openimageio-2.1.9.0-bin/share/info -DCMAKE_INSTALL_MANDIR=/nix/store/7axwcf3cd5gf8khqad9ah3wwrkj2xlw0-openimageio-2.1.9.0-bin/share/man -DCMAKE_INSTALL_OLDINCLUDEDIR=/nix/store/ndysx89p7y5nmj74ggxx4r504x8sz3p5-openimageio-2.1.9.0-dev/include -DCMAKE_INSTALL_INCLUDEDIR=/nix/store/ndysx89p7y5nmj74ggxx4r504x8sz3p5-openimageio-2.1.9.0-dev/include -DCMAKE_INSTALL_SBINDIR=/nix/store/7axwcf3cd5gf8khqad9ah3wwrkj2xlw0-openimageio-2.1.9.0-bin/sbin -DCMAKE_INSTALL_BINDIR=/nix/store/7axwcf3cd5gf8khqad9ah3wwrkj2xlw0-openimageio-2.1.9.0-bin/bin -DCMAKE_INSTALL_NAME_DIR=/nix/store/1h2f37yp8fxx9152rqs9jilzh31642nr-openimageio-2.1.9.0/lib -DCMAKE_POLICY_DEFAULT_CMP0025=NEW -DCMAKE_OSX_DEPLOYMENT_TARGET= -DCMAKE_OSX_SYSROOT= -DCMAKE_FIND_FRAMEWORK=last -DCMAKE_STRIP=/nix/store/m8ih8gw7qnd2c7p0qgv3cn4b6abkbanb-binutils-2.31.1/bin/strip -DCMAKE_RANLIB=/nix/store/m8ih8gw7qnd2c7p0qgv3cn4b6abkbanb-binutils-2.31.1/bin/ranlib -DCMAKE_AR=/nix/store/m8ih8gw7qnd2c7p0qgv3cn4b6abkbanb-binutils-2.31.1/bin/ar -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_INSTALL_PREFIX=/nix/store/1h2f37yp8fxx9152rqs9jilzh31642nr-openimageio-2.1.9.0 -DUSE_PYTHON=OFF -DUSE_QT=OFF -DCMAKE_INSTALL_LIBDIR=lib`

**Comment by lgritz** [comment]
Thanks for alerting us, you are correct! Looking into it right away.

**Comment by lgritz** [comment]
Fix coming right up.

**Comment by lgritz** [comment]
Fix is here: https://github.com/OpenImageIO/oiio/pull/2441

**Comment by lgritz** [comment]
This was fixed by #2441.
