### ISSUE TITLE
farmhash symbols included in libOpenImageIO.a and llld on OSX doesnt like duplicate symbols

### ISSUE THREAD

**Issue by samhodge** [OpenImageIO/oiio#2472]
**Describe the bug**
When linking under machO under OSX you cannot have a duplicate symbol.

libOpenImageIO includes farmhash::Hash and several other symbols in the same namespace as Google's farmhash.

If you have another program that includes these symbols they are included in the .a file for libOpenImageIO.a

Other static symbols such as libpng.a and libjpeg.a and libtiff.a are not included in the libOpenImageIO archive

It seems that although farmhash is an external dependency it is absorbed into the OpenImageIO library

As a result it is not possible to statically link to OpenImageIO and another program that has already has farmhash's symbol included in it's .a file

**To Reproduce**
1. Create static libOpenImageIO.a
2. create NCBI static library that depends on farmhash.h
3. Link libOpenImageIO.a and the NCBI archive on macOS
4. Symbols will collid

**Expected behavior**
farmhash not included in the .a file for OpenImageIO library

**Evidence**
Do you have error messages? (please quote exacty) Screenshots? Example
command lines or scripts that reliably reproduce the error? If it only
happens with certain image files, can you attach the smallest image you
can make that reproduces the problem?

**Platform information:**
 - OIIO branch/version: 1.8.10
 - OS: macOS 10.13
 - C++ compiler: llvm clang
 - Any non-default build flags when you build OIIO: BUILDSTATIC LINKSTATIC

running sed -i s/farmhash/farmhashz/g on the files works as a hack

**Comment by lgritz** [comment]
Yep, I think I see the problem.

**Comment by lgritz** [comment]
Indeed, the file accidentally left some symbols unwrapped by the OIIO-specific namespace.

I will backport to the current supported release branch, 2.1, in addition to the current master, of course. The version 1.8 you are using is super old and won't be patched. I'm not even any longer patching 2.0 except for serious emergencies.

**Comment by samhodge** [comment]
Thanks for the super quick response.

I will look to updating to a newer version provided it doesn't force me to C++14 or above.

Sam

**Comment by lgritz** [comment]
No, we are still C++11 as the minimum requirement

**Comment by lgritz** [comment]
Closed via PR #2473
