### ISSUE TITLE
[FEATURE REQUEST] Ability to provide a WrapMode to ImageBufAlgo::resample

### ISSUE THREAD

**Issue by alister-chowdhury** [OpenImageIO/oiio#2479]
Hello,

When using resample over fit, resize etc because of its performance benefits.
However when upscaling small images, the default WrapBlack used in interppixel causes an unwanted black haloing effect around the borders.

My proposition would be to simply add wrap=WrapBlack as an argument to resample, and have it feed wrap to interppixel.

Many thanks.

**Comment by lgritz** [comment]
That's a really good idea.

**Comment by alister-chowdhury** [comment]
@lgritz 
Would you like me to close this ticket and #2480 ?

**Comment by lgritz** [comment]
Thanks for reminding me, I'll care of it.

Closed due to merge of #2341
