### ISSUE TITLE
[FEATURE REQUEST] Ability to provide a WrapMode to ImageBufAlgo::fit

### ISSUE THREAD

**Issue by alister-chowdhury** [OpenImageIO/oiio#2480]
Hello again,

This is pretty much in the same vein as https://github.com/OpenImageIO/oiio/issues/2479
Whereby using ImageBufAlgo::fit, with exact=true, results in warp being called with a wrap mode of WrapBlack.

And my proposed solution would also be to allow an optional argument of wrap=WrapBlack for ImageBufAlgo::fit.

If you'd agree with that, and are comftable, I could make a PR with both changes at the same time?

Many thanks

**Comment by lgritz** [comment]
Yes, a PR implementing this would be very welcome!

**Comment by lgritz** [comment]
Closed due to merge of #2341
