### ISSUE TITLE
[BUG] Documentation appears to be incorrect for use of make_textures opaque detection.

### ISSUE THREAD

**Issue by alister-chowdhury** [OpenImageIO/oiio#2482]
Originally I thought this was a spelling mistake on my part, (since maketx was correctly dropping alphas).

But it appears the documentation is out of date / incorrect.

It suggests to use "maketx:opaquedetect", however looking at the source of make_texture it should actually be ["maketx:opaque_detect"](https://github.com/OpenImageIO/oiio/blob/0a7054e44208dd41f30b0e2c20681f6706fe19a9/src/maketx/maketx.cpp#L366).

A quick search showed this to affect the following files:
[src/doc/imagebufalgo.rst](https://github.com/OpenImageIO/oiio/blob/ad31ad8ebf3880b37d6f82009683591434b387a7/src/doc/imagebufalgo.rst#L1693)
[src/doc/pythonbindings.rst](https://github.com/OpenImageIO/oiio/blob/ad31ad8ebf3880b37d6f82009683591434b387a7/src/doc/pythonbindings.rst#L3394)
[src/doc/imagebufalgo.tex](https://github.com/OpenImageIO/oiio/blob/cbef74aa5860eb0f48ae014d3c8b6da1fc91a295/src/doc/imagebufalgo.tex#L2634)
[src/doc/pythonbindings.tex](https://github.com/OpenImageIO/oiio/blob/dcdffbb4edc5bf03ec8d2745bf45d85f25230839/src/doc/pythonbindings.tex#L3376)

Many thanks

**Comment by lgritz** [comment]
Quite right! I will fix right away.

**Comment by lgritz** [comment]
Fixed by #2483
