### ISSUE TITLE
terminate called after throwing an instance of 'std::length_error'   what():  vector::_M_default_append

### ISSUE THREAD

**Issue by ShanQiong** [OpenImageIO/oiio#2490]
Hello, I am new to this, I occurs a problem when using read_scanlines. My code is something like:
Mat img(256, 86016, CV_8UC3); // opencv create image, 86016 is the width of level 0 in a pyramid multiresolution tiff

when I use in->read_scanlines(0, 256, 0, TypeDesc::UINT8, img.data); it occurs an error: terminate called after throwing an instance of 'std::length_error'   what():  vector::_M_default_append. 

However when the width is half , like:
Mat img(256, 43008, CV_8UC3);
in->read_scanlines(0, 256, 0, TypeDesc::UINT8, img.data); 

it works well

isn't a bug that the source code limit the line's length when using read_scanlines

**Comment by lgritz** [comment]
Can you explain why you are declaring a matrix (image, in OpenCV speak) that is 256x86016? Is that really the resolution you are looking for? Is that because you know it's the real resolution of the file, but you are reading it only in 256-scanline chunks?

Does the exception actually happen *within* the call to read_scanlines? Or does it happen afterwards?

What is the actual resolution, channels, and type of the file? For example, if you do `oiiotool -info -v thefile.ext`, what does it say?

What OS are you running? What version of OIIO? What version of OpenCV? You've given us very little to go on.

**Comment by ShanQiong** [comment]
thanks for your reply
the original pyramid tiff has a big size in the first level. Its size is about 86016(width)x89600(height). I want to transform this pyramid tiff to a dzi file(deepZoom format) with the tilesize is 256. So I first create a matrix(256(height)x86016(width), and then tile this matrix into many small tiles(256x256).

And the exception actually happen within the call to read_scanlines. However when I read the second subimage(43008x45056) with read_scanlines, it did work well. 

In addition, I also use read_tiles to read a whole(512x86016) in the first subimage, it also works well

So I read the source code of openimageio, I found the size of 256x86016x24b(rgb) bigger than 64MB. For this situation, the read_scanlines read data into several chunk(64MB). 

Sorry that the source code may be a little complicated for me, I think it may be a bug?

In addition, using oiiotool , it can get the information in the following:
Reading test_001.tif
test_001.tif         : 86016 x 89600, 3 channel, uint8 tiff
    9 subimages: 86016x89600 [u8,u8,u8], 43008x45056 [u8,u8,u8], 21504x22528 [u8,u8,u8], 10752x11264 [u8,u8,u8], 5632x5632 [u8,u8,u8], 3072x3072 [u8,u8,u8], 1536x1536 [u8,u8,u8], 1024x1024 [u8,u8,u8], 512x512 [u8,u8,u8]
    channel list: R, G, B
    tile size: 512 x 512
    compression: "jpeg"
.....
....
Orientation: 1 (normal)
    planarconfig: "contig"
    Software: "Philips DP v1.0"
    oiio:BitsPerSample: 8
    tiff:ColorSpace: "YCbCr"
    tiff:Compression: 7
    tiff:PhotometricInterpretation: 6
    tiff:PlanarConfiguration: 1

**Comment by lgritz** [comment]
Aha, many more clues.

The file you are reading from is *tiled*, but you are trying to read from it with *read_scanlines*. I bet that is where things go wrong. 

In general, you must read scanline files (ones that report tile size 0) with read_scanline/read_scanlines, and you must read tiled files with read_tile/read_tiles.

So if the file is broken into 512x512 tiles, what I would do is make your matrix be fullwidth x 512, read ONE ROW OF TILES into it, then output two rows of 256x256 tiles to the second file you are trying to write, and repeat.

**Comment by ShanQiong** [comment]
Thank you for replying again
Yeah, I use read_tiles in the first level, and it works well.
But I just wonder that I use read_scanlines to read the second level of the tiled image, it also work well. I also test other tile image(the first level is  with a width of about 65000 or more much), and it also doesn't work. Sometimes it occurs with an error: terminate called after throwing an instance of 'std::length_error' what(): vector::_M_default_append, and sometimes the error is a segmentation fault(the width is about 60000). 

Anyway, My problem is solved, but I think it may be a bug for read_scanlines. Next time, if I have more time, I may try a deep look of the source code

Thank you again

**Comment by lgritz** [comment]
`oiiotool -v -info -a thefile.ext`

I'm wondering if maybe in your original file, are some levels tiled and others scanline?

I can't think of a reason why read_scanlines should ever work for a tiled TIFF file. I think if there is a bug in read_scanlines, it is simply the fact that it should return with an error if you even try to use it at all on a tiled image.

**Comment by ShanQiong** [comment]
this is the full information about the tif image
test_001.tif         : 86016 x 89600, 3 channel, uint8 tiff
    9 subimages: 86016x89600 [u8,u8,u8], 43008x45056 [u8,u8,u8], 21504x22528 [u8,u8,u8], 10752x11264 [u8,u8,u8], 5632x5632 [u8,u8,u8], 3072x3072 [u8,u8,u8], 1536x1536 [u8,u8,u8], 1024x1024 [u8,u8,u8], 512x512 [u8,u8,u8]
 subimage  0: 86016 x 89600, 3 channel, uint8 tiff
    channel list: R, G, B
    tile size: 512 x 512
    oiio:BitsPerSample: 8
    ImageDescription: "<?xml version="1.0" encoding="UTF-8" ?>
<DataObject ObjectType="DPUfsImport">
	<Attribute Name="DICOM_MANUFACTURER" Group="0x0008" Element="0x0070" PMSVR="IString">Hamamatsu</Attribute>
	<Attribute Name="PIM_DP_SCANNED_IMAGES" Group="0x301D" Element="0x1003" PMSVR="IDataObjectArray">
		<Array>
			<DataObject ObjectType="DPScannedImage">
				<Attribute Name="PIM_DP_IMAGE_TYPE" Group="0x301D" Element="0x1004" PMSVR="IString">WSI</Attribute>
				<Attribute Name="UFS_IMAGE_PIXEL_TRANSFORMATION_METHOD" Group="0x301D" Element="0x2013" PMSVR="IString">0</Attribute>
				<Attribute Name="DICOM_BITS_ALLOCATED" Group="0x0028" Element="0x0100" PMSVR="IUInt16">8</Attribute>
				<Attribute Name="DICOM_BITS_STORED" Group="0x0028" Element="0x0101" PMSVR="IUInt16">8</Attribute>
				<Attribute Name="DICOM_DERIVATION_DESCRIPTION" Group="0x0008" Element="0x2111" PMSVR="IString">tiff-useBigTIFF=1-useRgb=0-levels=10003,10002,10000,10001-processing=0-q80-sourceFilename=&quot;T12-02872_1017268 - 2016-01-28 16.23.48.ndpi&quot;</Attribute>
				<Attribute Name="DICOM_HIGH_BIT" Group="0x0028" Element="0x0102" PMSVR="IUInt16">7</Attribute>
				<Attribute Name="DICOM_LOSSY_IMAGE_COMPRESSION" Group="0x0028" Element="0x2110" PMSVR="IString">01</Attribute>
				<Attribute Name="DICOM_LOSSY_IMAGE_COMPRESSION_METHOD" Group="0x0028" Element="0x2114" PMSVR="IStringArray">&quot;PHILIPS_TIFF_1_0&quot;</Attribute>
				<Attribute Name="DICOM_LOSSY_IMAGE_COMPRESSION_RATIO" Group="0x0028" Element="0x2112" PMSVR="IDoubleArray">&quot;3&quot;</Attribute>
				<Attribute Name="DICOM_PHOTOMETRIC_INTERPRETATION" Group="0x0028" Element="0x0004" PMSVR="IString">RGB</Attribute>
				<Attribute Name="DICOM_PIXEL_REPRESENTATION" Group="0x0028" Element="0x0103" PMSVR="IUInt16">0</Attribute>
				<Attribute Name="DICOM_PIXEL_SPACING" Group="0x0028" Element="0x0030" PMSVR="IDoubleArray">&quot;0.000226316&quot; &quot;0.000226321&quot;</Attribute>
				<Attribute Name="DICOM_PLANAR_CONFIGURATION" Group="0x0028" Element="0x0006" PMSVR="IUInt16">0</Attribute>
				<Attribute Name="DICOM_SAMPLES_PER_PIXEL" Group="0x0028" Element="0x0002" PMSVR="IUInt16">3</Attribute>
				<Attribute Name="PIIM_PIXEL_DATA_REPRESENTATION_SEQUENCE" Group="0x1001" Element="0x8B01" PMSVR="IDataObjectArray">
					<Array>
						<DataObject ObjectType="PixelDataRepresentation">
							<Attribute Name="DICOM_PIXEL_SPACING" Group="0x0028" Element="0x0030" PMSVR="IDoubleArray">&quot;0.000227273&quot; &quot;0.000227273&quot;</Attribute>
							<Attribute Name="PIIM_DP_PIXEL_DATA_REPRESENTATION_POSITION" Group="0x101D" Element="0x100B" PMSVR="IDoubleArray">&quot;0&quot; &quot;0&quot; &quot;0&quot;</Attribute>
							<Attribute Name="PIIM_PIXEL_DATA_REPRESENTATION_COLUMNS" Group="0x2001" Element="0x115E" PMSVR="IUInt32">86016</Attribute>
							<Attribute Name="PIIM_PIXEL_DATA_REPRESENTATION_NUMBER" Group="0x1001" Element="0x8B02" PMSVR="IUInt16">0</Attribute>
							<Attribute Name="PIIM_PIXEL_DATA_REPRESENTATION_ROWS" Group="0x2001" Element="0x115D" PMSVR="IUInt32">89600</Attribute>
						</DataObject>
						<DataObject ObjectType="PixelDataRepresentation">
							<Attribute Name="DICOM_PIXEL_SPACING" Group="0x0028" Element="0x0030" PMSVR="IDoubleArray">&quot;0.000454545&quot; &quot;0.000454545&quot;</Attribute>
							<Attribute Name="PIIM_DP_PIXEL_DATA_REPRESENTATION_POSITION" Group="0x101D" Element="0x100B" PMSVR="IDoubleArray">&quot;0&quot; &quot;0&quot; &quot;0&quot;</Attribute>
							<Attribute Name="PIIM_PIXEL_DATA_REPRESENTATION_COLUMNS" Group="0x2001" Element="0x115E" PMSVR="IUInt32">43008</Attribute>
							<Attribute Name="PIIM_PIXEL_DATA_REPRESENTATION_NUMBER" Group="0x1001" Element="0x8B02" PMSVR="IUInt16">1</Attribute>
							<Attribute Name="PIIM_PIXEL_DATA_REPRESENTATION_ROWS" Group="0x2001" Element="0x115D" PMSVR="IUInt32">45056</Attribute>
						</DataObject>
						<DataObject ObjectType="PixelDataRepresentation">
							<Attribute Name="DICOM_PIXEL_SPACING" Group="0x0028" Element="0x0030" PMSVR="IDoubleArray">&quot;0.000909091&quot; &quot;0.000909091&quot;</Attribute>
							<Attribute Name="PIIM_DP_PIXEL_DATA_REPRESENTATION_POSITION" Group="0x101D" Element="0x100B" PMSVR="IDoubleArray">&quot;0&quot; &quot;0&quot; &quot;0&quot;</Attribute>
							<Attribute Name="PIIM_PIXEL_DATA_REPRESENTATION_COLUMNS" Group="0x2001" Element="0x115E" PMSVR="IUInt32">21504</Attribute>
							<Attribute Name="PIIM_PIXEL_DATA_REPRESENTATION_NUMBER" Group="0x1001" Element="0x8B02" PMSVR="IUInt16">2</Attribute>
							<Attribute Name="PIIM_PIXEL_DATA_REPRESENTATION_ROWS" Group="0x2001" Element="0x115D" PMSVR="IUInt32">22528</Attribute>
						</DataObject>
						<DataObject ObjectType="PixelDataRepresentation">
							<Attribute Name="DICOM_PIXEL_SPACING" Group="0x0028" Element="0x0030" PMSVR="IDoubleArray">&quot;0.00181818&quot; &quot;0.00181818&quot;</Attribute>
							<Attribute Name="PIIM_DP_PIXEL_DATA_REPRESENTATION_POSITION" Group="0x101D" Element="0x100B" PMSVR="IDoubleArray">&quot;0&quot; &quot;0&quot; &quot;0&quot;</Attribute>
							<Attribute Name="PIIM_PIXEL_DATA_REPRESENTATION_COLUMNS" Group="0x2001" Element="0x115E" PMSVR="IUInt32">10752</Attribute>
							<Attribute Name="PIIM_PIXEL_DATA_REPRESENTATION_NUMBER" Group="0x1001" Element="0x8B02" PMSVR="IUInt16">3</Attribute>
							<Attribute Name="PIIM_PIXEL_DATA_REPRESENTATION_ROWS" Group="0x2001" Element="0x115D" PMSVR="IUInt32">11264</Attribute>
						</DataObject>
						<DataObject ObjectType="PixelDataRepresentation">
							<Attribute Name="DICOM_PIXEL_SPACING" Group="0x0028" Element="0x0030" PMSVR="IDoubleArray">&quot;0.00363636&quot; &quot;0.00363636&quot;</Attribute>
							<Attribute Name="PIIM_DP_PIXEL_DATA_REPRESENTATION_POSITION" Group="0x101D" Element="0x100B" PMSVR="IDoubleArray">&quot;0&quot; &quot;0&quot; &quot;0&quot;</Attribute>
							<Attribute Name="PIIM_PIXEL_DATA_REPRESENTATION_COLUMNS" Group="0x2001" Element="0x115E" PMSVR="IUInt32">5632</Attribute>
							<Attribute Name="PIIM_PIXEL_DATA_REPRESENTATION_NUMBER" Group="0x1001" Element="0x8B02" PMSVR="IUInt16">4</Attribute>
							<Attribute Name="PIIM_PIXEL_DATA_REPRESENTATION_ROWS" Group="0x2001" Element="0x115D" PMSVR="IUInt32">5632</Attribute>
						</DataObject>
						<DataObject ObjectType="PixelDataRepresentation">
							<Attribute Name="DICOM_PIXEL_SPACING" Group="0x0028" Element="0x0030" PMSVR="IDoubleArray">&quot;0.00727273&quot; &quot;0.00727273&quot;</Attribute>
							<Attribute Name="PIIM_DP_PIXEL_DATA_REPRESENTATION_POSITION" Group="0x101D" Element="0x100B" PMSVR="IDoubleArray">&quot;0&quot; &quot;0&quot; &quot;0&quot;</Attribute>
							<Attribute Name="PIIM_PIXEL_DATA_REPRESENTATION_COLUMNS" Group="0x2001" Element="0x115E" PMSVR="IUInt32">3072</Attribute>
							<Attribute Name="PIIM_PIXEL_DATA_REPRESENTATION_NUMBER" Group="0x1001" Element="0x8B02" PMSVR="IUInt16">5</Attribute>
							<Attribute Name="PIIM_PIXEL_DATA_REPRESENTATION_ROWS" Group="0x2001" Element="0x115D" PMSVR="IUInt32">3072</Attribute>
						</DataObject>
						<DataObject ObjectType="PixelDataRepresentation">
							<Attribute Name="DICOM_PIXEL_SPACING" Group="0x0028" Element="0x0030" PMSVR="IDoubleArray">&quot;0.0145455&quot; &quot;0.0145455&quot;</Attribute>
							<Attribute Name="PIIM_DP_PIXEL_DATA_REPRESENTATION_POSITION" Group="0x101D" Element="0x100B" PMSVR="IDoubleArray">&quot;0&quot; &quot;0&quot; &quot;0&quot;</Attribute>
							<Attribute Name="PIIM_PIXEL_DATA_REPRESENTATION_COLUMNS" Group="0x2001" Element="0x115E" PMSVR="IUInt32">1536</Attribute>
							<Attribute Name="PIIM_PIXEL_DATA_REPRESENTATION_NUMBER" Group="0x1001" Element="0x8B02" PMSVR="IUInt16">6</Attribute>
							<Attribute Name="PIIM_PIXEL_DATA_REPRESENTATION_ROWS" Group="0x2001" Element="0x115D" PMSVR="IUInt32">1536</Attribute>
						</DataObject>
						<DataObject ObjectType="PixelDataRepresentation">
							<Attribute Name="DICOM_PIXEL_SPACING" Group="0x0028" Element="0x0030" PMSVR="IDoubleArray">&quot;0.0290909&quot; &quot;0.0290909&quot;</Attribute>
							<Attribute Name="PIIM_DP_PIXEL_DATA_REPRESENTATION_POSITION" Group="0x101D" Element="0x100B" PMSVR="IDoubleArray">&quot;0&quot; &quot;0&quot; &quot;0&quot;</Attribute>
							<Attribute Name="PIIM_PIXEL_DATA_REPRESENTATION_COLUMNS" Group="0x2001" Element="0x115E" PMSVR="IUInt32">1024</Attribute>
							<Attribute Name="PIIM_PIXEL_DATA_REPRESENTATION_NUMBER" Group="0x1001" Element="0x8B02" PMSVR="IUInt16">7</Attribute>
							<Attribute Name="PIIM_PIXEL_DATA_REPRESENTATION_ROWS" Group="0x2001" Element="0x115D" PMSVR="IUInt32">1024</Attribute>
						</DataObject>
						<DataObject ObjectType="PixelDataRepresentation">
							<Attribute Name="DICOM_PIXEL_SPACING" Group="0x0028" Element="0x0030" PMSVR="IDoubleArray">&quot;0.0581818&quot; &quot;0.0581818&quot;</Attribute>
							<Attribute Name="PIIM_DP_PIXEL_DATA_REPRESENTATION_POSITION" Group="0x101D" Element="0x100B" PMSVR="IDoubleArray">&quot;0&quot; &quot;0&quot; &quot;0&quot;</Attribute>
							<Attribute Name="PIIM_PIXEL_DATA_REPRESENTATION_COLUMNS" Group="0x2001" Element="0x115E" PMSVR="IUInt32">512</Attribute>
							<Attribute Name="PIIM_PIXEL_DATA_REPRESENTATION_NUMBER" Group="0x1001" Element="0x8B02" PMSVR="IUInt16">8</Attribute>
							<Attribute Name="PIIM_PIXEL_DATA_REPRESENTATION_ROWS" Group="0x2001" Element="0x115D" PMSVR="IUInt32">512</Attribute>
						</DataObject>
					</Array>
				</Attribute>
				<Attribute Name="PIM_DP_IMAGE_COLUMNS" Group="0x301D" Element="0x1007" PMSVR="IUInt32">86016</Attribute>
				<Attribute Name="PIM_DP_IMAGE_ROWS" Group="0x301D" Element="0x1006" PMSVR="IUInt32">89600</Attribute>
				<Attribute Name="PIM_DP_SOURCE_FILE" Group="0x301D" Element="0x1000" PMSVR="IString">%FILENAME%</Attribute>
			</DataObject>
		</Array>
	</Attribute>
	<Attribute Name="PIM_DP_UFS_BARCODE" Group="0x301D" Element="0x1002" PMSVR="IString">MTAxNzI2OA==</Attribute>
	<Attribute Name="PIM_DP_UFS_INTERFACE_VERSION" Group="0x301D" Element="0x1001" PMSVR="IString">3.0</Attribute>
	<Attribute Name="DICOM_SOFTWARE_VERSIONS" Group="0x0018" Element="0x1020" PMSVR="IStringArray">&quot;4.0.3&quot;</Attribute>
</DataObject>
"
    Orientation: 1 (normal)
    Software: "Philips DP v1.0"
    tiff:PhotometricInterpretation: 6
    tiff:ColorSpace: "YCbCr"
    tiff:PlanarConfiguration: 1
    planarconfig: "contig"
    tiff:Compression: 7
    compression: "jpeg"
 subimage  1: 43008 x 45056, 3 channel, uint8 tiff
    channel list: R, G, B
    tile size: 512 x 512
    oiio:BitsPerSample: 8
    ImageDescription: "level=1 mag=22 quality=80"
    Orientation: 1 (normal)
    Software: "Philips DP v1.0"
    tiff:PhotometricInterpretation: 6
    tiff:ColorSpace: "YCbCr"
    tiff:PlanarConfiguration: 1
    planarconfig: "contig"
    tiff:Compression: 7
    compression: "jpeg"
    tiff:subfiletype: 1
 subimage  2: 21504 x 22528, 3 channel, uint8 tiff
    channel list: R, G, B
    tile size: 512 x 512
    oiio:BitsPerSample: 8
    ImageDescription: "level=2 mag=11 quality=80"
    Orientation: 1 (normal)
    Software: "Philips DP v1.0"
    tiff:PhotometricInterpretation: 6
    tiff:ColorSpace: "YCbCr"
    tiff:PlanarConfiguration: 1
    planarconfig: "contig"
    tiff:Compression: 7
    compression: "jpeg"
    tiff:subfiletype: 1
 subimage  3: 10752 x 11264, 3 channel, uint8 tiff
    channel list: R, G, B
    tile size: 512 x 512
    oiio:BitsPerSample: 8
    ImageDescription: "level=3 mag=5.5 quality=80"
    Orientation: 1 (normal)
    Software: "Philips DP v1.0"
    tiff:PhotometricInterpretation: 6
    tiff:ColorSpace: "YCbCr"
    tiff:PlanarConfiguration: 1
    planarconfig: "contig"
    tiff:Compression: 7
    compression: "jpeg"
    tiff:subfiletype: 1
 subimage  4: 5632 x 5632, 3 channel, uint8 tiff
    channel list: R, G, B
    tile size: 512 x 512
    oiio:BitsPerSample: 8
    ImageDescription: "level=4 mag=2.75 quality=80"
    Orientation: 1 (normal)
    Software: "Philips DP v1.0"
    tiff:PhotometricInterpretation: 6
    tiff:ColorSpace: "YCbCr"
    tiff:PlanarConfiguration: 1
    planarconfig: "contig"
    tiff:Compression: 7
    compression: "jpeg"
    tiff:subfiletype: 1
 subimage  5: 3072 x 3072, 3 channel, uint8 tiff
    channel list: R, G, B
    tile size: 512 x 512
    oiio:BitsPerSample: 8
    ImageDescription: "level=5 mag=1.375 quality=80"
    Orientation: 1 (normal)
    Software: "Philips DP v1.0"
    tiff:PhotometricInterpretation: 6
    tiff:ColorSpace: "YCbCr"
    tiff:PlanarConfiguration: 1
    planarconfig: "contig"
    tiff:Compression: 7
    compression: "jpeg"
    tiff:subfiletype: 1
 subimage  6: 1536 x 1536, 3 channel, uint8 tiff
    channel list: R, G, B
    tile size: 512 x 512
    oiio:BitsPerSample: 8
    ImageDescription: "level=6 mag=0.6875 quality=80"
    Orientation: 1 (normal)
    Software: "Philips DP v1.0"
    tiff:PhotometricInterpretation: 6
    tiff:ColorSpace: "YCbCr"
    tiff:PlanarConfiguration: 1
    planarconfig: "contig"
    tiff:Compression: 7
    compression: "jpeg"
    tiff:subfiletype: 1
 subimage  7: 1024 x 1024, 3 channel, uint8 tiff
    channel list: R, G, B
    tile size: 512 x 512
    oiio:BitsPerSample: 8
    ImageDescription: "level=7 mag=0.34375 quality=80"
    Orientation: 1 (normal)
    Software: "Philips DP v1.0"
    tiff:PhotometricInterpretation: 6
    tiff:ColorSpace: "YCbCr"
    tiff:PlanarConfiguration: 1
    planarconfig: "contig"
    tiff:Compression: 7
    compression: "jpeg"
    tiff:subfiletype: 1
 subimage  8:  512 x  512, 3 channel, uint8 tiff
    channel list: R, G, B
    tile size: 512 x 512
    oiio:BitsPerSample: 8
    ImageDescription: "level=8 mag=0.171875 quality=80"
    Orientation: 1 (normal)
    Software: "Philips DP v1.0"
    tiff:PhotometricInterpretation: 6
    tiff:ColorSpace: "YCbCr"
    tiff:PlanarConfiguration: 1
    planarconfig: "contig"
    tiff:Compression: 7
    compression: "jpeg"
    tiff:subfiletype: 1

**Comment by ShanQiong** [comment]
it work well really for other subimage

**Comment by lgritz** [comment]
Well, your info shows it's tiled for all subimages.

I have no idea why it works ever. The only thing I can think of is, maybe deep in the underlying TIFF library, perhaps it is trying its best to allow TIFFReadScanline to sort of do the right thing for tiled files by buffering... but that code has some kind of bug and doesn't work once the images are above some really huge width?

I don't even know if libtiff tries to do such scanline-for-tile emulation. I'm just speculating.

But I will write myself a note to add the proper error messages in our TIFF module to fail when a tiled file is attempting to read by scanlines or vice versa.

Closing because you've got a solution figured out and I don't think this is really a bug.

**Comment by ShanQiong** [comment]
Thanks for your reply
