### ISSUE TITLE
[BUG] iinfo not returning a non-zero return code

### ISSUE THREAD

**Issue by jdietrch** [OpenImageIO/oiio#2506]
**Describe the bug**
oiiotool --info returns a non-zero return code when run on a file it doesn't recognize. This is what I would expect. However, iinfo returns zero when run on the same file.

**To Reproduce**
(The shell is bash, and the command echo $? shows the return value of the most recent command.)
```
jdietrch@saturn:~/a$ cat abc.txt
This is a text file.
jdietrch@saturn:~/a$ oiiotool --info abc.txt
oiiotool ERROR: read : OpenImageIO could not find a format reader for "abc.txt". Is it a file format that OpenImageIO doesn't know about?

Full command line was:
> oiiotool --info abc.txt
jdietrch@saturn:~/a$ echo $?
255
jdietrch@saturn:~/a$ iinfo abc.txt
iinfo ERROR: OpenImageIO could not find a format reader for "abc.txt". Is it a file format that OpenImageIO doesn't know about?

jdietrch@saturn:~/a$ echo $?
0
jdietrch@saturn:~/a$
```
**Expected behavior**
Along with the error message, I expect iinfo to return a non-zero return code as oiiotool --info does.

**Evidence**
See above.

**Platform information:**
I am running Debian testing and have version  2.1.11.2~dfsg0-3 of the openimageio-tools package installed.

Let me know if I can provide any further information.

Thank you,
James Dietrich

**Comment by lgritz** [comment]
Quite right. Fix coming.
