### ISSUE TITLE
[BUG] ImageInput::open causes uncaught exception in macOS sandbox environment

### ISSUE THREAD

**Issue by gregcotten** [OpenImageIO/oiio#2517]
OIIO Version 2.1.9.0 running in sandbox on macOS. I would usually just forgo the sandboxing altogether, but I'm making a QuickLook plugin that **requires** it.

Essentially, the plugin becomes authorized to read a file by the user requesting to QuickLook a file, and eventually that absolute file path gets passed to ```ImageInput::open```. I'm not exactly sure why opening from an absolute file path would necessitate the creation of a ```directory_iterator```, but I am not intimately familiar with the underworking of OIIO.

```
terminating with uncaught exception of type boost::filesystem::filesystem_error: boost::filesystem::directory_iterator::construct: Operation not permitted
```

Specifically a uncaught exception occurs when boost's ```directory_iterator``` is constructed. I know it's somewhere in [filesystem.hpp](https://github.com/OpenImageIO/oiio/blob/605ff8035a556f8f06ccabfb599ea99e86d3e5e9/src/libutil/filesystem.cpp) as that is the only place where it gets called, but I'm not compiling from OIIO source so I don't get a fun stack trace to narrow it down. That's the next step, just wanted to put this on the radar!

**Comment by lgritz** [comment]
I'm not sure why this is hitting an exception for you, but I think I do see where an exception can go uncaught. I will have a fix shortly.

**Comment by lgritz** [comment]
Proposed solution in #2522

**Comment by gregcotten** [comment]
Looks like that would solve the exception! Now to see if ImageInput::open can actually read a sandbox-scoped file path...
