### ISSUE TITLE
[HELP] When I try to build from source on CentOS7 I get an issue with pybind11

### ISSUE THREAD

**Issue by shdwdln** [OpenImageIO/oiio#2519]
When I try to configure the project with cmake I get the following error:

CMake Warning at src/cmake/externalpackages.cmake:91 (find_package):
  Could not find a configuration file for package "pybind11" that is
  compatible with requested version "2.4.2".

  The following configuration files were considered but not accepted:

    /usr/local/share/cmake/pybind11/pybind11Config.cmake, version: 2.4.dev4

Call Stack (most recent call first):
  src/python/CMakeLists.txt:7 (checked_find_package)

pybind11 library not found
    Try setting pybind11_ROOT ? 
    Maybe this will help:  src/build-scripts/build_pybind11.bash 
CMake Error at src/cmake/externalpackages.cmake:127 (message):
mpybind11 is required, aborting.
Call Stack (most recent call first):
  src/python/CMakeLists.txt:7 (checked_find_package)

What am I missing here?

**PLEASE DO NOT ASK USAGE QUESTIONS USING GITHUB "ISSUES"**

If you are pretty sure that you have identified a **BUG** in OpenImageIO,
please file a [bug report issue](https://github.com/OpenImageIO/oiio/issues/new?template=bug_report.md).

But if you are just asking a question:
* How do I...?
* I need help with...
* Am I doing something wrong?
* I can't build OpenImageIO

For anything of this nature, the best way to get help using OpenImageIO is
to ask a question on the [oiio-dev developer mail list](http://lists.openimageio.org/listinfo.cgi/oiio-dev-openimageio.org).

The [documentation](https://openimageio.readthedocs.org)
is pretty comprehensive, so please check there first; you may find the answer
more quickly than you can get your question answered on the mail list.

**Comment by shdwdln** [comment]
I did run this:
`src/build-scripts/build_pybind11.bash`

and then set the 
pybind11_DIR to the new location
`/home/x/_DEV/oiio_3.17.20/oiio/ext/dist/share/cmake/pybind11`

now it is saying:
`CMake Error at ext/dist/share/cmake/pybind11/pybind11Config.cmake:108 (include):
  include could not find load file:

    /home/dillon/_DEV/oiio_3.17.20/oiio/ext/dist/share/cmake/pybind11/pybind11Targets.cmake
Call Stack (most recent call first):
  src/cmake/externalpackages.cmake:91 (find_package)
  src/python/CMakeLists.txt:7 (checked_find_package)


CMake Error at ext/dist/share/cmake/pybind11/pybind11Config.cmake:111 (set_property):
  set_property could not find TARGET pybind11::pybind11.  Perhaps it has not
  yet been created.
Call Stack (most recent call first):
  src/cmake/externalpackages.cmake:91 (find_package)
  src/python/CMakeLists.txt:7 (checked_find_package)


CMake Error at ext/dist/share/cmake/pybind11/pybind11Config.cmake:112 (set_property):
  set_property could not find TARGET pybind11::embed.  Perhaps it has not yet
  been created.
Call Stack (most recent call first):
  src/cmake/externalpackages.cmake:91 (find_package)
  src/python/CMakeLists.txt:7 (checked_find_package)


CMake Error at ext/dist/share/cmake/pybind11/pybind11Config.cmake:120 (set_property):
  set_property could not find TARGET pybind11::pybind11.  Perhaps it has not
  yet been created.
Call Stack (most recent call first):
  src/cmake/externalpackages.cmake:91 (find_package)
  src/python/CMakeLists.txt:7 (checked_find_package)


CMake Error at ext/dist/share/cmake/pybind11/pybind11Config.cmake:123 (get_property):
  get_property could not find TARGET pybind11::pybind11.  Perhaps it has not
  yet been created.
Call Stack (most recent call first):
  src/cmake/externalpackages.cmake:91 (find_package)
  src/python/CMakeLists.txt:7 (checked_find_package)


CMake Error at ext/dist/share/cmake/pybind11/pybind11Config.cmake:124 (get_property):
  get_property could not find TARGET pybind11::module.  Perhaps it has not
  yet been created.
Call Stack (most recent call first):
  src/cmake/externalpackages.cmake:91 (find_package)
  src/python/CMakeLists.txt:7 (checked_find_package)


[32mFound pybind11 2.4.3 [m
`

**Comment by shdwdln** [comment]
So I opened the file:
`/home/x/_DEV/oiio_3.17.20/oiio/ext/pybind11/CMakeLists.txt`
and only added the line
`message(STATUS "PYBIND11_EXPORT_NAME ${PYBIND11_EXPORT_NAME}")`
after the line
`set(PYBIND11_EXPORT_NAME "${PROJECT_NAME}Targets")`
and then ran make && make install
and it said every file was up to date except:
`
-- Up-to-date: /home/x/_DEV/oiio_3.17.20/oiio/ext/dist/include/pybind11/pybind11.h
-- Up-to-date: /home/x/_DEV/oiio_3.17.20/oiio/ext/dist/include/pybind11/pytypes.h
-- Up-to-date: /home/x/_DEV/oiio_3.17.20/oiio/ext/dist/include/pybind11/stl_bind.h
-- Up-to-date: /home/x/_DEV/oiio_3.17.20/oiio/ext/dist/share/cmake/pybind11/pybind11Config.cmake
-- Installing: /home/x/_DEV/oiio_3.17.20/oiio/ext/dist/share/cmake/pybind11/pybind11ConfigVersion.cmake
-- Up-to-date: /home/x/_DEV/oiio_3.17.20/oiio/ext/dist/share/cmake/pybind11/FindPythonLibsNew.cmake
-- Up-to-date: /home/x/_DEV/oiio_3.17.20/oiio/ext/dist/share/cmake/pybind11/pybind11Tools.cmake
-- Installing: /home/x/_DEV/oiio_3.17.20/oiio/ext/dist/share/cmake/pybind11/pybind11Targets.cmake
`
then the oiio configure works...

Like wuuuuuut -____-

**Comment by hobbes1069** [comment]
The OIIO mailing list is a much better place for these types of questions (as the template points out). What version of OIIO do you need? I maintain OIIO for Fedora EPEL and built the latest I could...

https://fedoraproject.org/wiki/EPEL

**Comment by lgritz** [comment]
I can't quite tell which version of OIIO you have, or which version of pybind11 you had installed.

I think your pybind11 is too old, as the message said. It needs >= 2.4.2. Your message indicates "2.4.dev4", but that's not any official release of pybind at all.

Then you tried to install your own, but you said "pybind11_DIR to the new location". Did you mean "pybind11_ROOT"? Because nothing is going to look at pybind11_DIR.

It sorta seems like maybe the build_pybind11 didn't work and you/it didn't notice.

I'm curious about what happens if you put `set -ex` near the top of build_pybind11.bash and then ran it from scratch (after removing all of ext). Does it appear to complete, or did it hit an error that we just didn't notice before?

**Comment by shdwdln** [comment]
The pybind11 version was just pulled down from github yesterday so it shouldn't be old. I did however use the suggested output of running:
`src/build-scripts/build_pybind11.bash`

... and it downloaded a version that appears to be compatible with this latest oiio.

Im really just trying to build a version of this for the python api.
I love the whl version this guy built but it is only for windows:
`https://www.lfd.uci.edu/~gohlke/pythonlibs/`

but now when I build I get this message:
`

[ 85%] Built target iv_autogen
[ 86%] Building CXX object src/python/CMakeFiles/PyOpenImageIO.dir/py_deepdata.cpp.o
[ 86%] Linking CXX executable ../../bin/imagecache_test
[ 86%] Linking CXX executable ../../bin/idiff
/usr/bin/ld: warning: libwebp.so.7, needed by /usr/lib64/libavcodec.so, may conflict with libwebp.so.4
/usr/bin/ld: warning: libwebp.so.7, needed by /usr/lib64/libavcodec.so, may conflict with libwebp.so.4
/usr/bin/ld: warning: libx265.so.169, needed by /usr/local/lib/libheif.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: /usr/local/lib64/libofstd.a(ofchrenc.cc.o): undefined reference to symbol 'ucnv_getName_50'
//usr/lib64/libicuuc.so.50: error adding symbols: DSO missing from command line
`

**Comment by shdwdln** [comment]
also, the packages in `http://mirrors.syringanetworks.net/fedora-epel/7/x86_64/Packages/o/`
are pretty outdated going back to 2016.

OpenColorIO-1.0.9-4.el7.x86_64.rpm                 (05-Oct-2016 13:20    410K)
OpenColorIO-devel-1.0.9-4.el7.x86_64.rpm       (05-Oct-2016 13:20     22K)
OpenColorIO-doc-1.0.9-4.el7.noarch.rpm           (05-Oct-2016 13:20    792K)
OpenColorIO-tools-1.0.9-4.el7.x86_64.rpm        (05-Oct-2016 13:20     99K)
OpenImageIO-1.5.24-3.el7.1.x86_64.rpm           (27-Nov-2016 00:14      2M)
OpenImageIO-devel-1.5.24-3.el7.1.x86_64.rpm (27-Nov-2016 00:14      2M)
OpenImageIO-iv-1.5.24-3.el7.1.x86_64.rpm       (27-Nov-2016 00:14     89K)
OpenImageIO-utils-1.5.24-3.el7.1.x86_64.rpm   (27-Nov-2016 00:14    266K)

**Comment by hobbes1069** [comment]
So is CentOS 7 :)

**Comment by lgritz** [comment]
Nonetheless, CentOS 7 is the standard setup in large VFX studios.

**Comment by hobbes1069** [comment]
In that case, the easiest (and I mean that as a relative term) would be to setup a COPR[1] to provide dependent packages and newer versions of the old packages CentOS provides. That way the most people can benefit from the work.

**Comment by lgritz** [comment]
How are you launching the build? Are you using the "make" wrapper, or invoking CMake directly?

Can you start a completely fresh build, with VERBOSE=1, and attach the full build output here so we can try to figure out what's going wrong?

Also, if you know that there are any formats that you don't need, you can also build with ENABLE_formatname=0 and it will skip it, maybe the things breaking at the moment are only needed for file formats you don't particularly need?

**Comment by shdwdln** [comment]
Ok I will do that! Thanks for your help

**Comment by lgritz** [comment]
No follow-up, I'm going to assume that the problem has been solved. Please re-open if you are continuing to have trouble getting a build with pybind11.
