### ISSUE TITLE
[HELP] Stitching deep EXRs

### ISSUE THREAD

**Issue by Sosoyan** [OpenImageIO/oiio#2536]
I'm using v1.6.17 ImageBufAlgo.add() to stitch tile rendered images together. It works fine with RGBAs, but in case of Deep what I'm getting is an empty file without any errors. 

Can you confirm whether this is expected or perhaps has fixed in the later versions?

**Comment by lgritz** [comment]
"Add" doesn't work for two deep images (though you can add an image and a constant -- it just adds to every sample in the image).

Maybe "paste" is a better approach?

But as an aside, v1.6 is 2016, four major releases ago. I don't trust the deep handling that far back.

**Comment by lgritz** [comment]
No response, and I think I answered the question. Closing.
