### ISSUE TITLE
[BUILD] latest 2.1.13.0 release fails to build

### ISSUE THREAD

**Issue by david-geiger** [OpenImageIO/oiio#2538]
Hi,

I tried on Mageia Cauldron to build latest 2.1.13.0 release but it fails to build:

> In file included from /home/iurt/rpmbuild/BUILD/oiio-Release-2.1.13.0/src/include/OpenImageIO/tiffutils.h:20,
                 from /home/iurt/rpmbuild/BUILD/oiio-Release-2.1.13.0/src/libOpenImageIO/exif.cpp:19:
/home/iurt/rpmbuild/BUILD/oiio-Release-2.1.13.0/src/libOpenImageIO/exif.cpp:532:5: error: expected identifier before numeric constant
  532 |     GPSTAG_VERSIONID         = 0,
      |     ^~~~~~~~~~~~~~~~
/home/iurt/rpmbuild/BUILD/oiio-Release-2.1.13.0/src/libOpenImageIO/exif.cpp:532:5: error: expected '}' before numeric constant
/home/iurt/rpmbuild/BUILD/oiio-Release-2.1.13.0/src/libOpenImageIO/exif.cpp:531:13: note: to match this '{'
  531 | enum GPSTag {
      |             ^
In file included from /home/iurt/rpmbuild/BUILD/oiio-Release-2.1.13.0/src/include/OpenImageIO/tiffutils.h:20,
                 from /home/iurt/rpmbuild/BUILD/oiio-Release-2.1.13.0/src/libOpenImageIO/exif.cpp:19:
/home/iurt/rpmbuild/BUILD/oiio-Release-2.1.13.0/src/libOpenImageIO/exif.cpp:532:5: error: expected unqualified-id before numeric constant
  532 |     GPSTAG_VERSIONID         = 0,

Attached the full build log:
[build.0.20200402145302.log](https://github.com/OpenImageIO/oiio/files/4421881/build.0.20200402145302.log)

Regards,
David

**Comment by lgritz** [comment]
Can you please try an experiment for me?

Edit src/libOpenImageIO/exif.cpp, and at line 530 (right before the definition of the GPSTag enum), please add this:

```
#ifdef GPSTAG_VERSIONID
#error "Oh no, GPSTAG_VERSIONID is already defined!"
#endif
```

Does that turn up anything?

**Comment by david-geiger** [comment]
So with your proposal experiment now it says: 

> /home/iurt/rpmbuild/BUILD/oiio-Release-2.1.13.0/src/libOpenImageIO/exif.cpp:530:2: error: #error "Oh no, GPSTAG_VERSIONID is already defined!"
  530 | #error "Oh no, GPSTAG_VERSIONID is already defined!"

[build.0.20200402161108.log](https://github.com/OpenImageIO/oiio/files/4422226/build.0.20200402161108.log)

**Comment by lgritz** [comment]
Interesting! I wonder which header is defining that?

OK, here's what I'd like you to try next:

* Delete those lines that you just added.

* For that one cpp file (that's the only place we use this), please search and replace all "GPSTAG_" to "OIIO_GPSTAG_".

**Comment by wally-mageia** [comment]
> Interesting! I wonder which header is defining that?

It's the latest git snapshot of libtiff.

```
$ grep -rl GPSTAG_VERSIONID /usr/include/
/usr/include/tiff.h

$ rpm -qa lib64tiff-devel
lib64tiff-devel-4.1.0-2.git20200329.1.mga8
```

**Comment by lgritz** [comment]
Aha, great.

I have tiff 4.1.0, but maybe you have an even more recent snapshot?

I will take a look at what libtiff has done and prepare an OIIO patch that will fix this.

**Comment by david-geiger** [comment]
Confirmed that build is now fixed, thanks.
