### ISSUE TITLE
[FEATURE REQUEST] Generic IOProxy JPEG reading

### ISSUE THREAD

**Issue by etsach** [OpenImageIO/oiio#2545]
**Is your feature request related to a problem? Please describe.**
JpegInput does not support generic IOProxy reading, only IOFile and IOMemReader

**Describe the solution you'd like**
Patch provided, adds support for generic IOProxy in JpegInput

[jpeg-reader-ioproxy.diff.zip](https://github.com/OpenImageIO/oiio/files/4445016/jpeg-reader-ioproxy.diff.zip)

**Comment by lgritz** [comment]
Can you please submit the patch as a PR?

**Comment by lgritz** [comment]
Hi, just checking back on this.. can you turn the patch you attached into a proper PR so we can review it and merge if everything is satisfactory?

**Comment by lgritz** [comment]
Closing, this was implemented quite a while back already.
