### ISSUE TITLE
[BUG] Generated CMake config files contain absolute paths

### ISSUE THREAD

**Issue by johngladp** [OpenImageIO/oiio#2559]
When building OIIO the generated OpenImageIOConfig.cmake and OpenImageIOTargets.cmake files contain absolute hardcoded paths.  This prevents the cmake install output from being relocated anywhere other than that absolute file location.  This prevents a built OIIO from being packaged and hosted on a packaging server as the config file points to the build output location on the build server not the location the package is unpacked.

**Expected behavior**
OpenImageIOConfig.cmake and OpenImageIOTargets.cmake are expected to contain relative paths.

**Evidence**
Generated OpenImageIOConfig.cmake and OpenImageIOTargets.cmake contain absolute paths.
Config.cmake.in uses the variable CMAKE_INSTALL_FULL_INCLUDEDIR and CMAKE_INSTALL_FULL_LIBDIR which expand to absolute paths.  This is a large component part of the issue.  Usage of these variables is described as "not sufficient" in the following cmake documentation:
https://cmake.org/cmake/help/latest/module/CMakePackageConfigHelpers.html

**Platform information:**
 - OIIO branch/version: 2.2.0
 - OS: Windows
 - C++ compiler: MSVC from VS2019 16.5.2
 - Any non-default build flags when you build OIIO: 
BUILD_SHARED_LIBS:FALSE
LINKSTATIC:TRUE

**Comment by merwaaan** [comment]
Can confirm that the absolute paths in OpenImageIOConfig.cmake and OpenImageIOTargets.cmake make it impossible to use find_package() for relocated CMake output (moved to another location, downloaded from a build server, etc).

**Comment by lgritz** [comment]
Thanks for the tip, I'll read over that page and try to figure out how to fix.
Though if either of you know exactly what to do, feel free to make a PR that directly fixes the problem.

**Comment by merwaaan** [comment]
@lgritz I got it to work by following that documentation page. I'll make a PR.

**Comment by p12tic** [comment]
@lgritz I think this issue should be closed as #3302 has been merged.
