### ISSUE TITLE
[BUG] IplImage references in imagealgobuf.h break in the absence of OpenCV

### ISSUE THREAD

**Issue by dankamongmen** [OpenImageIO/oiio#2566]
**Describe the bug**
Background information is available at [Notcurses #541](https://github.com/dankamongmen/notcurses/issues/541). I was writing some code against OIIO 
as shipped in Debian Unstable's 2.1.13.0~dfsg0, and Fedora 32's 2.1.13.0-2.fc32. I had the same result on both (note that neither is built against OpenCV). My code `#include`d the following:

```c
#include <OpenImageIO/filter.h>
#include <OpenImageIO/version.h>
#include <OpenImageIO/imageio.h>
#include <OpenImageIO/imagebuf.h>
#include <OpenImageIO/imagebufalgo.h>
```

and linked `-lOpenImageIO`, following the various suggestions of `pkg-config`. No matter what I did, I got the following linker failure:

```
/usr/bin/ld: libnotcurses.so.1.3.2: undefined reference to `OpenImageIO_v2_1::ImageBufAlgo::from_IplImage(IplImage const*, OpenImageIO_v2_1::TypeDesc)'
collect2: error: ld returned 1 exit status
```

I had no direct calls to this, but there are `inline` functions in `imagealgobuf.h` which reference them. Here's the problem: at the top of this file, you have

```c
#if !defined(__OPENCV_CORE_TYPES_H__) && !defined(OPENCV_CORE_TYPES_H)
struct IplImage;  // Forward declaration; used by Intel Image lib & OpenCV
```

and later you have

```c
ImageBuf OIIO_API from_IplImage (const IplImage *ipl,
inline bool from_IplImage (ImageBuf &dst, const IplImage *ipl,
OIIO_API IplImage* to_IplImage (const ImageBuf &src);
```

If OpenCV headers (in particular, `<opencv2/core/types_c.h>`) are `#include`d, this compiles up just fine. In their absence, unadorned `IplImage` is a distinct type from `struct IplImage`. They mangle to:

`_ZN16OpenImageIO_v2_112ImageBufAlgo13from_IplImageEPK8IplImageNS_8TypeDescE`

and

`_ZN16OpenImageIO_v2_112ImageBufAlgo13from_IplImageEPK9_IplImageNS_8TypeDescE`

Note `EPK8` v `EPK9`. Hence the missing symbol; hence my failed link.

I verified that changing these to `struct IplImage*`, rebuilding OIIO, reinstalling OIIO, and rebuilding my program worked. The problem with that, of course, is that if OpenCV **is** present, you'll draw a "referenced typedef'd type with `struct`" complaint from the compiler.

I submit the following (I have it in a branch, ready to PR):

```c
#if !defined(__OPENCV_CORE_TYPES_H__) && !defined(OPENCV_CORE_TYPES_H)
struct IplImage;
#define IplImage struct IplImage
```

**To Reproduce**
1. Install OpenImageIO-devel on Fedora 32, or libopenimageio-dev on Debian Unstable
2. Ensure OpenCV is **not** installed
3. Write code using IBA
4. Try and fail to link it

**Expected behavior**
My program links.

**Evidence**
See above. I'm happy to provide more information.

**Platform information:**
 - OIIO branch/version: 2.1.13
 - OS: Fedora 32, Debian Unstable
 - C++ compiler: g++ 9.3.0
 - Any non-default build flags when you build OIIO:

https://github.com/dankamongmen/oiio/tree/dankamongmen/opencv-struct-link

**Comment by lgritz** [comment]
The IplImage functions are all deprecated anyway. Maybe the simplest solution is just to enclose the declarations inside

    #if defined(__OPENCV_CORE_TYPES_H__) || defined(OPENCV_CORE_TYPES_H)

so that even the declarations are not seen by the compiler at all unless OpenCV headers are included first?

Let me try this and submit a PR for you to try.

**Comment by dankamongmen** [comment]
That will certainly also work. I was just trying not to spread `#ifdef`s through the code.

Yeah, they're deprecated, but due to the inline, you get hit with this even if you're not explicitly using them :(. Thanks for looking into this! However it gets fixed is fine with me :).

**Comment by lgritz** [comment]
OK, take a look at #2568 as proposed solution.

I wonder why there had been no problems before. Generally, if nobody calls the inline function, it will not be instantiated, and therefore no linkage would be required. I wonder if there is something odd in your other project (maybe a particular set of compiler flags?) that was causing it to need to fully instantiate that inline function even if not called?

**Comment by dankamongmen** [comment]
I'll grab that and run it through, but it looks sound. And yes, you are correct; I am providing `-fkeep-inline-functions` to g++. That explains why it's breaking, though I'd say (and I think you agree) that it's desirable to work even with said flag. Both your solution and my proposed one achieve that goal. Thanks for looking into this. I'll have verification for you shortly--feel free to assign me the PR for review (or not to).

**Comment by dankamongmen** [comment]
(btw, not that you asked, but I'm using `-fkeep-inline-functions` because part of my contracted API is implemented as inline functions, and without them present in the generated library, they're not available to wrappers in other languages. i saw you starred notcurses; thanks!)

**Comment by dankamongmen** [comment]
I confirm a good fix with your PR.

**Comment by lgritz** [comment]
Yes, I totally agree that this ought to work with `-fkeep-inline-functions`. I never had need to use that, and I guess nobody else did, so this went unnoticed. But I do see that it's technically a bug.

notcurses looks very interesting!

**Comment by dankamongmen** [comment]
Your PR looks solid. I'm liking OIIO -- i was able to port my multimedia engine over to it (from ffmpeg) in a day, which means notcurses has multimedia in Fedora Core (which doesn't have ffmpeg, but does have OIIO). I'm running into some performance problems with video, but that's surely due to my ignorance.

**Comment by lgritz** [comment]
Neato. 

I'll be honest with you, OIIO is designed for still images, with allowances for file formats that support multiple "subimages" per file. Video has been sorta crammed in by making a video look to OIIO like it's just a multi-subimage image file, but with LOTS of subimages. For video, it's meant to "work", but not to perform like you would want a true video reader like ffmpeg. (It also doesn't understand audio at all... like I said, it was not designed for video except for fairly limited use cases like splitting a shot into individual frames as separate files, but not as a reader for a high quality media player.)

Maybe that's not what you were referring to, but I thought I'd warn you since you mentioned performance and video.
