### ISSUE TITLE
[FEATURE REQUEST] LibRaw 0.20

### ISSUE THREAD

**Issue by limburgher** [OpenImageIO/oiio#2577]
**Is your feature request related to a problem? Please describe.**
Currently oiio doesn't build out of the box on the newly-released LibRaw 0.20 Beta 1.

**Describe the solution you'd like**
There are some deprecated methods, and some data types have changed. I started a patch but the changes required seem to be non-trivial

**Describe alternatives you've considered**
0.19.x will be EOL at some point...

**Additional context**
I can provide my patch so far at your request.

**Comment by lgritz** [comment]
Which version of OIIO?

**Comment by limburgher** [comment]
2.1.14.0.

**Comment by lgritz** [comment]
If you can do so easily, can you just try the current master and see if that builds? I remember doing some work on this recently. If all it takes is a backport of what I already did in master, I can do that right away.

**Comment by limburgher** [comment]
It builds, both freshly checked out and tarred up and put through the RPM build process (I'm the LibRaw Fedora RPM maintainer, for context). Do you want to backport what's needed and cut a release, or something else? I see the soname has changed.

**Comment by lgritz** [comment]
I'll backport. Do you need a release right away?

I tested on my end as well, and it looks like I get a clean build but one of the tests fails (meaning the image is different). I'll look into this, might need a little tweaking before I backport.

**Comment by limburgher** [comment]
It's not super urgent. Next week or whatever is fine. :)

**Comment by lgritz** [comment]
I usually cut official tagged released on the first of each month, but if somebody really needs it, I can do any time.

I do want to track down the test failure first, though.

**Comment by limburgher** [comment]
Cool, let me know when you've fixed the test and released something you're happy with.

**Comment by lgritz** [comment]
Gwyn, not necessarily related to this fix, but can I ask your opinion... what's the oldest LibRaw release that you think is reasonable for us to continue supporting and testing against? (Keeping in mind that many people who build OIIO from source are relying on a LTS Linux distro of some sort, so the dependencies may be a bit old.)

**Comment by limburgher** [comment]
EPEL for EL-6 has 0.16.x, so that's probably a good indicator.

**Comment by lgritz** [comment]
Tagged Release-2.1.15.0, which should address this problem.

**Comment by limburgher** [comment]
Thank you!
