### ISSUE TITLE
[FEATURE REQUEST] Export PLUGIN_SEARCH_PATH to cmake config

### ISSUE THREAD

**Issue by StefanBruens** [OpenImageIO/oiio#2583]
With #1056, it is possible to specify a default search location, but it would be nice if a plugin build system could get this path from e.g. OpenImageIOConfig.cmake

**Comment by lgritz** [comment]
Like this?  #2584

**Comment by StefanBruens** [comment]
Yes, mostly:
```
set_and_check (OpenImageIO_INCLUDE_DIR "/usr/include")
set_and_check (OpenImageIO_INCLUDES    "/usr/include")
set_and_check (OpenImageIO_LIB_DIR     "/usr/lib64")
set_and_check (PLUGIN_SEARCH_PATH         "/usr/lib64/OpenImageIO-2.1")

```
The variable should be prefixed with `OpenImageIO_` as well, otherwise we risk name clashes.

**Comment by lgritz** [comment]
Quite right. Amended.
