### ISSUE TITLE
OpenImageIo undefined references

### ISSUE THREAD

**Issue by FaraoniLuca** [OpenImageIO/oiio#2585]
Hi, I've downloaded and compliled OpenImageIo, in linux. However, when I try to use it i got the following error:

(libOpenImageIo.a)(socketoutout.cpp.o): undefined reference to symbol 'pthread_join@GLIBC_2.2.5'

Now if I add -pthread as flag with CMake, I'll pass the error but this new one occur

(libOpenImageIo.a)(plugin.cpp.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'

If now i add -ldl as flag, the error persist and no way to compile.

**Comment by hobbes1069** [comment]
Basic issues are better discussed on the mailing list, not in github. Obviously thousands of people are compiling OIIO without issue so it's likely for the problem to be on your end, but you've provided no details as to your build environment, not even a distro, gcc compiler version, etc. I don't think it's possible to help you with the information you've given us.

**Comment by lgritz** [comment]
I don' think I ever saw a follow-up on the mail list, and there isn't enough information on this ticket to help with. (Didn't even say which architecture or OS distro they're having trouble building on, or supply build output.)

Closing. Please re-open if there's still trouble, and include full verbose build log.
