### ISSUE TITLE
[BUG] crash in RLAInput

### ISSUE THREAD

**Issue by zavinator** [OpenImageIO/oiio#2599]
**Describe the bug**
OIIO crashes in rlainput.cpp when trying to load an alembic file. I know that the library is not suited for loading alembic files (the user has choosen it by an accident). Maybe it can be a general problem in the RLA loader...

**To Reproduce**
1. Open the attached file (OIIO::ImageInput::open)
2. It crashes in rlainput.cpp

**Expected behavior**
Return an error without crash.

**Evidence**
[cube.zip](https://github.com/OpenImageIO/oiio/files/4728548/cube.zip)

**Platform information:**
 - OIIO branch/version: 2.1.15
 - OS: Win10 x64
 - C++ compiler: VS2019
 - Any non-default build flags when you build OIIO:

**Comment by lgritz** [comment]
Thanks for the repro case. On it!

**Comment by lgritz** [comment]
Proposed fix in #2600

**Comment by lgritz** [comment]
Thanks for the example. And it turns out that this bug (or at least, another instance of rla crashing when accidentally fed a non-image input) was reported at my work, and I had never quite gotten around to repro and fix it. So this was a good opportunity.
