### ISSUE TITLE
[HELP] Understanding how to set up the Python Bindings

### ISSUE THREAD

**Issue by Zelkanok** [OpenImageIO/oiio#2601]
I have successfully built and installed OpenImageIO through vcpkg, and I'm currently attempting to set up the python bindings. So far, I've followed the instructions on https://openimageio.readthedocs.io/en/release-2.1.16.0/pythonbindings.html, and have included the path to the python subdirectory in PYTHONPATH, but I still cannot import the module into my script.

* Windows 10
* Python 3.7

Sorry if this seems simple...but I'm not exactly sure what else to go off of in the documentation.

**Comment by lgritz** [comment]
The python subdirectory got built for sure, you can see the dll there?

What exactly happens when you try to import the module? Do you get some kind of exception or error message?

**Comment by Zelkanok** [comment]
Unfortunately, there are only py_*.cpp files, python_tests, pi_oiio.h, and CMakeLists.txt in my python directory. Just to clarify, the python subdirectory is usually under the src directory, correct?

When I'm trying to import the module, it says that there is "No module named 'OpenImageIO' ".

**Comment by lgritz** [comment]
I you see .cpp and .h, you are looking at the SOURCE area, not the area where anything has actually been built or installed.

**Comment by lgritz** [comment]
That should read, "IF you see..."

**Comment by lgritz** [comment]
So you seem to have not actually pointed your PYTHONPATH to the right directory. And... I'm still not sure we have established for sure that you built the python module in the first place.

**Comment by Zelkanok** [comment]
I've been following the vcpkg installation instructions, so I'll have to search a little bit more for where OpenImageIO is actually installed...

About whether or not I've built the python module, I assume that since I haven't been looking in the right location, that I haven't built it at all. Is there a guide on how to build the python module?

**Comment by lgritz** [comment]
When building with vcpkg, the python bindings are an optional extension. So you need to run

    vcpkg install openimageio[pybind11]:x64-windows

Other options can be seen by looking at the openmageio port file for vcpkg: https://github.com/microsoft/vcpkg/blob/master/ports/openimageio/portfile.cmake#L30

You may need to enable several options if you want all oiio features enabled. "tools" is another important one, if you want the command line tools.

**Comment by Zelkanok** [comment]
After running this installation, is the python module automatically built, or do I need to use pybind11 in some way to actually build the module?

**Comment by lgritz** [comment]
You need pybind11 present to actually build it, but vcpkg will take care of all of the dependency building for you.

**Comment by lgritz** [comment]
In other words, that command will build OIIO, including the python bindings, and any missing dependencies (like pybind11) will also be built in the process.

But you may still need to put the right path where it was installed into your PYTHONPATH.

**Comment by Zelkanok** [comment]
I'm sorry, I still haven't been able to find a python subdirectory with any dll...

Where would you usually find the python directory, or the installation directory for that matter? Would it be in a build directory (like cmake)?

**Comment by lgritz** [comment]
Did you ever resolve this?

I'm not a vcpkg expert, but I would expect it to go wherever all the other vcpkg stuff installs to.

**Comment by Zelkanok** [comment]
Unfortunately, I did not. Sorry that I didn't follow up, and I've discontinued working on the project involved with OpenImageIO. Sorry for all the hassle.
