### ISSUE TITLE
[DOC] Missing info about PNG compression

### ISSUE THREAD

**Issue by kslyre** [OpenImageIO/oiio#2603]
I noticed that the file size of my images is much smaller than the original if I save them in the PNG file format.

After some time I discovered, that PNG plugin uses attribute `png:compressionLevel` with `6` as default value. And there is no mention of this attribute in the documentation.

**Comment by lgritz** [comment]
Do you just want this documented? Or are you asking for a different behavior?

**Comment by lgritz** [comment]
Currently, we just always use PNG_COMPRESSION_TYPE_DEFAULT when writing PNG files.
I suspect that because we just use the default, that's why we didn't say anything special about it in the docs.

**Comment by kslyre** [comment]
I think it's worth to be documented. I'm not familiar with libpng, so for me, it was not obvious how to achieve lossless quality.

**Comment by lgritz** [comment]
It's always lossless.
