### ISSUE TITLE
Apple Silicon / arm64 compilation

### ISSUE THREAD

**Issue by gregcotten** [OpenImageIO/oiio#2625]
I just received a shiny new Apple Silicon DTK, and was thinking about how I might go about making a arm64 (or Universal Binary) build of OpenImageIO. Obviously there are going to be dependency issues here, though Apple is working on boost + OpenEXR Apple Silicon compilation.

I'm eager to get started trying to make this thing build on arm64, so if you could point me in the right direction / let me know what pitfalls I'm in for I would be very grateful!

**Comment by lgritz** [comment]
I'm pretty sure that the Debian folks routinely build OIIO for arm64. (Among other architectures: https://buildd.debian.org/status/package.php?p=openimageio&suite=sid )

I know they get a clean build, but I'm not sure they run the testsuite, so I can't swear that there aren't some minor bugs to be tracked down.

So it may be easy, just start by giving it a try, and I'll help you work through any issues that crop up that seem to be on our end.

**Comment by hobbes1069** [comment]
Fedora builds for both armv7hf and aarch64, you can poke around the build logs here:
https://koji.fedoraproject.org/koji/buildinfo?buildID=1530502

I've never had luck getting all the tests to pass so I don't run them for the package. I try again every couple of years though :)

**Comment by gregcotten** [comment]
Thanks for all this! I usually install dependencies of olio using homebrew - they have been [tracking arm64 compilation compatibility for the default formulae](https://github.com/Homebrew/brew/issues/7857). Cmake just now is able to be built on arm64 macOS. The behemoth oiio dependency That Shall Not Be Named (boost) is not compiling on arm64 yet, so I'm waiting on a patch before I can try building OIIO.

**Comment by lgritz** [comment]
Today I've been fooling around with restoring TravisCI runs and using it to run on Ubuntu Linux aarch64 (arm64). It's not exactly the same as the MacOS ARM (aka "Apple Silicon"), but it should still allow us to flush out any bugs on the OIIO side when building or running on that architecture.

I will update with a PR when I get it working.

The biggest problem I'm having at the moment is that on Ubuntu bionic, the standard cmake package is 3.10, which is too old for us, and the pre-built versions you can get from the Kitware GH release pages are only for Intel (no aarch64 binaries), so I'm having to build cmake 3.12 from source, which is chewing up most of my allotted 50 minutes of build time per run, and making the iteration time (as I make more and more of the build work properly) very long. Basically, I do a run, wait an hour, see what minor error or missing package caused it to fail, change two lines, repeat. If I could find aarch64 pre-built binaries of a CMake >= 3.12, I could shorten the iteration time by a factor of 4-5 probably.

Hopefully, also at some point soon, GitHub Actions CI will support either Linux aarch64 and/or directly support the Apple ARM, that would make things much easier in the long run.

**Comment by lgritz** [comment]
Trying to establish an aarch64 build in our CI: https://github.com/OpenImageIO/oiio/pull/2634
Still failing a few tests, but not sure if any of it is serious.

**Comment by lgritz** [comment]
I believe that an Apple Silicon build should just work as of the current master. PR #2739 (from Apple) should fix some particulars.

**Comment by gregcotten** [comment]
Any hint as to how to build for arm64 on an x86_64 Mac?
