### ISSUE TITLE
[BUG] load images from multiple threads

### ISSUE THREAD

**Issue by fabiencastan** [OpenImageIO/oiio#2630]
**Describe the bug**
When reading images from multiple threads, the process could get stuck if there are multiple RAW images.

**To Reproduce**
Load multiple RAW images from different threads.

**Expected behavior**
A way to ensure that the read of images can be done safely in a multi-threaded context.

**Evidence**
Here is the backtrace I get:
```
#0  0x00007fffe67234ed in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007fffe671edcb in _L_lock_883 () from /lib64/libpthread.so.0
#2  0x00007fffe671ec98 in pthread_mutex_lock () from /lib64/libpthread.so.0
#3  0x00007fffd7bfae79 in xmlInitializeGlobalState () from /lib64/libxml2.so.2
#4  0x00007fffd7bfbf03 in xmlGetGlobalState () from /lib64/libxml2.so.2
#5  0x00007fffd7bfb4d5 in __xmlDefaultSAXHandler () from /lib64/libxml2.so.2
#6  0x00007fffd7c55469 in xmlDefaultSAXHandlerInit () from /lib64/libxml2.so.2
#7  0x00007fffd7b88602 in xmlInitParserCtxt () from /lib64/libxml2.so.2
#8  0x00007fffd7b88dac in xmlNewParserCtxt () from /lib64/libxml2.so.2
#9  0x00007fffdaf6ed29 in CameraMetaDataLR::CameraMetaDataLR(char*, int) () from /path/to/libraw/0.19.5b/platform-linux/build-release/lib/libraw_r.so.19
#10 0x00007fffdaf6f207 in LibRaw::LibRaw(unsigned int) () from /path/to/libraw/0.19.5b/platform-linux/build-release/lib/libraw_r.so.19
#11 0x00007fffe61322f4 in OpenImageIO_v2_1::RawInput::open_raw(bool, std::string const&, OpenImageIO_v2_1::ImageSpec const&) () from /path/to/oiio/2.1.16/platform-linux/build-release/lib64/libOpenImageIO.so.2.1
#12 0x00007fffe6134e24 in OpenImageIO_v2_1::RawInput::open(std::string const&, OpenImageIO_v2_1::ImageSpec&, OpenImageIO_v2_1::ImageSpec const&) () from /path/to/oiio/2.1.16/platform-linux/build-release/lib64/libOpenImageIO.so.2.1
#13 0x00007fffe6134f27 in OpenImageIO_v2_1::RawInput::open(std::string const&, OpenImageIO_v2_1::ImageSpec&) () from /path/to/oiio/2.1.16/platform-linux/build-release/lib64/libOpenImageIO.so.2.1
#14 0x00007fffe5f9d650 in OpenImageIO_v2_1::ImageInput::create(std::string const&, bool, OpenImageIO_v2_1::ImageSpec const*, OpenImageIO_v2_1::string_view) () from /path/to/oiio/2.1.16/platform-linux/build-release/lib64/libOpenImageIO.so.2.1
#15 0x00007fffe5f84902 in OpenImageIO_v2_1::ImageInput::open(std::string const&, OpenImageIO_v2_1::ImageSpec const*) () from /path/to/oiio/2.1.16/platform-linux/build-release/lib64/libOpenImageIO.so.2.1
#16 0x0000000000414079 in aliceVision::image::readImageMetadata(std::string const&, int&, int&) ()
```

So it seems that libraw is calling a global initialization of the xml lib on the first image load. So if 2 RAW images are loaded in parallel, the process could randomly get stuck.
Is there a way to call an initialization of all the plugins in the main thread?

**Platform information:**
 - OIIO branch/version: 2.1.16
 - OS: CentOS 7.6.1810
 - C++ compiler: g++ 4.9
 - Any non-default build flags when you build OIIO: no

**Comment by lgritz** [comment]
Looks like it's happening in the setup for open, inside the LibRaw constructor. We can probably use a mutex to make sure we aren't doing that in two threads at once. Let me give it a stab.

**Comment by lgritz** [comment]
Can you try #2633 and see if that fixes for you?

**Comment by fabiencastan** [comment]
Thanks a lot for the very quick fix!
It seems to work, but as it is not fully repeatable it is difficult to be sure.
I will continue to test it intensively during the day and let you know if it has fully solved the problem.

**Comment by fabiencastan** [comment]
I didn't get a single error in all my work today, so that definitely solved the issue.
Thanks a lot.
