### ISSUE TITLE
[BUG] Incorrect output cutting a region out of a huge 16-bit single-channel TIFF

### ISSUE THREAD

**Issue by mike1158** [OpenImageIO/oiio#2656]
**Describe the bug**
Incorrect output cutting a region out of a huge 16-bit single-channel TIFF

**To Reproduce**
Using this image as input:  https://planetarymaps.usgs.gov/mosaic/Mars/HRSC_MOLA_Blend/Mars_HRSC_MOLA_BlendDEM_Global_200mp_v2.tif

Run this:
`oiiotool Mars_HRSC_MOLA_BlendDEM_Global_200mp_v2.tif --cut 2048x2048+0+0 testcrop.tif`

The left half of the resulting tif is incorrect (you will have to offset the values to see--they are all negative)

For comparison, the output of writing an exr looks correct:
`oiiotool Mars_HRSC_MOLA_BlendDEM_Global_200mp_v2.tif --cut 2048x2048+0+0 testcrop.exr`

The results are the same no matter what the cut geometry is.

**Expected behavior**
Should be a valid crop

**Platform information:**
 - OIIO branch/version:
oiio-Release-2.1.18.1 + libtiff-4.1.0
oiio-Release-1.8.13 + libtiff 4.0.3

 - OS:
CentOS 7.7

 - C++ compiler:
oiio-Release-2.1.18.1: g++ 6.3.1
oiio-Release-1.8.13: g++ 4.8.5

 - Any non-default build flags when you build OIIO:
For oiio-2.1.18.1:  -march=westmere
For oiio-1.8.13: none

**Comment by lgritz** [comment]
Wow, that is an enormous file, and uncompressed!

Looking into it...

**Comment by lgritz** [comment]
I suspect that somewhere there is a 32 bit multiply that should be 64, and it's causing an overflow for this enormous image.

**Comment by mike1158** [comment]
Hey Larry, thanks for taking a look.  

Doing some more poking around, and it's not just --cut.  This also does weird things, with or without `--native` or `--noautocc`:

`oiiotool --native --debug -v --noautocc -i Mars_HRSC_MOLA_BlendDEM_Global_200mp_v2.tif -resize 10% -o Mars_HRSC_MOLA_BlendDEM_Global_200mp_v2_scaled.tif`

Not sure if it's related or not, but the pixel values in the (otherwise valid) exr output and the (otherwise-correct right-half) tif outupt from a `--cut` or `--resize` are lower than a similar operation in ImageMagick (probably any version, but this is 7.0.10 build with HDRI support):

`magick convert Mars_HRSC_MOLA_BlendDEM_Global_200mp_v2.tif -resize 10% Mars_HRSC_MOLA_BlendDEM_Global_200mp_v2_scaled_IM.tif`

I'm less familiar with ImageMagick, so don't know if it's the thing doing some sort of CC, and I don't have a trustworthy tool that's capable of viewing the original directly.

Thanks again,
-miker

**Comment by lgritz** [comment]
Yeah, it's an image with 5B pixels, so I'm suspecting int32 overflow, probably in some common routine, rather than a flaw in the logic of just --cut.

**Comment by lgritz** [comment]
@mike1158 I'm having trouble reproducing this, both with the current master as well as 2.1.18. It's slow (I mean, it is an 11 GB image), but it seems correct to me. 

Can you spell out in detail HOW you are concluding that it's incorrect? What is the test you are performing?

once you make testcrop.tif (which you think is incorrect), if you do this:

    oiiotool testcrop.tif -o testcrop.exr

Is that resulting exr correct? (Meaning that the TIFF contained the right data all along, and it was your subsequent read or display of it that was broken.)

**Comment by mike1158** [comment]
Bug turned out to in the viewing tool, not oiiotool.

**Comment by lgritz** [comment]
Aha, I was suspecting something like that. The TIFF file was "int16" (signed), which is pretty rare compared to the usual "uint16", so usually I'm not surprised if apps handle that incorrectly.

Glad it's resolved. Cheers, Mike!
