### ISSUE TITLE
[BUG] ImageSpec.attribute() always expects a tuple when explicitly setting the data type

### ISSUE THREAD

**Issue by filmkorn** [OpenImageIO/oiio#2674]
**Describe the bug**
I'm getting a `TypeError` when explicitly specifying attribute's data type when copying attributes between specs. In oiio-1.8 there doesn't seem to be any validation on the passed type of the `value` so I'm not quite sure if our code is correct. Now `attribute()` recognizes the data type on it's own but we used to pass a the source attribute's TypeDesc and convert double attributes to floats - though it's not clear to me why this was done and if ImageSpecs ever hold double attributes.

**To Reproduce**

```python
>>> spec = ImageSpec()
>>> spec.attribute("name", oiio.TypeDesc("string"),  "value")
Traceback (most recent call last):
  File "<input>", line 1, in <module>
TypeError: attribute(): incompatible function arguments. The following argument types are supported:
    1. (self: OpenImageIO.ImageSpec, arg0: unicode, arg1: float) -> None
    2. (self: OpenImageIO.ImageSpec, arg0: unicode, arg1: int) -> None
    3. (self: OpenImageIO.ImageSpec, arg0: unicode, arg1: unicode) -> None
    4. (self: OpenImageIO.ImageSpec, arg0: unicode, arg1: OpenImageIO.TypeDesc, arg2: tuple) -> None
Invoked with: <OpenImageIO.ImageSpec object at 0x7f02140caf10>, 'name', <TypeDesc 'string'>, 'value'
```

**Expected behavior**
No error is raised.

**Evidence**
See above.

**Platform information:**
 - OIIO branch/version: 2.2 beta1
 - OS: Cent7
 - C++ compiler: gcc 6.4.0
 - Any non-default build flags when you build OIIO:

Any advice would be appreciated.

**Comment by filmkorn** [comment]
If I understand correctly I should only pass the `TypeDesc` if the value is a tuple. Interestingly this doesn't seem to work:

```python
>>> spec = ImageSpec()
>>> spec.attribute("test_tuple", TypeInt, (1, 2, 3))
>>> spec.extra_attribs[0]
IndexError
```

Getting the feeling that copying every extra_attrib one by one is not a bright idea.

**Comment by lgritz** [comment]
Sorry about the delay. I think your are right, and a proposed fix is in PR #2695

**Comment by filmkorn** [comment]
This works and simplifies our client code.

I still can't get it to copy tuples as shown in my previous reply. It might be unrelated - would you like me to create a new issue for this?

**Comment by lgritz** [comment]
Oh, I assumed that was all part of the same example.

Yes, could you file another issue that gives a couple lines of Python that reproduce the error?
