### ISSUE TITLE
[BUG] Python: InputImage.read_image() returns ndarray of dtype uint16 for TypeHalf

### ISSUE THREAD

**Issue by filmkorn** [OpenImageIO/oiio#2689]
**Describe the bug**
When reading an image with `InputImage.read_image()` in format TypeHalf, we seem to get an ndarray with type uint16.

**To Reproduce**

```python
>>> import OpenImageIO as oiio

>>> input_image = oiio.InputImage.open("source.exr")

>>> data = input_image.read_image(0, 0, 1, 1, oiio.TypeFloat)
>>> data.dtype
dtype('float32')

>>> data = input_image.read_image(0, 0, 1, 1, oiio.TypeHalf)
>>> data.dtype
dtype('uint16')  # Should be float16?
```

**Expected behavior**
dtype should be float16?

**Evidence**

[This line](https://github.com/OpenImageIO/oiio/blob/742173e39588e07cf43cbe7b49dd22d624a48388/src/python/py_oiio.h#L532) looks 
a bit suspicious to me?

**Platform information:**
 - OIIO branch/version: 2.2.5.0-beta2
 - OS: Cent7
 - C++ compiler: gcc-6.4.0
 - Any non-default build flags when you build OIIO:

**Comment by lgritz** [comment]
Yes, this does look like an oversight. I think I didn't quite realize that numpy already understood the half type, but a bit of googling revealed the magic incantation.

I don't suppose you can try #2694 and see if it fully addresses it for you?

**Comment by filmkorn** [comment]
Thanks Larry! Can confirm this fixes the issue.
