### ISSUE TITLE
[BUG]Python ImageBuf.make_writeable() + write() causes bad values for image with mixed depth channels

### ISSUE THREAD

**Issue by captainhammy** [OpenImageIO/oiio#2691]
**Describe the bug**
OpenImageIO.ImageBuf writes out channels with bad values when the source image contains channels of mixed depths.

Background:  We are using OpenImageIO to inject metadata into rendered images.  This pipeline code just attempts to lazily do this by reading the source image via ImageBuf, making it writeable, adding some specmod attributes and writing it to a new file using the code below (metadata injection omitted as it is not relevant to this bug.)

The attached .exr file contains an single part image generated by Redshift where RGBA are all 32-bit and two aovs (P, N) are 16-bit.  These mixed depths seem to be causing this issue.  If all the channels are the same depth (all 32-bit, all 16-bit) then there is no issue.

**To Reproduce**
Unzip the attached image [multidepth.exr.zip](https://github.com/OpenImageIO/oiio/files/5158255/multidepth.exr.zip)

Replace paths with valid source and target and execute the following statements in Python:

```
>>> import OpenImageIO as oiio
>>> filepath = "/path/to/multidepth.exr"
>>> target_path = "/some/target.exr"
>>> img_in = oiio.ImageBuf(filepath)
>>> img_in.make_writeable()
>>> img_in.write(target_path)
```
View the image and notice the resulting image is not correct.  See screenshot in Evidence below

**Expected behavior**
The images should match and not contain bad values.

**Evidence**
Comparison between source and re-written images: ![rewrite_bug](https://user-images.githubusercontent.com/1617380/91893860-a1d3c700-ec49-11ea-8c11-2c66c03826ea.png)

**Platform information:**
 - OIIO branch/version: 2.2.5.0-beta2
 - OS: Cent7
 - C++ compiler:  gcc-6.4.0
 - Any non-default build flags when you build OIIO:

**Comment by captainhammy** [comment]
I should mention that in an effort to work around/update the code I did find this example thiat is basically doing the same thing as we're trying to do https://openimageio.readthedocs.io/en/latest/imageoutput.html#copying-an-entire-image  however I appear to get the same result.

**Comment by lgritz** [comment]
Proposed fix: https://github.com/OpenImageIO/oiio/pull/3088

**Comment by captainhammy** [comment]
Thanks Larry!
