### ISSUE TITLE
aligned_malloc and aligned_free symbols not exported on Windows

### ISSUE THREAD

**Issue by ix-dcourtois** [OpenImageIO/oiio#2700]
**Describe the bug**

Not sure this is the correct category, but as the title says, OIIO exposes `aligned_malloc` and `aligned_free` in the `platform.h` header, but doesn't export their symbols on Windows. All the other functions in this header are either inlines or templates, so this problem only happen with those 2 (as far as I could tell)

Problem is that any other lib that will use `OIIO::aligned_*` functions will fail linking on Windows with an undefined symbol.
This happened for me when building OpenShadingLanguage.

**To Reproduce**

1. Create a simple `main.cpp` file in which you allocate something using OIIO's `aligned_malloc`
2. On Windows, build into an executable
3. > unresolved symbol and linking fails.

**Expected behavior**

`aligned_malloc` and `aligned_free` should either export symbols, or be declared inline and defined in the `platform.h` header like all the other functions in this header.

I'm not sure what the best solution is. I temporarily fixed this by going full inline in `platform.h`, but maybe a cleaner solution would be to move the declaration of those 2 functions in `sysutil.h` (since they are defined in `sysutil.cpp`) and use `OIIO_API` on their declaration there (this macro not being available in `platform.h` yet, this can't be used there)

**Platform information:**
 - OIIO 2.1.15.0:
 - OS: Windows
 - C++ compiler: MSVC 2017

**Comment by lgritz** [comment]
Quite right! Fix coming shortly...

**Comment by lgritz** [comment]
Proposed fix in #2701

**Comment by ix-dcourtois** [comment]
Nice, thanks for the quick fix!
