### ISSUE TITLE
[BUG] ImageSpec: Failing to set tuple attribute

### ISSUE THREAD

**Issue by filmkorn** [OpenImageIO/oiio#2702]
**Describe the bug**
If I understand correctly, the following code should work and set a tuple attribute:

**To Reproduce**

```python
>>> import OpenImageIO as oiio
>>> spec = oiio.ImageSpec()
>>> spec.attribute("test_int", oiio.TypeInt, 42)
>>> spec.getattribute("test_int")
42L  # Works.

>>> spec = oiio.ImageSpec()
>>> spec.attribute("test_tuple", oiio.TypeInt, (1, 2, 3))
>>> spec.getattribute("test_tuple")
<type 'NoneType'>

>>> spec.extra_attribs[0]
Traceback (most recent call last):
  File "<input>", line 4, in <module>
IndexError
```

**Expected behavior**
I'm not quite sure if this is expected to work like this? (Until recently) we didn't have a unittest covering this scenario and I have not encountered of a production rendering including this kind of metadata yet. Looking at the docs I thought this was supposed to work though, so I though I should flag it.

**Evidence**
See above.

**Platform information:**
 - OIIO branch/version: https://github.com/OpenImageIO/oiio/pull/2695/commits/cd5a9ce23e45af7c7cae666dba99f64abaa3ae18
 - OS: Cent7
 - C++ compiler: gcc-4.8.5
 - Any non-default build flags when you build OIIO:

**Comment by lgritz** [comment]
42 is an int, but (1,2,3) is not. You want:

    spec.attribute("test_tuple", "int[3]", (1,2,3))

**Comment by filmkorn** [comment]
@lgritz Thanks, works well. Closing.

**Comment by filmkorn** [comment]
@lgritz How would the call look like in OIIO-1?
The signature is:
```
attribute(OpenImageIO_v1_8::ImageSpec {lvalue}, std::string, OpenImageIO_v1_8::TypeDesc, boost::python::tuple {lvalue})
    attribute(OpenImageIO_v1_8::ImageSpec {lvalue}, std::string, OpenImageIO_v1_8::TypeDesc, boost::python::api::object {lvalue})
    attribute(OpenImageIO_v1_8::ImageSpec {lvalue}, std::string, std::string)
    attribute(OpenImageIO_v1_8::ImageSpec {lvalue}, std::string, int)
    attribute(OpenImageIO_v1_8::ImageSpec {lvalue}, std::string, float)
```

Choosing the first option:
```
>>> s = oiio.ImageSpec()
>>> s.attribute("tuple", oiio.TypeInt,  (1,2,3))
>>> s.extra_attribs[0].value
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'value'
```

**Comment by lgritz** [comment]
I would have to look at the old code (OIIO 1.x is from 2017/2018), but part of OIIO 2.x involved a complete overhaul of the Python bindings including switching its implementation from boost python to pybind11. It was a badly needed overhaul. It would not surprise me if in OIIO 1.x's python bindings, that entire classes or useful methods were not implemented at all or were done outright wrong.
