### ISSUE TITLE
[HELP] Writing metadata into EXR images

### ISSUE THREAD

**Issue by akilaln** [OpenImageIO/oiio#2714]
I'm trying to write metadata into EXR using ImageBuf class in the following way
```
 buf = ImageBuf("test.exr") 
 buf.specmod().attribute("test_attr", "str_value")
 buf.write("test.exr")
```
The metadata seems to be getting written correctly but the file seems to be losing out on data as the files size looks much smaller. I followed your  documentation adding arbitrary data but I probably am missing something specifically for EXRs.

**Comment by lgritz** [comment]
How do you know it's losing data? What is missing? Does it look correct when you view it?

Just because the file on disk is smaller doesn't really tell you that anything is wrong. Maybe your input file was uncompressed, but the output file is (losslessly) compressed?

**Comment by akilaln** [comment]
Hi Larry,
Thanks for your reply
Ya it's just the reduction in file size that is concerning. The files
probably look the same when I view it like you said its lossless
compression. But is there a way to turn off the compression when writing
out?

**Comment by lgritz** [comment]
buf.specmod().attribute("compression", "none");

**Comment by lgritz** [comment]
I'm going to assume all questions here have been adequately answered. Re-open the issue or, even easier, just follow up on the oiio-dev list if there are further questions.
