### ISSUE TITLE
[FEATURE REQUEST] Writing black and white stencil TIFF images.

### ISSUE THREAD

**Issue by alister-chowdhury** [OpenImageIO/oiio#2720]
Hey there,

It appears† that OIIO is happy enough to read in black and white tiffs:
https://github.com/OpenImageIO/oiio/blob/master/src/tiff.imageio/tiffinput.cpp#L863-L876

And actually appears to be using atleast one in your test suite:
https://github.com/OpenImageIO/oiio/blob/master/testsuite/tiff-suite/ref/out.txt#L109-L110
https://github.com/OpenImageIO/oiio/blob/master/testsuite/tiff-suite/run.py

But much to my surprise the lowest you can go is 2 bits per sample:
https://github.com/OpenImageIO/oiio/blob/master/src/tiff.imageio/tiffoutput.cpp#L405-L409
```c++
    case TypeDesc::UINT8:
        if (m_bitspersample != 2 && m_bitspersample != 4
            && m_bitspersample != 6)
            m_bitspersample = 8;
        sampformat = SAMPLEFORMAT_UINT;
        break;
```
via
```c++
    spec.attribute("oiio:BitsPerSample", 2);
```

While this is fine for the most part, it compresses down very nicely and reduces a lot of the I/O overhead of rasterizing alpha masks, it seems a bit odd (possibly an oversight?) that 1 bits per sample can't be used.

By no means is this anything critical, but is one of those things that really just irks you.

If you're happy for me to have a go at making the change, please do let me know.

Many thanks,
Alister

---
† It's been a while since I've had to write a TIFF outside of using OIIO, so haven't directly observed OIIO consume a black and white tiff of my creation.

**Comment by lgritz** [comment]
So we can read 1 bit TIFF but not write it? Yeah, that doesn't surprise me too much, we often are more liberal in what we can read than what we will write. I can imagine myself thinking: "Does anybody who isn't a fax machine really want to generate 1 bit images? Probably not, we can wait to implement this functionality until somebody asks for it."

I would be very happy if you wanted to take a shot at implementing it!

**Comment by alister-chowdhury** [comment]
PR merged, closing ticket
