### ISSUE TITLE
Animated webp images unsupported

### ISSUE THREAD

**Issue by MickeyKnox** [OpenImageIO/oiio#2721]
OpenImageIO does not support Animated webp images. Not only does it not support the Animation, not even the first frame is read. Instead, there is an error about the image not being valid GIF.

Single image webp images work fine.

Are there plans to add support for animated wbp images?

**Comment by lgritz** [comment]
Nobody had really noticed or complained before, so in that sense there were no plans prior to your filing this issue.

It would be great for somebody to take this on and make a PR that fixes it. I can't imagine that it is especially difficult technically. If somebody were to step forward and volunteer to do that, then there would (by definition) be a plan.

**Comment by lgritz** [comment]
I'm working on this!  Have made some progress, will report back shortly, hopefully with a PR.

**Comment by lgritz** [comment]
Please try #2730 for the fix for reading animated webp. This doesn't include the ability to write animated webp; one thing at a time.

**Comment by lgritz** [comment]
@MickeyKnox Are you able to try out the proposed #2730 fix and verify that it is an improvement for you?
