### ISSUE TITLE
[HELP] Windows Build - python binding 

### ISSUE THREAD

**Issue by adamjrbaker** [OpenImageIO/oiio#2731]
OS: Windows 10
Python: 3.8 | 2.7

I (believe) have successfully built and installed OpenImageIO through vcpkg. Now I am trying to set up the python binding I have read over some of the other issues talking about how pybind11 needs to also be installed. 

**Installed items**
`openimageio[core,pybind11,tools]:x64-windows`

_NOTE: This is my first attempt trying to build anything of this nature and I am not sure what the next steps are._

**Repo Steps:**
* `git clone vcpkg`
* `.\vcpkg\bootstrap-vcpkg.bat`
* `\vcpkg install openimageio:x64-windows`  from my understanding this installs both `[tools]` and `[core]`
* `\vcpkg install openimageio[pybind11]:x64-windows` install python bind
* `.\vcpkg integrate install`

I am assuming I will have to point a `PYTHONPATH` but not sure location of the python module.  The install.md is not clear on the next step.

**Comment by debaetsd** [comment]
Not sure exactly what the question is here? what is not working for you?

I have no clue on how it would work when using vcpkg but python binding on Windows work fine.

OIIO cmake setup should find it after installing pybind somewhere cmake can find it (for example by configuring `CMAKE_PREFIX_PATH`).
To install pybind11, I just use cmake install (but with `-D PYBIND11_TEST=0` as I'm not running the tests anyway and not having to install pytest).
Upon completion of the build, you should find `OpenImageIO.pyd` python binary that can be loaded using the regular python import command.
If it complain about failing to load a module, it cannot find OpenImageIO.dll (or one of the dependencies) and that can be solved using the regular Windows DLL tricks (copy to local directory, modify PATH, ...)

**Comment by lgritz** [comment]
Can we close this? The Windows CI (even though not 100% passing tests yet) is definitely building the Python bindings.

**Comment by adamjrbaker** [comment]
You can close this if you would like, I was still unable to build it successfully for windows for use with pytyhon. This might come down to my lack of understanding of VCPKG or CMake.
