### ISSUE TITLE
Can't load image using OpenImageIO

### ISSUE THREAD

**Issue by brukted** [OpenImageIO/oiio#2738]
I was trying to load image using opeimageio which I installed using vcpkg. But I get an error saying F:\vcpkg\installed\x64-windows\include\OpenImageIO\fmt\format-inl.h(1371,8): error C2061: syntax error: identifier 'HANDLE'. My code is this
```
#include <OpenImageIO/imageio.h>
#include <string_view>
#include <tuple>
#include <vector>

std::tuple<int, int, int> loadImageFromFile(std::string_view filePath,
                                            std::vector<unsigned char> &data) {  
  auto input = OIIO::ImageInput::open(filePath.data());
  auto &specs = input->spec();
  int width = specs.width;
  int height = specs.height;
  int channels = specs.nchannels;
  data = std::vector<unsigned char>(width * height * channels);
  input->read_image(OIIO::TypeDesc::UINT8, &data[0]);
  input->close();
  return {width, height, channels};
}
```
Thanks!

**Comment by lgritz** [comment]
Do you know what version of OIIO you are using? 

Also, if you look in F:\vcpkg\installed\x64-windows\include\OpenImageIO\fmt\core.h, you'll see a line close to the top that says

    #define FMT_VERSION xxxxxx

Can you tell me what version that says?

**Comment by brukted** [comment]
it says #define FMT_VERSION 60200.  Also I use fmt for the project which has  the same version. To let you know I formatted  format-inl.h(line 24) from
```
#ifdef _WIN32
#  include <io.h>
#  include <windows.h>
#endif
```
to
```
#ifdef _WIN32
   #include <io.h>
   #include <windows.h>
#endif
```
and It is working now.

**Comment by lgritz** [comment]
WHAT?

The spaces? Really?

**Comment by brukted** [comment]
I think the issue is with the way I  setup my  build.  Defining  _WIN32  manually also worked but It raises another error. You can  close the issue if you want to.

**Comment by lgritz** [comment]
OK, sounds like something spooky on your end. Will close for now, feel free to reopen if you end up tracing it back to something on our end.
