### ISSUE TITLE
[FEATURE REQUEST] HTML download for docs, please!

### ISSUE THREAD

**Issue by Correct-Syntax** [OpenImageIO/oiio#2745]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when projects only have pdf downloads for documentation! :)

**Describe the solution you'd like**
Please have a HTML version of the docs for download.

**Describe alternatives you've considered**
Building it myself -but that is extra hassle.

**Additional context**
None.

Thank you.

**Comment by lgritz** [comment]
The HTML docs are hosted at https://openimageio.readthedocs.org

Does that cover what you need?

**Comment by Correct-Syntax** [comment]
Hi, 

I am wanting this for offline reading. I find HTML easier to navigate, especially with really long docs.

Usually sphinx will allow for downloading the HTML docs as well as the PDF. In the below image, the HTML download link would normally be along side the PDF download link.

Basically, you will need to enable it in the read the docs settings, I believe. 👍 

Example with HTML download I am talking about: [wagtail cms](https://docs.wagtail.io/en/stable/)

Thank you for your time!

![Screenshot 2020-10-20 201223](https://user-images.githubusercontent.com/60711001/96661000-b448b380-1310-11eb-9f2e-c814930b985c.jpg)

**Comment by lgritz** [comment]
Ah, I will try that! Thanks for the tip.

**Comment by lgritz** [comment]
This should be working now for "master". It will do the same for the next 2.2 release, which is scheduled for Nov 1.

**Comment by Correct-Syntax** [comment]
Thanks. :)
