### ISSUE TITLE
About forgotten, unfinished, incomplete C⁺⁺11 and abandoned projects

### ISSUE THREAD

**Issue by Jamaika1** [OpenImageIO/oiio#2760]
Still someone is using old libraries.
https://github.com/Jamaika1/MoxMxf_mxflib_dpx_IlmThread

**Comment by lgritz** [comment]
Is this a real issue or just spam?
Please explain precisely what you think is broken.

**Comment by lgritz** [comment]
I'm going to close. Please re-open with a real explanation if this is not a spambot.
