### ISSUE TITLE
[BUG] GIFs with non ascii filenames fail to open on windows

### ISSUE THREAD

**Issue by SRHMorris** [OpenImageIO/oiio#2775]
**Describe the bug**
Calling `OIIO::ImageInput::open(filename);` fails for gif images with non ascii filenames on windows. Other image plugins appear to work fine though I've not tested all of them, presumably because they use the OIIO::Filesystem stuff.

I assume this works correctly on any os that uses utf8. Renaming the file so that it contains only ascii characters works as expected.

Github will have renamed the file I guess, so just rename it to something like "test×.gif".

![testgif×](https://user-images.githubusercontent.com/69468379/100256304-8cb2bf80-2f3c-11eb-9fe4-44530bc518b5.gif)

**To Reproduce**
1. call OIIO::ImageInput::open() on the attached image, which has a non ascii '×' character in the filename
2. OIIO::geterror() returns "Failed to open given file"

**Platform information:**
 - OIIO branch/version: 2.2.7.0
 - OS: windows 10
 - C++ compiler: msvc
 - Any non-default build flags when you build OIIO:

**Comment by lgritz** [comment]
I don't have a Windows machine, so can't test easily. I made my best guess as a proposed fix in #2777 . Can you apply that patch and see if it does the trick for you?

**Comment by SRHMorris** [comment]
It definetely appears to load correctly now. However unfortunetly I'm now getting a crash when the ImageInput goes out of scope. The last few lines of the call stack are the following

```
0	(unknown)	close 	 (address: 0x7FF8AB014CF0, no symbols)
2	(unknown)	fclose_nolock 	 (address: 0x7FF8AAF86030, no symbols)
4	(unknown)	fclose 	 (address: 0x7FF8AAF861C0, no symbols)
6	OpenImageIO	OpenImageIO_v2_2::GIFInput::close 	 (src\gif.imageio\gifinput.cpp:464, address: 0x7FF897DFA2C0)
8	OpenImageIO	OpenImageIO_v2_2::GIFInput::~GIFInput 	 (src\gif.imageio\gifinput.cpp:37, address: 0x7FF897DF9F40)
10	OpenImageIO	OpenImageIO_v2_2::GIFInput::`scalar deleting destructor' 	 (address: 0x7FF897DF9FD0, no symbols)
12	AppName	std::default_delete<OpenImageIO_v2_2::ImageInput>::operator() 	 (C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.27.29110\include\memory:2402, address: 0x7FF6C478AC00)
14	AppName	std::unique_ptr<OpenImageIO_v2_2::ImageInput,std::default_delete<OpenImageIO_v2_2::ImageInput> >::~unique_ptr<OpenImageIO_v2_2::ImageInput,std::default_delete<OpenImageIO_v2_2::ImageInput> > 	 (C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.27.29110\include\memory:2514, address: 0x7FF6C4788F30)
```

**Comment by lgritz** [comment]
Hmmm... that makes me think that perhaps Giflib is closing the handle when it's done reading the file, and so my fclose is redundant. Let me look at their docs and see if it clarifies.

**Comment by lgritz** [comment]
OK, PR has been updated. Try again?

**Comment by SRHMorris** [comment]
Yeah that seems to have fixed it, thanks!

**Comment by SRHMorris** [comment]
Oh sorry, I forgot but to build I also had to include fcntl.h in gifinput.cpp and change _O_READ to _O_RDONLY

**Comment by lgritz** [comment]
Strange, it compiled ok on our Windows CI. But I will make those changes... 

OK, updated with PR with your suggestions. Can you give one more try, please?

Thanks for the help with this.

**Comment by SRHMorris** [comment]
Sorry, that should be including fcntl.h in gifinput.cpp so that _O_RDONLY and _O_BINARY are defined. But apart from that it works fine.

**Comment by lgritz** [comment]
Ah yes, of course! Modified, and I also added a comment so that users of the new Filesystem::open() flavor will know to do this.

**Comment by lgritz** [comment]
How's the latest take? Did I get it this time?

**Comment by SRHMorris** [comment]
Yeah, it all seems good now, thanks!

**Comment by lgritz** [comment]
Thanks for all the help verifying! I will merge and backport to 2.2.
