### ISSUE TITLE
[BUG] OSX Segfault with versions 2.2.8 and 2.2.9 (while 2.2.7 is OK)

### ISSUE THREAD

**Issue by SylvainCorlay** [OpenImageIO/oiio#2789]
I am the maintainer of the conda-forge Openimageio package, and the package started segfaulting on import of the openimageio Python package since Version 2.2.8 (which was therefore not integrated on conda-forge).

Update PRs and build logs on all platforms are vailable here:

   https://github.com/conda-forge/openimageio-feedstock/pulls

**Comment by carlocab** [comment]
This sounds like https://github.com/OpenImageIO/oiio/issues/2806. Try the patch in https://github.com/OpenImageIO/oiio/pull/2807.

CC @lgritz

**Comment by lgritz** [comment]
@SylvainCorlay Are you able to try the patch mentioned above and see if it helps?

**Comment by lgritz** [comment]
No reply for years. Closing.
