### ISSUE TITLE
[FEATURE REQUEST] Support AVIF images

### ISSUE THREAD

**Issue by EwoutH** [OpenImageIO/oiio#2793]
The [AV1 Image File Format](https://aomediacodec.github.io/av1-avif/) (AVIF) is quickly gaining traction, so I was wondering if it could be supported by oiio.

[libheif](https://github.com/strukturag/libheif), which is already used by oiio, supports both HEIF and AVIF images, while a separate [libavif](https://github.com/AOMediaCodec/libavif) is also available.

**Comment by hjmallon** [comment]
https://github.com/OpenImageIO/oiio/pull/2811 should have added some decoding support
https://github.com/OpenImageIO/oiio/pull/2812 adds some encoding

**Comment by lgritz** [comment]
Does this combination of these two patches close this issue? Or is there more work to be done?

**Comment by lgritz** [comment]
I think this is implemented now (in master, and RB-2.2, so should be in the Feb 1 release).
