### ISSUE TITLE
[BUG] Python extension module has explicit linkage with build-time Python interpreter

### ISSUE THREAD

**Issue by carlocab** [OpenImageIO/oiio#2806]
**Describe the bug**
`lib/python3.9/site-packages/OpenImageIO.so` has explicit linkage with the Python executable used at build-time. This [blog post](https://blog.tim-smith.us/2015/09/python-extension-modules-os-x/) describes why this is a problem.

I discovered this while trying to update Homebrew's version of OpenImageIO to 2.2.9 here: https://github.com/Homebrew/homebrew-core/pull/66826 

Homebrew CI complained about the explicit linkage:
```
==> brew audit openimageio --online --git --skip-style
==> FAILED
openimageio:
  * python modules have explicit framework links
    These python extension modules were linked directly to a Python
    framework binary. They should be linked with -undefined dynamic_lookup
    instead of -lpython or -framework Python.
      /usr/local/opt/openimageio/lib/python3.9/site-packages/OpenImageIO.so
```

This CI failure first emerged when we tried to upgrade OpenImageIO to version 2.2.8 (https://github.com/Homebrew/homebrew-core/pull/64191), so I'm guessing this linkage was introduced there. I've tried various ways of passing the `-undefined dynamic_lookup` flag to the compiler, but that doesn't seem to have helped. It seems this option is also defined in 

https://github.com/OpenImageIO/oiio/blob/5167b11277fffcd9fe18fe4dc35b3eb2669d8c44/src/cmake/pythonutils.cmake#L79-L81

so I don't know why there is still explicit linkage.

This doesn't seem to be a peculiarity of building with Homebrew, as I can reproduce the issue even with a vanilla CMake build.

**To Reproduce**
1. Build OpenImageIO on macOS.
2. `cd $prefix/lib/python3.9/site-packages`
3. `otool -L OpenImageIO.so`

**Expected behavior**
There should be no explicit linkage to the build-time Python interpreter.

**Evidence**
```
❯ otool -L OpenImageIO.so
OpenImageIO.so:
        /usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/Python (compatibility version 3.9.0, current version 3.9.0)
        @rpath/libOpenImageIO.2.2.dylib (compatibility version 2.2.0, current version 2.2.10)
        /usr/local/opt/openexr/lib/libIlmImf-2_5.25.dylib (compatibility version 25.0.0, current version 25.0.3)
        /usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
        /usr/local/opt/ilmbase/lib/libImath-2_5.25.dylib (compatibility version 25.0.0, current version 25.0.3)
        /usr/local/opt/ilmbase/lib/libIexMath-2_5.25.dylib (compatibility version 25.0.0, current version 25.0.3)
        /usr/local/opt/ilmbase/lib/libHalf-2_5.25.dylib (compatibility version 25.0.0, current version 25.0.3)
        /usr/local/opt/ilmbase/lib/libIlmThread-2_5.25.dylib (compatibility version 25.0.0, current version 25.0.3)
        /usr/local/opt/ilmbase/lib/libIex-2_5.25.dylib (compatibility version 25.0.0, current version 25.0.3)
        /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 904.4.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.60.1)
```

**Platform information:**
 - OIIO branch/version: 2.2.8, 2.2.9, 2.2.10
 - OS: macOS 10.14, 10.15, 11.0
 - C++ compiler: Apple Clang
 - Any non-default build flags when you build OIIO:
     - `-DCMAKE_INSTALL_PREFIX=/tmp/openimageio`
     - `-DCMAKE_INSTALL_LIBDIR=lib`
     - `-DCMAKE_OSX_SYSROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk` 

**IF YOU ALREADY HAVE A CODE FIX:** There is no need to file a separate issue,
please just go straight to making a [pull request](https://github.com/OpenImageIO/oiio/pulls).

**Comment by lgritz** [comment]
Aha, I see, yes. I'm not sure why that linkage is present. Thanks for this investigation, I'll try to figure out how to ensure that linkage doesn't happen.

**Comment by carlocab** [comment]
Sure. In case it helps, while trying to find a fix, I found that `LINK_FLAGS` appears to have been deprecated in the latest version of CMake. [1] They recommend using `LINK_OPTIONS` instead, but it doesn't appear to be a drop-in replacement as `s/LINK_FLAGS/LINK_OPTIONS` leads to a failed build.

In other CMake builds I've seen `INTERFACE_LINK_LIBRARIES` used instead (and that seems to work elsewhere) but making that change didn't work for me either. The build succeeds, but the explicit linkage remains.

Unfortunately, I haven't had time to really look at the contents of `pythonutils.cmake` carefully enough to do anything more meaningful than naive substitutions.

[1] https://cmake.org/cmake/help/latest/prop_tgt/LINK_FLAGS.html

**Comment by lgritz** [comment]
@carlocab: I think maybe I have it... would you mind giving this a try on your end and see if it looks like the solution?

#2807

**Comment by carlocab** [comment]
Thanks for getting to it so quickly. Running the build now. Will update you soon.

**Comment by carlocab** [comment]
Perfect:
```
❯ otool -L OpenImageIO.cpython-39-darwin.so
OpenImageIO.cpython-39-darwin.so:
        @rpath/libOpenImageIO.2.3.2.dylib (compatibility version 2.3.2, current version 2.3.2)
        /usr/local/opt/openexr/lib/libIlmImf-2_5.25.dylib (compatibility version 25.0.0, current version 25.0.3)
        /usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
        /usr/local/opt/ilmbase/lib/libImath-2_5.25.dylib (compatibility version 25.0.0, current version 25.0.3)
        /usr/local/opt/ilmbase/lib/libIexMath-2_5.25.dylib (compatibility version 25.0.0, current version 25.0.3)
        /usr/local/opt/ilmbase/lib/libHalf-2_5.25.dylib (compatibility version 25.0.0, current version 25.0.3)
        /usr/local/opt/ilmbase/lib/libIlmThread-2_5.25.dylib (compatibility version 25.0.0, current version 25.0.3)
        /usr/local/opt/ilmbase/lib/libIex-2_5.25.dylib (compatibility version 25.0.0, current version 25.0.3)
        /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 904.4.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.60.1)
```

**Comment by lgritz** [comment]
Awesome, thanks for checking!
