### ISSUE TITLE
[BUG] Fails to import Canon R5 8K file

### ISSUE THREAD

**Issue by eliot-lightcraft** [OpenImageIO/oiio#2816]
**Describe the bug**
I was experimenting with Canon R5 clips, both 4K and 8K, simply opening the file and saving out JPEG frames. The 4K files worked fine with the below Python code but the 8K file didn't. 

**To Reproduce**

Installed OpenImageIO with Homebrew with default settings.
8K file link: https://www.dropbox.com/s/clbr051susjwe0a/8K8A0231.MP4?dl=0

Code:

```
#!/usr/bin/env python

import OpenImageIO as oiio
from OpenImageIO import ImageBuf, ImageSpec, ImageBufAlgo
import os

src = '8K8A0231.MP4'
buf = ImageBuf(src)

frames = range(buf,nsubimages)
print (frames)

for frame in range(buf.nsubimages):
	buf.reset(src, subimage = frame)
	buf.write('myFrame_{l}.jpg'.format(l=frame))
```

**Expected behavior**
I executed this from the command line with 
> python3 pyframes.py

I expected it to write out a numbered series of JPEG still frames like it did with the 4K file. It doesn't seem to open the file correctly.

**Platform information:**
 - OIIO branch/version: today's build from Homebrew
 - OS: On Mac OSX 10.15.7, Macbook Pro 2013
 - C++ compiler: Xcode
 - Any non-default build flags when you build OIIO: none

**Comment by lgritz** [comment]
Apologies that this did not get an immediate response. Closing because the example file no longer lives at that link address. Please re-open or file a new issue if it's still a problem.
