### ISSUE TITLE
[HELP] Do you have any feedback about this ? (Homebrew/pkg-config --cflags)

### ISSUE THREAD

**Issue by barbak** [OpenImageIO/oiio#2868]
Hi all !

I wanted to have your feedback about this issue in homebrew with the openimageio package.
https://github.com/Homebrew/homebrew-core/issues/71360

You may spare me a lot of time of my free time if you do so :)

Thanks in advance.

**Comment by lgritz** [comment]
You're right. Patch coming right up.
