### ISSUE TITLE
[BUG] RAW image paths with ö do not open, or open broken

### ISSUE THREAD

**Issue by AdamMainsTL** [OpenImageIO/oiio#2881]
**Describe the bug**
Opening a RAW image with a filename or folder path which includes ö (and some other similar characters) either doesn't work, or opens broken. For example, `image.orf` will load file, but `imäge.orf` will fail with an IO error. Likewise, a CR2 with ä in it will open completely solid green but will open correctly if the ä is removed.

**To Reproduce**
1. Find any RAW file
2. Ensure it opens correctly
3. Rename the file or folder it's in to include ö
4. Try opening it again and get an error/bad image

**Expected behavior**
I expect the image to open correctly. Non-RAW images with the same names do work, so it's something in the RAW side of things that is breaking.

**Evidence**
Going to just point to some raw files I found online as examples since I don't know what files I have that I can give out.

CR2 opens fine, but when renamed shows up as pure green: http://www.rawsamples.ch/raws/canon/1dm2/RAW_CANON_1DM2.CR2
ORF opens fine, but when renamed gives an IO error: http://www.rawsamples.ch/raws/olympus/e3/RAW_OLYMPUS_E3.ORF

Error for when it doesn't load:
> Could not open file "C:/Users/Admin/Pictures/Debug/CR3/IMG_0482_räw.CR3", Input/output error

**Platform information:**
 - OIIO branch/version: 2.2.11.1
 - OS: Windows
 - C++ compiler: MSVC 2019
 - Any non-default build flags when you build OIIO:

**Comment by lgritz** [comment]
Yes, I see what's happening. Proposed fix is #2888
