### ISSUE TITLE
[BUG] Loading BMP crashes in open 

### ISSUE THREAD

**Issue by DougRogers** [OpenImageIO/oiio#2898]
[PRINTER.zip](https://github.com/OpenImageIO/oiio/files/6160445/PRINTER.zip)

_open_ crashes on the attached bmp.

**Comment by lgritz** [comment]
Indeed, there is a bug, using a field that is uninitialized when the BMP is of type OS2_V1.

I am preparing a patch that will fix this.

**Comment by lgritz** [comment]
From what I can tell, his BMP file is an early variant of the format from Windows 2.0, which was a 16 bit operating system circa 1987. This explains why we had not previously run across an image that triggered this bug.

**Comment by DougRogers** [comment]
The file could very well be that old.  I am writing an image browser that scans all drives for images.  This file was in my images I have collected over the years.  It has a modiy date of 1993 (and a creation date of 2014 oddly).  As part of the scanning process, I was gathering image width and height. My program crashed when I tried to get the specs for this file.  Unfortunately, reading with and height of large numbers of image files is too slow, so I had to remove it.

Personal note:  Good to see you on this project.  It looks extremely useful and I am happy to see how easy it is to use.  It's been a long time since our NVIDIA days.

**Comment by lgritz** [comment]
Are you able to try the patch in #2899 and verify that it works on any of the broken BMPs you have?

Also, would it be ok for me to add this file to the testsuite so we have a regression test for this case?

**Comment by DougRogers** [comment]
I am using vcpkg to install and build OpenImage I/O.   I think I can just copy the files in the change list and rebuild the package in vcpkg to get this change, unless you know of a better way to do this with vcpkg.

I will rerun on all the files after I install this patch.

Feel free to use the file as you wish.

**Comment by DougRogers** [comment]
Modifying the source in the vcpkg build tree did not work.  It reverted the change when I rebuilt it.

**Comment by lgritz** [comment]
No worries, I was just hoping for the extra check if it was easy.

**Comment by DougRogers** [comment]
This bmp also fails to load

[magick.zip](https://github.com/OpenImageIO/oiio/files/6167435/magick.zip)

**Comment by DougRogers** [comment]
Another 
[palette-1c-8b.zip](https://github.com/OpenImageIO/oiio/files/6167977/palette-1c-8b.zip)

**Comment by DougRogers** [comment]
[decodecolormap.zip](https://github.com/OpenImageIO/oiio/files/6168030/decodecolormap.zip)

**Comment by lgritz** [comment]
@DougRogers The magick.zip and palette-1c-8b.zip are both the older "BMP version 1" file type that involves the same bug as your PRINTER.BMP. So I think that the same PR fixes all three.

I'm not sure about decodecolormap.bmp crashes in a different way, I'm still looking into that. But I'm suspecting that it may be a truncated or corrupted file, because ImageMagick's "identify" says it's not a valid image, and MacOS Preview.app will not display it. (That's still no excuse for OIIO crashing upon reading it, I'm fixing that.)

**Comment by DougRogers** [comment]
After looking at the origin of this file, I believe that decodecolormap.bmp is a stress test case that is intentionally corrupted.

**Comment by lgritz** [comment]
Aha, so it is serving its purpose. I have a handle on a fix.

**Comment by DougRogers** [comment]
All the files I submit are free to use as test cases.

**Comment by lgritz** [comment]
Pushed an update to the PR that gives a reasonable error message and does not crash for the decodecolormap file.
