### ISSUE TITLE
[BUG] Assert loading TGA

### ISSUE THREAD

**Issue by DougRogers** [OpenImageIO/oiio#2900]
Crash occurs when opening the attached TGA image.

You can use this for testing purposes.

[round_grill.zip](https://github.com/OpenImageIO/oiio/files/6166822/round_grill.zip)

**Comment by DougRogers** [comment]
This file also.
[iron_grill.zip](https://github.com/OpenImageIO/oiio/files/6167378/iron_grill.zip)

Both can be used for testing.

**Comment by DougRogers** [comment]
And this one too.
[euro_frnt_2.zip](https://github.com/OpenImageIO/oiio/files/6167617/euro_frnt_2.zip)

**Comment by lgritz** [comment]
All three of these open ok for me. Do you get any stack trace or other clue where it crashes?

I'm trying on a Mac, so I guess it's also possible it's a Windows only issue.

Do they crash every time reliably?

**Comment by DougRogers** [comment]
They all fail consistently the same way with vector subscript out of range.

![image](https://user-images.githubusercontent.com/7563851/111793004-0ec74b00-8882-11eb-8946-f03aa4369782.png)

`bool TGAInput::open(const std::string& name, ImageSpec& newspec)`  _m_buf_ is empty_, buf.c[1]_ is 0

![image](https://user-images.githubusercontent.com/7563851/111794484-8184f600-8883-11eb-8307-8c501c389829.png)

**Comment by DougRogers** [comment]
This is an assert vs. a crash.  I updated the title.  Release mode works, but the debug build accesses an empty vector field.  

 Recommend using _m_buf.data()_ instead o_f &m_buf[0]_

**Comment by lgritz** [comment]
I see what's going on. Interesting corner case.

These images lack a thumbnail. 

I think that all previous TGA files I've encountered either have a thumbnail, or indicate the lack of thumbnail by having 0 in the "offset to thumbnail" field. These files have a nonzero offset, and a thumbnail record in that offset, but the thumbnail record indicates a 0x0 size.

Fix coming.

**Comment by lgritz** [comment]
Yes, it looks like all the tga files previously in our testsuite have thumbnails.

**Comment by lgritz** [comment]
Proposed fix in #2903
