### ISSUE TITLE
[BUG] Raw file formats not listed in extension_list

### ISSUE THREAD

**Issue by DougRogers** [OpenImageIO/oiio#2901]
Using this code sequence to get supported file formats:
```
    std::string extensionsListStr;
    oiio::getattribute("extension_list", extensionsListStr);
```
RAW file formats are not included.  CR2, CR3, NEF, NRW, ARW etc.

**Comment by lgritz** [comment]
Works for me. Does it list extenstions for all the other formats?

If you do:

    oiiotool --help

toward the bottom where it lists all the formats (not extensions) it knows, do you see raw there?

How sure are you that the OIIO you are using was compiled with raw enabled (it can be disabled if libraw is not found at build time)?

**Comment by DougRogers** [comment]
vcpkg builds everything.  I'm not sure of the options at all.  I will investigate.

**Comment by DougRogers** [comment]
Added libraw as option and extension list included the raw formats.
