### ISSUE TITLE
[BUG] TGA displaying incorrectly.

### ISSUE THREAD

**Issue by DougRogers** [OpenImageIO/oiio#2916]
This:
[Sparnk__specular.zip](https://github.com/OpenImageIO/oiio/files/6209208/Sparnk__specular.zip)

should look like this:
![image](https://user-images.githubusercontent.com/7563851/112573155-f1760d80-8da8-11eb-94d8-8cd7606280a1.png)

but I am getting this:
![image](https://user-images.githubusercontent.com/7563851/112573241-1c606180-8da9-11eb-88a1-672ae1a6a061.png)

**Comment by lgritz** [comment]
Again, looks fine to me in OIIO's "iv".

How are you displaying that image?

**Comment by DougRogers** [comment]
Bug appears to be in QtOIIO.
