### ISSUE TITLE
[FEATURE REQUEST] Read TIFF from memory

### ISSUE THREAD

**Issue by DougRogers** [OpenImageIO/oiio#2920]
Some raw formats have TIFF previews that need to read from memory.  It would be nice to have the ability to read these using OIIO.  As it is now, I have to have a separate TIFF reader that can do this.

This function may be helpful:

extern TIFF* TIFFStreamOpen(const char*, std::ostream *);

https://stackoverflow.com/questions/4624144/c-libtiff-read-and-save-file-from-and-to-memory

**Comment by lgritz** [comment]
Working on that right now!

**Comment by DougRogers** [comment]
Do you need a test case where the previews are embedded TIFFs?

**Comment by lgritz** [comment]
No, I just meant TIFF IOProxy support as a first step. The unit test imageinout_test already tests proxies on all input types that advertise support for them.

**Comment by lgritz** [comment]
Implemented by #2921.

Today is Mar 28. It's too late to backport this in time for the Apr 1 release of 2.2.13. So I don't anticipate that this will be in an official release until 2.2.14 (presumably May 1), so if you want to use it before then, you'll need to build OIIO from source.

**Comment by DougRogers** [comment]
Not urgent.  I have a workaround.--
-Doug
