### ISSUE TITLE
[BUG] GIF file fails to open

### ISSUE THREAD

**Issue by DougRogers** [OpenImageIO/oiio#2924]
[PATTERN0.zip](https://github.com/OpenImageIO/oiio/files/6223230/PATTERN0.zip)

_in_ is nullptr
```
   auto in = ImageInput::open(filePath);
    if (in)
    {
        const ImageSpec &spec = in->spec();
        int xres              = spec.width;
        int yres              = spec.height;
        int channels          = spec.nchannels;
        in->close();
    }
```

**Comment by DougRogers** [comment]
I guess this is a feature request.

**Comment by lgritz** [comment]
Works for me.

Do you get an error? (If `in` is nullptr, you can retrieve with `OIIO::geterror()`).
How sure are you that GIF support was compiled in at build time?

**Comment by DougRogers** [comment]
Is GIF another option?  It is not in the extension list.

**Comment by lgritz** [comment]
Almost all formats are optional. I think only TIFF, PNG, and OpenEXR are hard failures if not found (and mostly because elements of those packages are used in OIIO in ways that are not confined strictly to reading those files).

**Comment by lgritz** [comment]
As kind of a separate issue from whether OIIO should consider more dependencies to be non-optional, I don't have any explanation for why vcpkg doesn't make several of the options (for which it can easily build the dependencies) on by default.

**Comment by lgritz** [comment]
The idea behind optional format dependencies is supposed to be: if a user doesn't have a package installed and doesn't particularly need that format, don't unnecessarily burden them with tracking down and building that dependency from scratch.

But with a package manager, there is no real burden on the user when the dependency is another package that the package manager can simply build itself by listing it as an oiio dependency. Vcpkg, I'm looking at you.

**Comment by lgritz** [comment]
If gif is not in your extension list, then this whole thing is just because you don't have support compiled in. Closing the issue.
