### ISSUE TITLE
[BUG] JPG fails to open

### ISSUE THREAD

**Issue by DougRogers** [OpenImageIO/oiio#2925]
[axe.zip](https://github.com/OpenImageIO/oiio/files/6223300/axe.zip)

**Comment by lgritz** [comment]
I can repro

**Comment by lgritz** [comment]
The file itself definitely has problems -- other utilities also complain about it. But I think we might be treating it as a fatal error when it doesn't need to be.

**Comment by lgritz** [comment]
Proposed fix in #2927. My assessment above was correct -- the header is indeed weird/corrupted, but not fatally so, and OIIO was treating message callbacks from jpeglib as fatal errors, when really they were more appropriate as warnings or just let it slide.

I will backport the fix to the supported release branch, but not in time for this week's release. It will have to wait for the next release.
