### ISSUE TITLE
[BUG] fillholes_pushpull seems to be doing something funky when the input image isn't 4 channels.

### ISSUE THREAD

**Issue by alister-chowdhury** [OpenImageIO/oiio#2937]
So, we typically use fillholes_pushpull to bleed edges of textures, at some point (I suspect recently) this seems to have stopped working correctly.

When applied to say 2 channels (1 colour + 1 alpha) it doesn't seem to apply the triangle filter correctly.
This was originally discovered on Linux (2.2.7) via C++ but I have been able to replicate it with the master branch on Windows via Python.
Which does indicate this isn't related to bindings or any specific platform.

Here's some replication steps, I've gotten it to write out the images at every stage for convenience.
```python
import OpenImageIO

# 1 channel texture (lets say something a bump map or something from Substance or Mari)
texture = OpenImageIO.ImageBuf(OpenImageIO.ImageSpec(256, 256, 1, OpenImageIO.UINT8))
OpenImageIO.ImageBufAlgo.checker(texture, 32, 32, 1, (0.0,), (1.0,))

# Stencil we want to bleed edges from (lets say a models UVs rasterized)
stencil = OpenImageIO.ImageBuf(OpenImageIO.ImageSpec(256, 256, 1, OpenImageIO.UINT8))
OpenImageIO.ImageBufAlgo.render_box(stencil, 0, 0, 128, 256, (1.0,), True)

# Make a temporary buffer which contains the texture + stencil
tmp_spec = OpenImageIO.ImageSpec(texture.spec())
tmp_spec.nchannels += 1
tmp_spec.channelnames = tmp_spec.channelnames + ("injected",)
tmp_spec.alpha_channel = tmp_spec.nchannels - 1
tmp = OpenImageIO.ImageBuf(tmp_spec)

OpenImageIO.ImageBufAlgo.paste(tmp, 0, 0, 0, 0, texture)
OpenImageIO.ImageBufAlgo.paste(tmp, 0, 0, 0, tmp_spec.alpha_channel, stencil)
tmp = OpenImageIO.ImageBufAlgo.premult(tmp)

# Bleed the edges
bled = OpenImageIO.ImageBufAlgo.fillholes_pushpull(tmp)

# Extract the original channels and discard the stencil
bled_texture = OpenImageIO.ImageBuf(texture.spec())
OpenImageIO.ImageBufAlgo.paste(bled_texture, 0, 0, 0, 0, bled)

texture.write("texture.tif")
stencil.write("stencil.tif")
tmp.write("tmp.tif")
bled.write("bled.tif")
bled_texture.write("bled_texture.tif")
```

(I'm attaching these as PNGs, cus github)
**Original texture**
![texture](https://user-images.githubusercontent.com/30833607/113989901-cbd91180-9848-11eb-84c1-c8eca419848c.png)

**Stencil**
![stencil](https://user-images.githubusercontent.com/30833607/113989980-e4e1c280-9848-11eb-835c-bc14e9bc1d01.png)

**Bled texture**
![bled_texture](https://user-images.githubusercontent.com/30833607/113990019-f1feb180-9848-11eb-856b-cb547eecdc32.png)

Interestingly, if you zoom in, you can see some aliasing, which indicates *something* involving down-scaling was taking place.
![bled_texture_zoom](https://user-images.githubusercontent.com/30833607/113990350-430ea580-9849-11eb-95af-815fd641d5ef.png)

Additionally, if you look at the top, within the same alias area, there is a mysterious white bar.
![bled_texture_top](https://user-images.githubusercontent.com/30833607/113993249-258f0b00-984c-11eb-904b-5877e4203f7f.png)

And if we were to change the original texture count to 3.
```python
texture = OpenImageIO.ImageBuf(OpenImageIO.ImageSpec(256, 256, 3, OpenImageIO.UINT8))
OpenImageIO.ImageBufAlgo.checker(texture, 32, 32, 1, (0.0, 0.0, 0.0), (1.0, 1.0, 1.0))

...

bled_texture.write("bled_texture_3_channels.tif")
```
The result is actually what we'd expect.
![bled_texture_3_channels](https://user-images.githubusercontent.com/30833607/113990397-53268500-9849-11eb-97e5-3da8bab26a92.png)

I had a quick looksie, and honestly couldn't see anything that looked especially suspect here where there was some special codepath that was taken if the channel count = 4.

Many thanks,
Alister

**Comment by alister-chowdhury** [comment]
I added a cheeky `std::cout << alpha << '\n';` in the `divide_by_alpha` routine, when applied to an 8x8, the results are... unexpected:
```
-2.53229e-29
-3.949e+28
-2.53229e-29
-3.949e+28
-2.53229e-29
-3.949e+28
-2.53229e-29
-3.949e+28
-2.53229e-29
-3.949e+28
-2.53229e-29
-3.949e+28
-2.53229e-29
-3.949e+28
-2.53229e-29
-3.949e+28
-2.5477e-29
inf
-0
-2.46812e+28
-3.85797e-34
```

**Comment by alister-chowdhury** [comment]
Aha!
I have found the bug!

```
@@ -1183,11 +1189,12 @@ ImageBufAlgo::fillholes_pushpull(ImageBuf& dst, const ImageBuf& src, ROI roi,
         w = std::max(1, w / 2);
         h = std::max(1, h / 2);
         ImageSpec smallspec(w, h, src.nchannels(), TypeDesc::FLOAT);
+        smallspec.alpha_channel = topspec.alpha_channel;
         ImageBuf* small = new ImageBuf(smallspec);
         ImageBufAlgo::resize(*small, *pyramid.back(), "triangle");
         divide_by_alpha(*small, get_roi(smallspec), nthreads);
         pyramid.emplace_back(small);
```

I'll make a PR shortly.

**Comment by lgritz** [comment]
I see, that makes sense. With 2 channels, it doesn't necessarily know that the second one is supposed to be alpha (whereas with 4 channels, it makes that guess and will tend to be right.  Good find!
