### ISSUE TITLE
[BUILD] will not build with openexr/Imath 3

### ISSUE THREAD

**Issue by pgajdos** [OpenImageIO/oiio#2945]
This is with 8.0.1 and 7.2.3.

```
[    4s] -- ----------------------------------------------------
[    4s] -- ------------- Configuring OpenVDBCore --------------
[    4s] -- ----------------------------------------------------
[    4s] CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
[    4s]   Could NOT find IlmBase (missing: IlmBase_INCLUDE_DIR) (Required is at least
[    4s]   version "2.2")
[    4s] Call Stack (most recent call first):
[    4s]   /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:582 (_FPHSA_FAILURE_MESSAGE)
[    4s]   cmake/FindIlmBase.cmake:258 (find_package_handle_standard_args)
[    4s]   openvdb/openvdb/CMakeLists.txt:49 (find_package)
```

**Comment by pgajdos** [comment]
Build log here:
https://build.opensuse.org/package/live_build_log/home:pgajdos:openexr3/openvdb/openSUSE_Factory_openexr3/x86_64

**Comment by lgritz** [comment]
The logs indicate that you are having trouble building OpenVDB. But this issue is on the OpenImageIO project. I think maybe you posted to the wrong project?

**Comment by hobbes1069** [comment]
FYI I'm in the same situation. Most of the packages in Fedora have failed to build with OpenEXR 3.0 but some (many?) of them may be due to Ilm being included in the new imath library. I'll open a new issue if it's something I can't fix on my own.

**Comment by pgajdos** [comment]
@lgritz not sure how that happened. Perhaps I had both bug trackers opened. Sorry for the noise.
