### ISSUE TITLE
[BUG] Texture conversion causes null pointer dereference with test .exr files

### ISSUE THREAD

**Issue by etheory** [OpenImageIO/oiio#2950]
**Describe the bug**
When using Windows 10 with OpenImageIO-2.2.10.0 results in certain .exr files causing segfaults during texture conversion.

**To Reproduce**
1. Download https://github.com/AcademySoftwareFoundation/openexr-images
2. With regards to the images, texture convert them using the options:
```
    config.attribute("maketx:nomipmap", false);
    config.attribute("maketx:oiio_options", true);
    config.attribute("maketx:checknan", true);
    config.attribute("maketx:filtername", "lanczos3");
    config.attribute("maketx:fileformatname", "tx");
```
Then any of the following textures:

- openexr-images\v2\LeftView\Ground.tx
- openexr-images\v2\LeftView\Leaves.tx
- openexr-images\v2\LeftView\Trunks.tx
- openexr-images\v2\LowResLeftView\composited.tx

3. Result in a segfault here: https://github.com/OpenImageIO/oiio/blob/5c96e9df6b3af74dd751bbc176290559cbca18d9/src/include/OpenImageIO/fmath.h#L1145 due to src being a nullptr

**Expected behavior**
I don't think any texture conversion should result in a segfault, instead, it should result in a warning indicating the conversion issue.

**Evidence**
![image](https://user-images.githubusercontent.com/1401669/115219487-eebdcc80-a14a-11eb-8bb7-b9d992978d09.png)

**Platform information:**
 - OIIO branch/version: 2.2.10.0
 - OS: OS Name: Microsoft Windows 10 Home - Version 10.0.19041 Build 19041
 - C++ compiler: Visual Studio Community 2019
 - Any non-default build flags when you build OIIO: default build for vcpkg x64-windows

**IF YOU ALREADY HAVE A CODE FIX:** There is no need to file a separate issue,
please just go straight to making a [pull request](https://github.com/OpenImageIO/oiio/pulls).

**Comment by lgritz** [comment]
You are quite right. The problem here was that those input images were "deep", which can't be used for textures. 
Nobody but you has ever tried, I guess. Fix in PR #2991.
