### ISSUE TITLE
[FEATURE REQUEST] Make finding Boost a bit more flexible

### ISSUE THREAD

**Issue by zomgrolf** [OpenImageIO/oiio#2956]
**Is your feature request related to a problem? Please describe.**
When building OIIO on Windows we tend to link almost all of its dependencies statically (i.e. with `LINKSTATIC` set to true). However, in some cases we want to link Boost dynamically (while other dependencies are still linked as static libs). While it's not too difficult to set up, it still requires some wrangling with the build system and I'd really like to make it a bit more straightforward.

**Describe the solution you'd like**
There is the `BOOST_CUSTOM` option, but using it requires carefully setting up all the variables, rather than letting the FindBoost module take care of that. Looking at [externalpackages.cmake](https://github.com/OpenImageIO/oiio/blob/f46c8b9a0f62738f1699c57a73368772c71f3b6c/src/cmake/externalpackages.cmake#L39) a fairly small change would enable the scenario I'm interested in (being able to choose the way Boost is linked independently from the `LINKSTATIC` setting) without the need for the fully manual setup.
The script uses the `Boost_USE_STATIC_LIBS` variable to tell FindBoost which type of libraries to look for. If `LINKSTATIC` is true, then it gets set to true as well, which means FindBoost will try to find static boost libraries. If it's not true, it seems to assume that `Boost_USE_STATIC_LIBS` is false, but that's not necessarily the case -- someone could still set it to true. 

I'd like to propose the following change: check if `Boost_USE_STATIC_LIBS` has already been defined, and if not, set it to the current value of the `LINKSTATIC` variable. Then, based on the value of `Boost_USE_STATIC_LIBS` add the necessary definitions for the MSVC compiler:
```
if (NOT DEFINED Boost_USE_STATIC_LIBS)
    # Set Boost_USE_STATIC_LIBS to true, but only if linking dependencies statically
    if (LINKSTATIC)
        set (Boost_USE_STATIC_LIBS ON)
    endif()
    # Or perhaps: set (Boost_USE_STATIC_LIBS "${LINKSTATIC}")	
endif ()

if (MSVC)
    if (NOT Boost_USE_STATIC_LIBS)
        add_definitions (-DBOOST_ALL_DYN_LINK=1)
    endif ()
endif () 
```
That would let the user set `Boost_USE_STATIC_LIBS` independently of the `LINKSTATIC` setting. Of course, that is a breaking change -- someone could be setting `Boost_USE_STATIC_LIBS` and expecting it to get ignored because they link dependencies statically. Knowing how these things go, someone is probably relying on this behavior to find the cure for cancer...

**Describe alternatives you've considered**
Using `BOOST_CUSTOM` and setting everything up manually.

**Comment by lgritz** [comment]
Hi, I rarely build for static libs, so this is a little outside my deep expertise. 

Can you propose the change you want as a PR, and if it passes all the CI tests, I'll be happy to merge it?
