### ISSUE TITLE
ImageCacheImpl exposed in ImageCache.h header

### ISSUE THREAD

**Issue by etheory** [OpenImageIO/oiio#2980]
I might be missing something obvious here but:
https://github.com/OpenImageIO/oiio/blob/9d4c6959b9da974b9f561427cc35ad6313327a24/src/include/OpenImageIO/imagecache.h#L30
why is ImageCacheImpl forward declared in ImageCache.h when it doesn't seem to be used anywhere?

Isn't this exposing the unneccessary knowledge that ImageCacheImpl provides the default implementation?

For someone sub-classing ImageCache for a custom implementation, I don't think they need that knowledge, since they might choose to implement it differently?

TextureSystemImpl is different in texture.h since it's directly used by the friend statement.

**Comment by etheory** [comment]
I just realized that ImageCacheImpl is an opaque concept, so it doesn't matter.

**Comment by lgritz** [comment]
I'm not sure I recall exactly why that's referenced in imagecache.h. Perhaps it no longer needs to be.
