### ISSUE TITLE
[BUG] Division by zero reading invalid image

### ISSUE THREAD

**Issue by DougRogers** [OpenImageIO/oiio#2982]
Image is a test case.

[b33651913.zip](https://github.com/OpenImageIO/oiio/files/6563408/b33651913.zip)

```
bool
ImageInput::read_image(int subimage, int miplevel, int chbegin, int chend,
                       TypeDesc format, void* data, stride_t xstride,
                       stride_t ystride, stride_t zstride,
                       ProgressCallback progress_callback,
                       void* progress_callback_data)
```
`        int chunk = std::max(1, (1 << 26) / int(spec.scanline_bytes(true)));`
It appears
`spec.scanline_bytes(true)`
return zero.

**Comment by lgritz** [comment]
Thanks for the example image. Fix proposed in #2983
