### ISSUE TITLE
What is the variable name when setting custom installation path in CmakeList?

### ISSUE THREAD

**Issue by mosjoker** [OpenImageIO/oiio#3010]
I tried 
```
set(OpenImageIO_DIR ${custom_path}/cmake/OpenImageIO)
find_package(OpenImageIO 2.0.9 REQUIRED)
```
OpenImageIO_DIR right?

**Comment by lgritz** [comment]
That depends, potentially, on a lot of things:

* What version of OIIO? Are you really using 2.0.9, or is that just a minimum?
* What version of CMake?
* Are you relying on OIIO's exported cmake config, or do you have a FindOpenImageIO.cmake module?

If you are using a currently supported OIIO (2.2 or higher, and which requires CMake >= 3.12), the answer would be OpenImageIO_ROOT.

**Comment by mosjoker** [comment]
@lgritz  Thank you for your reply.  Solved.
