### ISSUE TITLE
[FEATURE REQUEST] Add overload of ImageCache::invalidate(ImageHandle*)

### ISSUE THREAD

**Issue by anderslanglands** [OpenImageIO/oiio#3034]
**Is your feature request related to a problem? Please describe.**
ImageSpec* ImageCache::imagespec(ImageHandle*, ...) returns a pointer to an ImageSpec that is valid until the ImageCache is destroyed, or until invalidate() is called on the file that the ImageHandle refers to. In the Rust bindings I could enforce this in the type system by consuming the ImageHandle when calling invalidate(), only there's no overload of invalidate() that takes an ImageHandle* instead of a ustring. 

**Describe the solution you'd like**
I would like an overload of ImageCache::invalidate that takes an ImageHandle* 

**Describe alternatives you've considered**
Unless I'm missing it, there doesn't appear to be a way of getting the filename from the ImageHandle, in which case my only option would be to store the filename in my ImageHandle wrapper itself (not the end of the world I suppose).

**Additional context**

**Comment by lgritz** [comment]
Piece of cake! I'll do this for you right away.

(As for why you can't get the filename from the handle... I think the idea was that since you needed the filename to get the handle in the first place, I figured you wouldn't have forgotten it so quickly.)

**Comment by anderslanglands** [comment]
Thanks Larry!
