### ISSUE TITLE
[BUG] oiio always describes EXR as openexr:version: 1, even when presented with a v2 exr.

### ISSUE THREAD

**Issue by voodoonofx** [OpenImageIO/oiio#3041]
This might actually be a feature request...

**EXR Images are always tagged with version 1**

According to page 5 of the [EXR spec](https://www.openexr.com/documentation/openexrfilelayout.pdf), while the magic numbers of the EXR header are always `76 2F 31 01` (`"v/1"` in ASCII), the next 4 bytes indicate the OpenEXR version of the file (with some other useful bit-shifted bits). However, OIIO always results in an attribute `openexr:version: 1`, regardless of the actual version of the EXR that exists in the file. This is true for iinfo, oiiotool, and the python bindings.

Along these lines, handling (and exposing) additional `openexr:` prefixed items could/should be exposed to parse the encoded data in bytes 5-8. Of particular interest is bit 12, indicating if a file is multi-part.

**To Reproduce**
Take any EXR image written as a version 2 EXR (byte 5 == 0x02):
```bash
# iinfo -a -v /tmp/BUS1835_cmp_lum_v0007.1037.exr
/tmp/BUS1835_cmp_lum_v0007.1037.exr : 2156 x 1136, 3 channel, half openexr
    3 subimages: 2156x1136 [h,h,h], 2156x1136 [h], 2156x1136 [h]
 subimage  0: 2156 x 1136, 3 channel, half openexr
    openexr:version: 1
 subimage  1: 2156 x 1136, 1 channel, half openexr
    openexr:version: 1
 subimage  2: 2156 x 1136, 1 channel, half openexr
    openexr:version: 1

(Some key/value pairs removed to protect the innocent)
```
For my example file, the first hex-encoded bytes of this file are:
`76 2F 31 01` `02 10 00 00` which indicate the file is OpenEXR 2.0+, and contains multi-part images.

**Expected behavior**
Ideally, OIIO will parse this field, setting the `openexr:version` field appropriately. Additional fields could be exposed as well such as `openexr:multipart` (if bit 12 is 1), `openexr:multichannel` (if bit 12 is 0), as well as others for the 4 bits of interest here. This would allow an extremely fast conditional handling of an image, especially when trying to determine if the image conforms to a project's delivery spec (which is my use-case here).

**Platform information:**
 - OIIO branch/version: Current Master (but tested in Fedora Core 32's dnf installed OpenImageIO 2.1.20
 - OS: Linux
 - C++ compiler: gnu gcc 10.3.1
 - Any non-default build flags when you build OIIO: Whatever they do in https://src.fedoraproject.org/rpms/OpenImageIO/blob/f34/f/OpenImageIO.spec

**Comment by lgritz** [comment]
OpenImageIO is just setting its "openexr:version" attribute to whatever the "version" metadata is in the exr file.

Even `exrheader` shows this to be 1 in clearly 2.0 file format images. There is also a `version()` method in `InputFile` (and related). Maybe that would be better to use?

@kdt3rd @cary-ilm any insight on the semantic difference between the "version" metadata versus what's returned by InputFile::version()?

**Comment by cary-ilm** [comment]
Correct me if I'm wrong, but the OpenEXR library itself does not provide "version" metadata by default, so that must be coming from somewhere else?

**Comment by lgritz** [comment]
```
$ exrheader v2/LeftView/Balls.exr

file v2/LeftView/Balls.exr:

file format version: 2, flags 0x800
channels (type chlist):
    A, 16-bit floating-point, sampling 1 1
    B, 16-bit floating-point, sampling 1 1
    G, 16-bit floating-point, sampling 1 1
    R, 16-bit floating-point, sampling 1 1
    Z, 32-bit floating-point, sampling 1 1
chunkCount (type int): 761
compression (type compression): zip, individual scanlines
dataWindow (type box2i): (247 319) - (1677 1079)
displayWindow (type box2i): (0 0) - (1919 1079)
lineOrder (type lineOrder): increasing y
name (type string): "rgba.left"
owner (type string): "Copyright 2012 Weta Digital Ltd"
pixelAspectRatio (type float): 1
screenWindowCenter (type v2f): (0 0)
screenWindowWidth (type float): 1
type (type string): "deepscanline"
version (type int): 1
view (type string): "left"
```

This is one of the openexr-images files. For some reason, there is a metadata called "version", set to 1. What is that supposed to be?

It also says `file format version: 2` (I checked, that comes from the version() method of the ImfScanlineInputFile), but that's not giving me what I want, either, for example on this clearly openexr 1.x file:

```
$ exrheader ScanLines/Desk.exr

file ScanLines/Desk.exr:

file format version: 2, flags 0x0
channels (type chlist):
    A, 16-bit floating-point, sampling 1 1
    B, 16-bit floating-point, sampling 1 1
    G, 16-bit floating-point, sampling 1 1
    R, 16-bit floating-point, sampling 1 1
compression (type compression): piz
dataWindow (type box2i): (0 0) - (643 873)
displayWindow (type box2i): (0 0) - (643 873)
lineOrder (type lineOrder): increasing y
pixelAspectRatio (type float): 1
screenWindowCenter (type v2f): (0 0)
screenWindowWidth (type float): 1
type (type string): "scanlineimage"
```

which says it's file format version 2, but certainly is not.

I'm  beginning to think that there is no way through the Imf API to actually tell which version of file it is (you could infer that if it's multi-part or deep, that it's 2.x, but are there any other 2.x cases that are neither deep nor multi-part?).

**Comment by cary-ilm** [comment]
I believe that the interpretation of the version number in the file is "was written by a library that implements that file version". GenericOutputFile::writeMagicNumberAndVersionField() writes EXR_VERSION, which has been hardcoded to "2" since OpenEXR 2.0. That probably just means that "Desk.exr" was written by a more recent library. 

It looks like all the images in https://github.com/AcademySoftwareFoundation/openexr-images have the file version type set to 2, although several have metadata version set to 1, but it's not clear where that came from.

**Comment by lgritz** [comment]
Fascinating plot twist!

**Comment by lgritz** [comment]
So, to summarize:

1. Some (but not all) of OpenEXR's own example files have metadata called "version", which I **INCORRECTLY** interpreted as the exr version of the file, but it's not. In fact, it may be that nobody quite remembers why it's there. It's just arbitrary metadata, and I should never have renamed it "openexr:version" to imply that it's the openexr file format version.

2. The API has `Input*File::version()`, but that isn't the file format version, either; it is effectively always 2 for OpenEXR 2.x library (and 3.x!). Technically, it means "the library implements version 2 of the file format" (e.g., OpenEXR >= 2.0.0), but is not specific to the file you're reading.

3. Byte 5 of an exr file (which I would have to directly read from the file, there is no API call that retrieves it) also has a version number. But as far as I can tell, just like InputFile::version(), this will always be 2 if the file was written by version >= 2.0 of the library, even if it is an old school vanilla file that can still be read by OpenEXR 1.x.

**Comment by cary-ilm** [comment]
GenericInputFile::readMagicNumberAndVersionField() has this:

```
    OPENEXR_IMF_INTERNAL_NAMESPACE::Xdr::read <OPENEXR_IMF_INTERNAL_NAMESPACE::StreamIO> (is, version);

    if (getVersion (version) != EXR_VERSION)
    {
        THROW (IEX_NAMESPACE::InputExc, "Cannot read "
                              "version " << getVersion (version) << " "
                              "image files.  Current file format version "
                              "is " << EXR_VERSION << ".");
    }
```
So it appears that a library that supports version 2 will reject all input files of version 1. I didn't think that was the case, but that was before my time.

**Comment by lgritz** [comment]
That doesn't make sense and clearly isn't true. I've never had trouble reading an old exr file with a new library.

**Comment by lgritz** [comment]
Can you imagine the pitchforks that would have come out when OpenEXR 2.0 release if people found that switching to the new library had rendered them unable to read any previously-written exr files? No way.

**Comment by cary-ilm** [comment]
EXR_VERSION appears to be _very_ old, it's been set to "2" since at least 2003:

https://github.com/AcademySoftwareFoundation/openexr/blob/OPENEXR_1_0_4/OpenEXR/IlmImf/ImfVersion.h

So it looks like the 1 changed to 2 in a hard break very early on at ILM, before the first public release, and things have been backwards compatible ever since?  I'm just guessing based on looking at the code.

@peterhillman, do you recall what happened to the format version when you added deep support?

**Comment by lgritz** [comment]
Oh, I wonder, then, if "version 1" is the pre-opensource ILM internal format, and "version 2" was *all* versions of OpenEXR, due to some revision in file layout made in the process of preparing it for release.

**Comment by cary-ilm** [comment]
GenericeOutputFile::writeMagicNumberAndVersionField() packs several pieces of information into the "version" field beyond the basic number, with bits that say whether the file is tiled, multi-part, deep, etc. exrheader reports this extra information as "flags". So the "version" field is much more basic than one would initially believe, it's really the "flags" that indicate the content of the file.
 
```
    int version = EXR_VERSION;

    if (parts == 1)
    {
        if (headers[0].type() == TILEDIMAGE)
            version |= TILED_FLAG;
    }
    else
    {
        version |= MULTI_PART_FILE_FLAG;
    }
    
    for (int i = 0; i < parts; i++)
    {
        if (usesLongNames (headers[i]))
            version |= LONG_NAMES_FLAG;

        if (headers[i].hasType() && isImage(headers[i].type()) == false)
            version |= NON_IMAGE_FLAG;
    }
```

GenericInputFile::readMagicNumberAndVersionField() checks the flags to determine if the library can read the contents (and reports the results with a rather cryptic error message):

```
    if (!supportsFlags (getFlags (version)))
    {
        THROW (IEX_NAMESPACE::InputExc, "The file format version number's flag field "
                              "contains unrecognized flags.");
    }
```

**Comment by lgritz** [comment]
Given that there is no simple call and no true version in the file (other than noticing that it's multi-part, deep, or has long names), should I even try to communicate this information at all? Is there any point for OIIO to set an attribute that contains the flag values or something? Or should I just stop incorrectly renaming "version" to "openexr:version", and call it a day?

What would be the point in asking, or knowing, what "version" the file is? The only thing I can think of is if you are using OIIO to try to identify if you have any openexr files that wouldn't be readable by a different app using openexr 1.x. Are there still any such apps? How would knowing that help?

@voodoonofx I think this is really a question for you. Do you need to know the version of the file? Or are you just noting that the version we are reporting was not conveying the information you (or I!) thought it did?

**Comment by peterhillman** [comment]
As @cary-ilm says, the "version" number isn't really useful.  Changes to the file format that break backwards compatibility are signalled by the bitmask, not the version integer. An older OpenEXR library should refuse to read a file that has a bit set that it doesn't understand. The idea is that a newly created file should still be readable by an older library version if it only uses features understood by that older library. It would make sense to increment the version integer if a change was made the file layout that broke backwards compatibility in all cases, or when all the version bits are used up.

Deep parts also contain a version number as an attribute. That's so a change to the deep scanline/tile data structure could be made. An older version of the library encountering a new version number would not be able to read the data from that part, but could still understand its header, and read other parts from the file.

Does OIIO indicate the setting of the bitmask? That's what you need to check a file's compatibility with 1.x. That might not be an issue any longer, but a future change might use another field in the bitmask, which it would be useful to check too.

For what it's worth, I made a tool which indicates a file as being an "EXR-2" if the multipart or non-image bits are set, or if any part has a compression type set to DWAA or DWAB

**Comment by lgritz** [comment]
OIIO doesn't (currently) let you get the bitmask. I could easily communicate that back, but I'm not really sure what the use case is. Nobody has ever asked for it. In general, we are trying to hide anything that is ultra specific to the file format, unless it is important and that information is actionable on the user's part.

**Comment by lgritz** [comment]
Minimal proposed change in #3044

This just STOPS mistaking the user attribute "version" for anything having to do with the file format -- it is not renamed "openexr:version" and has no special semantic meaning.

**Comment by dekekincaid** [comment]
Just some additional thought on this.  Even having a version does not guarantee any ability to read it between versions.  OpenEXR 1.x introduced support for long channel/layer names(31 char vs 256) and long key value pairs in metadata which broke all compatibility with libraries compiled without that option to read the files.  

OpenEXR 2 -> 1 backward compatibility is possible with 2.X if you use the right combination of single part, compression and short metadata keys/channel/file names.  People had to do this for many years after 2.x came out because DI applications were so far behind on their library versions. This always been very inside baseball knowledge though.  No one every had a write 1.5, 1.7 or 2.x EXR version.  

This all being said having the version of the library in a key would be nice.  It is always useful when that information is inside a file from another vendor with the oiiotool command used to write the file so I can sudo reverse engineer where the file came from and what colorspace they used.

**Comment by voodoonofx** [comment]
> Given that there is no simple call and no true version in the file (other than noticing that it's multi-part, deep, or has long names), should I even try to communicate this information at all? Is there any point for OIIO to set an attribute that contains the flag values or something? Or should I just stop incorrectly renaming "version" to "openexr:version", and call it a day?
> 
> What would be the point in asking, or knowing, what "version" the file is? The only thing I can think of is if you are using OIIO to try to identify if you have any openexr files that wouldn't be readable by a different app using openexr 1.x. Are there still any such apps? How would knowing that help?
> 
> @voodoonofx I think this is really a question for you. Do you need to know the version of the file? Or are you just noting that the version we are reporting was not conveying the information you (or I!) thought it did?

Like everyone else, I incorrectly read 'openexr:version' as a reliable way to detect if a file is 2.0+ (multi-part), but checking the number of sub-images is more reliable in my use case. Perhaps it's just nice to have some additional exr specific flags to check quickly if a file is multi-part, multi-channel, etc according to what's set in the bit flags. Though, that's simple enough for me to extract byte 5-8 and find out for myself.

Thank you for diving so deeply into this one!
