### ISSUE TITLE
iv - togglable overlay of the display & data windows

### ISSUE THREAD

**Issue by lgritz** [OpenImageIO/oiio#308]
Add a toggleable visual overlay to outline the location of the
display window, and/or the data window. (I can suggest color for these
to match other apps).  By default, only show the display window, but
should a dotted-line outside the display window, for the data window,
demonstrating what additional pixels are available.

**Comment by lgritz** [comment]
Coalescing

**Comment by tkchanat** [comment]
PR created here: https://github.com/AcademySoftwareFoundation/OpenImageIO/pull/4443
