### ISSUE TITLE
[BUILD]openimageio binding in python doubt

### ISSUE THREAD

**Issue by ShawnDen-coder** [OpenImageIO/oiio#3081]
hello;

I am using the brew install openimageio, unable to success will be my/usr/local/Cellar/openimageio 2.2.17.0 / lib, and my python3.7 binding.Can I have a detailed demonstration? Do I not quite understand how openimageio is installed on my python3.7

**Comment by lgritz** [comment]
Old and not very descriptive. Closing, with apologies that nobody directly replied as soon as it was filed. If this is still a problem, please re-open with a detailed description of how to reproduce.
