### ISSUE TITLE
[BUG] png and pnm plug-ins do not set default ColorSpace

### ISSUE THREAD

**Issue by MarkCallow** [OpenImageIO/oiio#3084]
**Describe the bug**
When a PNG file without any color space chunks (no sRGB, iCCP or gAMA) is read the plug-in does not set the `oiio:ColorSpace` attribute.

The pnm plug-in also does not set `oiio:ColorSpace`.

**To Reproduce**
1. Set a breakpoint at the line after a program calls `ImageSpec::find_attribute("oiio:ColorSpace")`
2. Open a .png file with no color space info or open a pnm file.
3. Observe that return value from `find_attribute` is `nullptr`.

**Expected behavior**
I expect the plug-ins to set the default color space information specified by the file format. Both the jpeg and webp plug-ins set `oiio:ColorSpace` to "sRGB" when there is no information in the file, the usual case. Like those specs, the PNG spec says sRGB is to be assumed in the absence of color space info. The PNM spec says that the images are in Rec709 space so that plug-in should set `oiio:ColorSpace` to "rec709".

**Evidence**
I'm attaching a png file with no color space info. No PNM (.pam, .pgm, .ppm) files have color space info so you can try with any file you can find.

![color_grid](https://user-images.githubusercontent.com/2244683/131670079-daed299f-d5a5-4eb9-966d-4662e0d318d2.png)

**Platform information:**
 - OIIO branch/version: 2.1.17
 - OS: macOS 11.5.2
 - C++ compiler: Clang
 - Any non-default build flags when you build OIIO:

**Comment by fabiencastan** [comment]
We have seen the same issue with png created by ffmpeg, the png does not contain the colorspace metadata.
And when we load it in OpenImageIO, the "oiio:ColorSpace" metadata is missing. We were assuming that oiio would set it in all cases.

**Comment by lgritz** [comment]
Fix proposed in #3321
