### ISSUE TITLE
iv color scheme

### ISSUE THREAD

**Issue by lgritz** [OpenImageIO/oiio#311]
We should change to (or at least have an option for) the the darker color scheme of professional apps.  Our current "dark palette" is an incomplete step in this direction.  Let's do it right.

**Comment by wrosecrans** [comment]
Do people still feel strongly about this?  Would just using https://github.com/ColinDuquesnoy/QDarkStyleSheet be adequate, or should there be a fully custom color set?  If it's an option, is setting at startup adequate, or does it need to be switable live during runtime?  i've used QDarkStylesheet in a previous project,a nd it's pretty easy to bolt on, sicne all the hard work is already done.  MIT licensed, so I think it's something we can just grab if we wanted to.

**Comment by lgritz** [comment]
Coalescing
