### ISSUE TITLE
[BUG] Cannot link against static OCIO

### ISSUE THREAD

**Issue by Arbeyem** [OpenImageIO/oiio#3236]
**Describe the bug**
Impossible to link against static OCIO with current CMake scripts.

**To Reproduce**
This became an issue since #2529.  The logic in src/cmake/modules/FindOpenColorIO.cmake is still correct, but the OpenImageIO library no longer links against tinyxml and yaml-cpp, causing undefined symbols.

**Expected behavior**
If OCIO is found and LINKSTATIC is defined, also target tinyxml and yaml-cpp when linking the OpenImageIO library.

**Platform information:**
 - OIIO branch/version:  Started during OIIO 2.1 (found using 2.1.20).  Current logic in master still has this issue. 
 - OS: Found in Windows, also present in Linux (CentOS 7)
 - C++ compiler:  MSVC14
 - Any non-default build flags when you build OIIO: LINKSTATIC=ON, BUILD_SHARED_LIBS=OFF

**Comment by DougRogers** [comment]
Can you link to the static version in vcpkg?

**Comment by lgritz** [comment]
I think this may be addressed by the recent #3278, which altered FindOpenColorIO.cmake so that it prefers an OpenColorIO exported cmake config if one is available (which it should be for OCIO 2.1), and that config ought to get the dependency libraries right.

**Comment by Arbeyem** [comment]
> I think this may be addressed by the recent #3278, which altered FindOpenColorIO.cmake so that it prefers an OpenColorIO exported cmake config if one is available (which it should be for OCIO 2.1), and that config ought to get the dependency libraries right.

That solution works for me.  The implementation of OPENCOLORIO_INTERFACE_LINK_LIBRARIES is a great addition.
