### ISSUE TITLE
[FEATURE REQUEST] Please add more python-specific examples to the docs and simplify the syntax for image read/write

### ISSUE THREAD

**Issue by KeygenLLC** [OpenImageIO/oiio#3241]
I'm having no luck finding any examples of how to pass numpy arrays to OpemImageIO so I can save float EXR files with subimages. With most python image libraries, numpy arrays are expected, so you can pass them along easily and not require tons of code to do it. This doesn't seem to be so with OpenImageIO. I saw the feature request  #2954 and that is how I actually tried to set it up first :)

I'm not a hardcore programmer, so maybe this stuff is simple to you guys. Your docs are honestly the most confusing I've read of the dozen or so image libraries I've tried, though possibly more from my lack of experience and your primary examples not being for python.

The only example I found of just opening several files to save to an exr that was close to comprehensive came from an issue on here, and the syntax was outdated from around 2016 (using `oiio.AppendSubimage`), which now just uses `"AppendSubimage"`. I did finally find the one spot in the docs for python that listed the new way.

```python
for i in paths:
    image_in = oiio.ImageInput.open(i)
    spec = image_in.spec()
    pixels = image_in.read_image(oiio.FLOAT)
    img_specs.append(spec)
    img_pixels.append(pixels)
    image_in.close()

output = oiio.ImageOutput.create(out_exr)
output.open(out_exr, tuple(img_specs))

for i, s in enumerate(img_specs):
    if i > 0:
        output.open(out_exr, s, "AppendSubimage")
    output.write_image(img_pixels[i])
output.close()
```
This seems unnecessarily lengthy. With Python, I would expect to just have to read `image_in` and `append` each to a list and nothing more. 2 lines instead of 6, and the pulling of `spec` and `pixels` would be done behind the scenes. Libraries that allow for multipage TIFF are simplified this way.

For those who need to specify spec, having it available is great. But if you have images/arrays that are all the same shape with the same number of channels, OpenImageIO should not need to have those things specifically coded.

Solution?
---
Clear and concise examples in the docs using Python without print functions. While seeing examples with `print()` is useful at times to see what is going on, the continual use of `print()` clutters up the code and makes it harder to read, at least for me.

Simplified syntax for reading multiple images from disk or from numpy arrays, and then writing those to flat files or those with subimages/layers. I'm no programming wizard, and this may be more trouble than it's worth, but here's some suggestions for simplifying. Anything with shorter and more logical syntax would be a plus.

```python
paths = [path1, path2, path3]
images = []

for p in paths:
    image = oiio.ImageInput.open(p)
    images.append(image)
    
file_path = os.path.join(MY_PATH, 'layeredEXR.exr')
ImageOutput.write_image(file_path, images, "AppendSubimage")

## And for a list of numpy arrays, perhaps something like:
images = [array1, array2, array3]
buf = oiio.ImageBuf(images)
    
file_path = os.path.join(MY_PATH, 'layeredEXR.exr')
ImageOutput.write_image(file_path, buf, "AppendSubimage")

# or just read the arrays directly and do everything behind the scenes...
with oiio.ImageOutput(file_path) as exr:
    for array in images:
        exr.write_image(array, "AppendSubimage", "float")
```

**Describe alternatives you've considered**
Honestly, there really are no alternatives. Your library seems to be the only thing for Python that can write layered float32 RGB EXR files. Everything else I tried did not support it or had tons of errors just trying to install it. Having clear examples and simplified syntax would negate the need to use any other library.

**Additional context**
I have use cases in my project where I need to open some files and save them in a layered EXR, but most times I'm manipulating things in Python and want to save multiple images from arrays into one file. I wouldn't assume this is something so esoteric that there would be no examples for it anywhere. Even after scouring the mailing list archives I have yet to find an answer and all the code snippets I pulled failed to work.

**Comment by lgritz** [comment]
> I'm having no luck finding any examples of how to pass numpy arrays to OpemImageIO so I can save float EXR files with subimages. With most python image libraries, numpy arrays are expected, so you can pass them along easily and not require tons of code to do it. This doesn't seem to be so with OpenImageIO. I saw the feature request #2954 and that is how I actually tried to set it up first :)
> I'm not a hardcore programmer, so maybe this stuff is simple to you guys. Your docs are honestly the most confusing I've read of the dozen or so image libraries I've tried, though possibly more from my lack of experience and your primary examples not being for python.

I would love for you to point me to specific documentation for other image libraries that you think are less confusing, so we can learn from those and figure out where we're going wrong. Lack of documentation is not a frequent complaint that we see.

In the Python bindings, actually *all* methods that accept pixel data do so by taking numpy arrays.

#2954 is specifically about initializing an ImageBuf solely with a numpy array. I'll try to get to that. But that's not directly relevant as far as I can tell, because in all your examples, you're dealing with the ImageOutput interface, not ImageBuf.

It is true that the library is primarily C++, with Python bindings added and probably a bit lighter on documentation than they should be. And in particular, maybe there's not a clear example of writing a multi-image file. I'm in the middle of beefing up the docs for Python, so here at least is a downpayment that addresses this particular issue: #3244


> For those who need to specify spec, having it available is great. But if you have images/arrays that are all the same shape with the same number of channels, OpenImageIO should not need to have those things specifically coded.

I think for most of our users, that's an unusual case. In general, you expect something to be different for each subimage, even if it's just the names of the channels, or other metadata. The resolution and channels (which, yes, can be inferred from the data array) are a small subset of what can be in the spec.


> ImageOutput.write_image(file_path, images, "AppendSubimage")

I see, so what you are suggesting is a variety of write_image that can take all the subimages at once and write the whole file? That actually seems pretty reasonable.

> And for a list of numpy arrays, perhaps something like:
> images = [array1, array2, array3]
> buf = oiio.ImageBuf(images)

That's a little trickier, because an ImageBuf contains *one* image, there's no such thing as a multi-image ImageBuf (as it is currently designed).

Anyway, I think that #3244 does specifically address the example you were looking for.

**Comment by KeygenLLC** [comment]
Hope you had a nice holiday. My browser just crashed and I lost everything I was writing somehow.... so hopefully I can remember what I wrote.

 > I would love for you to point me to specific documentation for other image libraries that you think are less confusing, so we can learn from those and figure out where we're going wrong. Lack of documentation is not a frequent complaint that we see.

As I said, I think it's probably a problem with me, and not the docs. Due to how much this library can do, the docs are dense.  I was expecting to see more basic examples but I can understand why they aren't there. Most people using a library like this they're probably fine the way they are.

> In the Python bindings, actually _all_ methods that accept pixel data do so by taking numpy arrays.
> 
> #2954 is specifically about initializing an ImageBuf solely with a numpy array. I'll try to get to that. But that's not directly relevant as far as I can tell, because in all your examples, you're dealing with the ImageOutput interface, not ImageBuf.

Must be my misunderstanding then. I haven't been using python for very long so I'm probably confusing what does what. I'm opening multiple images (or creating multiple images from one, all float32 RGB data), storing them in variables as arrays, performing various operations on them, and I need to write them into a single exr without saving them individually. If that doesn't requires using buffers, that's fine. I am currently opening EXRs with `cv2.imread(path, cv2.IMREAD_UNCHANGED)` and then on to numpy arrays, passing them through various functions. I'm obviously not passing this data correctly to oiio.

> It is true that the library is primarily C++, with Python bindings added and probably a bit lighter on documentation than they should be. And in particular, maybe there's not a clear example of writing a multi-image file. I'm in the middle of beefing up the docs for Python, so here at least is a downpayment that addresses this particular issue: #3244

Thanks, man. I know this library is not for entry-level stuff, and do appreciate it. I worked in VFX industry for many years as an artist, and what I'm doing is complicated on the art side, but I never had to go deeper than writing the occasional expression or MEL script, though Renderman certainly wasn't for the faint of heart. That's probably where the disconnect comes in. I'm using to working in GUI apps where all of this is going on behind the scenes so I'm skipping steps that are not logical to me that the library requires.

> I think for most of our users, that's an unusual case. In general, you expect something to be different for each subimage, even if it's just the names of the channels, or other metadata. The resolution and channels (which, yes, can be inferred from the data array) are a small subset of what can be in the spec.

I suppose if it was a rendering pipeline I would expect it, yes. I also keep forgetting this plug-in is for VFX when most I use aren't, so I almost expect the opposite of what annoyed me about the others when I first started using them :) But yes, in my case it's layer names and the data itself that is different, but the size/shape and channels are the same in most cases. I'm not dealing with render passes, volumetric data, ID mattes or anything, at least not yet. Just doing a lot of pixel fiddling and need to output it.

> 
> > ImageOutput.write_image(file_path, images, "AppendSubimage")
> 
> I see, so what you are suggesting is a variety of write_image that can take all the subimages at once and write the whole file? That actually seems pretty reasonable.

Cool. 

> > And for a list of numpy arrays, perhaps something like:
> > images = [array1, array2, array3]
> > buf = oiio.ImageBuf(images)
> 
> That's a little trickier, because an ImageBuf contains _one_ image, there's no such thing as a multi-image ImageBuf (as it is currently designed).

I see. Must be my confusion again. I was unsuccessful just opening an image with another library and then trying to output it with oiio (I think I was testing converting RAW to EXR), so I'm missing something obvious when it comes to passing the data along in a way it expects. I'm going to revisit it again in a few days with a clear head and take another stab at it. Finishing up a multi-threaded socket server at the moment which was a task and a half and headed toward dreaded asyncio.

> Anyway, I think that #3244 does specifically address the example you were looking for.

Sounds good man. I appreciate it. Thanks for the detailed reply and for making a tool like this available that can handle damn near anything. I was reading through the docs the past few days here and there, and it's pretty wild all the different things it can do. Started getting flashbacks of my Maya days. Seems like you could build an entire VFX pipeline with it using a few other libs for content management and such. I have a list of other tools I'd like to build with it and custom LUTs that can work with float images using OpenImageIO and OpenColorIO to streamline color grading... if I can wrap my head around 3D LUTs with 1D shapers. 👍🏻

**Comment by lgritz** [comment]
#3246 addresses the "construct ImageBuf directly from numpy array" request.
