### ISSUE TITLE
[BUG] Install silently fails with Anaconda, macOS

### ISSUE THREAD

**Issue by KeygenLLC** [OpenImageIO/oiio#3242]
**Describe the bug**
There is a bug trying to install oiio with [Anaconda](https://anaconda.org/conda-forge/openimageio). I'm not sure if you guys are in charge of distributing it through conda-forge or not, but figured I'd mention it.

I got it to install normally, once, on macOS Mojave a few weeks ago. It installed all the necessary dependencies (ilmbase, boost, etc). However, trying to install it in Big Sur the other day on another machine, and trying to install in Mojave in another Anaconda env fails presently, though it doesn't appear to. It finishes without error, Anaconda will list all the libraries as being installed, but the `.so` and other files are not in the env subfolders (or anywhere else on the system that I can find).

**To Reproduce**
1. Launch terminal, activate Anaconda env
2. `conda install -c conda-forge openimageio`
3. Package is not installed anywhere. Searching system files produces no results. Manual checks turned up empty.

**Expected behavior**
Package would be available in `/conda_install_location/envs/MYENV/lib/python3.8/site-packages`

**Evidence**
Nothing to show since it is a lack of the .so being compiled/written and no errors are thrown during install.

**Platform information:**
 - OIIO branch/version: 2.2.18
 - OS: macOS 10.14 and macOS 11.6
 - C++ compiler: clang/cmake I assume
 - Any non-default build flags when you build OIIO: didn't build it myself, used Anaconda

**Sort-of workaround:**
Since I got oiio installed recently (same version 2.2.18) I am able to copy the `.so` from my successful install to other envs and it works properly.

**Comment by lgritz** [comment]
No, we are not actually directly involved in how the library is packaged up for Conda.
I think this is an issue that should be filed against conda, I don't think there's anything we can do about it (unless whoever is responsible for the conda package happens to be reading this issue here).

**Comment by KeygenLLC** [comment]
Okay. I'll try to find who manages it. Thanks.
