### ISSUE TITLE
[BUG] vcpkg build failing on macOS

### ISSUE THREAD

**Issue by abbaswasim** [OpenImageIO/oiio#3251]
**Describe the bug**
If I install openimageio with `vcpkg install openimageio` it fails with `Error: Building package openimageio:x64-osx failed with: BUILD_FAILED` The issue is coming from https://github.com/OpenImageIO/oiio/blob/master/src/cmake/modules/FindOpenColorIO.cmake where in the version vkpkg is using has 

```
        if (LINKSTATIC)
            set_target_properties(OpenColorIO::OpenColorIO PROPERTIES
                INTERFACE_COMPILE_DEFINITIONS "-DOpenColorIO_STATIC")
        endif()
```
This results in command line like `....bin/c++ -D-DOpenColorIO_STATIC ...` which is not a valid cmake command line argument it needs to be `...bin/c++ -DOpenColorIO_STATIC ... without the second `-D`.

While the version on master has the following and doesn't have this problem.

```
        if (LINKSTATIC)
            target_compile_definitions(OpenColorIO::OpenColorIO
                INTERFACE "-DOpenColorIO_STATIC")
        endif()
```

**To Reproduce**
1. install vcpkg on macOS
2. install openimageio using `vkpck install openimageio`
3. You will get error `Error: Building package openimageio:x64-osx failed with: BUILD_FAILED` 

**Expected behavior**
vkpkg should build and install openimageio cleanly. 

**Evidence**
<img width="1320" alt="Screenshot 2021-12-29 at 12 42 05" src="https://user-images.githubusercontent.com/5260991/147663303-f9d81e51-2ada-40cb-a7d6-b487b50dcb60.png">

**Platform information:**
 - OIIO branch/version: version available in vcpkg port.cmake
 - OS: macOS 11.6.2 (20G314)
 - C++ compiler: clang++
 - Any non-default build flags when you build OIIO: N/A

I already have a code fix but this was fixed in latest version of OIIO. So I think all you need is to update/upgrade to the latest version in  vcpkg portfile. You could also argue the issue is in vcpkg repo and https://github.com/microsoft/vcpkg/blob/master/ports/openimageio/portfile.cmake file but I am not familiar with vkpkg port files. Assuming OIIO maintainers matains that?

**Comment by lgritz** [comment]
No, we don't maintain the vcpkg recipes. You should file this bug against the vcpkg project for them to update and/or apply the patches.

**Comment by abbaswasim** [comment]
Looks like latest master of `vcpkg` has fixed the issue, they are up to date. I think it's brew that needs updating now. I will leave it here and wait till that happens. You can close the issue.
