### ISSUE TITLE
[HELP] Helping cmake find the correct include location for PNG

### ISSUE THREAD

**Issue by gregcotten** [OpenImageIO/oiio#3270]
Hi!

I'm having an issue on macOS with building OIIO when I want to point PNG_Root to a specific folder.

I use in the cmake build:

```
-DPNG_ROOT={PATH_TO_PNG_ROOT}
```

It seems to get the right library location, but falls back to headers deep inside my system Mono.framework. 

I was having the same issue with pointing TIFF to the right place, but was able to get around it by adding an explicit ```-DTIFF_INCLUDE_DIR={PATH_TO_TIFF_ROOT}/include``` on top of ```-DTIFF_ROOT={PATH_TO_TIFF_ROOT}```.

With PNG, setting PNG_INCLUDE_DIRS or PNG_INCLUDE_DIR has no effect it seems.

Here's the output during the build for finding PNG:

```
-- Found PNG: {PATH_TO_PNG_ROOT}/lib/libpng16.a (found version "1.4.12") 
-- Found PNG 1.4.12 
--     PNG_INCLUDE_DIR = /Library/Frameworks/Mono.framework/Headers;/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include
--     PNG_INCLUDE_DIRS = /Library/Frameworks/Mono.framework/Headers;/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include
--     PNG_LIBRARIES = {PATH_TO_PNG_ROOT}/lib/libpng16.a;/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/libz.tbd
```

**Comment by lgritz** [comment]
Well the finding and responding to PNG in particular comes from the FindPNG.cmake module that ships with CMake itself.

Reading through that source, it looks like it uses `PNG_PNG_INCLUDE_DIR` (don't ask I didn't make up this name), so maybe building with -DPNG_PNG_INCLUDE_DIR=/path/to/png/includes might help?

**Comment by lgritz** [comment]
https://cmake.org/cmake/help/latest/command/find_library.html

says: "On macOS the CMAKE_FIND_FRAMEWORK and CMAKE_FIND_APPBUNDLE variables determine the order of preference between Apple-style and unix-style package components."

https://cmake.org/cmake/help/latest/variable/CMAKE_FIND_FRAMEWORK.html

So maybe I would suggest `-DCMAKE_FIND_FRAMEWORK=LAST` (or even NEVER?) might help ensure that the other png root location is always searched before the frameworks area.

**Comment by gregcotten** [comment]
Yep, that did it!
