### ISSUE TITLE
[BUG] searchpath_split contains empty paths

### ISSUE THREAD

**Issue by ThiagoIze** [OpenImageIO/oiio#3274]
**Describe the bug**
I haven't verified if it was this comment, but I believe the Nov 30 commit that removed using boost for `searchpath_split()` introduced a regression where now we can get empty paths returned. This was detected by our unit tests.

**To Reproduce**
Try `OIIO::Filesystem::searchpath_split(std::string(""), paths, false);` and then you should find that older OIIO returned an empty vector while the new OIIO has a vector that contains an empty string. This happens with non-empty search paths as well.

I worked around this in our code by removing empty strings, but it'd probably be better to fix this in OIIO itself, either by using my fix or by identifying what part of OIIO is allowing empty paths through:

```
      OIIO::Filesystem::searchpath_split(the_string, paths, false);
      auto it = std::remove(paths.begin(), paths.end(), std::string());
      std::distance(it, paths.end());
      paths.erase(it, paths.end());
```

**Expected behavior**
I would have expected there to be no change in behavior.

**Platform information:**
I tested this on the lastest OIIO master and on an OIIO master that's maybe a year old, so somewhere between these the regression happened.

**Comment by lgritz** [comment]
I can't reproduce. I even put a test in as #3303. Can you look at what I did there and make it jibe with this bug report? 
Furthermore, simply inspecting the implementation of searchpath_split [here](https://github.com/OpenImageIO/oiio/blob/master/src/libutil/filesystem.cpp#L167), it's easy to see that for an empty string path, the while loop will never execute and the function will simply return the just-initialized (empty) vector.

Any insight?

**Comment by ThiagoIze** [comment]
Apologies, I messed up the report. Try this string: `":"` This is nothing, followed by a path separator, and nothing. This whole thing should return an empty vector but instead we get a vector with one element.

**Comment by lgritz** [comment]
Solution proposed in #3306
