### ISSUE TITLE
[FEATURE REQUEST] Support the MaterialX `<UVTILE>` substitution marker

### ISSUE THREAD

**Issue by jessey-git** [OpenImageIO/oiio#3275]
**Is your feature request related to a problem? Please describe.**
MaterialX introduced a particular substitution marker[1] that is currently not very well supported in the ecosystem. It's actual unclear on what the future of it might be[2]. As I cannot predict the outcome of what might happen here :), I suppose the only recourse is to support it.

**Describe the solution you'd like**
Add the `<UVTILE>` substitution pattern to `ImageCacheFile` processing. This is a 1-based format and is equivalent to `<U>_<V>` according to the current MaterialX spec.

**Describe alternatives you've considered**
Currently, in the renderer where this was noticed, we will manually manipulate the incoming filename and replace the `"<UVTILE>"` substring with `"<U>_<V>"`.

[1] Page 18 of http://www.materialx.org/assets/MaterialX.v1.38.Spec.pdf 
[2] USD only supports `<UDIM>` but they wish to extend that in the future. It's unclear if that means to extend to only `<UVTILE>` or extend to all OIIO tokens as I can find no public discussion on the details.

**Comment by lgritz** [comment]
This should be fairly straightforward.

**Comment by lgritz** [comment]
Implemented by #3280
