### ISSUE TITLE
Legal .ras file crashes on open

### ISSUE THREAD

**Issue by DougRogers** [OpenImageIO/oiio#3297]
This file opens in IrfanView
[goldenears.zip](https://github.com/OpenImageIO/oiio/files/7922103/goldenears.zip)

**Comment by DougRogers** [comment]
This too.
[goldenears_gray.zip](https://github.com/OpenImageIO/oiio/files/7922115/goldenears_gray.zip)

**Comment by lgritz** [comment]
Sun RAS file! Haven't seen one of those for a long time.

OIIO does not currently have a reader for this. I'd happily accept a PR if somebody wanted to add one.

I could not replicate a crash, I just get an error message like

    $ iinfo -v goldenears.ras
    iinfo ERROR: "goldenears.ras" : OpenImageIO could not find a format reader for "goldenears.ras". Is it a file format that OpenImageIO doesn't know about?

**Comment by DougRogers** [comment]
Duplicate of https://github.com/OpenImageIO/oiio/issues/3300
