### ISSUE TITLE
Cannot open legal .pcx file

### ISSUE THREAD

**Issue by DougRogers** [OpenImageIO/oiio#3298]
[input.zip](https://github.com/OpenImageIO/oiio/files/7922148/input.zip)

**Comment by lgritz** [comment]
OIIO does not currently support PCX files. PCX was the format of ZSoft's "PC Paintbrush" program, which had its last release in 1991. I remember it well, it was big in the 80s on DOS machines!

If somebody wanted to write a PCX reader and make a PR, we would be happy to accept it.
