### ISSUE TITLE
Legal BMP file cannot be opened

### ISSUE THREAD

**Issue by DougRogers** [OpenImageIO/oiio#3347]
ImageInput::open fails for this fil
[gracehopper.zip](https://github.com/OpenImageIO/oiio/files/8128893/gracehopper.zip)
e

**Comment by lgritz** [comment]
Aha!  Solution here: https://github.com/OpenImageIO/oiio/pull/3375

It was an "undocumented" header configuration that PhotoShop is happy to write despite not being described in MSDN.

**Comment by lgritz** [comment]
@DougRogers Is that bmp file ok to check into our testsuite? It doesn't seem to have any attached license or ownership information, though I assume that the likeness of her is from a government photo and thus probably in the public domain.

**Comment by DougRogers** [comment]
Should be fine.  The image is posted here, albeit in a different format.

https://commons.wikimedia.org/wiki/File:Grace_Hopper.jpg

**Comment by DougRogers** [comment]
I think that bmp is poster here:
https://chromium.googlesource.com/chromium/src/+/HEAD/third_party/blink/renderer/platform/testing/data/
