### ISSUE TITLE
Heap corruption reading .mov file

### ISSUE THREAD

**Issue by DougRogers** [OpenImageIO/oiio#3371]
When opening and reading the attached file, a heap corruption is reported in Windows. 

call stack is stopped in ffmpeginput.cpp

FFmpegInput::~FFmpegInput() { close(); }

![image](https://user-images.githubusercontent.com/7563851/160020189-ca297ec6-01da-415b-a73a-e4f63b95c173.png)

`
              std::string filePath = "IMG_1683.mov";

		ImageSpec config;
		config["oiio:UnassociatedAlpha"] = 1;

		auto inp = ImageInput::open(filePath.c_str(), &config);
		if (inp)
		{

			const ImageSpec& spec = inp->spec();
			int width = spec.width;
			int height = spec.height;
			int channels = spec.nchannels;
			std::vector<unsigned char> pixels(width * height * channels);
			inp->read_image(TypeDesc::UINT8, &pixels[0]);

			inp->close();
		}
		else
		{
			qDebug() << "Cannot open file " << filePath.c_str();
		}
	}
`
[IMG_1683.zip](https://github.com/OpenImageIO/oiio/files/8346119/IMG_1683.zip)

**Comment by lgritz** [comment]
Proposed fix in #3376.

I haven't been able to reproduce the crash myself -- maybe it's only symptomatic on windows, or maybe only for certain versions of ffmpeg?

But you pointed me to the destructor, which only calls close(), and just looking over that it's not hard to see that it might be written in a way that two closes (one explicit, then again called by the destructor) could cause problems if ffmpeg internals weren't safe if passed null pointers to some of those cleanup routines.

**Comment by DougRogers** [comment]
Seems reasonable.  I will retest when this is checked in to the main branch.  Is there a way I can be notified when this fix is added to the man branch?

**Comment by lgritz** [comment]
I think that because you are participating on this issue, you'll get the notice when it closes, which will happen automatically after the merge.

As an aside, if you're really trying the master branch, please note that in your example

	inp->read_image(TypeDesc::UINT8, &pixels[0]);

might trigger a deprecation warning for using the old, non-thread-safe read_image variety. If that's the case, you can fix by changing to

	inp->read_image(0, 0, 0, -1, TypeDesc::UINT8, &pixels[0]);
