### ISSUE TITLE
[BUILD Windows] No Path Found

### ISSUE THREAD

**Issue by yesilcimenahmet** [OpenImageIO/oiio#3410]
Hi,

I am using VS2019, I have successfully compiled OpenEXR but when I am trying to build OIIO I could not find the path for "IlmBase_DIR", 
"OPENEXR_ILMIMF_LIBRARY", "OPENEXR_HALF_LIBRARY" paths. I could not find any *ilmimf*.lib and *half*.lib

Can you help me?

**Comment by DougRogers** [comment]
I would recommend [vcpkg ](https://vcpkg.io/en/index.html) to install the dependencies.

**Comment by DougRogers** [comment]
Something like:

`vcpkg install OpenEXR  --triplet x64-windows --recurse`

shoould work

**Comment by lgritz** [comment]
Advice given long ago. Closing.
