### ISSUE TITLE
[BUG] Exiv2 test jp2 image crashes in read_image

### ISSUE THREAD

**Issue by DougRogers** [OpenImageIO/oiio#3427]
`        std::vector<unsigned char> pixels(width * height * channels);
        bool success = imageInput->read_image(0, 0, 0, -1, oiio::TypeDesc::UINT8, &pixels[0]);
[issue_ghsa_583f_w9pm_99r2_poc.zip](https://github.com/OpenImageIO/oiio/files/8864448/issue_ghsa_583f_w9pm_99r2_poc.zip)
`

![image](https://user-images.githubusercontent.com/7563851/172699420-4c1e158b-7b0a-4638-8f3d-ac6bbdcfd7d8.png)

**Comment by etheory** [comment]
I'm glad someone else is able to repro this. I mentioned this to @lgritz but he was unable to repro on his end. I can't figure out where it's coming from. If I attach a debugger it looks like the openjpeg library itself is segfaulting on initialization.

**Comment by lgritz** [comment]
I can repro with this example!

**Comment by lgritz** [comment]
Proposed fix in #3440
