### ISSUE TITLE
BMP Crash During Read

### ISSUE THREAD

**Issue by DougRogers** [OpenImageIO/oiio#3428]
[Mask.zip](https://github.com/OpenImageIO/oiio/files/8866524/Mask.zip)

**Comment by DougRogers** [comment]
[chun-li.zip](https://github.com/OpenImageIO/oiio/files/8866647/chun-li.zip)

**Comment by lgritz** [comment]
I'm having trouble reproducing with these examples. Can you confirm which version of OIIO specifically you tried? Do you by any chance have a stack trace of the crash?

**Comment by DougRogers** [comment]
It is actually a bounds assert

fscanline[i] = 255
m_colortable size = 255

mscanline[j]     = m_colortable[fscanline[i]].r;

![image](https://user-images.githubusercontent.com/7563851/173069180-b13dcd58-07f4-4ed6-a76a-cfed6325eb30.png)

I will get lastest

**Comment by DougRogers** [comment]
Latest fails also generates the assert.

**Comment by lgritz** [comment]
ok, I can reproduce
