### ISSUE TITLE
Stress Test:  Invalid PNG crashes

### ISSUE THREAD

**Issue by DougRogers** [OpenImageIO/oiio#3437]
![image](https://user-images.githubusercontent.com/7563851/173209281-c6dd40e1-3c30-42d8-8958-63f4a453ad8b.png)
[invalid_gray_alpha_sbit.zip](https://github.com/OpenImageIO/oiio/files/8884950/invalid_gray_alpha_sbit.zip)

**Comment by lgritz** [comment]
Proposed fix: #3442
