### ISSUE TITLE
Stress Test:  Bad jp2 causes crash

### ISSUE THREAD

**Issue by DougRogers** [OpenImageIO/oiio#3441]
![image](https://user-images.githubusercontent.com/7563851/173248847-4f87e7b0-a30a-47da-b2ff-fecb6a9dc630.png)
[00029-jasper-uninitvalue-jpc_pi_nextcprl.zip](https://github.com/OpenImageIO/oiio/files/8886550/00029-jasper-uninitvalue-jpc_pi_nextcprl.zip)

**Comment by lgritz** [comment]
This crash is in the very same spot as reported in #3427, which makes me suspect that is a duplicate and also will be solved by #3440. I'll give that a try...

**Comment by DougRogers** [comment]
ok.  Please let me know when this gets checked into main

**Comment by lgritz** [comment]
Confirmed. This is fixed by #3440.

**Comment by lgritz** [comment]
Closing as it appears fixed by #3441 (which I just merged into master).
