### ISSUE TITLE
[BUILD] Issues rpath-ing the OpenImageIO.cpython-38-darwin.so when running make release (Apple Silicon)

### ISSUE THREAD

**Issue by vvzen** [OpenImageIO/oiio#3519]
Hi!

I am trying to build OpenImageIO on a macOS with an M1 chip (running on macOS 12.3).
The actual build process goes fine, no issues at all.
When I try to `make install` though, it spits out this error:
```
[ 93%] Built target testtex
[100%] Built target PyOpenImageIO
Install the project...
-- Install configuration: "Release"
error: /Library/Developer/CommandLineTools/usr/bin/install_name_tool: for: /opt/opensource-builds/oiio/dist/lib/python3.8/site-packages/OpenImageIO/OpenImageIO.cpython-38-darwin.so (for architecture arm64) option "-add_rpath /opt/opensource-builds/oiio/dist/lib" would duplicate path, file already has LC_RPATH for: /opt/opensource-builds/oiio/dist/lib
error: /Library/Developer/CommandLineTools/usr/bin/install_name_tool: no LC_RPATH load command with path: /opt/opensource-builds/oiio/build/lib found in: /opt/opensource-builds/oiio/dist/lib/python3.8/site-packages/OpenImageIO/OpenImageIO.cpython-38-darwin.so (for architecture arm64), required for specified option "-delete_rpath /opt/opensource-builds/oiio/build/lib"
```

The fact that
>option "-add_rpath /opt/opensource-builds/oiio/dist/lib" would duplicate path, file already has LC_RPATH

seems to be true, in fact since I can see that:
```bash
$ otool -l  /opt/opensource-builds/oiio/dist/lib/python3.8/site-packages/OpenImageIO/OpenImageIO.cpython-38-darwin.so | grep -B 1 -A 3 RPATH
Load command 16
          cmd LC_RPATH
      cmdsize 32
         path /opt/homebrew/lib (offset 12)
Load command 17
--
Load command 20
          cmd LC_RPATH
      cmdsize 56
         path /opt/opensource-builds/oiio/dist/lib (offset 12)
```
Not sure if it's linked to it, but maybe this PR offers some context: https://github.com/OpenImageIO/oiio/pull/1671 ?

After looking at that PR, I tried commenting the `set (MACOSX_RPATH ON)` line, and `make install` went fine (no errors).
I'm not an expert of RPATHs on macOS, but it seems that the RPATH is already being set at compile time, so trying to re-set it at install time fails.

My diff is currently the following:
```diff
$ git diff
diff --git a/src/cmake/compiler.cmake b/src/cmake/compiler.cmake
index 7ba971a1..bba0e18a 100644
--- a/src/cmake/compiler.cmake
+++ b/src/cmake/compiler.cmake
@@ -608,7 +608,7 @@ endif ()
 ###########################################################################
 # Rpath handling at the install step
 #
-set (MACOSX_RPATH ON)
+#set (MACOSX_RPATH ON)
 if (CMAKE_SKIP_RPATH)
     # We need to disallow the user from truly setting CMAKE_SKIP_RPATH, since
     # we want to run the generated executables from the build tree in order to
```
Thanks!

Valerio

**Comment by lgritz** [comment]
So basically you are saying that you think we should alter this one line in compiler.cmake to NOT enable the MACOS_RPATH variable?

I'm very much not an expert on its effect. 

This line was originally added in #1671 (this section of code was in "install.cmake" at the time, much later transplanted to compile.cmake). This dates from 2017, and although I seem to be the author, I don't remember anything about why I did it.

We can certainly try removing it, and as long as it builds for me and passes CI, if that helps you, I don't see why we shouldn't do it.

**Comment by vvzen** [comment]
Hi @lgritz !
More or less - from my tests it seemed redundant. Although I'm not really an expert either - I just examined the compiler warnings and checked what was going on with/without this line. If you have a CI for both ARM and x86 macOS builds, it might be worth trying to remove it and see if things still build fine for both architectures (and checking with which cmake version). Sadly I can't provide much more rational reasoning for the why.
Googling around, I found some more context here:
- https://cmake.org/cmake/help/latest/prop_tgt/MACOSX_RPATH.html
- https://cmake.org/cmake/help/latest/policy/CMP0042.html#policy:CMP0042 

Specifically, CMP0042 says that
> MACOSX_RPATH is enabled by default

so maybe that's what's happening here..?

**Comment by lgritz** [comment]
How about this: #3523

It passes CI and also works for my on my own Mac laptop.
But neither of those are ARM-based Macs.

**Comment by vvzen** [comment]
That's great. I'm on a ARM machine (M1 MAX) so I can confirm that commenting works there too!

Another wild guess for the "why" could be that the rpath is already being set via the `INSTALL_NAME_DIR` variable instead? Quoting from https://cmake.org/cmake/help/latest/prop_tgt/MACOSX_RPATH.html :

> When this property is set to TRUE, the directory portion of the install_name field of this shared library will be @rpath unless overridden by [INSTALL_NAME_DIR](https://cmake.org/cmake/help/latest/prop_tgt/INSTALL_NAME_DIR.html#prop_tgt:INSTALL_NAME_DIR).

Looking around, it seems that you're already setting this var?
```
$ grep -B 5 -e CMAKE_INSTALL_NAME_DIR --color site/spi/Makefile-bits
## Generic OSX machines (including LG's laptop)
else ifeq (${platform}, macosx)
    USE_SIMD ?= sse4.2
    MY_CMAKE_FLAGS += \
        -DCMAKE_BUILD_WITH_INSTALL_RPATH=1 \
        -DCMAKE_INSTALL_NAME_DIR="${working_dir}/dist/lib"
```
Anyway, if that change works for you guys, it definitely works for me too!

PS: I also just realized that Github's CI is not currently currently supporting building on Apple Silicon, but it's on their roadmap: https://github.com/github/roadmap/issues/528 

(now, the other part of the macOS ARM-equation would be to have the conda-recipe building fine for ARM too, but that might be a lot of work, given how the conda recipes are actually written.. )
