### ISSUE TITLE
[BUG] Regression in HDR read performance with 2.4 release (~10x)

### ISSUE THREAD

**Issue by jessey-git** [OpenImageIO/oiio#3585]
**Describe the bug**
There seems to be a clear regression in performance when moving to 2.4.x and reading HDR files. A small app, included below, shows a 10second read time in 2.4 vs. a 1second read in 2.3

**To Reproduce**
1. Create an ImageInput from a .hdr file
2. Measure how long it takes to read the image
3. Observe it takes a lot longer than it used to

**Expected behavior**
Performance closer to the 1second case should hopefully be possible. Certainly not the 10 seconds.

**Evidence**
See below for the sample program as well as where to download a free .hdr if you don't have one handy.

It will output a simple timing:
2.3
```
Read time: 992 ms
Read time: 994 ms
```

2.4
```
Read time: 10057 ms
Read time: 10383 ms
```

A quick profile just says that seeking and freading are the main bottlenecks. I'm guessing these are called more frequently/less efficiently since the big HDR refactor last year?
![first-pass](https://user-images.githubusercontent.com/7989986/194224262-cf9402b7-c68b-4edc-93de-7492758a2cc2.png)

**Platform information:**
 - OIIO branch/version: 2.4.4.2
 - OS: Windows 10
 - C++ compiler: VS 2019 and VS 2022 compiled in the Release configuration

----
Use the following free HDR: https://polyhaven.com/a/autoshop_01 (use the 8k HDR variant which should be 97mb)

```
#include <cstdio>
#include <memory>
#include <chrono>
#include <OpenImageIO/imageio.h>

int main()
{
    const char* filepath = "t:/autoshop_01_8k.hdr";
    std::unique_ptr<OIIO::ImageInput> in = OIIO::ImageInput::create(filepath);

    OIIO::ImageSpec spec;
    OIIO::ImageSpec config;
    config.attribute("oiio:UnassociatedAlpha", 1);

    if (!in->open(filepath, spec, config)) {
        printf("Failed to open\n");
        return -1;
    }

    int width = spec.width;
    int height = spec.height;
    int channels = spec.nchannels;

    int scanlinesize = width * channels * sizeof(unsigned char);
    unsigned char* pixels = (unsigned char*)malloc(width * height * 4);

    auto start = std::chrono::high_resolution_clock::now();
    if (!in->read_image(OIIO::TypeDesc::UINT8, (unsigned char*)pixels + (height - 1) * scanlinesize, OIIO::AutoStride, -scanlinesize, OIIO::AutoStride)) {
        printf("Failed to read\n");
        return -1;
    }
    in->close();
    auto end = std::chrono::high_resolution_clock::now();

    printf("Read time: %lld ms\n", std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count());

    free(pixels);
    return 0;
}

```

**Comment by lgritz** [comment]
Ooh, good catch. I will look into this. Thanks for the alert.

**Comment by aras-p** [comment]
@lgritz if you're busy I can also try taking this one!

**Comment by lgritz** [comment]
I was going to try to look today, but I haven't started yet, so if you want to try, go for it!

I suspect that when I added IOProxy support to HDR recently, I probably introduced an inefficiency.

**Comment by lgritz** [comment]
To repeat what I said in another thread, a good way to time how long it takes to do a full read with minimal conversions and no SHA-1 overhead is

    time oiiotool --native -i:now=1 file.exr

The `now=1` modifier causes the input to be read in full rather than going through the ImageCache, and all at once. And the `--native` keeps it in the data type of the file itself if at all possible (versus the oiiotool default of tending to convert everything to float upon input so that image processing operations are done at full speed and precision).

This should be fairly close to what you'd get with the test harness above of just minimally opening and doing a read_image().

**Comment by lgritz** [comment]
I can confirm at least a 3x regression on Mac as well.

Aras, let me know if you're going to take a stab at this.

**Comment by aras-p** [comment]
Yeah I'll look at it today.

**Comment by jessey-git** [comment]
I can confirm that 2.4.5 fixes the regression and improves performance beyond the old series.
