### ISSUE TITLE
[BUG] OIIO only read the Normal channel from a 3-passes EXR file.

### ISSUE THREAD

**Issue by klydeid** [OpenImageIO/oiio#3593]
**Describe the bug**
Hello. i have a EXR file with 3 passes. Normal/albedo/C.
But when i use ImageInput::open function to open it then check the ImageSpec. i found that it looks like OIIO convert the first channel (Normal channel) to RGB. 
here is what the EXR file in Houdini Mplay:
![image](https://user-images.githubusercontent.com/82641456/194736842-19c30b47-ddd9-480c-a4ff-8a3738772af0.png)

here is the ImageSpec infomation:
![image](https://user-images.githubusercontent.com/82641456/194736806-dd0895e7-4b1f-4e37-924e-f9dee415e8d5.png)

**Platform information:**
 - OIIO branch/version: 2.3.15
 - OS: windows
 - C++ compiler: MSVC_2019x64

**Comment by lgritz** [comment]
Can you send me the exr file so I can directly take a look?

**Comment by klydeid** [comment]
thanks Larry! check this:
https://www.dropbox.com/s/jz4k2jz1cjkwa71/fishtail_v1_0090.exr?dl=0

**Comment by lgritz** [comment]
The *parts* have "name" attributes "N", "albedo", and "C", respectively.

But then each part has 3 channel with names "R", "G", and "B". All of them.

**Comment by lgritz** [comment]
```
oiiotool -info -v -a fishtail_v1_0090.exr
```

or also you can confirm with

```
exrheader fishtail_v1_0090.exr
```

**Comment by lgritz** [comment]
It looks like Houdini is naming the channels R, G, B no matter which data happens to be in the subimage. So all fine, you were reading the "N" data all along.

**Comment by klydeid** [comment]
emm. sorry for my stupid question. i just want to load the C/albedo channel then drawing with opengl.
in this case. how can i load the "C" or "albedo" channel in C++.

**Comment by klydeid** [comment]
i use ImageInput::seek_subimage() function to get what i want.  sorry for my stupid quesion. T T

i haven't used subimage before. i always think that the subimage is used for Animation/Sequence Image like WEBP file.

**Comment by lgritz** [comment]
Subimages are used for all cases of multiple images in one file -- parts of a multi-part exr, multiple images in a tiff file, or frames in an image file, animated gif or webp, etc.

**Comment by klydeid** [comment]
thanks Larry! it helps a lot!
