### ISSUE TITLE
Legal PSD file cannot be opened

### ISSUE THREAD

**Issue by DougRogers** [OpenImageIO/oiio#3658]
Legal PSD file does not open.  Loads into Photoshop

`
                ImageSpec config;
                config["oiio:UnassociatedAlpha"] = 1;

                auto imageInput = ImageInput::open(i->path(), &config);
`

https://www.dropbox.com/s/11nyoxaa2dl2baq/_DSC0707.zip?dl=0

**Comment by lgritz** [comment]
Aha, I see what's happening. There was something up with the thumbnail in this file, it was an odd number of columns, and I missed the fact that the header might pad to make thumbnail byte width aligned more stringently. I was seeing the numbers not match and thinking it indicated a corrupted header, but I see now it's not.

Fix coming.

**Comment by lgritz** [comment]
Proposed fix in #3677
