### ISSUE TITLE
std::vector<unsigned char> profile(profile_size) is not compatible with typedef char JOCTET

### ISSUE THREAD

**Issue by Anyeos** [OpenImageIO/oiio#3663]
**Describe the bug**
`std::vector<unsigned char> profile(profile_size)` is not compatible with `typedef char JOCTET`
```
oiio/src/jpeg.imageio/jpegoutput.cpp:323:60: error: invalid conversion from ‘__gnu_cxx::__alloc_traits<std::allocator<unsigned char>, unsigned char>::value_type*’ {aka ‘unsigned char*’} to ‘const JOCTET*’ {aka ‘const char*’} [-fpermissive]
  323 |                 jpeg_write_marker(&m_cinfo, JPEG_APP0 + 2, &profile[0],
```
Both the Visual Code Studio and the gcc compiler complains about that.

**To Reproduce**
Open on Visual Code Studio or try to build with cmake.

**Expected behavior**
Correct usage of the type for the profile declaration.

**Evidence**
```
oiio/src/jpeg.imageio/jpegoutput.cpp:323:60: error: invalid conversion from ‘__gnu_cxx::__alloc_traits<std::allocator<unsigned char>, unsigned char>::value_type*’ {aka ‘unsigned char*’} to ‘const JOCTET*’ {aka ‘const char*’} [-fpermissive]
  323 |                 jpeg_write_marker(&m_cinfo, JPEG_APP0 + 2, &profile[0],
```

**Platform information:**
 - OIIO branch/version: recent from git (v2_5_0)
 - OS: Ubuntu 20.04
 - C++ compiler: gcc-9.4.0
 - Any non-default build flags when you build OIIO: none

### Note
It now compiles changing `std::vector<unsigned char> profile(profile_size)` by `std::vector<char> profile(profile_size)` but now running `"imageinout_test"` I receive: 
`JPEG parameter struct mismatch: library thinks size is 584, caller expects 640`

**Comment by Anyeos** [comment]
#Workaround
Compiled against jpeg 62 instead of 80 and it worked.

I really don't understand what did Ubuntu because the source they used is based on the version 62 of the library but they called the others libraries "80 version".
And I don't understand what application needs that specific version and why I cannot install both the 62 and the 80 dev packages. 
The 62 version complains about removing a lot of dev packages of other libraries/utilities. So I choose to linking against the 62 version instead and it worked as expected and `imageinout_test` passed all tests now.

**Comment by lgritz** [comment]
I suspect that these are two unrelated problems.

You are quite right about the first one -- that there is a type mismatch. I'm not exactly sure why it wasn't caught in CI or by any of the other compilers. But it's undeniably correct that we're passing an unsigned char* to a function that wants a signed char*. I've proposed a fix in PR #3664.

But I don't see any way that this is related to the second issue you mention, the JPEG parameter struct mismatch." If I had to guess, I bet that what's happening is that you have TWO versions of libjpeg installed somehow, and you were reading one set of headers, but linking against the other library.

**Comment by Anyeos** [comment]
Yes, I don't understand what is the second problem but that happens when I solve the first.
But I had no installed the libjpeg 62 at first. I dont know from where it can try to use that library. I installed it later and copied jconfig.h to /usr/include because I did not found an jconfig.h on files from any dev package in Ubuntu 20.04.
But recently I searched for jconfig.h (only to make a backup of the jconfig.h that I copied) and surprisingly I found 6 results. And there are various jconfig.h lying on different sub directories, so maybe if I specify the correct one OpenImageIO will build correctly as expected. For now I don't will try that because I already have a working copy so I don't need to do that.

Thank you for your help.

**Comment by Anyeos** [comment]
### Update
It failed now on Blender with complains about built over libjpeg 62 when the lib being used is 80. The definitive solution for my 2nd problem was using the jconfig.h provided under `/usr/include/x86_64-linux-gnu/jconfig.h`. That was the working one using version 80 of the library. And making a symlink to `/usr/include/jconfig.h` solved my problem to compile for Blender (because I am using the provided script).

Sorry if I am off-topic with this but it is originally related with the difficult that I had trying to build the OpenImageIO library. And I want to let it so someone can find it if him face the same difficult.
If you think I must write this somewhere else please let me know. For now I don't have a blog or something to do that.

And now I have a good working build without modifying anything (neither the "unsigned char" thing). So I think this issue don't occur often but in some particular situation when libjpeg was built with char instead of unsigned char.

**Comment by lgritz** [comment]
Thanks for the updates
