### ISSUE TITLE
[Config.cmake.in] An OpenImageIO_INCLUDE_DIR path error

### ISSUE THREAD

**Issue by MonicaLiu0311** [OpenImageIO/oiio#3680]
I am the official maintainer of `vcpkg`, and I have encountered problems when upgrading to a new version.

**Describe the bug**
The calculation of the `OpenImageIO_INCLUDE_DIR` path is inaccurate, so the include directory cannot be found.

**To Reproduce**
1) git clone https://github.com/microsoft/vcpkg.git
2) cd vcpkg
3) .\bootstrap-vcpkg.bat
4) Modify the version information in the `portfile.cmake` and `vcpkg.jaon` files in order to upgrade to 2.4.5.0.
5) .\vcpkg install openimageio
6) Create a cmake project to test usage, where the code information is as follows:
![CMakeSetting](https://user-images.githubusercontent.com/110024546/202608193-f32a8073-c22a-4f02-9612-9f11a48ed36c.png)
![CMakeList](https://user-images.githubusercontent.com/110024546/202608197-fcfa855d-1c32-43bd-a620-82a6d8f8b53a.png)
7) Output details:
```
1> CMake generation started for configuration: 'x86-Debug'.
1> Command line: "C:\Windows\system32\cmd.exe" /c "%SYSTEMROOT%\System32\chcp.com 65001 >NUL && "C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\ENTERPRISE\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe"  -G "Visual Studio 16 2019" -A Win32  -DCMAKE_CONFIGURATION_TYPES:STRING="Debug" -DCMAKE_INSTALL_PREFIX:PATH="C:\Users\monica\source\repos\CMakeFindUsage\out\install\x86-Debug" -DCMAKE_TOOLCHAIN_FILE=E:/src/Monica/vcpkg03/scripts/buildsystems/vcpkg.cmake "C:\Users\monica\source\repos\CMakeFindUsage" 2>&1"
1> Working directory: C:\Users\monica\source\repos\CMakeFindUsage\out\build\x86-Debug
1> [CMake] -- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19045.
1> [CMake] -- The C compiler identification is MSVC 19.29.30147.0
1> [CMake] -- The CXX compiler identification is MSVC 19.29.30147.0
1> [CMake] -- Detecting C compiler ABI info
1> [CMake] -- Detecting C compiler ABI info - done
1> [CMake] -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x86/cl.exe - skipped
1> [CMake] -- Detecting C compile features
1> [CMake] -- Detecting C compile features - done
1> [CMake] -- Detecting CXX compiler ABI info
1> [CMake] -- Detecting CXX compiler ABI info - done
1> [CMake] -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x86/cl.exe - skipped
1> [CMake] -- Detecting CXX compile features
1> [CMake] -- Detecting CXX compile features - done
1> [CMake] -- Found ZLIB: optimized;E:/src/Monica/vcpkg03/installed/x86-windows/lib/zlib.lib;debug;E:/src/Monica/vcpkg03/installed/x86-windows/debug/lib/zlibd.lib (found version "1.2.13") 
1> [CMake] -- Found PNG: optimized;E:/src/Monica/vcpkg03/installed/x86-windows/lib/libpng16.lib;debug;E:/src/Monica/vcpkg03/installed/x86-windows/debug/lib/libpng16d.lib (found version "1.6.37") 
**1> [CMake] ***************************************************output info * start**************************************************
1> [CMake] *******_CURR_INSTALL_LIBDIR=E:/src/Monica/vcpkg03/installed/x86-windows***************
1> [CMake] *******_ABS_CMAKE_INSTALL_LIBDIR=E:/src/Monica/vcpkg03/installed/x86-windows/lib***************
1> [CMake] *******_ABS_CMAKE_INSTALL_INCLUDEDIR=E:/src/Monica/vcpkg03/installed/x86-windows/include***************
1> [CMake] *******_INCLUDEDIR_RELATIVE_TO_LIBDIR=../include***************
1> [CMake] *******_CURR_INSTALL_INCLUDE_DIR=E:/src/Monica/vcpkg03/installed/include***************
1> [CMake] ***************************************************output info * end****************************************************
1> [CMake] *****_var=OpenImageIO_INCLUDE_DIR
1> [CMake] *****_file=E:/src/Monica/vcpkg03/installed/include**
1> [CMake] CMake Error at E:/src/Monica/vcpkg03/installed/x86-windows/share/imath/ImathConfig.cmake:13 (message):
1> [CMake]   File or directory E:/src/Monica/vcpkg03/installed/include referenced by
1> [CMake]   variable OpenImageIO_INCLUDE_DIR does not exist !
1> [CMake] Call Stack (most recent call first):
1> [CMake]   E:/src/Monica/vcpkg03/installed/x86-windows/share/openimageio/OpenImageIOConfig.cmake:98 (set_and_check)
1> [CMake]   E:/src/Monica/vcpkg03/scripts/buildsystems/vcpkg.cmake:834 (_find_package)
1> [CMake]   CMakeFindUsage/CMakeLists.txt:10 (find_package)
1> [CMake] -- Configuring incomplete, errors occurred!
1> [CMake] See also "C:/Users/monica/source/repos/CMakeFindUsage/out/build/x86-Debug/CMakeFiles/CMakeOutput.log".
1> 'C:\Windows\system32\cmd.exe' '/c "%SYSTEMROOT%\System32\chcp.com 65001 >NUL && "C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\ENTERPRISE\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe"  -G "Visual Studio 16 2019" -A Win32  -DCMAKE_CONFIGURATION_TYPES:STRING="Debug" -DCMAKE_INSTALL_PREFIX:PATH="C:\Users\monica\source\repos\CMakeFindUsage\out\install\x86-Debug" -DCMAKE_TOOLCHAIN_FILE=E:/src/Monica/vcpkg03/scripts/buildsystems/vcpkg.cmake "C:\Users\monica\source\repos\CMakeFindUsage" 2>&1"' execution failed with error: ''C:\Windows\system32\cmd.exe' '/c "%SYSTEMROOT%\System32\chcp.com 65001 >NUL && "C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\ENTERPRISE\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe"  -G "Visual Studio 16 2019" -A Win32  -DCMAKE_CONFIGURATION_TYPES:STRING="Debug" -DCMAKE_INSTALL_PREFIX:PATH="C:\Users\monica\source\repos\CMakeFindUsage\out\install\x86-Debug" -DCMAKE_TOOLCHAIN_FILE=E:/src/Monica/vcpkg03/scripts/buildsystems/vcpkg.cmake "C:\Users\monica\source\repos\CMakeFindUsage" 2>&1"' returned with exit code: 1'.
```

**Platform information:**
 - OIIO branch/version: 2.4.5.0,master
 - OS: Windows(x86 and x64)
 - C++ compiler: VS2019

**IF YOU ALREADY HAVE A CODE FIX:
Problematic code location: [Config.cmake.in#L40-L46](https://github.com/OpenImageIO/oiio/blob/master/src/cmake/Config.cmake.in#L40-L46)
I think that since `_CURR_INSTALL_LIBDIR` is used to splice addresses, `_CURR_INSTALL_LIBDIR` should be used for calculation. Suggested changes: 
```
get_filename_component(_CURR_INSTALL_LIBDIR "${CMAKE_CURRENT_LIST_DIR}/../../" ABSOLUTE)
get_filename_component(_ABS_CMAKE_INSTALL_LIBDIR "${VCPKG_IMPORT_PREFIX}/lib" ABSOLUTE)
get_filename_component(_ABS_CMAKE_INSTALL_INCLUDEDIR "${VCPKG_IMPORT_PREFIX}/include" ABSOLUTE)

file(RELATIVE_PATH _INCLUDEDIR_RELATIVE_TO_LIBDIR
     "${_CURR_INSTALL_LIBDIR}" "${_ABS_CMAKE_INSTALL_INCLUDEDIR}")

get_filename_component(_CURR_INSTALL_INCLUDE_DIR
                       "${_CURR_INSTALL_LIBDIR}/${_INCLUDEDIR_RELATIVE_TO_LIBDIR}" ABSOLUTE)
```
(I used the above code to configure successfully, but I am not sure if it will have any impact on users who build with other compilers, so I did not raise PR to modify.)

**Comment by MonicaLiu0311** [comment]
Looking forward to your suggestions for revision, thank you.

**Comment by MonicaLiu0311** [comment]
Related PR: https://github.com/OpenImageIO/oiio/pull/3487

**Comment by MonicaLiu0311** [comment]
@lgritz @fpsunflower @edgarv 
Can you pay attention to this issue? thanks.

**Comment by lgritz** [comment]
I have to admit, I'm totally confused by this.

The first change you suggest are these lines

```cmake
get_filename_component(_ABS_CMAKE_INSTALL_LIBDIR "@CMAKE_INSTALL_FULL_LIBDIR@" ABSOLUTE)
get_filename_component(_ABS_CMAKE_INSTALL_INCLUDEDIR "@CMAKE_INSTALL_FULL_INCLUDEDIR@" ABSOLUTE)
```

and your proposed change is

```cmake
get_filename_component(_ABS_CMAKE_INSTALL_LIBDIR "${VCPKG_IMPORT_PREFIX}/lib" ABSOLUTE)
get_filename_component(_ABS_CMAKE_INSTALL_INCLUDEDIR "${VCPKG_IMPORT_PREFIX}/include" ABSOLUTE)
```

Is that really part of your suggested change? I don't see how using `${VCPKG_IMPORT_PREFIX}` can possibly work for people not using VcPkg. Maybe this was just another change you made locally, but not the suggested change to the project?

The second change you suggest is

```cmake
file(RELATIVE_PATH _INCLUDEDIR_RELATIVE_TO_LIBDIR
     "${_ABS_CMAKE_INSTALL_LIBDIR}" "${_ABS_CMAKE_INSTALL_INCLUDEDIR}")
```

to

```cmake
file(RELATIVE_PATH _INCLUDEDIR_RELATIVE_TO_LIBDIR
     "${_CURR_INSTALL_LIBDIR}" "${_ABS_CMAKE_INSTALL_INCLUDEDIR}")
```

This one confuses me as well. If we're trying ultimately to ask for the relative path between lib and include dirs, then we want both to be abs, or both be curr, but your suggested change is to compute the relative path between _CURR_INSTALL_LIBDIR and _ABS_CMAKE_INSTALL_INCLUDEDIR? That doesn't look right to me. Can you explain?

**Comment by MonicaLiu0311** [comment]
@lgritz 

Config.cmake.in#L40-L46]:
get_filename_component(_CURR_INSTALL_LIBDIR "${CMAKE_CURRENT_LIST_DIR}/../../" ABSOLUTE)
get_filename_component(_ABS_CMAKE_INSTALL_LIBDIR "@CMAKE_INSTALL_FULL_LIBDIR@" ABSOLUTE)
get_filename_component(_ABS_CMAKE_INSTALL_INCLUDEDIR "@CMAKE_INSTALL_FULL_INCLUDEDIR@" ABSOLUTE)
file(RELATIVE_PATH _INCLUDEDIR_RELATIVE_TO_LIBDIR
     "${_ABS_CMAKE_INSTALL_LIBDIR}" "${_ABS_CMAKE_INSTALL_INCLUDEDIR}")
get_filename_component(_CURR_INSTALL_INCLUDE_DIR
                       "${_CURR_INSTALL_LIBDIR}/${_INCLUDEDIR_RELATIVE_TO_LIBDIR}" ABSOLUTE)
					   
The value obtained:
①    _CURR_INSTALL_LIBDIR			=	E:/src/Monica/vcpkg03/installed/x86-windows
②    _ABS_CMAKE_INSTALL_LIBDIR		=	E:/src/Monica/vcpkg03/installed/x86-windows/lib
③    _ABS_CMAKE_INSTALL_INCLUDEDIR	=	E:/src/Monica/vcpkg03/installed/x86-windows/include

Relative distance:
_INCLUDEDIR_RELATIVE_TO_LIBDIR	=	../include

Current calculation results:
`_CURR_INSTALL_INCLUDE_DIR`		=	E:/src/Monica/vcpkg03/installed/include

The correct result should be something like this:
`_CURR_INSTALL_INCLUDE_DIR` = E:/src/Monica/vcpkg03/installed/`x86-windows`/include
(Because "../" in "../include" eliminates a file layer "x86-windows", so the real include path cannot be found.)


What I mean is, you use ② and ③ to calculate the relative distance, but you use ① to concatenate the calculated results; 
if A and B are the same value, then of course there is no problem, but in fact they are not the same.

**Comment by MonicaLiu0311** [comment]
I guess your splicing may be based on other file hierarchy divisions, but the vcpkg hierarchy division is as follows:
```
/x86-windows
/x86-windows/lib
/x86-windows/include
```

I can apply a patch in vcpkg to solve this problem, but this is not the optimal solution, so I choose to report this problem upstream first.

**Comment by jreichel-nvidia** [comment]
I believe I observed the same problem (in the context of OIIO 2.4.x via vcpkg, but on Linux). Removing "../" from
`get_filename_component(_CURR_INSTALL_LIBDIR "${CMAKE_CURRENT_LIST_DIR}/../../" ABSOLUTE)`
worked fine for me. No idea whether this is specific to vcpkg's directory layout or not.

**Comment by MonicaLiu0311** [comment]
> I believe I observed the same problem (in the context of OIIO 2.4.x via vcpkg, but on Linux). Removing "../" from `get_filename_component(_CURR_INSTALL_LIBDIR "${CMAKE_CURRENT_LIST_DIR}/../../" ABSOLUTE)` worked fine for me. No idea whether this is specific to vcpkg's directory layout or not.

Also solved my problem.

**Comment by lgritz** [comment]
This is just subtle enough that I'm not sure what the final solution turned out to be and I have no way to easily test a VcPkg build.

Can somebody please make a PR that proposes the final wording that seems to work?

---

Also, I want to point out that (for this or any other problem that crops up in the future) it's FINE to add a top level CMake 

    option (OIIO_BUILD_FOR_VCPKG "Set ON when building for VcPkg OFF)

and the VcPkg recipe can kick off the cmake build enabling the option.
Then, anyplace we need to, we can have

    if (OIIO_BUILD_FOR_VCPKG)
        # do different things specifically for VcPkg
    else ()
        # code for everybody else
    endif ()

**Comment by MonicaLiu0311** [comment]
> option (OIIO_BUILD_FOR_VCPKG "Set ON when building for VcPkg OFF)

>if (OIIO_BUILD_FOR_VCPKG)
    # do different things specifically for VcPkg
else ()
    # code for everybody else
endif ()

After thinking about it, it is not very good to distinguish vcpkg specifically. I made a patch in vcpkg to solve it. Thank you for your reply.

**Comment by lgritz** [comment]
> After thinking about it, it is not very good to distinguish vcpkg specifically. I made a patch in vcpkg to solve it. Thank you for your reply.

To be honest, I'm not so sure about this. This a trade-off between multiple valid priorities.

In my view as the OIIO maintainer, every patch regarding OIIO that lives on the vcpkg side is an opportunity for future OIIO releases to inadvertently make a change that will break your patch and delay vcpkg's ability to move to the new OIIO release because it will take somebody on the vcpkg side who is also familiar with OIIO to unbreak it again. Whereas if the extra logic lives on the OIIO side, any of us contemplating a change in that section of code will recognize it as such and tread carefully. As well, the existence of any vcpkg-side patches to OIIO (beyond the bare minimum necessary) is a normalization of making continued custom patches to OIIO on the vcpkg side and makes such things proliferate, and disincentivizes the vcpkg maintainers from pushing patches back upstream to OIIO.

I understand that it's a little ugly to have `if (OIIO_BUILD_FOR_VCPKG)` scattered around, but is it really any worse than `if (WINDOWS)` or `if (APPLE)` or other system-specific soce that we all acknowledge is necessary?

**Comment by MonicaLiu0311** [comment]
There are two reasons for patching:
1. Because vcpkg has its own file directory hierarchy, other platforms will also have different directory levels from vcpkg. If OpenImageIO uses the option to solve it, then it may need to be added indefinitely in the future.
2. Applying a patch to vcpkg is a temporary solution to the problem. If OpenImageIO makes changes in the next version, vcpkg will delete this patch when it is updated.
3. The following is also one of the reasons.
    >I understand that it's a little ugly to have if (OIIO_BUILD_FOR_VCPKG) scattered around, but is it really any worse than if (WINDOWS) or if (APPLE) or other system-specific logic that we all acknowledge is necessary?
