### ISSUE TITLE
OpenJpeg is not found under none-standard path

### ISSUE THREAD

**Issue by lashgar** [OpenImageIO/oiio#3697]
Since this change: https://github.com/OpenImageIO/oiio/commit/0541331cdb70005e2aca326379966b9068e938cc#r91843154 OpenImageIO cannot be configured to find OpenJpeg from none-standard path. Basically cmake argument `OpenJPEG_ROOT` is no longer supported. What is the way to set OpenJpeg path now?

**Comment by lgritz** [comment]
Do you know which version of OpenJPEG you are using? And what is the nonstandard location?

**Comment by lgritz** [comment]
But the change doesn't really remove the use of OpenJPEG_ROOT. Any time you call `find_package(<pkgname>)` to execute module `Find<pkgname>.cmake`, any find_path or find_library calls contained therein will implicitly understand that `<pkgname>_ROOT` should be used as a searchpath. So the idea is that we should be able to rely on your setting OpenJPEG_ROOT to the nonstandard location and it should be able to find the components. So I'd like to get to the bottom of why this doesn't seem to be working for you. In particular, for OIIO's latest release or for master,

1. If you set env or CMake variable OpenJPEG_ROOT to the right spot, can it not find it? And if not, why not?
2. Failing that, can you directly set `-DOPENJPEG_LIBRARY_RELEASE=/path/to/libopenjp2.so` and `-DOPENJPEG_INCLUDE_DIR=/path/to/openjpeg/includes`, those are additional overrides.

If neither of those work, then what I think would be helpful is if you could `ls -R /path/to/openjpeg` so I can see the file layout, maybe something nonstandard is going on. Also, when you do a fresh cmake config step, use `-DVERBOSE=1` and it will print information about each found package, like for me it says

```
-- Found OpenJPEG 2.5
--     OPENJPEG_INCLUDES = /usr/local/include/openjpeg-2.5
--     OPENJPEG_INCLUDE_DIR = /usr/local/include/openjpeg-2.5
--     OPENJPEG_LIBRARIES = /usr/local/lib/libopenjp2.dylib
```

it may fail, but I'd like to see which specific parts it finds and which it doesn't.

**Comment by lashgar** [comment]
Problem solved, I was calling cmake with wrong arguments. Setting `OpenJPEG_ROOT` works is sufficient to specify openjpeg path. I verified with the current tip of master (rev dc5bffcf3f0fce36be108fb8e5b3060a754a4a6b) and OpenJPEG 2.5 is found ok:
```
...
-- Found JPEG 90                                                                                                                                 
-- Using internal PugiXML                                                                                                                        
-- Found Python 3.11.0                                                  
-- Found PNG 1.6.39                                                                                                                              
-- Found BZip2 1.0.8                                                                                                                             
-- Found Freetype 2.12.1                                                                                                                         
-- Could NOT find OpenColorIO (missing: OpenColorIO_DIR)                                                                                         
-- OpenColorIO library not found                                        
--     Try setting OpenColorIO_ROOT ?                                   
--     Maybe this will help:  src/build-scripts/build_opencolorio.bash  
-- Not using OpenCV -- disabled                                                                                                                  
-- Could NOT find TBB (missing: TBB_DIR)                                
-- TBB library not found                                                                                                                         
--     Try setting TBB_ROOT ?                                                                                                                    
-- DCMTK library not found                                                                                                                       
--     Try setting DCMTK_ROOT ?                                                                                                                  
-- Found FFmpeg 5.1                                                                                                                              
-- Found GIF 5.2.1 
-- Libheif library not found 
--     Try setting Libheif_ROOT ? 
-- Found LibRaw 0.20.2 
-- Found OpenJPEG 2.5 
...
```
Here are the cmake arguments for this call:
```
cmake ../oiio/ \
  -DUSE_FFMPEG=ON \
  -DOIIO_BUILD_TOOLS=OFF \
  -DOIIO_BUILD_TESTS=OFF \
  -DUSE_OPENCV=OFF \
  -DCMAKE_INSTALL_PREFIX=/root/miniconda/envs/new-conda/ \
  -DCMAKE_INSTALL_LIBDIR=lib \
  -DCMAKE_BUILD_TYPE=Release \
  -DOpenJPEG_ROOT=/root/miniconda/envs/new-conda/
```
