### ISSUE TITLE
[HELP] Reading an image and flipping it vertically into a non-interleaved buffer

### ISSUE THREAD

**Issue by jesseyeh** [OpenImageIO/oiio#3700]
When reading images, is there a way to:
1. Read images into a non-interleaved pixel buffer (so the order of the buffer values looks like RRRGGGBBB instead of RGBRGBRGB)
2. Flip images vertically upon reading

I was able to attain a non-interleaved buffer following the `read_image` example in the documentation (https://openimageio.readthedocs.io/en/latest/imageinput.html#reading-channels-to-separate-buffers), but in order to also flip the image vertically, it looks like I need to provide a negative `y` stride. However, because the stride represents the distance between pixel rows in the buffer itself, it doesn't seem possible to specify a stride value that makes sense for a non-interleaved buffer. Is there a way to achieve both?

**Comment by lgritz** [comment]
Many formats (and/or their underlying libraries) don't have a good way to read scanlines with random access -- quite often reading a scanline earlier than the last one you read will require starting again at zero and working your way back up.

So you definitely want to *read* them in forward order, but you can have it reverse the data as it fills in, by using strides (which you don't supply in the example above at all).

I think the solution you're looking for is the following:

```
for (int channel = 0; channel < numChannels; ++channel) {
    read_image (subimage, miplevel,
                channel, channel + 1,
                OIIO::TypeDesc::FLOAT,
                &pixelBuffer[width * height * channel + (width * (height - 1))],
                sizeof(float),  // xstride
                -(spec.width * spec.nchannels * sizeof(float)) // ystride
                );
}
```

What we are doing is pointing the "start" of the buffer to where the LAST scanline for this channel goes, and telling it that the y (scanline-to-scanline) stride is the negative of what it would ordinarily be, so it starts each scanline earlier in your buffer. It's reading the file forward (fast), but it's writing the data to your buffer in reverse scanline order.

**Comment by jesseyeh** [comment]
I had to change the `ystride` to `-(spec.width * sizeof(float)`, but aside from that, your solution works for me. Thanks for the detailed explanation!

**Comment by lgritz** [comment]
Yes, of course, sorry for the typo. I will edit the comment above so it's correct for anybody who reads this later.
