### ISSUE TITLE
[BUG] ImageBufAlgo.render_text with linefeed "\n" interpret as ☒ 

### ISSUE THREAD

**Issue by VeroniqueHuang** [OpenImageIO/oiio#3720]
**Describe the bug**
When using render_text with python3 on a image, when the text contains "\n" character it is interpret as "☒". I expect to do a new line.

**To Reproduce**
in a python file :
```
img = ImageBuf("image.png")
myText = "Hello world \n Hello you !"
if not oiio.ImageBufAlgo.render_text (img,
                                   100,100, 
                                    myText, 
                                    20,
                                    "Font/Roboto/Roboto-Regular", 
                                    white,
                                    alignx="center"):
        print ("error: " + img.geterror())

> python3 main.py
```

** Result**
`Hello World ☒ Hello You !` 

**Expected behavior**
`Hello World` 
`Hello You !` 

**Platform information:**
 - OIIO branch/version: OIIO version 2.2.18
 - OS: Ubuntu 22.04.1 LTS
 - Python compiler: python3

**Comment by lgritz** [comment]
I believe that this was fixed by #3024 and is works correctly in OIIO 2.3 and newer.
