### ISSUE TITLE
[BUG] ImageInput::open with JPEG images is not thread-safe

### ISSUE THREAD

**Issue by mugulmd** [OpenImageIO/oiio#3756]
**Describe the bug**
I tried to read the format name of 4 JPEG images using 2 or more threads, but a segmentation fault occurred when calling `ImageInput::open`.
This never happened when using a single thread.

**To Reproduce**
Short example program to reproduce the behavior:
```
#pragma omp parallel for num_threads(nbThreads)
for (auto path : imagePaths) {
    auto tid = std::this_thread::get_id();
    LOG(tid << " opening image " << path);
    auto input = OIIO::ImageInput::open(path);
    if (!input) {
        LOG(tid << " failed with error: " << OIIO::geterror());
    }
    auto name = input->format_name();
    LOG(tid << " format name: " << name);
}
```

**Expected behavior**
No segmentation fault.
If `ImageInput::open` failed, I expect it to return a null pointer and retrieve an error message from `OIIO::geterror()` as it is documented.

**Evidence**
When running the above example program with `nbThreads = 2` and getting a segmentation fault I have the following backtrace:

```
#0  0x00007ffff7925cf3 in OpenImageIO_v2_4::decode_icc_profile(OpenImageIO_v2_4::span<unsigned char const, -1l>, OpenImageIO_v2_4::ImageSpec&, std
::string&) () from /s/apps/users/multiview/oiio/2.4.7.0/platform-linux/build-release/lib/libOpenImageIO.so.2.4
#1  0x00007ffff7a8165a in OpenImageIO_v2_4::JpgInput::read_icc_profile(jpeg_decompress_struct*, OpenImageIO_v2_4::ImageSpec&) () from /s/apps/user
s/multiview/oiio/2.4.7.0/platform-linux/build-release/lib/libOpenImageIO.so.2.4
#2  0x00007ffff7a82902 in OpenImageIO_v2_4::JpgInput::open(std::string const&, OpenImageIO_v2_4::ImageSpec&) () from /s/apps/users/multiview/oiio/
2.4.7.0/platform-linux/build-release/lib/libOpenImageIO.so.2.4
#3  0x00007ffff79a4736 in OpenImageIO_v2_4::ImageInput::create(OpenImageIO_v2_4::basic_string_view<char, std::char_traits<char> >, bool, OpenImage
IO_v2_4::ImageSpec const*, OpenImageIO_v2_4::Filesystem::IOProxy*, OpenImageIO_v2_4::basic_string_view<char, std::char_traits<char> >) () from /s/
apps/users/multiview/oiio/2.4.7.0/platform-linux/build-release/lib/libOpenImageIO.so.2.4
#4  0x00007ffff798c8b5 in OpenImageIO_v2_4::ImageInput::open(std::string const&, OpenImageIO_v2_4::ImageSpec const*, OpenImageIO_v2_4::Filesystem:
:IOProxy*) () from /s/apps/users/multiview/oiio/2.4.7.0/platform-linux/build-release/lib/libOpenImageIO.so.2.4
```

One set of images with which the bug seems to occur often is [Monstree](https://github.com/alicevision/dataset_monstree) (approximately 50% of the trials end up in a segmentation fault when using the mini datasets).

**Platform information:**
 - OIIO branch/version: 2.4.7.0
 - OS: CentOS Linux 7 (Core)
 - C++ compiler: GCC 9.3.1
 - Any non-default build flags when you build OIIO:

**Comment by fabiencastan** [comment]
Hello @lgritz,
It would be great if you could check this problematic issue!
