### ISSUE TITLE
[FEATURE REQUEST] make oiio easier to cross compile by not using check_cxx_source_runs

### ISSUE THREAD

**Issue by russelltg** [OpenImageIO/oiio#3773]
**Is your feature request related to a problem? Please describe.**

I'm cross-compiling oiio (specifically Linux x86_64 -> Linux aarch64), and I have to set `-DDCOMPILER_SUPPORTS_ATOMIC_WITHOUT_LIBATOMIC_EXITCODE=0` to be able to compile this library, which works fine but looking at the test that's being performed it seems like a `check_cxx_source_compiles` would be sufficient to see if libatomic is necessary? This would allow cmake to cross compile it without any extra flags passed. 

**Describe the solution you'd like**

Use `check_cxx_source_compiles` instead of `check_cxx_source_runs` for libatomic.

**Describe alternatives you've considered**

Doing nothing

**Additional context**

If this seems reasonable, I'm happy to open a PR.

**Comment by lgritz** [comment]
Sounds reasonable. Please do submit a PR if you have a fix.
