### ISSUE TITLE
[BUG] Greyscale DNG read as 3 channel, not 1

### ISSUE THREAD

**Issue by MikePelton** [OpenImageIO/oiio#3797]
**Describe the bug**
Opening a greyscale  (i.e. 1 byte per pixel) DNG file returns a spec with 3 channels rather than 1, even though opening the same file with libraw gets it right. I realise greyscale DNG isn't exactly common but we use it all the time for infra-red camera arrays!

The behaviour is the same whether or not a hint spec is provided (see the commented lines).

**To Reproduce**
```
std::string filename = "...../Frame0000000001.dng";
    //ImageSpec specHint(2048, 2048, 1, TypeDesc::UINT16);
   // std::unique_ptr<ImageInput> inp = ImageInput::open(filename, &specHint);
    std::unique_ptr<ImageInput> inp = ImageInput::open(filename);
    if (!inp)
        return -1;

    const ImageSpec& spec = inp->spec();
    int xres = spec.width;
    int yres = spec.height;
    int channels = spec.nchannels;
```

channels here is 3, not 1 as expected, and subsequent conversion to another format (e.g. JPG) results in black images.

**Expected behavior**
channels should be 1, or the grey image should be up-channeled to RGB

**Evidence**
Script as above, can't see how to attach an image file :-(

**Platform information:**
 - OIIO branch/version: latest
 - OS: Windows
 - C++ compiler: Vs 2022
 - Any non-default build flags when you build OIIO: nope, as build by vcpkg

**Comment by lgritz** [comment]
Can you email me the image, or host it someplace where I can download it?

Do you know which format reader it's using? Right after you do the open, how about

    std::cout << "format " << inp->format_name() << "\n";

**Comment by lgritz** [comment]
GH says you can attach files by dragging or pasting them right into the comment box here when you leave a comment.

**Comment by MikePelton** [comment]
Hi Larry and thanks for picking up on this so quickly. A couple of extra details: vcpkg tells me the openimageio version is "2.3.10.1#2" and it's on Windows 11. Also the response to the format_name() query is "raw", and worth adding too is that inp->read_image returns false whether I specify UINT8 or UINT16. There's a 5MB sample image [here](https://pollytiles-my.sharepoint.com/:i:/g/personal/mike_pollytiles_onmicrosoft_com/ESY7jdIaGcNFjypzBZotxj4BviyC-GkffEDA3ER383R9wQ?e=lcfXi3) which is from an IOI industrial camera (and copyright, not that it has any inherent value!) and as I say libraw gets it okay. Let me know if I can help further!

**Comment by lgritz** [comment]
Yeah, ok, I can reproduce weirdness with this example. Thanks, that was very helpful!

I have a fix. Please see #3798. Are you able to apply that patch on your end to verify that it solves your problems? Or are you not really going to be able to verify until we have the patch in a full release which is then picked up by vcpkg?

**Comment by MikePelton** [comment]
Thanks again for jumping on this Larry - you're right we'd need to run this in the context of vcpkg for real so if you need verification of that fix at scale once it's bagged up into a release, I'd be more than happy to help.
