### ISSUE TITLE
[HELP] Compiler error in simd.h with CUDA/__AVX__ 

### ISSUE THREAD

**Issue by dedoardo** [OpenImageIO/oiio#3809]
Hi Larry and everyone,

It seems like you can run into a compiler error when compiling a CUDA file that defines `__AVX__` and includes `simd.h`. 
This happens because the SIMD intrinsics header [is not included when `__CUDA_ARCH__` is defined](https://github.com/OpenImageIO/oiio/blob/master/src/include/OpenImageIO/simd.h#L85) but later the code [still attempts to define the AVX version](https://github.com/OpenImageIO/oiio/blob/master/src/include/OpenImageIO/simd.h#L139
) and uses the types resulting in undefined symbols.
For the SSE case [this is prevented](https://github.com/OpenImageIO/oiio/blob/master/src/include/OpenImageIO/simd.h#L107) by explicitly defining `OIIO_NO_SSE` and the idea for the fix we had in mind was to add the AVX equivalent.

```
#if defined(__CUDA_ARCH__) && !defined(OIIO_NO_AVX)
#define OIIO_NO_AVX 1
#endif
```

Thought I would check in with you before making a PR to see if you were aware of the issue and maybe had a different fix in mind.
For reference, we encountered this issue when building OpenShadingLanguage with Optix support.

Cheers,
Edoardo

**Comment by lgritz** [comment]
OK, that seems fine to include a clause like you have above, but I'm still confused about how `__AVX__` gets defined for a Cuda compile. Can you clarify where that gets set?

**Comment by lgritz** [comment]
Specifically, grep shows that OIIO itself does not define `__AVX__` anywhere, which makes me wonder where it's coming from. It is intended to be a "read-only" signal from the compiler that we should be generating AVX-enabled code. If some other code or build system is defining it behind the compiler's back, that seems like a mistake.

(Maybe that is a fact of life and we need a clause like you describe as a workaround on our end. But it should really get reported to whomever is incorrectly setting the symbol.)

**Comment by dedoardo** [comment]
Thanks for getting back to me quickly! I agree with this not being an OIIO issue per se.
The chain of events appears to be the following:
- OpenShadingLanguage is built as an external project with `USE_SIMD="avx,..."` and `USE_OPTIX=TRUE` 
- The `SIMD_COMPILE_FLAGS` variable is set to include the `-m` architecture flags [here](https://github.com/AcademySoftwareFoundation/OpenShadingLanguage/blob/main/src/cmake/compiler.cmake#L309)
- The cmake proceeds to [compile the PTX](https://github.com/AcademySoftwareFoundation/OpenShadingLanguage/blob/main/src/liboslexec/CMakeLists.txt#L202) bytecode of some standard noise functions [with the simd flags included](https://github.com/AcademySoftwareFoundation/OpenShadingLanguage/blob/main/src/cmake/cuda_macros.cmake#L70)

Building for CPU and GPU simultaneously results in the SIMD flags being mixed together and it's actually the PTX backend for LLVM not the CUDA compiler. 
I believe this can also be fixed in the CMakeLists.txt of OpenShadingLanguage, happy to move the discussion over there.

**Comment by lgritz** [comment]
OH, I see, yes, Cuda that is launched with -m for the CPU side may still leave those symbols alive for the Cuda side. I get it. Your suggestion makes total sense, I will propose a specific fix.

**Comment by lgritz** [comment]
Proposed fix https://github.com/OpenImageIO/oiio/pull/3810

**Comment by dedoardo** [comment]
Thanks Larry, the fix looks great! I discovered a similar instance of this problem in the meantime :)
I was running `OpenImageIO-2.4.6.1` previously, but now that I have updated it, a new version of `fmt` is being used that [attempts to use `__float128`](https://github.com/fmtlib/fmt/blob/a33701196adfad74917046096bf5a2aa0ab0bb50/include/fmt/format.h#L740). 
I am trying to better understand the support of this feature because the NVCC compiler itself seems to support it (on godbolt), but when compiling through LLVM with the PTX backend I get errors saying `error: __float128 is not supported on this target`

I don't know if this is something that really belongs in OpenImageIO, but thought it was worth sharing since we encounter the problem when building the OpenShadingLanguage standard library for Optix. 

The problem can be worked around defining `-DFMT_USE_FLOAT128=0`. 
I also noticed that there is a recent commit on fmtlib that does better checking and circumvents the issue. Unfortunately it hasn't been released yet https://github.com/fmtlib/fmt/commit/99070899b7476da670fc7a70c4515ddf3bab2bfc

Will report when I know more, thanks again for the PR!

**Comment by lgritz** [comment]
On the float128 issue, would it be sufficient to just `#define FMT_USE_FLOAT128=0` in src/include/OpenImageIO/detail/fmt.h ?  (Perhaps guarded by something that only disables it for the Cuda target?)

**Comment by dedoardo** [comment]
Yes, adding the following bit of code fixed it. I wanted to make sure that it wasn't some of our compiler setup but it seems something [specific to the nvptx backend for llvm](https://discourse.llvm.org/t/compiling-cuda-code-fails/61240/8). Maybe nvcc emulates it? 
```
#ifdef __CUDA_ARCH__ && !defined(FMT_USE_FLOAT128)
#define FMT_USE_FLOAT128 0
#endif
```

I need to figure out what to sign in order to make a PR :)

**Comment by lgritz** [comment]
> I need to figure out what to sign in order to make a PR :)

Nothing! Historically, CLAs have been optional for this project; I strongly encourage them for large changes or new features, but not for minor fixes or anything too small to ever plausibly be the subject of a serious IP fight. Just go ahead and make the PR.

**Comment by dedoardo** [comment]
PR is here https://github.com/OpenImageIO/oiio/pull/3823
