### ISSUE TITLE
[BUG] OIIO Mailing List Search Broken

### ISSUE THREAD

**Issue by robinrowe** [OpenImageIO/oiio#3815]
Went to http://lists.openimageio.org/pipermail/oiio-dev-openimageio.org/. Searched for "Windows" to find any list mails on that topic...

Result:

ht://Dig error

htsearch detected an error. Please report this to the webmaster of this site by sending an e-mail to: [mailman@listserver-elm.dreamhost.com](mailto:mailman@listserver-elm.dreamhost.com) The error message is:

Unable to read word database file '/usr/local/dh/mailman/elm/archives/private/oiio-dev-openimageio.org/htdig/db.words.db'
Did you run htdig?

**Comment by lgritz** [comment]
I'm inclined to recommend that we not bother looking at this. One of the first things that will happen when OIIO is accepted as an ASWF project will be that LF will help us set up a new mail list on aswf.io and do the work to import the history of the old list, so we'll be able to search the archives then. Work specific to fixing anything broken in the old list that will be retired in a month is probably not a good use of time.

**Comment by lgritz** [comment]
New mail list is now up and people should sign up for it here: https://lists.aswf.io/g/oiio-dev/

The old list will be retired in days. Closing this issue as no longer relevant.
