### ISSUE TITLE
[BUG] oiiotool uses wrong channel for alpha when dropping channels

### ISSUE THREAD

**Issue by Latios96** [OpenImageIO/oiio#3837]
**Describe the bug**

I have an OpenExr file that I try to convert to a PNG file using oiiotool. The OpenExr file has six channels: R, G, B, sampleCount.R, sampleCount.G, sampleCount.B

oiiotool recognizes that the OpenExr file has more channels than a PNG file can support and saves only channels 0,1,2,3, so channel 3 ends up as the alpha channel in the png file. This is not correct, because channel 3 is not an alpha channel, it's an arbitrary additional channel in the OpenExr file.

To me this looks like a bug. I had a quick look at the source code and oiiotool assumes that the input channel has an alpha channel if the channel count is larger than 3 (see [here](https://github.com/OpenImageIO/oiio/blob/5152be9a57f2f0fd9296496b4cebf93252424ab9/src/oiiotool/oiiotool.cpp#LL5663C1-L5664C1)). It might be a really rare case to have an OpenExr file with more than 3 channels but no alpha channel. But I think it should be possible to detect if the input image actually has an alpha channel. 

**To Reproduce**
1. Download the attached OpenExr file
2. `oiiotool -i reference.exr -o reference.png`
3. oiiotool states `oiiotool WARNING: -o : Can't save 6 channels to png... saving only 0,1,2,3`

**Expected behavior**
oiiotool should only save the RGB channels from the OpenExr to the PNG file

**Attachments**
[reference.zip](https://github.com/OpenImageIO/oiio/files/11469679/reference.zip)

**Comment by lgritz** [comment]
You are quite right. Proposed fix: https://github.com/OpenImageIO/oiio/pull/3838

**Comment by Latios96** [comment]
Just tried your fix, works as expected for me. Thanks for the quick fix!
