### ISSUE TITLE
[DOC] ImageOutput: Writing Images wrong Python example code

### ISSUE THREAD

**Issue by johhnry** [OpenImageIO/oiio#3846]
**Describe the bug**
In the **Image Output Made Simple** section: https://openimageio.readthedocs.io/en/latest/imageoutput.html#image-output-made-simple

The example Python code simply doesn't work.

**To Reproduce**

```python
# main.py

import OpenImageIO as oiio
import numpy as np

filename = "foo.jpg"
xres = 640
yres = 480
channels = 3  # RGB
pixels = np.zeros((yres, xres, channels), dtype=np.uint8)

out = oiio.ImageOutput.create (filename)
if out is None:
    return
spec = ImageSpec(xres, yres, channels, 'uint8')
out.open (filename, spec)
out.write_image (pixels)
out.close ()
```

```shell
$ python main.py

 File "<cwd>\main.py", line 13
    return
    ^^^^^^
SyntaxError: 'return' outside function
```

Also `ImageSpec` is not imported from `oiio` so it doesn't work.

**Comment by lgritz** [comment]
That looks right. It would be really great if you could try making that into a PR.

**Comment by ziggycross** [comment]
Will do today :)

**Comment by hisergiorojas** [comment]
Hey @lgritz [ImageInput](https://openimageio.readthedocs.io/en/latest/imageinput.html) also as the same issue in the documentation.
