### ISSUE TITLE
[BUG] Jpeg2000 32bit buffer write as a 8bit int instead of 16bit.

### ISSUE THREAD

**Issue by ssh4net** [OpenImageIO/oiio#3876]
**Describe the bug**
Based on OIIO documentation, if output file format is not support original buffer depth it should be converted on-fly into nearest supported. In case of 32bit float and JPEG2000 that support 16bit integer, ImageBuf should be saved in 16bit, but it saving in 8bit.

**To Reproduce**
```
    out->open(outputFileName, rspec, ImageOutput::Create);
    out->write_image(out_buf.spec().format, out_buf.localpixels(), 
        out_buf.pixel_stride(), out_buf.scanline_stride(), out_buf.z_stride(), 
        *progress_callback, progressBar);
    out->close();

```
**Expected behavior**
Expected 32bit float -> 16bit int

**Platform information:**
 - OIIO branch/version: 2.4.11 (VCPKG) 
 - OS: Windows
 - C++ compiler: VS2019
 - Any non-default build flags when you build OIIO:

For this moment is workaround, explicitly convert 32 bit float to 16bit int. Than JPEG2000 saving 16bit correctly.

**Comment by lgritz** [comment]
Proposed fix here: https://github.com/OpenImageIO/oiio/pull/3878
