### ISSUE TITLE
[BUG] 0.0f is raw:Exposure invalid value. range 0.25f - 8.0f

### ISSUE THREAD

**Issue by ssh4net** [OpenImageIO/oiio#3888]
**Describe the bug**
Invalid image file "D:/TEST/CameraRaws/_DSC2538.ARW": raw:Exposure invalid value. range 0.25f - 8.0f

```
config["raw:Exposure"] = 0.0f;
```

**To Reproduce**
```
ImageSpec config;
config["raw:Exposure"] = 0.0f;
ImageBuf input_buf(inputFileName, 0, 0, nullptr, &config, nullptr);
bool read_ok = outBuf.read(0, 0, 0, last_channel, true, o_format, progress_callback, progressBar);

```
**Expected behavior**
or something wrong in docs or in code. 0.0f in range but code give error.

**Platform information:**
 - OIIO branch/version: 2.4.1 (VCPKG
 - OS: Windows 10
 - C++ compiler: Visual Studio 2022

**Comment by lgritz** [comment]
Looking at the libraw documentation here https://www.libraw.org/docs/API-datastruct-eng.html

It describes the underlying parameters that we are setting:

```
int exp_correc; float exp_shift,exp_preser;

Exposure correction before demosaic.

* exp_correc: positive value turns the feature on (default: off).
* exp_shift: exposure shift in linear scale. Usable range from 0.25 (2-stop darken) to 8.0 (3-stop lighter). Default: 1.0 (no exposure shift).
* exp_preser: preserve highlights when lighten the image. Usable range from 0.0 (no preservation) to 1.0 (full preservation). 0.0 is the default value.
```

**Comment by ssh4net** [comment]
Oh. I see. So 1.0 is 2^0EV.

**Comment by lgritz** [comment]
I see now that the explanation in our documentation is incorrect, saying that 0 is "no change", when that actually should be 1.0. I will correct that with a PR.

**Comment by lgritz** [comment]
Docs fix: https://github.com/OpenImageIO/oiio/pull/3889
