### ISSUE TITLE
[BUG] neon support is disabled on macOS arm

### ISSUE THREAD

**Issue by 1-Olivier** [OpenImageIO/oiio#3909]
Commit 22a8196c8f5a77a767cac36de595bcd07afb885d  does `#define OIIO_NO_NEON 1` whenever `__aarch64__` is set so a macOS arm build ends up with no neon support. By the commit message and comments, I don't think that was the intent.

Stuff still works. I only found out because I have an assertion in my code that some buffers provided by OSL should be 16 byte aligned and they weren't.

**Comment by lgritz** [comment]
You are quite right, that looks wrong. Should be an easy fix, I will prepare a PR right away.

**Comment by lgritz** [comment]
Please see proposed fix in #3911. @1-Olivier can you try that out on your end and verify that it looks right to you?

**Comment by 1-Olivier** [comment]
Looks good and works for me.
