### ISSUE TITLE
Image is all white when loaded

### ISSUE THREAD

**Issue by DougRogers** [OpenImageIO/oiio#3962]
Attached is a PSD file that only produces white when loaded.  It loads properly into Photoshop.

16 bit pixels.

[OIIOTest.zip](https://github.com/OpenImageIO/oiio/files/12432795/OIIOTest.zip)

**Comment by lgritz** [comment]
🎣 Mackerel!

Anybody care to take a stab at this?

**Comment by lgritz** [comment]
@DougRogers Doug, are you quite sure? I don't have PhotoShop myself, but Gimp also displays it as all white. Using my Mac's Preview.app is also not helpful, just displays the image as black. Mac's ColorSync utility also shows all white.

**Comment by DougRogers** [comment]
Quite Sure.
[TestPSD.zip](https://github.com/OpenImageIO/oiio/files/12508565/TestPSD.zip)

**Comment by lgritz** [comment]
Interesting. I wonder what's unusual about this psd file that is also preventing GIMP and Apple Preview.app from decoding it properly.

**Comment by DougRogers** [comment]
This image has two 16 bpp layers.

**Comment by DougRogers** [comment]
It looks like it has three layers, not two and the third one is all white.  I suspect that is what is being displayed but the other programs.

**Comment by DougRogers** [comment]
Not three layers, either.  Two layers and an "image data section"  that is supposed to be the merged image.  It is all white.  I'm not sure why this is correct in Photoshop.

**Comment by DougRogers** [comment]
It seems if you export from Photoshop and specify "Maximize Compatibility", it merges the layers and creates an image data section.

https://www.adobe.com/devnet-apps/photoshop/fileformatashtml/#50577409_89817

**Layer and Mask Information Section**
The fourth section of a Photoshop file contains information about layers and masks. This section of the document describes the formats of layer and mask records.

The complete merged image data is not stored here. The complete merged/composite image resides in the last section of the file. See [See Image Data Section](https://www.adobe.com/devnet-apps/photoshop/fileformatashtml/PhotoshopFileFormats.htm#50577409_89817). If maximize compatibility is unchecked then the merged/composite is not created and the layer data must be read to reproduce the final image.

-------------------------------------------------------------------------------
This image did not have maximize compatibility selected when exported.  It is odd because that section *is* present and it is all white.  I don't know how PS interpreted this.

I suppose it makes sense to only support the format when maximize capability is selected, but I don't see a way to check that since the image data section is present.

**Comment by DougRogers** [comment]
It just occurred to me that PS would not look at the image data section.  It would just load the layers and build the image from that.  

It looks like the issue is that PS exports an image data section with all white when maximum compatibility is not selected.

**Comment by DougRogers** [comment]
I am really surprised that the image data section is not always included in the PSD file format.

**Comment by DougRogers** [comment]
Photoshop files have to be exported with maximum compatibility, or they store all white images.
