### ISSUE TITLE
Redefinition of NOMINMAX causes warning in Windows

### ISSUE THREAD

**Issue by DougRogers** [OpenImageIO/oiio#3964]
In platform.h for Windows, there is a definition of NOMINMAX that causes warnings when it is already defined.

```
//Avoid min and max being defined
#if defined(_WIN32)
#define NOMINMAX
#endif
```
Furthermore, right above it is another definition of NOMINMAX correctly wrapped by an ifdef

```
#if defined(_WIN32)
#    ifndef WIN32_LEAN_AND_MEAN
#        define WIN32_LEAN_AND_MEAN
#    endif
#    ifndef VC_EXTRALEAN
#        define VC_EXTRALEAN
#    endif
#    ifndef NOMINMAX
#        define NOMINMAX
#    endif
#    ifndef NOGDI
#        define NOGDI
#    endif
#    include <windows.h>
#endif


```

**Comment by lgritz** [comment]
Where exactly do you see the more complicated second one? I'm not seeing that in platform.h or anywhere else in the codebase.

**Comment by DougRogers** [comment]
Right below it

![image](https://github.com/OpenImageIO/oiio/assets/7563851/19b622a2-5c4b-4650-a64a-a2781ecbc70d)

**Comment by DougRogers** [comment]
This is the current version in vcpkg.  Version 2.4.14.0

**Comment by lgritz** [comment]
Aha, I see. That has been eliminated from master -- it was changed so we never directly include windows.h in platform.h.

I'll certainly fix it so that it doesn't do the #define if it's already been done, and do the full set of defines in the few places where we need windows.h.
