### ISSUE TITLE
[BUG] Chromaticity values are missing in OpenEXR

### ISSUE THREAD

**Issue by trougnouf** [OpenImageIO/oiio#3975]
**Describe the bug**

When trying to save OpenEXR images with given chromaticity values for lin. rec. 2020, these values are not read by darktable and the image defaults to linear sRGB. I've tried setting the ColorSpace and the chroma values to no avail.

**To Reproduce**
Run the following to generate two yellow images using OpenEXR and OpenImageIO:

```python
import numpy as np
from typing import Literal, Optional
import OpenEXR
import Imath
import OpenImageIO as oiio


def rgb_img_to_file(
    # TODO merge with pt_helpers.tensor_to_imgfile
    img: np.ndarray,
    fpath: str,
    color_profile: Literal["lin_rec2020", "lin_sRGB", "gamma_sRGB"],
    bit_depth: Optional[int] = None,
) -> None:
    """Save (c,h,w) RGB image to file."""
    if fpath.endswith("exr"):
        if bit_depth is None:
            bit_depth = 16 if img.dtype == np.float16 else 32
        elif bit_depth == 16 and img.dtype != np.float16:
            img = img.astype(np.float16)
        elif bit_depth == 32 and img.dtype != np.float32:
            img = img.astype(np.float32)
        else:
            raise NotImplementedError(
                f"rgb_img_to_file: {bit_depth=} with OpenEXR and {img.dtype=}"
            )
        if OPENEXR_PROVIDER == "OpenImageIO":
            output = oiio.ImageOutput.create(fpath)
            if not output:
                raise RuntimeError(f"Could not create output for {fpath}")
            # Set the format and metadata

            spec = oiio.ImageSpec(
                img.shape[2],
                img.shape[1],
                img.shape[0],
                oiio.HALF if bit_depth == 16 else oiio.FLOAT,
            )
            if color_profile == "lin_rec2020":
                # Set chromaticities for Rec. 2020
                spec.attribute("oiio:ColorSpace", "Rec2020")
                spec.attribute("rla:RedChroma", "0.708, 0.292")
                spec.attribute("rla:GreenChroma", "0.17, 0.797")
                spec.attribute("rla:BlueChroma", "0.131, 0.046")
                spec.attribute("rla:WhitePoint", "0.3127, 0.3290")
            elif color_profile == "lin_sRGB":
                # Set chromaticities for linear sRGB
                spec.attribute("oiio:ColorSpace", "lin_srgb")
                spec.attribute("rla:RedChroma", "0.64, 0.33")
                spec.attribute("rla:GreenChroma", "0.30, 0.60")
                spec.attribute("rla:BlueChroma", "0.15, 0.06")
                spec.attribute("rla:WhitePoint", "0.3127, 0.3290")
            else:
                print(f"warning: no color profile for {fpath}")

            # Set compression to ZIPS
            spec.attribute("compression", "zips")
            # Bit depth
            if not bit_depth:
                if img.dtype == np.float16:
                    bit_depth = 16
                elif img.dtype == np.float32:
                    bit_depth = 32
                else:
                    raise NotImplementedError(
                        f"rgb_img_to_file: {img.dtype=} with OpenEXR"
                    )

            # spec.set_format(oiio.HALF if bit_depth == 16 else oiio.FLOAT)
            # Open the output file and write the image data
            if output.open(fpath, spec):
                success = output.write_image(
                    np.ascontiguousarray(img.transpose(1, 2, 0))
                )  # .tolist())
                output.close()
                if not success:
                    breakpoint()
                    raise RuntimeError(
                        f"Error writing {fpath}: {output.geterror()} ({img.shape=})"
                    )
            else:
                raise RuntimeError(f"Error opening output image: {fpath}")
        elif OPENEXR_PROVIDER == "OpenEXR":
            # Init OpenEXR header
            header = OpenEXR.Header(img.shape[-1], img.shape[-2])
            header["Compression"] = Imath.Compression(
                Imath.Compression.ZIPS_COMPRESSION
            )
            # Chromaticities
            assert color_profile is None or color_profile.startswith(
                "lin"
            ), f"{color_profile=}"
            if color_profile == "lin_rec2020":
                header["chromaticities"] = Imath.Chromaticities(
                    Imath.chromaticity(0.708, 0.292),
                    Imath.chromaticity(0.17, 0.797),
                    Imath.chromaticity(0.131, 0.046),
                    Imath.chromaticity(0.3127, 0.3290),
                )
            elif color_profile == "lin_sRGB":
                header["chromaticities"] = Imath.Chromaticities(
                    Imath.chromaticity(0.64, 0.33),
                    Imath.chromaticity(0.30, 0.60),
                    Imath.chromaticity(0.15, 0.06),
                    Imath.chromaticity(0.3127, 0.3290),
                )
            elif color_profile is None:
                pass
            else:
                raise NotImplementedError(
                    f"rgb_img_to_file: OpenEXR with {color_profile=}"
                )
            if bit_depth == 16:
                header["channels"] = {
                    "R": Imath.Channel(Imath.PixelType(Imath.PixelType.HALF)),
                    "G": Imath.Channel(Imath.PixelType(Imath.PixelType.HALF)),
                    "B": Imath.Channel(Imath.PixelType(Imath.PixelType.HALF)),
                }
                np_data_type = np.float16
            elif bit_depth == 32:
                # converting to np.float32 even though it's already the dtype, otherwise
                # *** TypeError: Unsupported buffer structure for channel 'B'
                # with negative values.
                header["channels"] = {
                    "R": Imath.Channel(Imath.PixelType(Imath.PixelType.FLOAT)),
                    "G": Imath.Channel(Imath.PixelType(Imath.PixelType.FLOAT)),
                    "B": Imath.Channel(Imath.PixelType(Imath.PixelType.FLOAT)),
                }
                np_data_type = np.float32
            else:
                raise NotImplementedError(f"rgb_img_to_file: OpenEXR with {bit_depth=}")
            # Save
            # TODO include EXIF metadata
            exr = OpenEXR.OutputFile(fpath, header)

            exr.writePixels(
                {
                    "R": img[0].astype(np_data_type),
                    "G": img[1].astype(np_data_type),
                    "B": img[2].astype(np_data_type),
                }
            )
            exr.close()
        else:
            raise NotImplementedError(f"rgb_img_to_file: {OPENEXR_PROVIDER=}")


yellow_image = np.ones((3, 100, 100), dtype=np.float32)
yellow_image[0] = 0.5
yellow_image[1] = 0.5
yellow_image[2] = 0.0
for OPENEXR_PROVIDER in ("OpenImageIO", "OpenEXR"):
    rgb_img_to_file(yellow_image, f"test_{OPENEXR_PROVIDER}.exr", "lin_rec2020", 16)

```

**Expected behavior**
The image should open with darktable where the "embedded matrix" input color profile matches linear rec. 2020.

**Platform information:**
 - OIIO branch/version: 2.4.12
 - OS: Arch Linux
 - C++ compiler: 13.2.1

**Comment by trougnouf** [comment]
(Moreover saving a tiff image with `spec.attribute("oiio:ColorSpace", "Rec2020")` does not appear to embed the Rec2020 color profile)

**Comment by lgritz** [comment]
It's true, support of chromaticities is probably missing from many of our readers/writers. This is a simple bug/missing feature that should be fixed. (🎣 Mackerel! For those who know what I mean.) By way of explanation, I'll just say that in 15 years, you're one of the very first people to notice that this is unimplemented, so that probably speaks to how often these attributes are used or trusted in the files. (That's not intended to be an excuse not to implement it.)

Setting "oiio:ColorSpace" to a name and expecting it to set the chromaticity attributes as a result (or the other way, reading chromaticities and inferring a named color space) is not currently a design feature at all. But maybe it should be?

I think there are a number of issues around how color information should be stored in image files and how OIIO should recognize that and understand it in a way that's independent of the individual file format. It also touches OpenColorIO and OpenEXR. This has been on my mind for a while and I'm going to try to get a joint discussion going with these groups so maybe we can chart a common way forward.

**Comment by jessey-git** [comment]
It looks like EXR does respond to the `chromaticities` attribute. It's not in the documentation but the code does look at this attribute for both input and output. E.g. changing Op's code to the following allows things to flow out:
`spec.attribute("chromaticities", oiio.TypeDesc("float[8]"), (0.708, 0.292, 0.17, 0.797, 0.131, 0.046, 0.3127, 0.3290))`

The original code used RLA format attributes which would certainly not work here.

**Comment by lgritz** [comment]
That's right, it does look like the exr input and output do understand the exr "chromaticities" attribute (and to OIIO, it looks like a `float[8]`).

But it does not have any semantics related to the color space -- it (currently) doesn't notice the chromaticities and use it to set the "oiio:ColorSpace" attribute, or upon output to set the chromaticities based on an existing color space. It's just dumb data, so to speak.

Regarding the RLA issue, it helps to know that a convention that OIIO uses for "namespaced" attributes of the form `prefix:name`: If the `prefix` is the name of a file format, it's assumed to be *specific* to that format (usually as a hint rather than literal metadata to be saved to the file). It will be ignored by all other formats (so "rla:foo" will NOT be saved an exr file in the way that something like "Exif:Flash" would be written as arbitrary exr metadata in the usual way).

**Comment by lgritz** [comment]
@nrusch To be clear, I don't think that merely setting an attribute (i.e., calling `spec.attribute("ColorSpace", "ACEScg")`) ought to ever have any effect on pixel values of the image described by the spec. But I can see how having that information attached to an image could affect downstream operations, including those done by OIIO. For example, if oiiotool understands that jpeg files have to be in sRGB but the image says it's something else, maybe it knows to automatically transform from that something else to sRGB before it outputs.

**Comment by lgritz** [comment]
By the way, has this issue been addressed to your satisfaction @trougnouf?

I think the bottom line is:
* Setting "rla:anything" won't have any effect when outputting OpenEXR.
* Setting `attribute("chromaticities", "float[8]", &my_chromatiticies)` should save the values in the openexr file.

Is there something more to fix or answer here for you, or should we close the issue?

**Comment by trougnouf** [comment]
> By the way, has this issue been addressed to your satisfaction @trougnouf?
> 
> I think the bottom line is:
> 
>     * Setting "rla:anything" won't have any effect when outputting OpenEXR.
> 
>     * Setting `attribute("chromaticities", "float[8]", &my_chromatiticies)` should save the values in the openexr file.
> 
> 
> Is there something more to fix or answer here for you, or should we close the issue?

Thank you!
Is this a recent fix that I should build the master branch to test? With openimageio 2.4.12.0 I tried applying `spec.attribute("chromacities", oiio.TypeDesc("float[8]"), [0.708, 0.292, 0.17, 0.797, 0.131, 0.046, 0.3127, 0.3290])` but darktable still sees an "embedded matrix" that matches "linear Rec709 RGB" rather than "linear Rec2020 RGB" (same as if I had not applied anything).
