### ISSUE TITLE
Script for installing build enviorment on Windows

### ISSUE THREAD

**Issue by matekm** [OpenImageIO/oiio#79]
A lot of people, especially before GSoC starts, write to me that settin up build enviorment on Windows is great pain. Binaries of externals that we store on our site not alway work - I'm not sure why, maybe the reason is that they were compiled for other version of Visual Studio that user have. Second problem is that our externals were compiled only for 32-bit build, so the are useless for 64-bit build on Windows.

So there is a need for a script (python, powershell or ruby) that will download dependencies, compile it with given compiler and install in given directory. Thanks to that we could remove our externals for windows and user will build dependencies with the compiler he/she use.

**Comment by StefanAchm** [comment]
Here is a script for installing on windows, that worked for me:

[run.zip](https://github.com/OpenImageIO/oiio/files/806129/run.zip)

!!! Read the first lines (how to install) in the script !!!

**Comment by lgritz** [comment]
Closing this old comment.
