### ISSUE TITLE
Cannot build static library for OIIO v1.3 and 1.4

### ISSUE THREAD

**Issue by efleurant** [OpenImageIO/oiio#838]
When trying to do **_make BUILDSTATIC=1**_ on oiio v1.3 and v.1.4, I get the following error messages:

**oiio 1.3**
'''
...
[100%] Building CXX object src/python/CMakeFiles/PyOpenImageIO.dir/py_oiio.cpp.o
Linking CXX shared library OpenImageIO.so
/usr/bin/ld: ../libOpenImageIO/libOpenImageIO.a(formatspec.cpp.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
../libOpenImageIO/libOpenImageIO.a: could not read symbols: Bad value
collect2: ld returned 1 exit status
make[3]: *** [src/python/OpenImageIO.so] Error 1
make[3]: Leaving directory`/tmp/oiio-RB-1.3/build/linux64'
make[2]: **\* [src/python/CMakeFiles/PyOpenImageIO.dir/all] Error 2
make[2]: Leaving directory `/tmp/oiio-RB-1.3/build/linux64'
make[1]: *** [all] Error 2
make[1]: Leaving directory`/tmp/oiio-RB-1.3/build/linux64'
make: **\* [cmake] Error 2
'''

**oiio 1.4**
'''
...
[100%] Building CXX object src/python/CMakeFiles/PyOpenImageIO.dir/py_oiio.cpp.o
Linking CXX shared library OpenImageIO.so
/usr/bin/ld: ../libOpenImageIO/libOpenImageIO.a(formatspec.cpp.o): relocation R_X86_64_32S against `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::_Rep::_S_empty_rep_storage' can not be used when making a shared object; recompile with -fPIC
../libOpenImageIO/libOpenImageIO.a: could not read symbols: Bad value
collect2: ld returned 1 exit status
make[3]: *** [src/python/OpenImageIO.so] Error 1
make[3]: Leaving directory`/tmp/oiio-master/build/linux64'
make[2]: **\* [src/python/CMakeFiles/PyOpenImageIO.dir/all] Error 2
make[2]: Leaving directory `/tmp/oiio-master/build/linux64'
make[1]: *** [all] Error 2
make[1]: Leaving directory`/tmp/oiio-master/build/linux64'
make: **\* [cmake] Error 2
'''
Now, when building without _BUILDSTATIC_ (so, only _make_), oiio builds perfectly fine for both versions.
I don't know if this is a bug or an issue on my side, would really appreciate any help.

I'm on CentOS 6.5, if you need more details about my build setup, please let me know.

**Comment by lgritz** [comment]
Is any of this still an issue in 1.5 or master?

**Comment by lgritz** [comment]
Closing, this refers to long-ago versions.
