### ISSUE TITLE
Add support for DNG and CinemaDNG file formats

### ISSUE THREAD

**Issue by rexbron** [OpenImageIO/oiio#86]
The CinemaDNG format is designed for storing high-resolution image streams in camera raw format. CinemaDNG is an open, documented format leveraging standard formats for video and imaging — DNG, TIFF, TIFF/EP, MXF, XMP. Each image is encoded using the DNG image format. The image stream can be stored in one of two formats: either as video essence in an MXF file, or as a sequence of image files in a file directory.

I don't think it is within OpenImageIO's design to support the MXF encoded CinemaDNG files, but it would be benificial to support the reading and writing of the image sequence format. 

Specification is available here: http://download.macromedia.com/pub/labs/cinemadng/cinemadng_p1_spec_091009.pdf

**Comment by gregcotten** [comment]
I think this is closed with the libraw plugin, yes?

**Comment by lgritz** [comment]
Agreed, long since fixed.
