### ISSUE TITLE
OpenImageIO python module installed by default into wrong location?

### ISSUE THREAD

**Issue by alex-weej** [OpenImageIO/oiio#926]
$PREFIX/lib/python/site-packages

Doesn't appear to be correct. It should be /lib/python$MAJ.$MIN/site-packages to be picked up by default.

Thanks

**Comment by nieder** [comment]
Adding `-DPYLIB_INSTALL_DIR=lib/python2.7/site-packages` to the cmake command seems to work around it.

**Comment by skycaptain** [comment]
For Homebrew this is finally adressed in Homebrew/homebrew-science#5938.

**Comment by lgritz** [comment]
Can this be closed, then? It needs no changes on the OIIO side of things?

Or are you saying that it's fixed only for Homebrew users, but everybody else still needs something else changed?

**Comment by alex-weej** [comment]
No, OIIO should really just fix it so people don't need to know that
workaround.

**Comment by skycaptain** [comment]
@lgritz: I fear the later. We fixed this just for Homebrew users, so that OpenImageIO.so gets installed inside lib/python{pyversion}/site-packages. But we did this *manually*.

@alex-weej: Since OIIO does not have an installation routine, why is this change necessary?

**Comment by lgritz** [comment]
Does this look right?  https://github.com/OpenImageIO/oiio/pull/1722
