### ISSUE TITLE
output of 16-bit uncompressed iff is broken

### ISSUE THREAD

**Issue by mjmvisser** [OpenImageIO/oiio#933]
I found this one when attempting to convert uncompressed 16-bit dpx to iff, but it works with any input:

$ oiiotool colorbars.png -d uint16 --compression none -o bad.iff
$ iv bad.iff

Forcing rle compression or uint8 data (or both) results in good output.

It's definitely something in the output code path as Maya reads bad.iff identically to iv.

Sample image to test with.

![colorbars](https://cloud.githubusercontent.com/assets/351739/3859475/08a592d8-1f19-11e4-8396-dd7319a1ebe5.png)

Definitely low priority since there's an easy workaround (just use --compression rle when generating iff), just posting in case anyone else runs into the same issue.

cheers,
-Mark

**Comment by lgritz** [comment]
Is this still broken, Mark? Did we ever resolve this?

**Comment by mjmvisser** [comment]
Sorry, I must have missed your response last year. Yes, I just tested generating an iff with the above command line and reproduced the issue, so generating uncompressed iff is still broken.

I have no opinion on keeping the (broken) uncompressed write path. I can say that we've been using --compression rle and it's been working fine since I logged this issue. 

I should add that the only reason we generate iff is because they're much, much faster in Maya image planes than any other format we've tried (important for animators scrubbing scenes).

**Comment by lgritz** [comment]
I don't see any real point in writing uncompressed iff files, so I will post a PR in which it forces RLE compression and doesn't allow uncompressed. It doesn't seem to be worth the trouble of trying to debug what's wrong with uncompressed iff.

**Comment by lgritz** [comment]
Ha! Would you believe I found the bug?

**Comment by lgritz** [comment]
Proposed fix in #1234

Please give this a try!

**Comment by mjmvisser** [comment]
Nice! 

Damn, I went back to my original test case (a real film scan DPX) and though there's no difference between RLE and uncompressed now, the image is all screwy. It's easy to reproduce, here's my test image (I get the exact same result with the Digital LAD as well):

[00255.dpx | uploaded via ZenHub](https://files.zenhub.io/561ea3c2493045306c757900)

oiiotool 00255.dpx -o bad.iff

**Comment by lgritz** [comment]
Yeah, that's how I found it -- just as I'd prepared the patch for "force RLE", I tested it on the color bar image at the head of this message and it still looked screwy (though only in the leftmost bar). Turns out that the RLE case actually checks if the RLE representation of a tile grows in size compared the uncompressed tile, and if so, just uses uncompressed. So there was no avoiding the uncompressed encoding code path. I considered asking you if you really needed 16 bits (forcing to 8 also fixed things), but figured that if it worked for the 8 bit uncompressed path and failed for the 16 bit, maybe I could just compare the two cases line by line and see if I could spot anything weird. And I did!

**Comment by lgritz** [comment]
Wait, I must've gotten something backwards...

**Comment by lgritz** [comment]
Pushed a fix to swap ends. Try now.

**Comment by mjmvisser** [comment]
Yeah! Fixed.

**Comment by mjmvisser** [comment]
Just thought of this: since the RLE path falls back on the uncompressed path, maybe RLE should be the default?

**Comment by lgritz** [comment]
Yes, that makes sense. I will amend the PR.

**Comment by lgritz** [comment]
Update pushed. If you don't explicitly ask for compression "none", you'll get RLE.

**Comment by mjmvisser** [comment]
LGTM!
