### ISSUE TITLE
psdinput error

### ISSUE THREAD

**Issue by ElaraFX** [OpenImageIO/oiio#941]
I tried open an psd file in OIIO it will crash when loading the file header.  I tried lots of version, the crash is the same.

**Comment by lgritz** [comment]
I'm trying to go through some old issues that have languished...

I get an error from oiio when opening this file, but I also note that neither Mac Preview.app nor GIMP will open the file either, complaining that it's not a valid PSD file.

Maybe the file is corrupt?

**Comment by lgritz** [comment]
Closing because In current master, this file seems to open just fine. Presumably the issue has been fixed by one of the various PSD fixes that have been contributed since this issue was filed.
