### ISSUE TITLE
Documentation: Threads attribute

### ISSUE THREAD

**Issue by normvcr** [OpenImageIO/oiio#946]
In section 2.2 (p 15), is written about the "threads" attribute:

"If set to 0, it means that it should use as many threads as there are hardware cores present on the
system."

This is not quite right on my system, Fedora20 x86_64.  I have a quad core, but each is hyperthreaded (a bunch of extra registers to remember the state of a single process), so when I set the attribute to 0, the actual attribute value is set to 8, not 4.

**Comment by lgritz** [comment]
At some point in 1.6, the definition and the behavior came into sync. Closing.
