### ISSUE TITLE
OpenImageIO cannot open JPEG file took from phones with premature end

### ISSUE THREAD

**Issue by YangYangTL** [OpenImageIO/oiio#951]
Since oiio always pass true as fatal error flag, so when it encounters recoverable "premature end of JPEG file warning", it will not open the image file, but most other softwares such as Photoshop, GIMP and IrfanView will open it. Currently I choose to pass false to it to open the file, but it should really depends on the level of the error.

myerr->jpginput->jpegerror (myerr, true);

**Comment by lgritz** [comment]
Can you provide a specific JPEG file that exhibits this problem?

**Comment by lgritz** [comment]
Closing, no follow up was forthcoming. If you have an example image file that exhibits this, please re-open or file a new issue.
