### ISSUE TITLE
DeepData populated with bogus values?

### ISSUE THREAD

**Issue by jalevine** [OpenImageIO/oiio#961]
In testing oiio with this image:

https://filetea.me/t1s0XHicn6xTEe9ozDwyR1Dbg

I've encountered an issues where some of the channels get populated with what appears to be bad values (512, -512, and occasional others like -2, 2).  Sometimes, the values for said pixels change if I re-run.  I am using the standard loop to read Deep Images provided in the OIIO programmer documentation.

I've tested this with oiiotool --stats and it reports the range of values for R,G,B,A as [-512,512].  I've also tested this with iv and it crashes on load.  However, with exrdisplay, the image loads fine (and also reports valid values in [0,1] for the exact same pixels), so I'm fairly convinced OpenEXR can read the image just fine.

**Comment by lgritz** [comment]
We have had a number of fixes and improvements to deep code paths lately, and this example seems to work fine now. I think whatever bug caused this has been fixed. Closing.
