### ISSUE TITLE
fast_sinpi compilation optimization issue with clang

### ISSUE THREAD

**Issue by etheory** [OpenImageIO/oiio#963]
Hi there!

I've noticed that for the fast_sinpi function in src/include/OpenImageIO/fmath.h, the following (first) line:
const float z = (x + 25165824.0f);

needs to be changed to:
volatile float z = (x + 25165824.0f);

in order to work correctly with the Clang compiler (3.2 in our case).

Clang appears to "prematurely" optimize the const and fold it into the subsequent numerical manipulation you are doing for speed, which ends up nulling it out (producing an unintended numerical result), and producing unintended side-effects.

We are using the above change to fix an issue we were having with the lanczos3 filter, which was producing black results for every mip-map level less then the highest during re-sampling with the above issue in clang 3.2.

regards,
Luke Emrose, Animal Logic.

**Comment by lgritz** [comment]
Is this still a problem for anybody? Is it an ongoing issue that we should address, or is it specific to versions of clang that are now too old to worry about?

**Comment by lgritz** [comment]
One more shot at this: is it relevant to try to address, or is it long since fixed in any modern compiler and we should just close the issue?

**Comment by etheory** [comment]
Hi Larry,

Sorry! I missed your last two posts until today.

This is not an issue for us any more, it's totally safe to close this ticket thanks!

Regards,

Luke
