### ISSUE TITLE
Linker Errors on Mac OS X 10.9.5

### ISSUE THREAD

**Issue by Alexander-Marshall** [OpenImageIO/oiio#991]
Hi,

I've been trying to compile OIIO on a Mac. It compiles fine, but when I do a manual build for a shared library, none of the utilities run and Xcode says it can't find the libraries when I reference them ("library not loaded - image not found"). When I do a manual build for a static library, the utilities run, but Xcode gives hundreds of linker errors whenever any OIIO code appears in my project.
I've also tried CMake, but I couldn't get it to produce an archive (said it couldn't find a release version of libOpenImageIO.1.4.14). 
Is this a known issue, or am I doing something wrong?

Thanks,
Alex

**Comment by lgritz** [comment]
Never got a reply. Closing. If you're still having troubles building on 1.5 or master, please submit a new ticket with a build log and/or the specific errors.
